### ISSUE TITLE
`_code_to_symbol`判断交易所逻辑不完整

### ISSUE THREAD

**Issue by kongscn** [waditu/tushare#10]
`tushare/stock/trading.py` `_code_to_symbol`：

``` python
return 'sh%s'%code if code[:1] == '6' else 'sz%s'%code
```

SSE B股以'9'开头，ETF以'5'开头，还有可转债等

**Comment by jimmysoa** [comment]
谢谢，目前只有A股数据，后期会考虑逐步加入您提出的这些金融产品数据。

**Comment by hebl** [comment]
ETF 以5开头，数据应该是可以的。

**Comment by jimmysoa** [comment]
好的，谢谢。
我知道那个意思，一些场内基金是可以获取的，但我设计是想把基金等数据跟股票分开，所以一直没加。

**Comment by xgdgsc** [comment]
@jimmysoa 现在是有深市B股，没有沪市B股，希望加上沪市B股，实现起来应该差不多吧？

**Comment by xgdgsc** [comment]
场内基金可以先支持数据获取啊，没必要分开。场外的分开还差不多。
