### ISSUE TITLE
有没有办法设置http_proxy

### ISSUE THREAD

**Issue by zhenyiy** [waditu/tushare#100]
因为有防火墙，无法连接上数据，得到urlopen error timed out错误，有没有办法可以设置http_proxy代理，谢谢

**Comment by jimmysoa** [comment]
通过IE设置代理就可以

**Comment by WandyYing** [comment]
目前我没发现有设置代理的地方，我提供一个方法。安装后，打开源码更改，自己添加代理，以fundamental.py为例子，需要添加代码示例如下：
try:
    from urllib.request import urlopen, Request, \
    install_opener, build_opener, ProxyHandler
except ImportError:
    from urllib2 import urlopen, Request, \
    install_opener, build_opener, ProxyHandler

    request = Request(ct.ALL_STOCK_BASICS_FILE)
    proxy_support = ProxyHandler({'http': 'proxyserver:proxyport','https': 'proxyserver:proxyport'})
    opener = build_opener(proxy_support)
    install_opener(opener)#添加代理
    text = urlopen(request, timeout=10).read()

所有用到urlopen的都添加如上代码

**Comment by zephoon** [comment]
有一个感觉比较通用简单的代理解决方案，在代码最前面插入这三行代码
```
import os
os.environ['http_proxy'] = <proxy url>
os.environ['https_proxy'] = <proxy url>
```
