### ISSUE TITLE
每分钟接口访问次数

### ISSUE THREAD

**Issue by hwypengsir** [waditu/tushare#1001]
积分为500的用户，每分钟可以访问多少次接口呢？

**Comment by jimmysoa** [comment]
不同的接口是不同的频次，比如日线行情是200次/分钟

**Comment by LeonGhibli** [comment]
> 不同的接口是不同的频次，比如日线行情是200次/分钟

在tushare.pro的文档里没有查询到日线行情，基金净值等接口的频次限制。请问达到多少积分可以提高访问频次或解除访问频次限制呢，还是说此类接口的访问频次限制是固定的，与积分无关?

**Comment by jimmysoa** [comment]
5000积分
