### ISSUE TITLE
建议龙虎榜数据top_inst，增加一个字段reason

### ISSUE THREAD

**Issue by yyxochen** [waditu/tushare#1002]
现在的top_inst中，没有办法区分因为不同原因上榜的席位。应该增加reason字段，这样就可以区分了。而且交易所的公开数据中，也是每个席位有reason的。

**Comment by jimmysoa** [comment]
请关联每日明细里的reason字段

**Comment by yyxochen** [comment]
top_list里有reason字段。但是没有交易席位字段。
单个股票，在单个交易日，会上榜多次。每次上榜的席位可能有差别。
根据top_list的reanson字段无法确定交易席位是哪个理由进入的。
