### ISSUE TITLE
周线数据缺失

### ISSUE THREAD

**Issue by alvincjq1980** [waditu/tushare#1003]
2019年4月4日周线数据缺失

st.get_hist_data('000651',ktype='W').head(2)
Out[9]: 
             open   high  close     ...           v_ma5      v_ma10      v_ma20
date                                ...                                        
2019-04-09  51.93  51.93  51.93     ...      2238464.05  2306436.81  1441474.51
2019-03-29  45.47  47.30  47.21     ...      2851749.95  2588761.31  1441474.51

pro.weekly刚刚已经补上了。

**Comment by jimmysoa** [comment]
已经好了的

**Comment by alvincjq1980** [comment]
> 已经好了的

pro.weekly部分数据还是缺失4月4日的。
stock='000651.SZ'

pro.weekly(ts_code=stock, fields='ts_code,trade_date,open,high,low,close,vol,amount').head(2)
Out[38]: 
     ts_code trade_date  close      ...         low          vol        amount
0  000651.SZ   20190329  47.21      ...       44.26  263427293.0  1.205407e+10
1  000651.SZ   20190322  46.16      ...       45.80  251413960.0  1.178008e+10

[2 rows x 8 columns]

**Comment by alvincjq1980** [comment]
st.get_hist_data('000651',ktype='W').head(2)
还是有问题啊。
