### ISSUE TITLE
index_weight接口取到的指数成分和权重有不少没更新

### ISSUE THREAD

**Issue by deepfuzzy** [waditu/tushare#1004]
比如，今天（20190411）取到的中小板399005和创业板399006权重还是去年20181228的，000807的权重还是20181130，这种情况还不少

**Comment by mhan11** [comment]
貌似上交所的指数都是正常的，深交所的都有问题，会不会是深交所获取数据的网站改版了。

**Comment by jimmysoa** [comment]
都有两个代码，399807.SZ
