### ISSUE TITLE
pro_bar不能获取指数分钟数据

### ISSUE THREAD

**Issue by mhan11** [waditu/tushare#1013]
df_index = ts.pro_bar(ts_code="000001.SH", freq='1min', asset="I", start_date='20190412', end_date='20190415')
local variable 'data' referenced before assignment
但是stock分钟数据可以获取
df_stk = ts.pro_bar(ts_code="000001.SZ", start_date='20190412', end_date='20190415', freq='60min')
见下图
![tushare_bug](https://user-images.githubusercontent.com/11676276/56147077-1f0d8600-5fda-11e9-8e62-623ad610b5e1.png)

**Comment by jimmysoa** [comment]
升级到1.2.27版本就可以了
