### ISSUE TITLE
pro_coinbar获取不到数据

### ISSUE THREAD

**Issue by bitseaman** [waditu/tushare#1016]
在尝试用pro_coinbarr获取bitstamp btcusd数据时，返回为"Exception: 系统内部错误".

代码如下：
import tushare as ts 
#设置tushare 的token
ts.set_token('token')
#初始化pro接口
pro = ts.pro_api()
#获取btc行情数据
df = pro.query('coinbar',exchange='bitstamp',symbol='btcusd',freq='daily',start_date='20190101',end_date='20190201')
print(df.head())

返回:
Exception: 系统内部错误

ps.本人积分足够用.

**Comment by jimmysoa** [comment]
没有采集这个交易所的数据
