### ISSUE TITLE
股票和指数日线缺失及错误

### ISSUE THREAD

**Issue by cathayandy** [waditu/tushare#1018]
您好，我从tushare.pro抓取了全部的个股及指数的日线数据，并做了简单的合法性验证，发现部分数据有缺失或错误。其中两个我去新浪对了一下发现个别域没有对上。详情如下：

`pro.index_daily`接口：

`'399130.SZ'` `[20021008, 20020923, 20011115, 20111114]` 缺失`amount`
`['399910.SZ', '399918.SZ', '399920.SZ']` `20080311` `high`不是最大的
`'399912.SZ'` `20080227` `high`不是最大的。去新浪对了一下，`close`没对上，新浪的`close`是6633.17，你的是6633.297， `vol`也有一点差异，新浪是117.20万，你的是1173341
`'399911.SZ'` `20080229` `high`不是最大的。去新浪对了一下，`close`没对上，新浪的`close`是4656.12，你的是4657.463

我的id：249443 https://tushare.pro/register?reg=249443

个股错误较多，我过后补上。

**Comment by jimmysoa** [comment]
为什么你认为新浪的是对的呢？可以去对比一下万得数据，谢谢
