### ISSUE TITLE
历史数据的columns 顺序能否调整下

### ISSUE THREAD

**Issue by ketra21** [waditu/tushare#1019]
今天第一次使用tushare，感觉好棒啊，不用自己爬数据了~~
在“历史行情”中data columns为：
open    high   close     low     volume    p_change...，虽然columns顺序并不影响数据处理，但是为了数据使用者方便查看，建议还是将high和low放一起比较合适（强迫症），有两种修改建议：
1）open    close   high     low      volume    p_change...
2）open    high    low      close    volume    p_change...
感觉这两种都比现有的好，个人更倾向于1）方案。
祝tushare越来越好！

**Comment by jimmysoa** [comment]
谢谢建议，目前顺序暂时不做调整了
