### ISSUE TITLE
通联接口获取基金数据报错

### ISSUE THREAD

**Issue by xxllp** [waditu/tushare#102]
我运行如下代码，获取某个类别的基金基本数据，会报错
```
fd = ts.Fund()
df=fd.Fund(listStatusCd='UN')
```

> File "D:\Anaconda2\lib\site-packages\tushare\datayes\fund.py", line 34, in Fund
>     return _ret_data(code, result)
>   File "D:\Anaconda2\lib\site-packages\tushare\datayes\fund.py", line 137, in _ret_data
>     df = pd.read_csv(StringIO(result))
>   File "D:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 491, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "D:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 278, in _read
>     return parser.read()
>   File "D:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 740, in read
>     ret = self._engine.read(nrows)
>   File "D:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 1187, in read
>     data = self._reader.read(nrows)
>   File "pandas\parser.pyx", line 758, in pandas.parser.TextReader.read (pandas\parser.c:7919)
>   File "pandas\parser.pyx", line 780, in pandas.parser.TextReader._read_low_memory (pandas\parser.c:8175)
>   File "pandas\parser.pyx", line 833, in pandas.parser.TextReader._read_rows (pandas\parser.c:8868)
>   File "pandas\parser.pyx", line 820, in pandas.parser.TextReader._tokenize_rows (pandas\parser.c:8736)
>   File "pandas\parser.pyx", line 1732, in pandas.parser.raise_parser_error (pandas\parser.c:22105)
> pandas.parser.CParserError: Error tokenizing data. C error: Expected 28 fields in line 3477, saw 31

初步认为是数据格式不规范，有无好的办法解决

**Comment by jimmysoa** [comment]
@xxllp 我找人看看，这个通联数据接口。

**Comment by jimmysoa** [comment]
数据里有特殊字符，先不要调用investField,investTarget这两列试试。 @xxllp

**Comment by xxllp** [comment]
确实，json格式的全部可以，但是需要转成我要的。准备开发个R语言包
