### ISSUE TITLE
深证日线数据问题答复 #1018

### ISSUE THREAD

**Issue by cathayandy** [waditu/tushare#1020]
> 为什么你认为新浪的是对的呢？

我发现数据错误是因为批量做了ohlc检查和数据非空检查。ohlc检查就是检查每条数据是否满足high是ohlc中最大的，low是ohlc中最小的。所以找出了以上错误。新浪是一个免费的比较方便的查询行情的平台，所以我找了新浪比对，并不是认为他正确，但至少新浪的数据满足ohlc的规则，因此贴出来作为一个参考。

> 可以去对比一下万得数据，谢谢

万德好像没有免费的数据？我只能查询到新浪、雪球等免费的数据。

---

经过您的提示，我对比了以下两个合约多家互联网上公开的免费数据。第一行是从`pro.index_daily`拿到的数据，后面是不同数据源和tushare的diff

```
399912.SZ 20080227
tushare - c: 6633.297  o: 6408.273 h: 6633.167 l: 6337.821 vol: 1173341.0 amount: 3003840.466
sina    - c: 6633.17 vol: 117.20w
xueqiu  - h: 6633.30
tencent - h: 6633.30
netease - h: 6633.30
baidu   - h: 6633.30   o: 6394.98
```

```
399911.SZ 20080229
tushare - c: 4657.463  o: 4582.493 h: 4656.895 l: 4572.723 vol: 2409296.0 amount: 4404710.639
sina    - c: 4656.12 vol: 240.44w
xueqiu  - h: 4657.46
tencent - h: 4657.46
netease - h: 4657.46
baidu   - h: 4657.46   o: 4595.67
```

可以看到虽然数据略有差异，但是他们都满足ohlc的规则。因为只有深圳的数据出了问题，所以我猜测这个差异可能是尾盘3分钟的集合竞价导致的，各家处理规则不同：sina应该是只计算到14:57，而其他家都是算到15:00，所以sina的成交也少一点。baidu不知道为什么开盘和其他家不一样。但我暂时没有逐笔数据所以验证不了这个猜测。

所以您这边数据的问题可能是您（或者您的数据提供方）内部合成价格规则不一致导致的，我猜测可能是close算到了15:00，high只算到了14:57。因为我手头暂时没有付费的、可靠的数据源，所以我的比对可能参考性没有那么高，还是希望您能抽空检查一下。感谢！

**Comment by cathayandy** [comment]
前情见 #1018

**Comment by jimmysoa** [comment]
对比了tushare 的 000912.SH 和000911.SH,已修正，谢谢
