### ISSUE TITLE
每日指标中的自由流通股本为负数

### ISSUE THREAD

**Issue by musicaudience** [waditu/tushare#1028]
`{
	"api_name":"daily_basic",
	"token":"XXXXXXXXXXXX",
	"params":{
		"trade_date":"20190424"
	},
	"fields":["trade_date", "ts_code", "pe", "pe_ttm", "pb", "ps", "ps_ttm", "total_share", "float_share", "free_share"]
}` 
调用的时候 “600657” 这一只股票的由流通股本为负数 "-5719.7841"

Tushare ID： 261375

**Comment by jimmysoa** [comment]
我确认了一下数据库，并没有发现这种负值的数据，请再次确认，谢谢。

**Comment by musicaudience** [comment]
> 我确认了一下数据库，并没有发现这种负值的数据，请再次确认，谢谢。

![image](https://user-images.githubusercontent.com/35216951/57124397-3610ee00-6db8-11e9-855c-159bfc3f3c6d.png)
数据库也许是对的，但接口上貌似不太对

**Comment by musicaudience** [comment]
![image](https://user-images.githubusercontent.com/35216951/60519224-b6e75a00-9d15-11e9-8b1b-a33a5d3f63db.png)
同样的问题今天再次出现了
