### ISSUE TITLE
通用行情接口pro_bar，指定结束日期不生效

### ISSUE THREAD

**Issue by yingbing** [waditu/tushare#1029]
请求参数如下
`ts.pro_bar(ts_code='510880.SH', asset='FD', adj='qfq', ma=[5, 10, 30, 200, 250], freq='D', start_date='20180110', end_date='20191011')`

但实际得到的结果却是到2019/04/30，2019/05/03调的接口
![QQ截图20190503043137](https://user-images.githubusercontent.com/1592237/57105026-5dd26880-6d5c-11e9-8172-dfe8fa16ecc0.png)

from tushare_id: ice_dy

**Comment by yingbing** [comment]
调试查看源码，发现获取基金数据的接口返回的数据本身就是错误，结果如下图：
![image](https://user-images.githubusercontent.com/1592237/57105581-b2c2ae80-6d5d-11e9-8df6-cef97abcd3df.png)

**Comment by jimmysoa** [comment]
end_date你输入的是20191011，到5月3一直放假，最近交易日是20190430，这个接口目前单次默认只返回1000行情。
