### ISSUE TITLE
pro数据是倒过来的，指标函数怎么办？

### ISSUE THREAD

**Issue by lachen2000** [waditu/tushare#1030]
原来用的是老版，数据是从晚到早排列，各种指标函数（例如KDJ,MACD,RSI,EXPMA等）用的也很好，刚刚升级到pro，发现数据是倒过来的，那么指标函数怎么办呢？有没有相应的函数可以直接使用

**Comment by luyifanlu** [comment]
设置index=False,

**Comment by lachen2000** [comment]
> 设置index=False,

谢谢你，刚刚试了下，好像不行，没有index这个输入参数。

**Comment by luyifanlu** [comment]
实在不行,将数据变成pandas数据,再设置index=False,

**Comment by xing-zhi** [comment]
@lachen2000 https://stackoverflow.com/questions/20444087/right-way-to-reverse-pandas-dataframe
pandas相关问题，搜索一下就有答案了。

稳健一点的做法是先判断一下数据的顺序，如果顺序不对，进行逆序，这样可以保证以后不用出现顺序不对的问题

除了没有保证接口的向后兼容外，不是tushare的问题
你应该是对pandas不熟，花点时间了解一下，使用的过程中免不了和它打交道

**Comment by lachen2000** [comment]
非常感谢，我再试试
