### ISSUE TITLE
资产负债表固定资产数据错误与重复

### ISSUE THREAD

**Issue by KaimingOuyang** [waditu/tushare#1038]
ts_code  ann_date f_ann_date  end_date  total_cur_assets    fix_assets  total_cur_liab    total_liab
600038.SH  20190426   20190426  20190331      1.997876e+10  0.000000e+00    1.440746e+10  1.515330e+10
600038.SH  20190426   20190426  20190331      1.997876e+10  0.000000e+00    1.440746e+10  1.515330e+10
600038.SH  20190321   20190321  20181231      2.073679e+10  2.182306e+09    1.528940e+10  1.601735e+10
600038.SH  20181026   20181026  20180930      1.936912e+10  0.000000e+00    1.416455e+10  1.498835e+10
600038.SH  20180825   20180825  20180630      1.881996e+10  2.270699e+09    1.382745e+10  1.461474e+10

这个第一条和第二条数据是重复的，固定资产显示为0（正确的值应该是2,133,647,617），请问这样的数据能不能修复一下呢？

**Comment by jimmysoa** [comment]
重复的问题可能某些或者某个字段有修正，需要确认update_flag字段的数据。为0的情况我们需要确认一下
