### ISSUE TITLE
[BUG]前复权数据与同花顺不一致

### ISSUE THREAD

**Issue by rowps** [waditu/tushare#1039]
代码：
df_bar = ts.pro_bar(ts_code='603156.SH', adj='qfq', start_date='20190507', end_date='20190509')
print(df_bar)
结果：
     ts_code trade_date   open   high  ...  change  pct_chg       vol      amount
0  603156.SH   20190509  35.75  35.77  ...   -1.18    -3.21  25671.86   89925.308
1  603156.SH   20190508  35.77  37.35  ...    0.61     1.69  35060.53  190153.269
2  603156.SH   20190507  34.56  36.31  ...    1.96     5.73  33827.22  177132.146
其中第2行的open、high等前复权数据与同花顺不一致（同花顺open为35.71）
![image](https://user-images.githubusercontent.com/9362411/57576429-4436cc80-7492-11e9-8523-6a31b7b87223.png)

（我的注册链接：https://tushare.pro/register?reg=265109）

**Comment by jimmysoa** [comment]
![图片](https://user-images.githubusercontent.com/6335378/57582173-08ccea00-74f4-11e9-93f9-6abc57ab9dbc.png)

**Comment by jimmysoa** [comment]
应该是复权机制不同，我们跟wind对比了一下，wind是35.78，high是37.35，说明基本一致。
