### ISSUE TITLE
fut_daily接口数据有误

### ISSUE THREAD

**Issue by wangyaochong** [waditu/tushare#1041]
调用ts_code=ICL.CFX，获取中证500当月连续的日线行情，2019.04.18和2019.04.19两天的行情不对，2019.04.18同花顺和通达信的收盘价都是5673，而tusharePro是5765.2，对于2019.04.19同花顺和通达信的收盘价都是5775.8，而tusharePro是5781.2，麻烦核查一下问题在哪

**Comment by jimmysoa** [comment]
我对比了一下万得的数据，跟tushare Pro是对的上的，这里可能有一些规则不同，具体认定主连的方法请参考Pro网站期货部分说明，谢谢。
