### ISSUE TITLE
exchange_ann接口没有2019年5月的数据,也不返回错误代码

### ISSUE THREAD

**Issue by keepBlazing** [waditu/tushare#1044]
pro.exchange_ann(start_date='2019-04-17 16:00:00', end_date='2019-04-17 18:00:00', fields='title, datetime')
以及
exchange_twitter
和
twitter_kol
都没有数据

**Comment by jimmysoa** [comment]
收到，前端时间暂停了，因为没有用户使用但是占据了不少资源。后面我们可以再启动

**Comment by Togal** [comment]
好像现在也没有启动？测试exchange_ann接口没有数据返回：
Empty DataFrame
Columns: [title, datetime]
Index: []
