### ISSUE TITLE
个股日k数据不正确

### ISSUE THREAD

**Issue by ELI95** [waditu/tushare#1048]
In [17]: daily_array
Out[17]: 
      ts_code trade_date   open   high    low  close  pre_close  change  pct_chg         vol       amount
0   300059.SZ   20190521  15.07  15.57  15.02  15.40      15.13    0.27   1.7845  1474134.54  2262963.121
1   300059.SZ   20190520  14.79  15.33  14.62  15.13      14.83    0.30   2.0229  1572859.03  2359199.898
2   300059.SZ   20190517  15.59  15.60  14.63  14.83      15.57   -0.74  -4.7527  1794868.26  2708093.785
3   300059.SZ   20190516  15.76  15.76  15.40  15.57      15.76   -0.19  -1.2056  1331402.72  2072155.915
4   300059.SZ   20190515  15.65  15.84  15.53  15.76      15.46    0.30   1.9405  1670856.28  2622393.691
5   300059.SZ   20190514  15.46  15.75  15.41  15.46      15.49   -0.03  -0.1937  1564046.54  2437038.323
6   300059.SZ   20190513  15.70  15.81  15.35  15.49      16.04   -0.55  -3.4289  1719686.42  2678094.478
7   300059.SZ   20190510  15.35  16.15  15.12  16.04      15.05    0.99   6.5781  3098632.73  4873861.438
8   300059.SZ   20190509  14.81  15.30  14.80  15.05      15.05    0.00   0.0000  1622293.24  2455843.768
9   300059.SZ   20190508  14.65  15.37  14.56  15.05      15.04    0.01   0.0665  1673005.24  2518470.638
10  300059.SZ   20190507  14.88  15.09  14.53  15.04      14.75    0.29   1.9661  2283237.42  3398406.902
11  300059.SZ   20190506  15.05  15.58  14.75  14.75      16.39   -1.64 -10.0061  2871043.90  4326568.981

**Comment by jimmysoa** [comment]
这种问题让我如何回答好
