### ISSUE TITLE
获取周成交量错误

### ISSUE THREAD

**Issue by wind417588** [waditu/tushare#1049]
2019.5.25日，通过get_hist_data接口获取本周的数据，成交量有误。以000014为例，获取到的是34.31,但真实的数据是52.84。原因，从凤凰网获取的数据源本身存在错误，这种数据源存在错误，是否有解决办法？

![exception](https://user-images.githubusercontent.com/46237775/58365441-f0e36600-7ef6-11e9-9231-c202562eddac.jpg)

**Comment by jimmysoa** [comment]
这个接口不再维护，请使用pro版行情。https://tushare.pro/document/2?doc_id=27
