### ISSUE TITLE
复权因子和复权数据似乎有问题?

### ISSUE THREAD

**Issue by ztp1978** [waditu/tushare#1050]
sz00001 = ts.pro_bar(ts_code='000001.SZ',adj='hfq',start_date='20190501')

  | close | ts_code | trade_date
-- | -- | -- | --
1334.18 | 000001.SZ | 20190524
1327.70 | 000001.SZ | 20190523
1339.58 | 000001.SZ | 20190522
1356.87 | 000001.SZ |  

登录雪球,检查
20190524的后复权close的值为: 1529.60

采用pro.daily 和 pro.adj_factor抓取数据,并按照
如下公式计算,得到的和pro_bar抓取的相同,但依然和雪球的数据不一致;
后复权 | 当日收盘价 × 当日复权因子 | hfq

我的ID:18601369567

**Comment by jimmysoa** [comment]
![图片](https://user-images.githubusercontent.com/6335378/58382504-6b96a900-7ffd-11e9-895d-5b49cecaec21.png)

为啥这么坚定的认为雪球就是对的？
