### ISSUE TITLE
get_tick_data中的一些警告 

### ISSUE THREAD

**Issue by callmehero** [waditu/tushare#1051]
..\tushare\stock\trading.py

get_tick_data() line 181行中

`df=pd.read_table(.....)` 该接口即将弃用，警告中建议使用read_csv代替修改方法如下,需要在原来的基础上加多一个参数

`df=pd.read_csv(..., sep='\t',)`

**Comment by jimmysoa** [comment]
get_k_data这个接口即将弃用，请用pro版行情：https://tushare.pro/document/2?doc_id=27
