### ISSUE TITLE
调用index_daily  提出内部系统错误

### ISSUE THREAD

**Issue by rcxinmo** [waditu/tushare#1058]
{
	"api_name":"index_daily",
	 "token":"",
	 "params":"{ts_code:00006}"
}
{
    "request_id": "3b2c575689ee11e9b139d00dd36710041559999189949462",
    "code": -1000,
    "msg": "系统内部错误",
    "data": null
}

**Comment by jimmysoa** [comment]
params参数输入错误，请参考网站http api的说明或者浏览Tushare官方公众号“挖地兔”的文章获取方法
