### ISSUE TITLE
很多股票数据有重复，如 白云机场、大连友谊 等

### ISSUE THREAD

**Issue by samlink** [waditu/tushare#1060]
白云机场（600004.SH），最近的年度和季度数据重复：
"items": [
            [
                "20190331",
                25523239604.14,
                650000000,
                100000000,
                20000000,
                null,
                15851920655.5
            ],
            [
                "20190331",
                25523239604.14,
                650000000,
                100000000,
                20000000,
                null,
                15851920655.5
            ],
            [
                "20181231",
                27064961458.48,
                650000000,
                null,
                520000000,
                null,
                15615719623.92
            ],
            [
                "20181231",
                27064961458.48,
                650000000,
                null,
                520000000,
                null,
                15615719623.92
            ],
            [
                "20180930",
                27931014166.18,
                903380000,
                500000000,
                null,
                3036339808.14,
                15709089773.45
            ], ……

**Comment by jimmysoa** [comment]
请确认报表类型，另外就是如果有任何修正，都可能是两条数据，update_flag=1是最新的一条数据

**Comment by zdqzyx** [comment]
> 请确认报表类型，另外就是如果有任何修正，都可能是两条数据，update_flag=1是最新的一条数据

那请问数据修正的时间有吗？我如何确保数据修正时间是在实际公告时间之前？避免用到了未来数据

注册ID：583998
