### ISSUE TITLE
港股通十大成交股 不支持按start_date,end_date的全量查找

### ISSUE THREAD

**Issue by SailBlade** [waditu/tushare#1061]
港股通十大成交股目前只支持
pro.ggt_top10(trade_date='20180727')
或者
pro.query('ggt_top10', ts_code='00700', start_date='20180701', end_date='20180727')
但是需要
      pro.ggt_top10(start_date='20180701', end_date='20180727')，目前接口不支持，或者有错，需要解决。

用户名： 18991376110@163.com

**Comment by jimmysoa** [comment]
是的，目前还不支持全市场的开始和结束日期参数
