### ISSUE TITLE
龙虎榜数据问题 - "000021.SZ" on 20190520

### ISSUE THREAD

**Issue by last99** [waditu/tushare#1065]
有一只股票000021.SZ，在20190520”龙虎榜每日明细“中， 但查询“龙虎榜机构交易明细”时，查询结果为空，没有此数据，如下：

>>> pro.query('top_list', trade_date='20190520', ts_code='000021.SZ')
  trade_date    ts_code name  close  pct_change  ...   net_amount  net_rate  amount_rate  float_values            reason
0   20190520  000021.SZ  深科技   8.76     10.0503  ...  12620087.46       1.9        14.24  1.287157e+10  日涨幅偏离值 达到7%的前五只证券

[1 rows x 15 columns]

>>> pro.query('top_inst', trade_date='20190520', ts_code='000021.SZ')
Empty DataFrame
Columns: [trade_date, ts_code, exalter, buy, buy_rate, sell, sell_rate, net_buy]
Index: []
>>>
我的Tushare ID：last99

**Comment by jimmysoa** [comment]
已经有数据，没有同步好
