### ISSUE TITLE
tushare/stocck/indicator.py下ma/ma计算有误

### ISSUE THREAD

**Issue by saintfly** [waditu/tushare#1066]
第37行
if len(values) == n:
        del values[0]
导致参与计算的数字个数为n-1。
若此功能已经移动到trendling.py，由于indicator.py计算效率较低，建议删除indicator.py。

昵称saintfly
邮箱saintfly@126.com

**Comment by saintfly** [comment]
md函数也有同样问题。

**Comment by jimmysoa** [comment]
这个接口以及废弃，没有地方使用
