### ISSUE TITLE
tushare下载的数据有缺失

### ISSUE THREAD

**Issue by nuanfeng2222** [waditu/tushare#1067]
中国商品期货的连续数据有缺失怎么解决？

**Comment by nuanfeng2222** [comment]
商品连续数据，比如代码RBL.SHF这样的，有很多缺失数据，怎么解决

**Comment by jimmysoa** [comment]
请把问题说具体一点，谢谢

**Comment by nuanfeng2222** [comment]
我想获取期货连续指数数据，就是品种挂牌交易合约按持仓量或成交量加权平均的。如果这样，应该有部分合约不活跃没成交量，反馈的就不是数据这样参与计算结果就是nan，是否在算法上捋捋一遍，这样数据就不是nan了

**Comment by nuanfeng2222** [comment]
比如RBL.SHF这个，有些数据本来应该有的就变成了nan

**Comment by jimmysoa** [comment]
目前的算法还不支持，等我们新版连续发布就可以了
