### ISSUE TITLE
资产负债表里应付账款缺失

### ISSUE THREAD

**Issue by siben168** [waditu/tushare#1068]
发现很多2019年一季报里都缺失应付账款数据，这里举个例子
![image](https://user-images.githubusercontent.com/10054371/59656173-59102980-91cf-11e9-9e1f-708e54c26689.png)
实际上在上市公司一季报里有
![image](https://user-images.githubusercontent.com/10054371/59656276-a391a600-91cf-11e9-882a-a424660cf0d4.png)

另外“update_flag” 是不是只有0和1的情况？

**Comment by siben168** [comment]
还有，update_flag, 0和1 哪个比较新？

Tushare 注册id：https://tushare.pro/register?reg=267642

**Comment by jimmysoa** [comment]
1是修正过的，其他问题我们确认一下
