### ISSUE TITLE
Feature request: 添加 count 参数

### ISSUE THREAD

**Issue by jaicat** [waditu/tushare#1070]
在获取行情数据的接口中建议增加 count 参数。现在有 start_date, end_date，但是可能这段时间内有没有行情的情况，比如停牌。

**Comment by mzgcz** [comment]
可以使用volume来判断是否停牌，例如volume为0表示停牌

**Comment by towry** [comment]
@mzgcz 不是判断停牌胡问题，是我想从结束时间向前取10个数据

**Comment by jimmysoa** [comment]
tushare行情里停牌的没有数据记录

**Comment by towry** [comment]
<img width="1023" alt="Screen Shot 2019-06-20 at 23 26 43" src="https://user-images.githubusercontent.com/8279858/59861224-f8d9dd00-93b2-11e9-99ae-dfb98c8b438a.png">


@jimmysoa

**Comment by jaicat** [comment]
<img width="1023" alt="Screen Shot 2019-06-20 at 23 26 43" src="https://user-images.githubusercontent.com/8734366/59861310-24f55e00-93b3-11e9-9750-a759c7f5e172.png">
