### ISSUE TITLE
ts.get_index() 返回数据异常 

### ISSUE THREAD

**Issue by Rockyzsu** [waditu/tushare#1073]
返回数据如下：
`In [13]: df.head()
Out[13]: 
     code       name  change       open   preclose      close       high  low        volume  amount
**1  00上证指数**  2917.3310    0.34  2917.8029  2987.1186  2997.3888  2915.0895  0.0  2.882965e+11     0.0
2  00Ａ股指数  3055.5519    0.34  3056.0540  3128.7605  3139.5399  3053.1962  0.0  2.881399e+11     0.0
3  00Ｂ股指数   289.9308    0.17   289.7077   292.9259   293.4148   289.6255  0.0  1.566826e+08     0.0
8  00综合指数  2856.8661    0.45  2855.3665  2938.4907  2951.7948  2854.6206  0.0  9.138664e+10     0.0
9  0上证380  4514.1281    0.42  4516.0220  4600.3969  4619.6057  4498.6770  0.0  5.501268e+10     0.0`

目测是爬虫问题，前面的code和name有问题

**Comment by Rockyzsu** [comment]
tushare id： yagamil@126.com

**Comment by jimmysoa** [comment]
升级到最新版即可
