### ISSUE TITLE
老接口取实时行情数据接口get_realtime_quotes()，取上交所6开头的数据时返回的数据列表多了一个空值导致转dataframe时报错

### ISSUE THREAD

**Issue by ZhaoJackie** [waditu/tushare#1076]
ts.get_realtime_quotes("600000")
![image](https://user-images.githubusercontent.com/42666454/60002531-6760b880-969b-11e9-9275-dfcec66c3343.png)
原码中返回来的data_list中多了最后一个空值，取创业板3开头和深交所0开头的股票代码时候，data_list返回来的数据中就不会多出最后一个空值。
所以在代码为6开头的时，转dataframe的时候就会由于行和列名两个列表不一致报错。
![image](https://user-images.githubusercontent.com/42666454/60002988-5795a400-969c-11e9-95a1-74401cc31ce7.png)

**Comment by LookingID** [comment]
是的，前几天调用的时候发现了，当时没仔细看，以为是网络问题。今天看了一下新浪接口返回数据，上市比深市多返回一个空字段，在本地代码tushare/stock/cons的常量定义LIVE_DATA_COLS加了一个placeholder就可以了。

**Comment by ZhaoJackie** [comment]
@LookingID 加了一个字段后 上市的数据是没问题了，但是相应的深市的代码不也会因为少了一个字段而报错了模

**Comment by ZhaoJackie** [comment]
![image](https://user-images.githubusercontent.com/42666454/60008777-3f775200-96a7-11e9-9fe7-75a1ceb09540.png)
暂时通过加了一段循环跳过了这个特定的情况，win和linux上测试了可以跳过这个错误而不影响其它市场的数据获取
`    for __index in range(len(data_list)):
        if len(ct.LIVE_DATA_COLS) != len(data_list[__index]):
            del data_list[__index][len(ct.LIVE_DATA_COLS)]`

**Comment by LookingID** [comment]
我这边加了之后，没有出错。大概跟你解析方式比如index之类或者读取字段有关，我只取部分数据。

**Comment by jimmysoa** [comment]
升级到最新版就可以了的

**Comment by LookingID** [comment]
@jimmysoa 谢谢，那就是没有升级版本了，我这边还是1.2.18。
