### ISSUE TITLE
复权导致 `get_h_data` 的数据问题

### ISSUE THREAD

**Issue by callmewhy** [waditu/tushare#108]
复权是现算的？

如果 `get_h_data` 分别取几个时间段，因为复权的问题会导致拼接处不能吻合。

**Comment by jimmysoa** [comment]
是现算的，但是复权因子用的是全部历史数据，get_h_data返回的是指定日期之间的数据。

**Comment by isscall** [comment]
复权算法可能有点问题，拿到的数据跟各种炒股软件的不一样，例如：
In[28]: s
Out[28]: '2006-10-27'
In[29]: e
Out[29]: '2016-05-13'
In[30]: stock
Out[30]: '601398'
In[31]: data = ts.get_h_data(stock, start=s, end=e)
[Getting data:]######################################
In[32]: i
Out[32]: '2007-12-03'
In[33]: data.get(i)
Out[33]: 
            open  high  close  low       volume       amount
date                                                        
2007-12-03  5.42  5.55   5.48  5.3  111312052.0  897176817.0

这里拿的是全部历史数据，前复权，所以跟各种炒股软件的前复权数据应该是一样的，但是很明显这里的差别还挺大的。

**Comment by isscall** [comment]
Why close it without any explanation? Thanks.

**Comment by jimmysoa** [comment]
点错了。。。最近几年的数据基本一致，太早的数据可能有差异，建议只取最近的
