### ISSUE TITLE
部分股票pro日线行情接口返回数据有问题

### ISSUE THREAD

**Issue by eagleliang** [waditu/tushare#1082]
比如 `pro.daily(ts_code='000652.SZ', start_date='2018-12-20', end_date='2019-07-02') `返回的数据却是 20180102 到 20181228的行情数据

类似的问题的个股还有一些。

我的id是225502

**Comment by eagleliang** [comment]
另外补充一下：

1. 这个接口返回的数据似乎不同时间不一样，拿上面的000652来说，我之前发现数据有问题，是看到获取到数据是2019-01-02 到2019-07-02

1. 在我报bug的时候为了重现，再次调用得到的结果如上
1. 同时我再直接调接口，但是`start_date='2019-01-01'` `end_date='2019-07-02'`的话，接口返回的数据为空dataframe

**Comment by jimmysoa** [comment]
日期格式用yyyymmdd，我们在sdk也做一下处理
