### ISSUE TITLE
通用行情接口中的复权因子用以计算'不复权'价格时会导致和实际价格不符，似乎是复权因子精度不够

### ISSUE THREAD

**Issue by eagleliang** [waditu/tushare#1085]
如果使用pro_bar接口返回的复权因子做不复权的价格计算，会出现结算结果和实际价格不一致的问题：有的结果是四舍五入就和实际一致了，有的结果必须直接舍去第三位小数才和实际价格一致。
比如：
'002902.SZ'在20190612这天除权，如果用pro_bar获取的'前复权'的结果中的复权因子计算20190610的收盘价：
`In [129]: 25.25*1.508/1.004`
`Out[129]: 37.92529880478087`
实际价格应该是37.93

又如：
'603506.SH'在20190701除权，用pro_bar的前复权结果中的复权因子计算20190627的收盘价：
`In [126]: 18.78*1.724/1.31`
`Out[126]: 24.715053435114502`
实际价格应该是24.71

如果只是精度问题，建议接口返回的因子至少保留4位小数，方便在上述计算的时候使用decimal计算时小数点后第三位的精度是正确的，从而四舍五入获得准确的实际不复权价格

**Comment by eagleliang** [comment]
我的ID 是225502

**Comment by jimmysoa** [comment]
不复权的数据建议直接用daily接口就行，另外，计算历史上某一天的前复权行情方式跟行情是不同的，所有行情软件都是以最近一个交易日开始复权。关于复权机制的问题，请参阅常见问题说明：https://tushare.pro/document/1?doc_id=122

**Comment by eagleliang** [comment]
并不是为了获取行情，这里应用的一个场景是一次获取行情后，同时利用复权因子计算每天实际涨跌停价。虽然现在是有新的接口可以获取个股的涨跌停价，但是在上面的场景里面需要两次接口访问。所以希望最好pro_bar里面的复权因子能够精度更高
