### ISSUE TITLE
stock_basic股票列表未包括更改过代码的股票

### ISSUE THREAD

**Issue by PhantomCSY** [waditu/tushare#1086]
目前我使用
`listing_status = ['L', 'D', 'P']`
`stocklist = []`
`for status in listing_status:`
`    stocklist += pro.stock_basic(exchange='', list_status=status, fields='ts_code').ts_code.tolist()`
获取全市场所有存在过的股票，但发现这样会遗漏那些曾经变更过代码的公司，例如深赤湾A 000022.SZ，江南嘉捷601313.SH，这个逻辑是否可以完善一下

**Comment by PhantomCSY** [comment]
另外，对这类股票在pro.daily接口里的处理逻辑似乎不一致，例如000022可以查到截至到变更以前的数据，而601313则无法查到数据

**Comment by jimmysoa** [comment]
合并重新上市的代码有一些还没有，后面我们完善好，谢谢
