### ISSUE TITLE
获取实时分笔行情时老是报错“AssertionError('33 columns passed, passed data had 34 columns”

### ISSUE THREAD

**Issue by jaggerwang** [waditu/tushare#1089]
Fork 了仓库，改成了使用 aiohttp 来异步请求数据，但今天发现不能用了，merge 了最新的 upstream 仓库也不行。这个仓库跟 pip 包不是同步更新？

**Comment by songmd** [comment]
我也发现了这个问题，df = ts.get_realtime_quotes('600000')，这一行代码，如果股票代码不是6开头就能成功，6开头的就不行

**Comment by jimmysoa** [comment]
升级到最新版就可以了

**Comment by jaggerwang** [comment]
@jimmysoa 关闭 Issue 之前请仔细阅读一下内容，我说的是仓库源码的更新问题。PIP 包我知道可以，但是同步请求，我们需要异步的，所以才 Fork 了仓库修改。

**Comment by jimmysoa** [comment]
对不起，我没有看清楚，报歉。
我想说的是，我们的定位是“开放平台”而不是“开源项目”，数据属于内容服务，技术开源不是我们的方向。

**Comment by jaggerwang** [comment]
了解了~
