### ISSUE TITLE
查询利润表和数据财务指标的小bug

### ISSUE THREAD

**Issue by sslee-lg** [waditu/tushare#1094]
#利润表
df1 = pro.income(ts_code='600516.SH', start_date='20180718', end_date='20190718',
                    fields='ts_code,ann_date,f_ann_date,end_date, n_income_attr_p')

查询结果：
     ts_code  ann_date f_ann_date  end_date  n_income_attr_p
**0  600516.SH  20190427   20190427  20190331     7.131508e+08
1  600516.SH  20190427   20190427  20190331     7.131508e+08**
2  600516.SH  20190427   20190427  20181231     5.592809e+09
3  600516.SH  20181027   20181027  20180930     4.524761e+09
4  600516.SH  20180824   20180824  20180630     3.166561e+09

（1）查询利润表，第1、2行存在重复数据

# 查询财务指标数据
df2 = pro.fina_indicator(ts_code='600516.SH', start_date='20180718', end_date='20190718',
                            fields='ts_code, ann_date, end_date, extra_item, profit_dedt')

查询结果：
     ts_code  ann_date  end_date   extra_item   profit_dedt
0  600516.SH  20190427  20190331  56348007.43  6.568028e+08
1  600516.SH  20190427  20181231  66793454.46  5.526016e+09
2  600516.SH  20181027  20180930 -79704190.81  4.604465e+09

（2）查询600516的利润表和财务指标数据，都是从20180718~20190718，但财务指标数据比利润表的结果少了end_date=20180630的结果

我的注册邮箱： 1034750050@qq.com

**Comment by jimmysoa** [comment]
重复的问题是有修正过，请取update_flag=1的是最新的
