### ISSUE TITLE
近期(pro版)20190727好多指数获取不到数据，详见内

### ISSUE THREAD

**Issue by xs1973** [waditu/tushare#1104]
完全获取不到2019年的收盘close数据，如,[('中证红利','000922.SH'),('红利低波100','930955.CSI'),('300红利','000821.SH'),('基本面50','000925.SH'),('300价值','000919.SH')]
只能获取20190710之前的收盘价close数据，如[('红利低波','h30269.CSI'),('SHS高股息','930917.CSI')]
账号：sinfo16@126.com

**Comment by jimmysoa** [comment]
非常规的指数采集有困难，我们尽力
