### ISSUE TITLE
需求：建议增加可根据代码list获取行情信息的功能

### ISSUE THREAD

**Issue by xs1973** [waditu/tushare#1106]
很多时候，我们并不需要全部A股的数据，但可能需要若干股票/基金的数据，如果全部获取既影响性能，也没必要。建议增加根据提供的股票list进行数据获取的功能

比如：日线行情
df = pro.daily(ts_code='000001.SZ', trade_date=‘20190729’)，这里的ts_code，可以是一个代码，也可以是一组代码的list

再比如：场内基金日线行情，
df = pro.fund_daily(ts_code='150018.SZ', trade_date=‘20190729’)，这里的ts_code，可以是一个代码，也可以是一组代码的list

谢谢！我主要是做指数和ETF基金的

**Comment by jimmysoa** [comment]
暂时要过一段时间，目前还不能支持
