### ISSUE TITLE
按照文档 用微信转账 50 元，没有被添加到高级群.

### ISSUE THREAD

**Issue by Mic1223211** [waditu/tushare#1107]
我可以提供微信转账截图，QQ： 493255328 , 请大神方便的时候处理下。 
2019年 7月31号  11 点 12分转的,谢谢。

**Comment by jimmysoa** [comment]
您的QQ加不上，要求填写真实姓名来认证。

**Comment by Mic1223211** [comment]
已经实名认证可以 再看以下么?

**Comment by jimmysoa** [comment]
还是需要输入你的真实姓名作为验证，我并不知道你的真名，这样吧，你加我的微信：migedatas 
然后给我你的Tushare账号就可以了
