### ISSUE TITLE
get_k_data()取出的数据是没有复权的 无论是否加autype='qfq'

### ISSUE THREAD

**Issue by pinglife** [waditu/tushare#1108]
get_k_data()取出的数据是没有复权的 无论是否加autype='qfq'.
默认和autype='qfq'取出的数据都和None一样.

**Comment by fenghuting** [comment]
我也一样有这个问题,更新版本后也是一样,怎么测都是不复权的数据.

**Comment by jimmysoa** [comment]
需要确定确实有没有复权。
另外，建议用pro版复权行情：https://tushare.pro/document/2?doc_id=146
