### ISSUE TITLE
业绩预告p_change_min, p_change_max无数据时返回值不统一

### ISSUE THREAD

**Issue by hbzong** [waditu/tushare#1109]
调用业绩预告时返回的p_change_min, p_change_max有的没有数据，当没有数据的时候，有的是标记成nan或NaN,type是numpy.float64，但是有的返回的是None，type显示是“<class 'NoneType'>“。

email: hbzong@qq.com

**Comment by jimmysoa** [comment]
目前是pandas自动识别，还没有做过多处理，用户暂时先自行过滤一下
