### ISSUE TITLE
请问历史行情没有成交额(amount),非日线的历史行情如何得到成交额？

### ISSUE THREAD

**Issue by Twilightlee** [waditu/tushare#111]
**get_hist_data**函数返回值没有“**成交额(amount)**”

**get_h_data**函数返回值有“**成交额(amount)**”，但是不能指定ktype

请问：**非日线的历史行情如何得到成交额？**

**Comment by jimmysoa** [comment]
sorry，目前还有找到好用的数据源。用get_tick_data来算是可以的

**Comment by Twilightlee** [comment]
明白了，多谢热心解答。
