### ISSUE TITLE
可转债基础信息cb_basic 以及 可转债行情cb_daily 都返回空dataframe

### ISSUE THREAD

**Issue by jkg77** [waditu/tushare#1110]
cb_basic()和cb_daily返回的是空的dataframe

**Comment by jimmysoa** [comment]
暂时还没上，行情是好的

**Comment by jkg77** [comment]
> 暂时还没上，行情是好的

是暂时还不支持的意思？文档说是可以用的哦

https://tushare.pro/document/2?doc_id=185
https://tushare.pro/document/2?doc_id=187

**Comment by jkg77** [comment]
> 暂时还没上，行情是好的

行情是好的意思是cb_daily()是可用的？您可以给个例子吗？我这里下面两个例子：
![image](https://user-images.githubusercontent.com/29140996/62529593-842f0500-b871-11e9-80c9-c7dcc878bda1.png)
都报错：
![image](https://user-images.githubusercontent.com/29140996/62529643-9741d500-b871-11e9-93e9-0b33041eed46.png)

**Comment by jimmysoa** [comment]
https://tushare.pro/document/2?doc_id=159
数据示例里有ts_code 你按照这种格式来

**Comment by jkg77** [comment]
> https://tushare.pro/document/2?doc_id=159
> 数据示例里有ts_code 你按照这种格式来

你给的例子是期权的例子。

我上面给的你们自己的链接才是可转债的，而且事例给的还是错的fx的。
https://tushare.pro/document/2?doc_id=187


![image](https://user-images.githubusercontent.com/29140996/62596122-877acd00-b913-11e9-855b-0933143cf950.png)
