### ISSUE TITLE
stock_company() employee 和main_business 返回位置错误

### ISSUE THREAD

**Issue by wanghan7678** [waditu/tushare#1111]
I'm running the following code:

fstr = 'ts_code, employees, main_business, business_scope'
pro = ts.get_tushare_api()
df = pro.stock_company(exchange='SZSE', fields=fstr)

print(df.iat[1,0])
print(df.iat[1,1])
print(df.iat[1,2])
print(df.iat[1,3])

It prints the below:

300696.SZ
机械零部件、模具、机电设备、电子元器件、成套电缆及电缆线束总成的设计、制造、销售；飞机零部件、地面设备的研发、制造、修理、技术服务及销售；飞机零部件的特种检测、理化试验及热表处理；货物及技术进出口(以上经营项目不含前置许可项目、后置许可项目凭许可证或审批文件经营)(依法须经批准的项目，经相关部门批准后方可展开经营活动)。
393.0
主营业务:公司立足航空领域,报告期内主要从事军用飞机和民用客机零部件的精密加工业务.主要产品:飞机机身,机翼,尾翼,起落架等机体相关零部件的精密加工.

The order of the fields of "employee, main_business, and business_scope" is incorrect. 

My username of tussore is 'LANWANGWANG'

**Comment by jimmysoa** [comment]
有些字段默认不显示，需要在fields里指定才可以

**Comment by wanghan7678** [comment]
字段在fstr中指定了。问题是：返回时，第二列应该是employee,第三列是main_business。但结果两个反了。

**Comment by jimmysoa** [comment]
你再确认一下，直接打印df看看，我看了没有问题

**Comment by wanghan7678** [comment]
挺奇怪的，去掉最后一个字段“business_scope”就是对的。但是加上就是错的。

import GinaTech02.Cnstock_tushare as ts

pro = ts.get_tushare_api()
df = pro.stock_company(exchange='SZSE', fields='ts_code, employees, main_business, business_scope')

print(df.iat[1,0])
print(df.iat[1,1])
print(df.iat[1,2])
print(df.iat[1,3])

print("-----------------------------------")

pro = ts.get_tushare_api()
df = pro.stock_company(exchange='SZSE', fields='ts_code, employees, main_business')

print(df.iat[1,0])
print(df.iat[1,1])
print(df.iat[1,2])


结果：
002960.SZ
消防设备研发、生产销售、代理；自营进出口业务；普通货运(仅限分支机构经营)。(法律、行政法规、国务院决定设定的许可经营项目，须取得许可并经登记机关登记后方可经营)
2135.0
主营业务:消防安全系统产品的研究,开发,生产和销售.主要产品:火灾自动报警及联动控制系统,电气火灾监控系统,自动气体灭火系统和气体检测监控系统等四大类消防安全系统产品.
-----------------------------------
002960.SZ
2135.0
主营业务:消防安全系统产品的研究,开发,生产和销售.主要产品:火灾自动报警及联动控制系统,电气火灾监控系统,自动气体灭火系统和气体检测监控系统等四大类消防安全系统产品.
