### ISSUE TITLE
1.2.39版本，抱歉，没有pro_bar接口

### ISSUE THREAD

**Issue by PCreamix** [waditu/tushare#1113]
`pro =tushare.set_token(xxxxx) 

data = pro.pro_bar(xxxxxx)`

提示》》》》Exception: 抱歉，没有pro_bar接口

但是用
`pro =tushare.set_token(xxxxx)

data=tushare.pro_bar(api=pro, xxxx)`
可以调用成功

**Comment by jimmysoa** [comment]
上面用法错误，下面对的
