### ISSUE TITLE
version 1.2.35 : ts.get_k_data 日线前复权收盘价有问题

### ISSUE THREAD

**Issue by swimmingcarp** [waditu/tushare#1115]
Hi,

调用 get_k_data 接口获取前复权股票价格，发现部分股票代码前复权有问题。

例如，调用：ts.get_k_data('603963', autype = 'qfq')
显示如下收盘价：
```
5/24/2019 ， 13.29
5/27/2019 ， 13.86
```
实际前复权收盘价为：
```
5/24/2019 ， 10.16
5/27/2019 ， 10.60
```
实际上通过 autype = 'qfq' 调用的收盘价是除权收盘价，并非前复权。

另外，603721，通过 ts.get_k_data('603721', autype = 'qfq')，获取到的前复权收盘价也有问题，同样是除权价格：

```
5/20/2019 ， 19
5/21/2019， 19.01
5/22/2019 ， 19
5/23/2019， 18.93
```

能否麻烦帮忙修复一下这个问题？

Thanks.
Carp

**Comment by jimmysoa** [comment]
旧版的目前不去看了，建议用pro版的复权接口：https://tushare.pro/document/2?doc_id=146

**Comment by swimmingcarp** [comment]
Okay.
