### ISSUE TITLE
股票代码更换导致的数据重复

### ISSUE THREAD

**Issue by wilsonzhu172** [waditu/tushare#1117]
000022.SZ深赤湾A股票在18年12月后换了名称和代码为001872.SZ招商港口，001872中包含了之前所有的历史行情，但是000022的行情也依然存在，这样会导致18年之前的数据中，这支股票被重复算了两次，建议删除000022.SZ的相关数据。目前在daily_basic和daily_中都发现了这样的冗余。

**Comment by jimmysoa** [comment]
做了历史延续到补齐，不影响数据使用
