### ISSUE TITLE
Pro Api pro_bar 接口缺失

### ISSUE THREAD

**Issue by aufalau** [waditu/tushare#1120]
Pro Api 调用pro_bar 时，抛出异常 ： 抱歉，没有pro_bar接口

**Comment by MartyLinZY** [comment]
用ts.pro_bar试下？

**Comment by sunyymq** [comment]
可能是使用之前没pro = ts.pro_api(token='xxxx')吧，需要在ts.pro_bar里带入参数pro_api = pro

**Comment by jimmysoa** [comment]
确认：
1、使用ts.而不是pro.
2、程序名不要用tushare.py
3、tushare SDK升级到最新版
