### ISSUE TITLE
pro_bar 获取数据报错

### ISSUE THREAD

**Issue by GoRockets** [waditu/tushare#1121]
运行以下代码时
data = tushare.pro_bar(xxxxx)

出现错误，显示：
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-23: ordinal not in range(128)

**Comment by sunyymq** [comment]
可能是使用之前没pro = ts.pro_api(token='xxxx')吧，需要在ts.pro_bar里带入参数pro_api = pro

**Comment by xinxu75** [comment]
遇到同样问题，tushare.pro_bar中已带入参数api = pro，仍显示错误：
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-23: ordinal not in range(128)以前同样的代码运行没出错
顺便提一下，最新版本里pro_bar参数pro_api=好像变成了api=

**Comment by jimmysoa** [comment]
Tushare SDK升级到最新版
