### ISSUE TITLE
上证指数日线获取不到

### ISSUE THREAD

**Issue by Whpitot** [waditu/tushare#1126]
刚刚试了上证指数，沪深300指数获取不到，可以看下是什么原因吗。
`df = pro.index_daily(ts_code='1B0300.SH', start_date='20190820', end_date='20190822')`

得到结果
```
Columns: [ts_code, trade_date, close, open, high, low, pre_close, change, pct_chg, vol, amount]
Index: []
```
上证指数代码：1A0001.SH
沪深300指数代码：1B0300.SH

平台ID: rainrow@live.com

**Comment by jimmysoa** [comment]
代码错误，请从https://tushare.pro/document/2?doc_id=94获取
