### ISSUE TITLE
权限访问

### ISSUE THREAD

**Issue by xinxu75** [waditu/tushare#1128]
更新SDK版本至1.2.41，刷新token，但运行
pro = ts.pro_api('...')
ts.pro_bar(api=pro, ts_code=scode, adj='hfq', start_date=sdt, end_date=edt)
时遇到以下报错：

抱歉，您没有权限访问该接口，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

**Comment by jimmysoa** [comment]
大于100积分才可以了，谢谢。
