### ISSUE TITLE
AttributeError: 'Engine' object has no attribute 'rollback'

### ISSUE THREAD

**Issue by tedljw** [waditu/tushare#113]
hi, I try to store data to mysql,but failed. Can you tell me what wrong with me.

computer information:
Linux 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 2.7.6

error log:

> > > from sqlalchemy import create_engine
> > > import tushare as ts
> > > df=ts.get_tick_data('600848', date='2016-04-15')
> > > engine = create_engine('mysql://root:123@localhost/test')>>> df.to_sql('tick_data',engine)
> > > Error on sql SELECT name FROM sqlite_master WHERE type='table' AND name='tick_data';
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1261, in to_sql
> > >     self, name, con, flavor=flavor, if_exists=if_exists, **kwargs)
> > >   File "/usr/lib/python2.7/dist-packages/pandas/io/sql.py", line 207, in write_frame
> > >     exists = table_exists(name, con, flavor)
> > >   File "/usr/lib/python2.7/dist-packages/pandas/io/sql.py", line 275, in table_exists
> > >     return len(tquery(query, con)) > 0
> > >   File "/usr/lib/python2.7/dist-packages/pandas/io/sql.py", line 90, in tquery
> > >     cur = execute(sql, con, cur=cur)
> > >   File "/usr/lib/python2.7/dist-packages/pandas/io/sql.py", line 53, in execute
> > >     con.rollback()
> > > AttributeError: 'Engine' object has no attribute 'rollback'

**Comment by smrithikolvi** [comment]
Hi, Can you tell me what was the solution for this issue : "Engine object has no attribute rollback"??
