### ISSUE TITLE
限售股解禁数据重复

### ISSUE THREAD

**Issue by gl-data** [waditu/tushare#1130]
在调取限售股解禁资料的时候，部分数据会重复出现，e.g.
`df= pro.share_float(ts_code='002933.sz',float_date='20190828')
df[['ann_date','float_date','float_share','holder_name']]`

返回结果为：
`   ann_date float_date  float_share             holder_name

0  20180827   20190828    7700000.0      北京科桥嘉永创业投资中心(有限合伙)

1  20180827   20190828    7368819.0                      张进

2  20180827   20190828    7368819.0                     张建迪

3  20180827   20190828    4400000.0  重庆西证价值股权投资基金合伙企业(有限合伙)

4  20180827   20190828    1100000.0      杭州聚登投资管理合伙企业(有限合伙)

5  20180827   20190828     475261.0                     郎安中

6  20180827   20190828    7936217.0                 其他自然人股东

7  20190827   20190828    7700000.0      北京科桥嘉永创业投资中心(有限合伙)

8  20190827   20190828    4400000.0  重庆西证价值股权投资基金合伙企业(有限合伙)

9  20190827   20190828    1100000.0      杭州聚登投资管理合伙企业(有限合伙)`

返回的结果中，第7-9条和第0、3、4条是重复的，而提出之后就和网站上的结果一致了
http://stock.jrj.com.cn/share,002933,xsjj.shtml

平台邮箱：gl_data@126.com

**Comment by jimmysoa** [comment]
看了一下是好了的
