### ISSUE TITLE
[dividend()]分红送配接口返回的数据中有重复的数据

### ISSUE THREAD

**Issue by whwalker** [waditu/tushare#1133]
dividend()，分红送配接口返回的数据中有重复的数据，比如
import tushare as ts
tsp = ts.pro_api()
df = tsp.dividend(ts_code='002540.SZ', fields='div_proc,stk_div,cash_div_tax,end_date,ex_date')
df = df.query('div_proc==\'实施\'')
print(df)
会打印以下数据，可以看到前3条数据都是重复的
    end_date div_proc  stk_div  cash_div  cash_div_tax   ex_date
1   20181231       实施      0.0  0.320297      0.320297  20190612
2   20181231       实施      0.0  0.320297      0.320297  20190612
7   20181231       实施      0.0  0.320297      0.320297  20190612
9   20171231       实施      0.0  0.060000      0.060000  20180621
10  20161231       实施      0.0  0.060000      0.060000  20170524
11  20151231       实施      0.0  0.050000      0.050000  20160617
12  20141231       实施      1.5  0.000000      0.000000  20150413
13  20131231       实施      0.0  0.190000      0.200000  20140507
14  20121231       实施      1.0  0.190000      0.200000  20130506
15  20111231       实施      0.0  0.225000      0.250000  20120529
16  20101231       实施      0.3  0.180000      0.200000  20110509

**Comment by jimmysoa** [comment]
有修正过的要调取update_flag指标过滤出来
