### ISSUE TITLE
关于新上南华期货指数问题

### ISSUE THREAD

**Issue by Septembear** [waditu/tushare#1137]
`import tushare as ts
import csv
ts.__version__

ts.set_token('**************')

pro = ts.pro_api()

#获取南华指数
df = pro.index_daily(ts_code='TA.NH', start_date='20180101', end_date='20190901')

print(df.head())

df.to_csv('PTA_NH_index_.csv')`

代码本身没有问题，但提取到的数据是南华PTA期货指数中的收益率指数，而非价格指数，希望得到关注并修改，或者分列收益率指数和价格指数为不同提取代码；也请复核其他品种是否也存在同样情况。

**Comment by Septembear** [comment]
ID:Jason

**Comment by Foristkirito** [comment]
我也有这个问题，不过我更在意的是，有没有地方能订阅南华指数的 tick 行情，花钱也可以

**Comment by jimmysoa** [comment]
我们努力，谢谢

**Comment by Foristkirito** [comment]
> 我们努力，谢谢

请问南华指数有 kbar 的数据吗？收费的也行。然后想请教一下你们这个南华的数据是怎么算出来的？

**Comment by Foristkirito** [comment]
> 我们努力，谢谢

急需

**Comment by jimmysoa** [comment]
有的
