### ISSUE TITLE
api error--from (brave_shi@163.com)

### ISSUE THREAD

**Issue by brave-shi** [waditu/tushare#1140]
df = ts.pro_bar(ts_code=stock_code,start_date=start, end_date=end, \
                 adj='qfq', ma=[20,60])
如没有qfq，没有报错，如果添加qfq，就会报下面错误，WIN10 python 3.7环境
传入参数：ts_code 600000.SZ start_date '20180111' end_date '20190510'

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tushare\pro\data_pro.py", line 182, in pro_bar
    raise IOError('ERROR.')
OSError: ERROR.

**Comment by jimmysoa** [comment]
Tushare sdk 请升级到最新版
