### ISSUE TITLE
get_tick_data报错

### ISSUE THREAD

**Issue by Mng12345** [waditu/tushare#1145]
使用`get_tick_data("000523", "2019-09-23")`返回为None，使用`get_tick_data("000523", "2019-09-23", src="tt")`报`HTTP Error 502: Bad Gateway`

**Comment by Mng12345** [comment]
调用新浪的url为`http://market.finance.sina.com.cn/downxls.php?date=2000-01-01&symbol=sz000523`在浏览器端调用，返回`服务已下线`，调用腾讯的url为`http://stock.gtimg.cn/data/index.php?appn=detail&action=download&c=sz000523&d=20000101`，返回`502 Bad Gateway`，调用网易的url为`http://quotes.money.163.com/cjmx/2000/20000101/1000523.xls`，返回`页面不存在`

**Comment by jimmysoa** [comment]
服务停止
