### ISSUE TITLE
stock_basic接口系统内部错误

### ISSUE THREAD

**Issue by lscho** [waditu/tushare#1148]
![image](https://user-images.githubusercontent.com/11583677/65825165-4913e580-e2a6-11e9-9c41-19a19a0cf7a7.png)

**Comment by lucyTheSlayer** [comment]
同样的情况，一直运行良好的接口近期报错

`{'request_id': 'be3b4338e31b11e997f837ce0efa10141569804390668817', 'code': -1000, 'msg': '系统内部错误', 'data': None}`

**Comment by lucyTheSlayer** [comment]
试了一下，应该是他们后台改动，我用的python的requests，之前的代码是：
`        r = requests.post("http://api.waditu.com", json={
            "api_name": "stock_basic",
            "token": TS_TOKEN,
            "fields": "symbol,name"
        }, timeout=10)`
改动后：
`r = requests.post("http://api.waditu.com", json={
            "api_name": "stock_basic",
            "token": TS_TOKEN,
            "params": {},
            "fields": "symbol,name"
        }, headers={'Content-Type': 'application/json'}, timeout=10)`
总结有两个点
1) **"params": {}** 就算为空也得写上去
2）**headers={'Content-Type': 'application/json'}** 必须指明Content-Type为application/json
这样就又能正常访问了

**Comment by lscho** [comment]
问题已解决，咨询官方技术，解决方法如上 @lucyTheSlayer 所示
