### ISSUE TITLE
通用行情接口获取300价值指数数据缺失

### ISSUE THREAD

**Issue by Jingle-seven** [waditu/tushare#1149]
![image](https://user-images.githubusercontent.com/18697377/65835188-f114c780-e315-11e9-9470-d00a1db1bedb.png)
300价值指数缺失近一年的数据，而沪深300则没问题。是系统数据库没有这部分数据吗？
![image](https://user-images.githubusercontent.com/18697377/65835206-2f11eb80-e316-11e9-98de-94ef499a9315.png)

**Comment by jimmysoa** [comment]
目前只有常用指数能保证
