### ISSUE TITLE
2019年10月11日调取个股龙虎榜明细数据重复

### ISSUE THREAD

**Issue by zssqljw** [waditu/tushare#1158]
入参如下

{
"api_name":"top_inst",
"token":"2d5c52d18f5da47c250f862f8cc6ceb3abc96b7af0b29007cc64ac91",
"params":{"trade_date":"20191011","ts_code":"002819.SZ"}, 
"fields":""
}

一个返回了20条记录

Tushare 注册邮箱：317377720@qq.com

**Comment by jimmysoa** [comment]
没有复现，谢谢
