### ISSUE TITLE
如何获得一段时间多只股票的历史分笔数据？

### ISSUE THREAD

**Issue by slippedgrey** [waditu/tushare#116]
`df` = `tushare.get_tick_data(‘6000484’,date=?)`

这个 语句是只能获得一只股票某一天的的数据吗？

我想获得一段时间多只股票的历史分比数据
请问该怎么做，谢谢了！

**Comment by ArthurAnanda** [comment]
我在tushare里面也没有找到同时获取多只股票行情数据的接口，但是你可以写一个循环把所有股票的数据并在一张表里
