### ISSUE TITLE
最近不能获取数据了？

### ISSUE THREAD

**Issue by yanghui1228** [waditu/tushare#1160]
In [5]: ts.get_today_all()                                                                
[Getting data:]#---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-5-817e78bf95ae> in <module>
----> 1 ts.get_today_all()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tushare/stock/trading.py in get_today_all()
    315     """
    316     ct._write_head()
--> 317     df = _parsing_dayprice_json('hs_a', 1)
    318     if df is not None:
    319         for i in range(2, ct.PAGE_NUM[1]):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tushare/stock/trading.py in _parsing_dayprice_json(types, page)
    117     request = Request(ct.SINA_DAY_PRICE_URL%(ct.P_TYPE['http'], ct.DOMAINS['vsf'],
    118                                  ct.PAGES['jv'], types, page))
--> 119     text = urlopen(request, timeout=10).read()
    120     if text == 'null':
    121         return None

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 456:

**Comment by jimmysoa** [comment]
这个接口你用的太频繁会被限制
