### ISSUE TITLE
龙虎榜明细数据缺失问题

### ISSUE THREAD

**Issue by zssqljw** [waditu/tushare#1161]
2019-08-01 值得买    没有龙虎榜明细数据 ，请帮忙看看
{"trade_date":"20190801","ts_code":"300785.SZ"}, 

东方财富网是有的
[http://data.eastmoney.com/stock/lhb,2019-08-01,300785.html](url)

 tushare e-mail address: 317377720@qq.com

**Comment by jimmysoa** [comment]
已经好了，谢谢
