### ISSUE TITLE
python3.7.4中安装时提示找不到对应的版本

### ISSUE THREAD

**Issue by Lanyd518** [waditu/tushare#1162]
操作系统是CentOS6.5，安装的python是最新的3.7.4，pip是19.0.3，setuptools是40.8.0
# python3 -m pip install tushare -i http://pypi.python.org/simple --trusted-host pypi.python.org
Looking in indexes: http://pypi.python.org/simple
Collecting tushare
  Could not find a version that satisfies the requirement tushare (from versions: )
No matching distribution found for tushare

**Comment by jimmysoa** [comment]
pip install tushare 安装即可
