### ISSUE TITLE
LIBOR数据不能更新到最新的，有计划什么时候恢复？

### ISSUE THREAD

**Issue by mumumiya** [waditu/tushare#1164]
目前LIBOR只能获取19年8月的数据，后面有计划恢复获取最新的吗？

**Comment by jimmysoa** [comment]
目前暂停了，过一段时间看需求再决定是否继续，谢谢

**Comment by bopo** [comment]
这个问题，我已经提交了pr了，请求合并

**Comment by jimmysoa** [comment]
请使用pro版的shibor接口

**Comment by mumumiya** [comment]
好，谢谢
 
---原始邮件---
发件人: "Jimmy"<notifications@github.com&gt;
发送时间: 2019年10月22日(星期二) 晚上10:29
收件人: "waditu/tushare"<tushare@noreply.github.com&gt;;
抄送: "mumumiya"<ghost.hust@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [waditu/tushare] LIBOR数据不能更新到最新的，有计划什么时候恢复？ (#1164)



请使用pro版的shibor接口

**Comment by mumumiya** [comment]
谢谢，shibor我也在用。


 
---原始邮件---
发件人: "Jimmy"<notifications@github.com&gt;
发送时间: 2019年10月22日(星期二) 晚上10:29
收件人: "waditu/tushare"<tushare@noreply.github.com&gt;;
抄送: "mumumiya"<ghost.hust@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [waditu/tushare] LIBOR数据不能更新到最新的，有计划什么时候恢复？ (#1164)



请使用pro版的shibor接口
