### ISSUE TITLE
000011在20150609这天的分笔数据有误

### ISSUE THREAD

**Issue by SuperPcBull** [waditu/tushare#117]
000011在20150609这天的分笔数据只到11:20:00，该行change为NaN，且之后的时间无数据，具体如下：

tushare.get_tick_data('000011',date='2015-06-09')
打印结果：
time  price  change  volume   amount type
0         11:2    NaN  -19.37       0        0   卖盘
1     11:21:59  19.37    0.02      15    29055   卖盘
2     11:21:56  19.35   -0.03      30    58050   卖盘
3     11:21:53  19.38    0.01      33    63954   买盘
4     11:21:50  19.37      --      12    23244   买盘
5     11:21:46  19.37    0.01      19    36803   买盘
6     11:21:43  19.36   -0.02     216   418176  中性盘
7     11:21:40  19.38      --     102   197676   买盘
8     11:21:37  19.38      --       6    11628   买盘
9     11:21:34  19.38    0.02      18    34884   买盘
10    11:21:25  19.36   -0.02      62   120032   卖盘

**Comment by jimmysoa** [comment]
新浪财经数据源错误，我看了下这个股票这一天确实没有。

**Comment by SuperPcBull** [comment]
感谢大神答复！
能否告知下新浪财经数据源的网址啊，是不是这个网址：http://finance.sina.com.cn/realstock/company/sz000011/nc.shtml。

还有下面这个股票这天数据返回也有问题，是不是数据源编码格式不对：
ts.get_tick_data('000016',date='2004-12-14')
打印如下：
'gbk' codec can't decode byte 0xff in position 2351: illegal multibyte sequence
'gbk' codec can't decode byte 0xff in position 2351: illegal multibyte sequence
'gbk' codec can't decode byte 0xff in position 2351: illegal multibyte sequence
Traceback (most recent call last):
  File "F:/PycharmProjects/Stock/main.py", line 27, in <module>
    print(ts.get_tick_data('000016',date='2004-12-14'))
  File "D:\Python34\lib\site-packages\tushare\stock\trading.py", line 166, in get_tick_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络和URL
