### ISSUE TITLE
stk_holdernumber接口存在公告日期小于截止日期的问题

### ISSUE THREAD

**Issue by 256481788jianghao** [waditu/tushare#1181]
不可能公告截止日期前的股东人数吧，以下是部分查询结果：

0	601077.SH	20191028	20191029	948725
1	603610.SH	20191028	20191029	40451
2	688098.SH	20191025	20191028	32032
3	002963.SZ	20191025	20191028	74129
4	688139.SH	20191024	20191025	63867
5	002965.SZ	20191024	20191025	73640
6	300795.SZ	20191021	20191022	51653
8	603815.SH	20191018	20191021	51493
252	300793.SZ	20191017	20191018	81581
254	603786.SH	20191014	20191015	42083
256	688368.SH	20191011	20191014	15123
2375	688068.SH	20190927	20190930	15087
2376	688030.SH	20190927	20190930	33813
2377	688036.SH	20190927	20190930	45171
2379	300792.SZ	20190926	20190927	39993
2383	300791.SZ	20190924	20190925	39993
2384	688116.SH	20190924	20190925	46650
2784	300790.SZ	20190919	20190920	57875
2787	002962.SZ	20190916	20190917	96968
3176	603927.SH	20190906	20190909	45334
3178	688168.SH	20190905	20190906	12895
3179	002961.SZ	20190904	20190905	86870
3637	603093.SH	20190829	20190830	68807
3640	300789.SZ	20190827	20190828	23003
3641	603755.SH	20190827	20190828	28253
3644	603992.SH	20190823	20190826	42955
3645	003816.SZ	20190823	20190826	
3647	002959.SZ	20190822	20190823	60075

**Comment by jimmysoa** [comment]
有啥问题？一般收盘后公布的公告日期都算下一个交易日的
