### ISSUE TITLE
stk_holdernumber接口获取的数据中holder_num包含NaN

### ISSUE THREAD

**Issue by 256481788jianghao** [waditu/tushare#1183]
这些NaN的原因是什么呢？公告日没有公告股东人数？数据如下：
       index    ts_code  ann_date  end_date  holder_num
2632     879  000037.SZ  20190328  20190228     32518.0
4836     593  000037.SZ  20190423  20190331     32518.0
9032      82  000037.SZ  20190515  20190510     18330.0
10640    231  000037.SZ  20190627  20190620     29664.0
10686    277  000037.SZ  20190627  20190620         NaN
11037    291  000037.SZ  20190708  20190628         NaN
11577    446  000037.SZ  20190816  20190630     28383.0
14904    107  000037.SZ  20190712  20190710         NaN
15168     28  000037.SZ  20190722  20190719         NaN
15658    131  000037.SZ  20190802  20190731     26849.0
16234    244  000037.SZ  20190815  20190809         NaN
16374     16  000037.SZ  20190821  20190820         NaN
16888    151  000037.SZ  20190903  20190830         NaN
17204      4  000037.SZ  20190911  20190910         NaN
17586      0  000037.SZ  20190919  20190916         NaN
17594      4  000037.SZ  20190923  20190920         NaN
18072     75  000037.SZ  20191008  20190930         NaN
19021   1024  000037.SZ  20191025  20190930     25172.0
19891     92  000037.SZ  20191012  20191010     25160.0
20168     46  000037.SZ  20191021  20191018         NaN

**Comment by jimmysoa** [comment]
是的，有些是缺的，已经补齐
