### ISSUE TITLE
tushare-1.2.18版本中 tushare\stock\trading.py 中from pandas.compat import StringIO 引用错误

### ISSUE THREAD

**Issue by dengwuyong** [waditu/tushare#1185]
tushare-1.2.18版本中 tushare\stock\trading.py  中from pandas.compat import StringIO 引用错误。
我装的是anacoda3，python版本为3.7.4 pandas版本是0.25.1，pandas.compat模块中没有 StringIO这个类，无法引用。我看了下源代码，tradeing.py是2014年写的，是否是引用的python27版本的pandas或者是其他版本的pandas呢 ？
ID:106830195@qq.com

**Comment by dengwuyong** [comment]
ID:106830195@qq.com

**Comment by dengwuyong** [comment]
刚刚尝试了下，python27的pandas的版本 0.24的确有pandas.compat import StringIO这个方法，Python3的pandas应该是没有了，直接在IO这个库里面有  这个引用有问题

**Comment by jimmysoa** [comment]
Tushare升级到最新版就好了，谢谢
