### ISSUE TITLE
新需求：指数日线行情(index_daily)接口，是否可以一次性下载当日所有指数数据

### ISSUE THREAD

**Issue by jasonshi1975** [waditu/tushare#1187]
指数日线行情(index_daily)接口，是否可以参考daily接口，输入trade_date，不输入ts_code，一次性下载当日所有指数数据，这样可以大大提高每日数据下载的速度
账号昵称：jasonshi

**Comment by jimmysoa** [comment]
指数太多，目前只提供各自常用的，按代码提取。谢谢
