### ISSUE TITLE
income接口存在重复数据

### ISSUE THREAD

**Issue by mjzxcvbnm** [waditu/tushare#1188]
df = pro.income(ts_code='002081.SZ')

df[['ts_code','ann_date', 'end_date', 'revenue']]
Out[107]: 
      ts_code  ann_date  end_date       revenue
0   002081.SZ  20191026  20190930  2.274064e+10
1   002081.SZ  20191026  20190930  2.274064e+10
2   002081.SZ  20190822  20190630  1.379563e+10
3   002081.SZ  20190822  20190630  1.379563e+10
4   002081.SZ  20190427  20190331  6.057030e+09
..        ...       ...       ...           ...
56  002081.SZ  20070419  20060331  4.051463e+08
57  002081.SZ  20061025  20051231  1.293130e+09
58  002081.SZ  20061117  20050930  8.679204e+08
59  002081.SZ  20061025  20041231  9.821815e+08
60  002081.SZ  20061025  20031231  6.821119e+08

[61 rows x 4 columns]

index 0和1重复
index 2和3重复

tushare账号：331870398@qq.com

**Comment by jimmysoa** [comment]
如果有修正的可能会有两条，请根据update_flag确定
