### ISSUE TITLE
ts.get_today_ticks函数无法在交易时间获取数据

### ISSUE THREAD

**Issue by SuperPcBull** [waditu/tushare#119]
譬如 ts.get_today_ticks('000001')
报错内容：
 [Getting data:]#ElementTree not initialized, missing root
ElementTree not initialized, missing root
ElementTree not initialized, missing root
获取失败，请检查网络和URL
[Getting data:]#ElementTree not initialized, missing root
ElementTree not initialized, missing root
ElementTree not initialized, missing root
获取失败，请检查网络和URL
[Getting data:]#ElementTree not initialized, missing root
ElementTree not initialized, missing root
ElementTree not initialized, missing root
获取失败，请检查网络和URL
Traceback (most recent call last):
  File "F:/PycharmProjects/Stock/main.py", line 45, in <module>
    ts.get_today_ticks('000001')
  File "D:\Python34\lib\site-packages\tushare\stock\trading.py", line 254, in get_today_ticks
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络和URL

**Comment by jimmysoa** [comment]
你的Python是哪个版本？我试了下没问题

**Comment by SuperPcBull** [comment]
我是3.4.4

**Comment by jimmysoa** [comment]
测试了一下也没问题啊，好奇怪。。。。。

**Comment by SuperPcBull** [comment]
哦，知道了！我再试试看，感谢waditu作答！！！
