### ISSUE TITLE
发现IPO数据没有及时更新

### ISSUE THREAD

**Issue by thorns2008** [waditu/tushare#1193]
感谢米哥，开源免费提供服务。

今天发现IPO数据没有及时更新，数据提取日期：2019-11-06 11:23

主要代码：
df = pro.new_share(start_date='20191106', end_date='20191130')
print(df[['ts_code','name','ipo_date','price','limit_amount']])

得到数据：
      ts_code  name  ipo_date  price  limit_amount
0   002968.SZ   新大正  20191120  26.76          1.75
1   300801.SZ  泰和科技  20191119  30.42          1.20
2   601916.SH  浙商银行  20191114   4.94         76.50
3   300806.SZ   斯迪克  20191113   0.00          1.15
4   300798.SZ  锦鸡股份  20191112   5.53          1.25
5   300805.SZ  电声股份  20191112   0.00          1.25
6   688196.SH  卓越新能  20191111   0.00          0.85
7   688138.SH  清溢光电  20191111   0.00          1.90
8   601658.SH  **邮储银行  20191107**   0.00         93.00
9   688111.SH  金山办公  20191107   0.00          1.40
10  688101.SH   三达膜  20191106   **0.00**          2.40
11  300803.SZ   指南针  20191106   **0.00**          1.70

数据没有及时更新：
1. 20191106   三达膜、指南针两只新股 IPO ，price 均为 0.00，已经是申购日了，申购价不可能还没公布。
2. 20191107  邮储银行 的IPO日期，早已改为　2019-11-28

**Comment by jimmysoa** [comment]
我们是定期刷新的，没事多刷刷
