### ISSUE TITLE
个股资金流向的数据有时候木有哦

### ISSUE THREAD

**Issue by thegreenflamingo** [waditu/tushare#1196]
`df = pro.moneyflow(ts_code = t_code, start_date = earlier_date, end_date = later_date)`
这个方法中，例如对于001872.SZ这只股票，当选取的时间范围是20120605-20120705的时候，返回的数据是null哈。

不知道是不是我错了哈。。。
谢谢waditu的团队了哈
id: 13916008459， 郑行健

**Comment by jimmysoa** [comment]
这个股票代码那时候还没有啊
