### ISSUE TITLE
调用通用行情接口, 有时会丢失数据

### ISSUE THREAD

**Issue by maizi123** [waditu/tushare#1199]
调用过程：
1） 调用pro.stock_basic获取股票列表。
2）根据获取到的股票列表，依次下载股票行情数据（时间跨度大于40天）。在下载过程中有某些股票的数据下载失败，每次下载失败的股票都不同（似乎是随机的）。

tushare user id: maizi
email: 15653535325@163.com or zhang.yuechuan@yahoo.com

**Comment by jimmysoa** [comment]
取决于积分，积分太少频次又太高，循环会被中断
