### ISSUE TITLE
reference.py中profit_data的bug

### ISSUE THREAD

**Issue by hezongjian** [waditu/tushare#120]
profit_data函数的前几行：
  
  if top <= 25:
        df, pages = _dist_cotent(year, 0, retry_count, pause)
        return df.head(top)
    elif top == 'all':

top不可能又是个整数又是个'all'的。如果指定了‘all'，前面那个if会导致类型不匹配错误。

**Comment by jimmysoa** [comment]
你是学Java/C的吧？ ^_^

**Comment by hezongjian** [comment]
这个是我iPython的输入，我哪里用的有问题么？

In [1]: import tushare as ts

In [2]: a = ts.profit_data(top='all')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-2ecae1950685> in <module>()
----> 1 a = ts.profit_data(top='all')

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tushare/stock/reference.py in profit_data(year, top, retry_count, pause)
     50     shares:转增和送股数（每10股）
     51     """
---> 52     if top <= 25:
     53         df, pages = _dist_cotent(year, 0, retry_count, pause)
     54         return df.head(top)

TypeError: unorderable types: str() <= int()

**Comment by hezongjian** [comment]
In [3]: a = ts.profit_data(year=2014,top='all')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-95e9aa30f0c8> in <module>()
----> 1 a = ts.profit_data(year=2014,top='all')

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tushare/stock/reference.py in profit_data(year, top, retry_count, pause)
     50     shares:转增和送股数（每10股）
     51     """
---> 52     if top <= 25:
     53         df, pages = _dist_cotent(year, 0, retry_count, pause)
     54         return df.head(top)

TypeError: unorderable types: str() <= int()

**Comment by jimmysoa** [comment]
Python3好像不支持，我修改一下，谢谢！
