### ISSUE TITLE
pro.daily获取得到的成交量不正确，出现小数且与实际数据不匹配

### ISSUE THREAD

**Issue by springyoung** [waditu/tushare#1200]
df = pro.daily(ts_code='603658.SH', start_date='20190901', end_date='20191118')
print(df.head(2))
#####
     ts_code trade_date    open    high  ...  change  pct_chg       vol      amount
0  603658.SH   20191118  105.99  107.80  ...     1.0   0.9524  17909.01  190041.578
1  603658.SH   20191115  107.54  107.97  ...    -2.8  -2.5974  14913.11  157000.126

**Comment by jimmysoa** [comment]
请确认单位
