### ISSUE TITLE
daily_basic接口获取的数据有部分缺失（例如：600018.SH)

### ISSUE THREAD

**Issue by jameslee529sh** [waditu/tushare#1204]
利用daily_basic接口获取600018.SH的每日交易指标，发现20061026前的数据缺失。
例如，
ts.pro_api().daily_basic(ts_code='600018.SH', start_date='20050101', end_date='20061030');
- 仅返回20161026，20161027，20161030三条数据。
- 调用时间20191123.

另，前几天调用ts.pro_api().daily()，也发现600018.SH的2005年及以前的交易数据部分字段有空值。但20191121后，再调用此函数就没有发现此问题了。

目前仅发现600018.SH有此问题。

**tushare ID**:  jameslee529@163.com

**Comment by jimmysoa** [comment]
这不是缺的问题，是股权改革变化代码的问题
