### ISSUE TITLE
调用pro.balancesheet()接口商誉显示None

### ISSUE THREAD

**Issue by zjred13** [waditu/tushare#1208]
对于商誉为0的股票，调用balancesheet接口，goodwill为none。
因为为0，建议返回前使用fillna(0)
例如 000049
<img width="1046" alt="goodwill-issue" src="https://user-images.githubusercontent.com/54545611/69912759-a2e08980-1468-11ea-9471-7c2d90d7c63f.png">

**Comment by jimmysoa** [comment]
有些就是木有
