### ISSUE TITLE
trade_cal交易日历2020年的数据啥时候有啊？

### ISSUE THREAD

**Issue by RocketCat86** [waditu/tushare#1209]
交易日历的数据到2019-12-31就没有了，2020年的啥时候有呢。别到明年了，拉不到数据了。

**Comment by jimmysoa** [comment]
本周内可以好

**Comment by palespring** [comment]
Hi, Jimmy, I still couldn't get the trade_cal api to 2020 trading day data.

**Comment by jimmysoa** [comment]
早就已经有了的，pro版接口

**Comment by refraction-ray** [comment]
> 早就已经有了的，pro版接口

请问非 pro 版的接口： http://file.tushare.org/tsdata/calAll.csv 这个还会更新增加2020年的交易日数据吗。
