### ISSUE TITLE
建议：数据格式锁版本

### ISSUE THREAD

**Issue by cathayandy** [waditu/tushare#1220]
数据格式能否锁版本？12.09的每日指标新增了dv_ratio和dv_ttm两个域，没有任何说明，也没有升级版本。

**Comment by jimmysoa** [comment]
请关注微信群和QQ群通知，同时关注本接口的官方文档更新，通知了多次。谢谢

**Comment by cathayandy** [comment]
能否在接口变动时更新github的changelog？或在官网维护一份changelog？微信群和QQ群毕竟没有覆盖所有用户。谢谢
