### ISSUE TITLE
新需求：能否提供南华商品指数的 kbar 数据，或者南华指数的计算方式？

### ISSUE THREAD

**Issue by Foristkirito** [waditu/tushare#1222]

**Comment by jimmysoa** [comment]
请参阅tushare pro网站，已经正常服务

**Comment by Foristkirito** [comment]
![image](https://user-images.githubusercontent.com/13299109/70873470-ff0ae800-1fe8-11ea-803f-a2c8ae5ca249.png)
并没有找到南华的 k 线数据
