### ISSUE TITLE
期货API不能获取数据问题

### ISSUE THREAD

**Issue by esun2** [waditu/tushare#1225]
fut_mapping API不能获取数据
![image](https://user-images.githubusercontent.com/7368235/70856343-cea64980-1f15-11ea-9d46-218ff3a9b5a9.png)

fut_daily API不能获取最新数据，2019-12-13日缺失
![image](https://user-images.githubusercontent.com/7368235/70856353-031a0580-1f16-11ea-95ba-78ec5053c86f.png)

Tushare的API很好用，希望能提高日线数据的及时性，提高数据质量（期货连续数据中有很多天窗）。如果能达到更高的可靠级别，我相信很多人是愿意付费使用的。

**Comment by esun2** [comment]
@jimmysoa 请及时处理，谢谢。

**Comment by jimmysoa** [comment]
已经解决
