### ISSUE TITLE
分钟级别数据缺失

### ISSUE THREAD

**Issue by alpha-qi** [waditu/tushare#123]
Jimmy 你好，非常感谢你写了这么一个python库，使用起来很方便。不过在使用过程中我发现利用get_hist_data()获取15分钟，30分钟，60分钟等分钟级别的股票数据时会有部分数据缺失，而且缺失情况不一。如：ts.get_hist_data('002284', ktype = '30')，得到的结果2016-04-29日只有7个时间点的数据，缺少11:30:00的数据；2016-03-28日只有7个时间点数据，缺少15:00:00的数据；2016-03-17缺少11:30:00的数据；2016-03-08日只有7个时间点数据，缺少10:30:00的数据；2016-03-02日只有6个时间点数据，缺少10:00:00和10:30:00的数据；2016-03-01日只有4个时间点数据，缺少10:00:00，10:30:00，11:00:00，11:30:00的数据。换成其他股票代买时也会缺少同样时间点的数据。
本来想自己fork后改改，也为tushare做点贡献，可惜自己python刚开始入门，有些力不从心。希望以后tushare能修复这个bug，越做做好，感激不尽！
        祝好！

**Comment by jimmysoa** [comment]
thanks.
