### ISSUE TITLE
[Bug]ts.pro_bar获得数据错误

### ISSUE THREAD

**Issue by Seraphli** [waditu/tushare#1235]
ts_code有两个获取近720天数据的时候会出错
300811.SZ
688078.SH
其他的都正常, 非调用次数限制导致, 而且可以复现
```
today = datetime.date.today()
end_date = today.strftime("%Y%m%d")
start_date = (today - datetime.timedelta(days=720)).strftime("%Y%m%d")
df = ts.pro_bar(ts_code=_row['ts_code'], adj='qfq',
                    start_date=start_date, end_date=end_date)
```
我是用这段代码循环获取的, 每次运行到这两支就有问题, 重试也没用

**Comment by Seraphli** [comment]
用的stock_basic来得到股票列表, 就是用的示例里面的参数, 'L'应该就是上市的股票

**Comment by jimmysoa** [comment]
多个股票请用逗号分隔

**Comment by Seraphli** [comment]
什么多个股票，我一个个拿的数据好吗，回答的是什么鬼？明明那两个数据当时是停牌的还出现在api的回复里面，现在还有几只是调用pro_bar直接回复空的dataframe的。问题没解决就直接自己close是什么鬼？

> 多个股票请用逗号分隔

**Comment by yufeng0528** [comment]
> 多个股票请用逗号分隔

多个股票可以用逗号分隔吗？我试了怎么不行，返回空

**Comment by Seraphli** [comment]
> > 多个股票请用逗号分隔
> 
> 多个股票可以用逗号分隔吗？我试了怎么不行，返回空

他们根本没有人在认真回复而已. 免费用户已经不受重视了.
