### ISSUE TITLE
5000积分是到底需要捐献多少钱啊？？

### ISSUE THREAD

**Issue by luckti** [waditu/tushare#1237]
想要使用所有数据，所有想知道个价格，能否明确告知？？

**Comment by jimmysoa** [comment]
谢谢，可以加我微信：migedatas

**Comment by yuanjh6** [comment]
既然需要积分,能否正大光明点,愣是没找到获取积分链接

**Comment by jimmysoa** [comment]
https://tushare.pro/document/1?doc_id=13
