### ISSUE TITLE
trade_cal增加第三种未确定状态

### ISSUE THREAD

**Issue by neilxp** [waditu/tushare#1239]
目前trade_cal返回的is_open只有0,1两种状态。

有些未来的日期，交易所未发公告表示是交易，但是根据历史经验，很可能是非交易日的，可以用第三种状态，比如-1表示。

例如2020年10月2日，历史上10月2日都是属于长假非交易日，目前trade_cal返回为is_open为1。

ID： https://tushare.pro/register?reg=337399

**Comment by jimmysoa** [comment]
目前没有，有变更的后期会调整
