### ISSUE TITLE
trade_cal 调用老是失败，是什么情况啊？

### ISSUE THREAD

**Issue by maya413** [waditu/tushare#1240]
trade_cal 调用老是失败，是什么情况啊？各位大佬有知道的吗？

**Comment by maya413** [comment]
OpentimeList = OpenList.isOpen[OpenList.calendarDate == DatetimeNOW]
    if len(OpentimeList.values) < 1:
        print("数据获取失败：" + DatetimeNOW)

**Comment by jimmysoa** [comment]
具体什么错误？没有信息不好回答。另外，请确认使用pro版的trade_cal，旧版已经不维护

**Comment by maya413** [comment]
Pro版本的接口 能提供下名称，调用实例吗？



---原始邮件---
发件人: "Jimmy"<notifications@github.com&gt;
发送时间: 2020年1月2日(周四) 中午12:29
收件人: "waditu/tushare"<tushare@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"maya413"<247370033@qq.com&gt;;
主题: Re: [waditu/tushare] trade_cal 调用老是失败，是什么情况啊？ (#1240)



具体什么错误？没有信息不好回答。另外，请确认使用pro版的trade_cal，旧版已经不维护

**Comment by jimmysoa** [comment]
https://tushare.pro/document/2?doc_id=26
