### ISSUE TITLE
channels获取有问题

### ISSUE THREAD

**Issue by xzb123** [waditu/tushare#1247]
在获取新浪数据后，调用df['content']没有问题
调用df['channels']有问题
![image](https://user-images.githubusercontent.com/25281695/71805140-696eef80-30a0-11ea-82df-57cb05350b76.png)

![image](https://user-images.githubusercontent.com/25281695/71805127-607e1e00-30a0-11ea-8669-4ee9b3f6a1d6.png)

![image](https://user-images.githubusercontent.com/25281695/71805106-4e03e480-30a0-11ea-836b-bd6d66cdc5a5.png)

**Comment by xzb123** [comment]
![4$BH7JWC`3HPKF213YC_Y G](https://user-images.githubusercontent.com/25281695/71805204-991df780-30a0-11ea-8541-67a7ac64b5a5.png)

**Comment by jimmysoa** [comment]
channels要在fields指定才有
