### ISSUE TITLE
8、在自己的博客或者互联网论坛发表Tushare相关的用途、用法等介绍性文章，通过QQ或微信截图和网址发给米哥，根据文章质量可获得100～1000积分

### ISSUE THREAD

**Issue by yuanjh6** [waditu/tushare#1249]
8、在自己的博客或者互联网论坛发表Tushare相关的用途、用法等介绍性文章，通过QQ或微信截图和网址发给米哥，根据文章质量可获得100～1000积分
米哥是谁?怎么联系他,谢谢

**Comment by yuanjh6** [comment]
账号:553882335@163.com
文章:https://blog.csdn.net/u011331731/article/details/103866913
米哥看见了求加积分,跪谢了,

**Comment by yuanjh6** [comment]
@米哥

**Comment by jimmysoa** [comment]
积分好了。不过大哥能否敬业点，直接拷贝文档

**Comment by yuanjh6** [comment]
^_^,谢谢啦!
