### ISSUE TITLE
新需求：增加Token管理功能

### ISSUE THREAD

**Issue by ForgotPS** [waditu/tushare#1251]
当前情况：Tushare Pro只支持一个Token，刷新后原有Token失效，转为新Token，对于多个地方要用殊为不便.
新需求：增加Token管理，可以随着积分变多，增加可用的Token数量，并单独管理。
具体需求：
1.可以在增加多个Token，并单独设定其中一个或多个独立生效、失效，可以设置生效时间段，以起始日期、结束日期两个栏位控制，如果都不设置则长期有效，如果单独设置起始日期，那么认为从设置日期开始，长期有效，若单独设置结束日期，则默认当前开始，至结束日期终止。
2.可以设置Token对应可使用的服务，例如一个Token只能调取资讯以及行业数据，不能调取行情数据，在创建Token的时候可以设置，默认可以使用所有API。
3.可以设置Token支持的渠道，例如通过HTTP调用、通过Mobile APP调用、通过固定IP调用等，在创建Token的时候可以设置，默认可以通过所有渠道调用。
4.可以设置Token使用的次数，例如调用100次以后失效，默认可以无限次调用。

TushareID ：lordwn@outlook.com

**Comment by jimmysoa** [comment]
谢谢，目前支持支持单个token的应用，ts.set_token设置token，ts.get_token查看当天token
