### ISSUE TITLE
通用行情接口缺失数据

### ISSUE THREAD

**Issue by yufeng0528** [waditu/tushare#1252]
```
df = ts.pro_bar('002623.SZ', adj=None, start_date='20191123', end_date='20200109', freq='30min')
```
12月份到1月份有些数据缺失了

**Comment by UnicornUnderMoon** [comment]
df = ts.pro_bar('000536.SZ', adj=None, start_date='19931130', end_date='19940623')
000536成交量数据为空。
tsp = tushare.pro_api()
df = tsp.daily(trade_date=“19931223”).sort_values(by=“ts_code”)
MissData = df.loc[df.ts_code>”600580.SH”]
600600到600695的成交量在19931223那天为空。

**Comment by jimmysoa** [comment]
@yufeng0528 具体哪天？我看没问题

@UnicornUnderMoon 那么早起的成交量我也不知道了，那个时候还不是电子化交易，这个数据没有意义。
