### ISSUE TITLE
pro_bar接口积分要求未列出

### ISSUE THREAD

**Issue by neilxp** [waditu/tushare#1255]
df = ts.pro_bar(ts_code=code, asset="FD", adj=None,
                            start_date=start_date.strftime("%Y%m%d"), end_date=t.strftime("%Y%m%d")).iloc[::-1]

在2020/1/10及以前，该账户调用该接口都是正常返回数据。2020/1/11调用该接口时，出现以下错误：

抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

https://tushare.pro/document/1?doc_id=108该页面未列出pro_bar接口的最低分值。

另外，pro_bar是在tushare下面，而非pro_api()下面，也不知是何用意。请赐教

ID: https://tushare.pro/register?reg=337399

**Comment by HarrisonXi** [comment]
同问+1

**Comment by jimmysoa** [comment]
需要查看权限列表中对应的，比如期货、基金、指数等的接口。这些都是基础数据，如果没有权限说明积分极低，需要换取积分。
