### ISSUE TITLE
pro.fina_mainbz_vip单次调取量问题

### ISSUE THREAD

**Issue by PiescesHusky** [waditu/tushare#1256]
pro.fina_mainbz_vip单次调取量最大为10000，调取一期的企业主营产品条数为15000以上，因而导致10000条之后的主营产品信息无法获取。建议调高单次调取量至20000，或增加调取10000条之后数据的方法。

**Comment by jimmysoa** [comment]
请分页提取

**Comment by PiescesHusky** [comment]
请教下，如何分页提取，没查到方法。谢谢！

**Comment by PiescesHusky** [comment]
> 请分页提取

请教下，如何分页提取，没查到方法。谢谢！

**Comment by jimmysoa** [comment]
offset和limit参数，offset=开始行 limit=每页行数
