### ISSUE TITLE
复权行情接口问题：调取当日所有股票时，行数超过全A股票总数

### ISSUE THREAD

**Issue by wuxiaoda** [waditu/tushare#1257]
在调取当日所有股票时，存在如下问题：

* 单只股票在同一个日期下，显示的数据不同

* 行数超过全A股票总数

![Tushare后复权数据问题.png](https://i.loli.net/2020/01/16/Rl5CU4v18NoLiDy.png)

TushareID：18698562750

**Comment by jimmysoa** [comment]
复权行情目前只能一只只股票提取，所以请设定ts_code
