### ISSUE TITLE
绑定邮箱时，输入企业域名，点击获取验证码，报错： 请使用手机注册

### ISSUE THREAD

**Issue by gikoluo** [waditu/tushare#1261]
1. 进入个人主页， 安全设置，电子邮箱， 点击绑定
2. 输入邮箱： wo@helloworld.com， 点击发送验证码
3. 出现报错提示： “请使用手机注册!”。

![image](https://user-images.githubusercontent.com/141950/72658543-538cf300-39ed-11ea-8133-b97b0f32c426.png)

TushareID： 345046

**Comment by jimmysoa** [comment]
提示很清楚了啊：请使用手机注册!

**Comment by gikoluo** [comment]
我正在 绑定邮箱， 弹出使用手机注册时什么意思？ 文不对题啊。

还有，如果不输入 企业后缀的邮箱， 而使用普通的163邮箱，就不会报错。

**Comment by jimmysoa** [comment]
不支持的邮箱请使用手机注册!
