### ISSUE TITLE
 ts.pro_bar接口中均价与均量数据提取异常

### ISSUE THREAD

**Issue by qinshang0925** [waditu/tushare#1262]
ts.pro_bar接口中均价与均量数据提取异常，‘20180316’之前MA50为空，‘20180126’之前MA20为空，MA是基于提取数据计算的，导致如果要提取一天的数据，为了保证可以读取MA50，时间跨度要选到这一日之前的50个交易日。严重消耗访问量

df = ts.pro_bar(ts_code='000001.SZ', adj='qfq', start_date='20180101', end_date='20181111',ma=[10,20,50,])

id:ChrisLau
email:tongxia19950413@163.com

**Comment by jimmysoa** [comment]
ma是动态计算的，必须要提取能计算的数据量。建议下载数据到本地自行计算ma
