### ISSUE TITLE
可转债基本信息missing columns

### ISSUE THREAD

**Issue by liyadi81** [waditu/tushare#1264]
可转债基本信息， 缺了利率说明之后的column。
![tushare1](https://user-images.githubusercontent.com/29722971/72857756-74667a00-3c73-11ea-9fa1-617767b52196.png)
![tushare2](https://user-images.githubusercontent.com/29722971/72857757-74667a00-3c73-11ea-977f-413ef48e34d2.png)

**Comment by liyadi81** [comment]
这些column原来默认不显示，手动在cb_basic后面写上fields = 'xxx,xxx'就可以看到了。
但还是缺了两个： Exception: 接口cb_basic不包含字段issue_rating        newest_rating
而且有的那个评级rating_comp也都是是空的。

**Comment by jimmysoa** [comment]
fields指定了就可以，如果是空的就没数据
