### ISSUE TITLE
积分300以上在R中仍无法读取周线数据

### ISSUE THREAD

**Issue by dy0630** [waditu/tushare#1265]
日线数据可以获取，周线数据获取结果为空
>  bar(ts_code = '600000.SH',start_date = '20191101',end_date = '20191111')
    ts_code trade_date  open  high   low close pre_close change pct_chg       vol
1 600000.SH   20191111 12.48 12.48 12.29 12.29     12.57  -0.28 -2.2275 385942.67
2 600000.SH   20191108 12.80 12.81 12.56 12.57     12.76  -0.19  -1.489 488418.66
3 600000.SH   20191107 12.95 12.95 12.71 12.76     12.92  -0.16 -1.2384 462672.81
4 600000.SH   20191106 12.95 13.10 12.86 12.92     12.95  -0.03 -0.2317  460239.2
5 600000.SH   20191105 12.74 13.19 12.69 12.95     12.74   0.21  1.6484 742743.89
6 600000.SH   20191104 12.75 12.89 12.69 12.74     12.75  -0.01 -0.0784 497379.96
7 600000.SH   20191101 12.50 12.83 12.44 12.75     12.51   0.24  1.9185 627057.33
      amount
1 477989.511
2 617218.205
3 592408.771
4 597016.896
5 962257.376
6 634816.416
7  793656.95
> bar(ts_code = '600000.SH',start_date = '20191101',end_date = '20191111',freq = 'W')
NULL
> bar(ts_code = '600000.SH',start_date = '20191101',end_date = '20191111',freq = 'Weekly')
NULL

**ID： 345414**

**Comment by jimmysoa** [comment]
可以了
