### ISSUE TITLE
stock_basic 您没有访问该接口的权限

### ISSUE THREAD

**Issue by chennanoka** [waditu/tushare#1283]
刚注册的用户无法访问 stock_basic 提示没有权限。 在https://tushare.pro/document/1?doc_id=108 并没有看到有积分要求。 是因为这个接口需要积分了？ 或是刚注册需要等系统更新？或是因为IP地址不是在境内？

谢谢

**Comment by rupyerlua** [comment]
同样遇到这个问题，应该咋解决呢

**Comment by rupyerlua** [comment]
哈哈，解决了，积分需求是120分，https://tushare.pro/document/1?doc_id=108这里没写，改下个人信息+20积分就可以了

**Comment by jimmysoa** [comment]
OK

**Comment by Tianyu00** [comment]
Thanks!!
