### ISSUE TITLE
双良转债110009.SH 日线行情数据不全

### ISSUE THREAD

**Issue by zhucj1981** [waditu/tushare#1285]
最后一段数据异常 
      ts_code trade_date  pre_close    open   close
0     110009.SH   20150506      93.82    0.00   93.82
1     110009.SH   20150505      93.82    0.00   93.82
2     110009.SH   20150504      93.82    0.00   93.82
3     110009.SH   20150430      93.82    0.00   93.82
4     110009.SH   20150429      93.82    0.00   93.82
5     110009.SH   20150428      93.82    0.00   93.82
6     110009.SH   20150427      93.82    0.00   93.82
7     110009.SH   20150424      93.82    0.00   93.82
8     110009.SH   20150423      93.82    0.00   93.82
9     110009.SH   20150422      93.82    0.00   93.82
10    110009.SH   20150421      93.82    0.00   93.82
11    110009.SH   20150420      93.82    0.00   93.82
12    110009.SH   20150417      93.82    0.00   93.82
13    110009.SH   20150416      93.82    0.00   93.82
14    110009.SH   20150415      93.82    0.00   93.82
15    110009.SH   20150414      93.82    0.00   93.82
16    110009.SH   20150413      93.82    0.00   93.82
17    110009.SH   20150410      93.82    0.00   93.82
18    110009.SH   20150409      93.82    0.00   93.82
19    110009.SH   20150408      93.82    0.00   93.82
20    110009.SH   20150407      93.82    0.00   93.82
21    110009.SH   20150403      93.82    0.00   93.82
22    110009.SH   20150402      93.82    0.00   93.82
23    110009.SH   20150401      93.82    0.00   93.82
24    110009.SH   20150331      93.82    0.00   93.82
25    110009.SH   20150330      93.82    0.00   93.82
26    110009.SH   20150327      93.82    0.00   93.82
27    110009.SH   20150326      93.82    0.00   93.82
28    110009.SH   20150325      93.82    0.00   93.82
29    110009.SH   20150324      93.82    0.00   93.82
         ...        ...        ...     ...     ...
1176  110009.SH   20100629     113.52  113.80  112.68
1177  110009.SH   20100628     113.50  113.81  113.52
1178  110009.SH   20100625     114.06  113.40  113.50
1179  110009.SH   20100624     113.23  113.08  114.06
1180  110009.SH   20100623     113.40  113.51  113.23
1181  110009.SH   20100622     113.71  113.50  113.40
1182  110009.SH   20100621     112.78  112.31  113.71
1183  110009.SH   20100618     113.70  113.00  112.78
1184  110009.SH   20100617     113.63  113.99  113.70
1185  110009.SH   20100611     113.51  113.60  113.63
1186  110009.SH   20100610     114.00  113.52  113.51
1187  110009.SH   20100609     113.13  113.06  114.00
1188  110009.SH   20100608     112.85  113.09  113.13
1189  110009.SH   20100607     113.50  113.01  112.85
1190  110009.SH   20100604     113.61  112.78  113.50
1191  110009.SH   20100603     112.05  114.00  113.61
1192  110009.SH   20100602     111.73  111.75  112.05
1193  110009.SH   20100601     114.12  114.00  111.73
1194  110009.SH   20100531     117.51  117.49  114.12
1195  110009.SH   20100528     118.17  118.21  117.51
1196  110009.SH   20100527     118.08  117.61  118.17
1197  110009.SH   20100526     118.00  118.00  118.08
1198  110009.SH   20100525     118.59  118.21  118.00
1199  110009.SH   20100524     117.52  117.79  118.59
1200  110009.SH   20100521     118.53  117.88  117.52
1201  110009.SH   20100520     118.52  118.43  118.53
1202  110009.SH   20100519     118.06  117.99  118.52
1203  110009.SH   20100518     117.30  117.35  118.06
1204  110009.SH   20100517     118.02  117.72  117.30
1205  110009.SH   20100514     100.00  120.58  118.02
[1206 rows x 5 columns]

**Comment by jimmysoa** [comment]
有啥问题?或者你再描述清楚,谢谢
