### ISSUE TITLE
每日指标(daily_basic)接口，添加end_date参数后，只能获取2019年12月31日以前的数据，2020年的数据获取不到

### ISSUE THREAD

**Issue by ustb-pomelo** [waditu/tushare#1287]
接口说明地址：https://tushare.pro/document/2?doc_id=32

测试结果截图：
![image](https://user-images.githubusercontent.com/13847603/74599434-b17c2b80-50bc-11ea-8e5e-ff89d8c5d3ec.png)

账号ID：276150

**Comment by jimmysoa** [comment]
日期格式：YYYYMMDD
