### ISSUE TITLE
daily basic 接口数据不全

### ISSUE THREAD

**Issue by aodiwei** [waditu/tushare#1290]
该接口返回的数据有部分字段总会出现数据缺失，比如pe, pe_ttm 这两个字段总会有部分日期有，有部分日期没有，pb字段也是类似情况，比如000410.SZ。
此外dv_ratio，dv_ttm这两个字段几乎所以股票都没数据。请问这是怎么回事？
ID: 347125

**Comment by jimmysoa** [comment]
PE数据是空是公司亏损，在tushare里pe没有负值
