### ISSUE TITLE
从接口获取到的数据和从深交所读取的数据不一致 Data mismatch between TUSHARE inteface and SZSE offical data

### ISSUE THREAD

**Issue by zergscut2017** [waditu/tushare#1291]
Code:
df = pro.index_dailybasic(ts_code='399006.SZ')
df.to_csv('D:\git\stock\cyb399006.csv')
20200221深交所限时创业板上市公司流通市值，50281.09亿
tushare的float_mv按照官方文档，（float_mv | float | Y | 当日流通市值（元）），2627.78亿，怎么会相差那么大？
当天399006的成交额就是2659亿
tushare提供的流通市值比成交额还小
![399006data_tushare](https://user-images.githubusercontent.com/32028062/75093025-01755980-55b9-11ea-942f-2f0a332ba8b9.JPG)
![399006data_SZSE](https://user-images.githubusercontent.com/32028062/75093026-033f1d00-55b9-11ea-9117-1c9597fc99cf.JPG)
![tushare_interface](https://user-images.githubusercontent.com/32028062/75093027-03d7b380-55b9-11ea-8258-891048152139.JPG)

**Comment by jimmysoa** [comment]
统计的是自由流通市值
