### ISSUE TITLE
pro版本大盘指数每日指标index_dailybasic怎么没提供成交量和成交额了？

### ISSUE THREAD

**Issue by zergscut2017** [waditu/tushare#1292]
dailybasic方法能返回个股的数据但是不返回大盘指数的数据
index_dailybasic并不返回成交量和成交额了？
index_dailybasic返回数据能否提供如下字段的计算公式？
turnover_rate | float | Y | 换手率
turnover_rate_f | float | Y | 换手率(基于自由流通股本)

https://tushare.pro/document/2?doc_id=128

**Comment by jimmysoa** [comment]
成交量成交额在行情接口里，index_daily
