### ISSUE TITLE
stock_company接口输入字段顺序与传入顺序不对应

### ISSUE THREAD

**Issue by JamesYue369** [waditu/tushare#1293]
通过http 方式调取接口
url:http://api.waditu.com/
httpmethod:post
入参：
{
	"api_name":"stock_company",
	"token": "8b976557957d7a928d640681bab558ff456d99bd47d11a925a38d77e",
	"params": {
		"exchange": "SSE"
	},
	"fields": "employees,chairman,manager,secretary,reg_capital,setup_date,province,province,introduction,website,email,office,main_business,business_scope"

}
返回特定字段：
"fields": [
            "chairman",
            "manager",
            "secretary",
            "reg_capital",
            "setup_date",
            "province",
            "introduction",
            "website",
            "email",
            "office",
            "business_scope",
            "employees",
            "main_business"
]
id: 350789

**Comment by jimmysoa** [comment]
没有严格对应关系，谢谢。
