### ISSUE TITLE
stock_basic接口默认参数建议

### ISSUE THREAD

**Issue by rupyerlua** [waditu/tushare#1297]
问题一：
在官方文档中（ https://tushare.pro/document/2?doc_id=25 ），“输入参数”表格中目前只有3个参数说明（is_hs，list_status，exchange），缺少fields字段的说明。根据我自己的实验，不设置fields字段的情况下会返回6个字段的内容。
问题二：
在不设置list_status参数的情况下，只会默认返回L（上市）的股票信息，建议改为不设置时返回所有（LDP三种）
同理，fields字段建议改为不设置时返回所有（14种）

**Comment by jimmysoa** [comment]
谢谢。
第一个问题，我们后续把fields参数说明加上
第二个问题，目前暂时默认返回上市状态的数据，不做调整
