### ISSUE TITLE
daily和daily_basic接口数据条数返回数量不一致

### ISSUE THREAD

**Issue by rupyerlua** [waditu/tushare#1298]
daily 接口一次性最多获取5000条数据
daily_basic 接口一次性最多获取4000条数据

对于较新的股还好，但是对于较旧的股，2组数据如果同时使用的话可能会对处理带来困难，希望能够使获取的数据量保持一致。
`df1 = ts_api.daily_basic(ts_code='000006.SZ')`
`df2 = ts.pro_bar(ts_code='000006.SZ', asset='E', freq='D', adj='hfq')`
`print(df1)`
`print(df2)`

>ts_code trade_date  close  ...  free_share     total_mv      circ_mv
>0     000006.SZ   20200226   4.84  ...  86230.9824  653397.6023  652581.0584
>1     000006.SZ   20200225   4.74  ...  86230.9824  639897.6518  639097.9787
>2     000006.SZ   20200224   4.82  ...  86230.9824  650697.6122  649884.4425
>3     000006.SZ   20200221   4.89  ...  86230.9824  660147.5775  659322.5983
>4     000006.SZ   20200220   4.88  ...  86230.9824  658797.5824  657974.2903
>...         ...        ...    ...  ...         ...          ...          ...
>3995  000006.SZ   20021121   8.55  ...  15780.7037  216820.8445  134925.0166
>3996  000006.SZ   20021120   8.88  ...  15780.7037  225189.3683  140132.6489
>3997  000006.SZ   20021119   9.00  ...  15780.7037  228232.4679  142026.3333
>3998  000006.SZ   20021118   8.90  ...  15780.7037  225696.5516  140448.2629
>3999  000006.SZ   20021115   9.05  ...  15780.7037  229500.4261  142815.3685
>
>[4000 rows x 18 columns]
>        ts_code trade_date   open  ...  pct_chg        vol       amount
>0     000006.SZ   20200226   4.66  ...   2.1097  224285.21  108985.3260
>1     000006.SZ   20200225   4.75  ...  -1.6598  153985.90   72623.1330
>2     000006.SZ   20200224   4.83  ...  -1.4315  144356.32   69508.2520
>3     000006.SZ   20200221   4.85  ...   0.2049  108504.29   52946.6230
>4     000006.SZ   20200220   4.84  ...   0.8264  106733.32   51801.7210
>...         ...        ...    ...  ...      ...        ...          ...
>4995  000006.SZ   19980910  12.10  ...   3.3100   21603.00   26763.9613
>4996  000006.SZ   19980909  11.90  ...   1.2600    7492.00    8967.6006
>4997  000006.SZ   19980908  11.98  ...   0.1700   12982.00   15629.0019
>4998  000006.SZ   19980907  11.90  ...   0.8500    5055.00    5967.1882
>4999  000006.SZ   19980904  11.75  ...   0.8500    4492.00    5307.2667
>
>[5000 rows x 11 columns]

**Comment by jimmysoa** [comment]
daily接口对于停牌的是没有数据的
