### ISSUE TITLE
pe数据不准确

### ISSUE THREAD

**Issue by maxsonic** [waditu/tushare#130]
比如300372，如果按照最新的财报来算，pe应该是982，但是tusahre的get_today_all返回的是425.439。查看了一下上一季度的财报，这个数据应该是按照上一季度的财报的每股盈利来算的。

**Comment by jimmysoa** [comment]
算法不一样，也可以用get_stock_basics()获取pe

**Comment by maxsonic** [comment]
@jimmysoa ，但是pe ratio不是应该以上一季度的每股盈利来算的么?
