### ISSUE TITLE
上市公司基本信息-stock_company 请求新增输入参数 【股票代码】

### ISSUE THREAD

**Issue by JamesYue369** [waditu/tushare#1300]
目前该接口只能按照【交易所代码】进行查询，这样在新增股票时想获取 公司基本信息时都要拉取全部数据很不方便，同时也浪费服务器资源。
所以建议添加一个查询参数：ts_code
谢谢作者～
账号：18521398694

**Comment by jimmysoa** [comment]
好的，记下了，尽快完成

**Comment by jimmysoa** [comment]
done
