### ISSUE TITLE
BUG: 指数H30094.CSI数据缺失

### ISSUE THREAD

**Issue by gundamze** [waditu/tushare#1301]
pro.index_daily(ts_code='H30094.CSI')

可以提取到2006到2016年6月的数据，此后数据缺失。

![image](https://user-images.githubusercontent.com/35365423/75671978-b6df9580-5cba-11ea-905e-e080e62561a4.png)

ID：349362

**Comment by jimmysoa** [comment]
很多指数数据需要授权才有
