### ISSUE TITLE
上市公司管理层信息-stk_managers 请求新增输入参数 【公告日期】

### ISSUE THREAD

**Issue by JamesYue369** [waditu/tushare#1302]
目前该接口只能按照【股票代码】进行查询，这样在新的公告期想获取 上市公司管理层**最新**信息时都要重新拉取上市公司历年的全部管理层数据很不方便，同时也浪费服务器资源。
所以建议添加一个查询参数：ann_date
谢谢作者～
账号：18521398694

**Comment by DTShare** [comment]
done.

**Comment by jimmysoa** [comment]
已经好了，谢谢。 添加了：ann_date / start_date / end_date
