### ISSUE TITLE
股票复权价格有误

### ISSUE THREAD

**Issue by fazhmshily** [waditu/tushare#1303]
股票复权价格可能有误。以20200302为复权基准，603336.SH在20190308的前复权收盘价，在pro_bar中提取结果为13.1364, 在wind中提取结果为13.13632269，在同花顺中显示的结果为13.11。

tushare id 352981.

**Comment by jimmysoa** [comment]
每家算法不同，我们根据交易所公布的价格复权的。至少Tushare跟Wind是没有太大差距的
