### ISSUE TITLE
大宗交易数据在20200302缺失

### ISSUE THREAD

**Issue by fazhmshily** [waditu/tushare#1304]
文档显示大宗交易(pro.block_trade)在每晚9点更新。但是20200302的数据在第二天(20200303)下午4点仍提取不到。

tushare id 352981.

**Comment by fazhmshily** [comment]
20200303的大宗交易数据在20200304上午10点仍提取不到。

**Comment by jimmysoa** [comment]
数据更新不到可以晚一点再更新
