### ISSUE TITLE
基金持股——查询到的数据的标题和列对不上

### ISSUE THREAD

**Issue by Bobbyisbobo** [waditu/tushare#1306]
![23](https://user-images.githubusercontent.com/30261565/75880269-e8da2e80-5e57-11ea-9a02-3917400edda4.jpg)

import tushare as ts
ts.fund_holdings(2019, 4)

得到的数据标题和列错位了

提交人ID:353000

**Comment by jimmysoa** [comment]
请使用pro版接口，https://tushare.pro/document/2?doc_id=121
