### ISSUE TITLE
1.2.52 tushare pro 在 colab 上 使用出错

### ISSUE THREAD

**Issue by gftgpu** [waditu/tushare#1307]
提示 import websocket module error . pip websocket 以后，依然还有 import error

**Comment by chenkjia** [comment]
是的，我也是，websocket安装后提示这个
    from websocket._exceptions import WebSocketConnectionClosedException
ModuleNotFoundError: No module named 'websocket._exceptions'

python 3.7
tushare 1.2.52

**Comment by jimmysoa** [comment]
删除webscoket，安装websocket-client
