### ISSUE TITLE
daily_basic接口部分股票的市盈率ttm不准确

### ISSUE THREAD

**Issue by wowh** [waditu/tushare#1309]
有一部分股票的市盈率ttm不准确，比如002734.SZ利民股份。

查看最近4个季度的财务数据净利润
2018年第四季度：55,897,077.20 
2019年前三季度为286,477,878.85 
合计为342374956.05。

总股本286,557,570
可以算出每股收益ttm为342374956.05/286,557,570=1.19478594
目前收盘价为15.52，可以算出市盈率ttm为15.52/1.19478594=12.98977455

目前主流的网站上显示的都是12.99，tushare这边获取的值为13.6768。

tushare ID：350126

**Comment by jimmysoa** [comment]
每家算法不一样。另外，PE有好几种，也需要确认一下是否对照的是同一标准

**Comment by wowh** [comment]
PE是有好几种，这里也具体说明了是PE TTM （滚动市盈率） 计算方法也都给出了，你可以自己算一下嘛。

信息都是按公司公告给的，又不是自己造的。
