### ISSUE TITLE
获取龙虎榜数据出错

### ISSUE THREAD

**Issue by kernel8liang** [waditu/tushare#131]
`
ts.top_list('2015-05-22')
raise IOError(ct.NETWORK_URL_ERROR_MSG)
`

这个接口时而能用，时而不能用。

**Comment by jimmysoa** [comment]
tushare什么版本？

**Comment by kernel8liang** [comment]
0.5.0
我在每次获取以后加了一个５秒的睡眠，就可以用了。

**Comment by 984958198** [comment]
目前仍然有出错的情况  __version__ = '0.5.0'
`Traceback (most recent call last):
  File "C:/Users/sa/Desktop/tushare-master/test_unittest.py", line 43, in <module>
    td = ts.top_list()
  File "C:\Users\sa\Desktop\tushare-master\tushare\stock\billboard.py", line 93, in top_list
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
IOError: 获取失败，请检查网络和URL`

原因：
原网页http://data.eastmoney.com/DataCenter_V3/stock2016/TradeDetail/pagesize=200,page=1,sortRule=-1,sortType=,startDate=2016-09-07,endDate=2016-09-07,gpfw=0,js=vardata_tab_1.html 
会出现为空数据 "Smoney":""  而代码里会将它转换为float
解决办法：
tushare\stock\billboard.py  第75行添加 
 `df['sell'] = [s if s else 0 for s in df['sell']] ` 将不标准数据默认为0

**Comment by jimmysoa** [comment]
@984958198 
直接提交pull request吧
