### ISSUE TITLE
系统未知错误，获取交易日历时出错

### ISSUE THREAD

**Issue by lrkkr** [waditu/tushare#1311]
调用情况：
today = datetime.date.today().strftime('%Y%m%d')
pro.trade_cal(exchange='', start_date=today, end_date=today)
错误信息：
Exception: 系统未知错误，欢迎上报！ 谢谢！request-id(ac7f38b264f711eab1a92bf9f44322931584082550194011)

**Comment by jimmysoa** [comment]
用str的数据就可以，yyyymmdd，可以直接输入先试试
