### ISSUE TITLE
返回重复数据的BUG

### ISSUE THREAD

**Issue by JangoZheng** [waditu/tushare#1312]
df = ts.pro_bar(ts_code='000001.SZ,000002.SZ', start_date='20200313', factors=['tor'])
调用时返回的数据会重复2次。
df = ts.pro_bar(ts_code='000001.SZ,000002.SZ,000003.SZ', start_date='20200313', factors=['tor'])
调用时返回的数据会重复3次。
也就是说，股票代码数量决定重复次数。
我的ID：348790

**Comment by jimmysoa** [comment]
你的tushare升级一下，目前不支持多个股票提取指标
