### ISSUE TITLE
股票回购接口-repurchase 请求添加查询条件参数【股票代码】ts_code

### ISSUE THREAD

**Issue by JamesYue369** [waditu/tushare#1316]
业务描述：
希望可以通过ts_code 查询个股历史回购记录
谢谢作者～
会员账号：18521398694

**Comment by jimmysoa** [comment]
已经加了，谢谢

**Comment by JamesYue369** [comment]
https://www.waditu.com/document/2?doc_id=124
网站文档还没有添加ts_code参数
