### ISSUE TITLE
限售股解禁接口-share_float  很多数据没有【公告日期】ann_date

### ISSUE THREAD

**Issue by JamesYue369** [waditu/tushare#1317]
业务描述：
后面的每天更新最新的数据时需要根据ann_date 来查询，如果ann_date字段没有数据就会造成公告日期的数据查询不到
谢谢作者～
会员账号：18521398694

**Comment by jimmysoa** [comment]
这种情况可以用其他参数来过滤

**Comment by JamesYue369** [comment]
好的
