### ISSUE TITLE
获取的tick数据有错误

### ISSUE THREAD

**Issue by kernel8liang** [waditu/tushare#132]
随机的选了一天的历史分笔数据　2016-04-05/600098，在行　798,　1211，数据有成交额，没有成交量。　

798,13:24:23,8.39,-0.01,0,285,卖盘，
1211,11:04:07,8.29,--,0,820,买盘。

不知道这样的数据概率会有多大。

**Comment by kernel8liang** [comment]
扫面了一下文件，发现这个问题非常普遍。这个问题可以解决吗？或者说　amount　这个维度的数据是否可靠？如果分笔数据不准会对做出来的模型有很大的影响。下面只是扫面了７，８个文件的结果。

     Unnamed: 0      time  price change  volume  amount type  avr
442         442  14:24:05   11.5     --       0     230   买盘  inf
17
      Unnamed: 0      time  price change  volume  amount type  avr
62            62  14:52:01  40.75     --       0    1630   卖盘  inf
114          114  14:46:31  40.66     --       0    2032   卖盘  inf
1080        1080  10:37:24  40.34     --       0     605   买盘  inf
1120        1120  10:31:17  40.40     --       0     848   卖盘  inf
1365        1365  10:07:52  41.00     --       0      41   卖盘  inf
1423        1423  10:02:16  40.91  -0.17       0    3272   卖盘  inf
1550        1550  09:51:03  41.20     --       0    3914   卖盘  inf
24
      Unnamed: 0      time  price change  volume  amount type  avr
565          565  14:25:45  17.75  -0.03       0    1704   卖盘  inf
591          591  14:24:14  17.64  -0.01       0    1693   卖盘  inf
814          814  14:11:29  17.45  -0.05       0    1675   买盘  inf
817          817  14:11:17  17.51     --       0    1680   卖盘  inf
1448        1448  13:34:27  18.00   0.01       0    1728   买盘  inf
1758        1758  13:16:29  18.22     --       0    1749   买盘  inf
2508        2508  11:01:58  19.10   0.01       0     802   买盘  inf
31
      Unnamed: 0      time  price change  volume  amount type  avr
806          806  13:45:27   8.20     --       0      16   卖盘  inf
2363        2363  09:55:28   8.26  -0.01       0      90   卖盘  inf
33
     Unnamed: 0      time  price change  volume  amount type  avr
411         411  13:21:38  14.27     --       0      14   卖盘  inf
437         437  13:10:32  14.28     --       0     314   卖盘  inf
728         728  10:25:53  14.27     --       0     713   买盘  inf
36
      Unnamed: 0      time  price change  volume  amount type  avr
542          542  14:26:18  70.25  -0.03       0    1756   卖盘  inf
941          941  14:03:10  71.02     --       0    3551   卖盘  inf
1971        1971  11:11:25  71.29     --       0    3564   买盘  inf
2257        2257  10:51:48  71.00     --       0    6745   卖盘  inf
2604        2604  10:31:38  71.91   0.04       0    1438   买盘  inf
2818        2818  10:18:26  72.10   0.04       0    3532   买盘  inf
2945        2945  10:10:25  72.04     --       0    3674   卖盘  inf

**Comment by jimmysoa** [comment]
这是新浪的数据源，因为是实时计算，对于免费数据他们并不保证质量。

**Comment by kernel8liang** [comment]
哦，好的。谢谢。这种数据如果是收费的大概要多少钱？

**Comment by jimmysoa** [comment]
可以参考一下通联数据,http://m.datayes.com
