### ISSUE TITLE
三表中信息不全

### ISSUE THREAD

**Issue by gongxunwei** [waditu/tushare#1330]
近期，有新增条目，需要添加识别，比如：
资产负债表：
  流动资产新增“应收款项融资”
  非流动资产新增“其他非流动金融资产”
利润表：
  营业支出中的“研发费用”（在财务指标中有包含，但在利润表中没有，对应的研发支出为空）

ID：351509

**Comment by jimmysoa** [comment]
嗯嗯，目前只在指标接口里有，后续我们重新整理后发布吧
