### ISSUE TITLE
pro_bar 无返回

### ISSUE THREAD

**Issue by yans-emc** [waditu/tushare#1343]
刚开始用tushare pro，下面的测试脚本只返回空的DataFrame（也没有任何报错），可能是什么原因呢？

# -*- coding: utf-8 -*-

import os
from datetime import date
import tushare as ts
import pandas as pd

__ts_token__ = '<隐藏了我的token>'

def test():
    ts.set_token(__ts_token__)
    pro = ts.pro_api()
    df = ts.pro_bar(api=pro, ts_code='000001.SZ', adj=None, start_date="20190101", end_date="20200420")
    print df

def main():
    print "\nDEBUG: TuShare Start - "
    ## Test Body

    test()

    ## End of Test Body
    print "DEBUG: End of TuShare"
    
if __name__ == '__main__':
    main()

输出为：
DEBUG: TuShare Start -
Empty DataFrame
Columns: []
Index: []
DEBUG: End of TuShare

**Comment by xujiach** [comment]
df = ts.pro_bar(api=pro, ts_code='000001.SZ', adj=None, start_date="20190101", end_date="20200420")
改为：（删去api=pro）
df = ts.pro_bar(ts_code='000001.SZ', adj=None, start_date="20190101", end_date="20200420")

**Comment by yans-emc** [comment]
这次在这里报错

    df = pro.pro_bar(ts_code='000001.SZ', adj=None, start_date="20190101", end_date="20200420")
  File "C:\ProgramData\Anaconda2\lib\site-packages\tushare\pro\client.py", line 44, in query
    raise Exception(result['msg'])
Exception: <exception str() failed>

**Comment by xujiach** [comment]
上述代码的pro.pro_bar应为ts.pro_bar

**Comment by yans-emc** [comment]
遇到另一个问题，adj赋予'qfq'或'hfq'就报exception，=None时没有错。

   df = ts.pro_bar(ts_code='000001.SZ', adj='qfq', start_date="20190101", end_date="20200420")
  File "C:\ProgramData\Anaconda2\lib\site-packages\tushare\pro\data_pro.py", line 190, in pro_bar
    print(e)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-24: ordinal not in range(128)

**Comment by jimmysoa** [comment]
tushare升级到最新版 @yans-emc
