### ISSUE TITLE
get_sina_dd和get_today_ticks数据有的是冲突的，买入和卖出那里不一致

### ISSUE THREAD

**Issue by amylaogong** [waditu/tushare#1349]
20200429测试：
![微信图片_20200429152730](https://user-images.githubusercontent.com/3362698/80571347-0f1ee380-8a2f-11ea-88f4-fc379cf425c1.png)

get_sina_dd()的部分数据：
,code,name,time,price,volume,preprice,type
0,601818,光大银行,15:00:18,3.73,3443100,3.73,买盘
_**1,601818,光大银行,14:45:09,3.72,799100,3.73,卖盘
2,601818,光大银行,14:44:03,3.73,1000600,3.73,买盘
3,601818,光大银行,14:43:57,3.72,1001000,3.72,卖盘**_
4,601818,光大银行,14:42:51,3.72,1210300,3.72,卖盘
5,601818,光大银行,14:38:24,3.72,2262700,3.72,卖盘
6,601818,光大银行,14:35:06,3.73,502400,3.73,买盘
7,601818,光大银行,14:33:39,3.73,515800,3.73,买盘
8,601818,光大银行,14:30:33,3.73,530400,3.73,买盘
9,601818,光大银行,14:29:12,3.73,500000,3.72,买盘
10,601818,光大银行,14:24:50,3.73,710761,3.73,卖盘
11,601818,光大银行,14:24:24,3.73,3211900,3.74,卖盘
12,601818,光大银行,14:23:54,3.74,1509000,3.74,买盘
13,601818,光大银行,14:20:48,3.73,1208639,3.73,买盘
14,601818,光大银行,14:20:42,3.73,2169200,3.73,买盘
15,601818,光大银行,13:58:26,3.73,501500,3.73,买盘
16,601818,光大银行,13:57:17,3.72,554500,3.73,卖盘
17,601818,光大银行,13:55:29,3.72,1220257,3.72,买盘

get_today_ticks()部分数据:

3973,144351,3.72,29,买入
3974,144354,3.72,93,买入
3975,144357,3.72,10010,买入
3976,144400,3.73,27,卖出
3977,144403,3.73,10006,卖出
3978,144406,3.73,1300,卖出
3979,144409,3.72,15,买入
3980,144415,3.72,125,买入
3981,144418,3.73,20,卖出
3982,144424,3.73,147,卖出
3983,144427,3.72,30,买入
3984,144430,3.73,233,卖出
3985,144433,3.72,620,买入
3986,144436,3.73,5,卖出
3987,144439,3.73,33,卖出
3988,144442,3.72,10,买入
3989,144448,3.73,11,卖出
3990,144451,3.73,2,卖出
3991,144454,3.73,78,卖出
3992,144457,3.73,529,卖出
3993,144500,3.73,360,卖出
3994,144503,3.72,6,买入
3995,144506,3.73,118,卖出
**_3996,144509,3.72,7991,买入_**
3997,144512,3.72,176,卖出
3998,144515,3.72,86,卖出
3999,144518,3.72,347,卖出
4000,144521,3.72,30,买入
4001,144524,3.72,1000,买入
4002,144527,3.72,202,买入
4003,144536,3.72,3,买入
4004,144539,3.72,102,买入
4005,144542,3.72,110,买入
4006,144545,3.72,18,买入
4007,144548,3.72,297,买入
4008,144551,3.72,730,买入
4009,144554,3.73,20,卖出
4010,144557,3.72,3980,买入
4011,144600,3.72,330,卖出
4012,144603,3.72,328,卖出
4013,144606,3.72,1,卖出
4014,144609,3.72,677,卖出
4015,144612,3.72,650,卖出
4016,144615,3.72,390,卖出
4017,144618,3.73,296,卖出
4018,144621,3.73,11,卖出
4019,144624,3.72,15,买入
4020,144627,3.72,42,买入
4021,144630,3.72,24,买入
4022,144633,3.72,245,买入
4023,144636,3.73,74,卖出
4024,144639,3.72,613,买入
4025,144642,3.72,60,买入
4026,144645,3.72,80,买入
4027,144648,3.72,480,买入
4028,144651,3.73,349,卖出
4029,144654,3.73,1017,卖出
4030,144700,3.72,212,买入
4031,144703,3.73,317,卖出
4032,144709,3.72,47,买入
4033,144715,3.73,1,卖出
4034,144718,3.72,49,买入
4035,144724,3.72,83,买入
4036,144727,3.72,118,买入
4037,144730,3.72,47,买入
4038,144733,3.72,662,买入
4039,144736,3.72,193,买入
4040,144739,3.73,85,卖出
4041,144742,3.72,420,买入
4042,144748,3.73,8,卖出
4043,144751,3.72,412,买入
4044,144754,3.72,177,买入
4045,144800,3.72,89,买入
4046,144803,3.73,29,卖出
4047,144809,3.73,3,卖出
4048,144812,3.73,1159,卖出
4049,144815,3.73,340,卖出
4050,144821,3.72,1272,买入
4051,144824,3.72,8,卖出
4052,144830,3.72,79,卖出
4053,144833,3.72,115,卖出
4054,144839,3.72,2,卖出
4055,144842,3.71,110,买入
4056,144845,3.72,42,卖出
4057,144848,3.72,1,卖出
4058,144851,3.72,2,卖出
4059,144854,3.72,34,卖出
4060,144903,3.72,413,卖出
4061,144906,3.72,47,卖出
4062,144909,3.72,1,卖出
4063,144912,3.72,102,卖出
4064,144915,3.72,339,卖出
4065,144918,3.71,265,买入
4066,144921,3.72,36,卖出
4067,144924,3.72,51,卖出
4068,144927,3.72,7,卖出
4069,144930,3.72,9,卖出
4070,144933,3.72,88,卖出
4071,144936,3.72,41,卖出
4072,144939,3.71,44,买入
4073,144942,3.72,93,卖出
4074,144945,3.72,358,卖出
4075,144948,3.72,298,买入
4076,144951,3.72,20,卖出
4077,144954,3.72,67,买入
4078,144957,3.73,173,卖出
4079,145000,3.72,517,买入
4080,145003,3.73,75,卖出
4081,145006,3.72,650,买入
4082,145009,3.72,550,买入
4083,145012,3.73,70,卖出
4084,145015,3.72,262,买入
4085,145018,3.72,195,买入
4086,145021,3.73,68,卖出
4087,145024,3.73,506,卖出
4088,145030,3.73,114,卖出
4089,145033,3.73,13,卖出
4090,145036,3.72,7,买入
4091,145042,3.73,1,卖出
4092,145045,3.72,105,买入
4093,145048,3.73,221,卖出
4094,145051,3.72,136,买入
4095,145054,3.73,49,卖出
4096,145057,3.73,172,卖出
4097,145100,3.73,17,卖出
4098,145103,3.73,95,卖出
4099,145106,3.72,30,买入
4100,145109,3.73,5,卖出
4101,145115,3.73,159,卖出
4102,145121,3.73,101,卖出
4103,145124,3.72,60,买入
4104,145127,3.72,30,买入
4105,145133,3.72,40,买入
4106,145145,3.73,12,卖出
4107,145148,3.73,55,卖出
4108,145151,3.73,291,卖出
4109,145154,3.72,11,买入
4110,145200,3.73,62,卖出
4111,145203,3.72,480,买入
4112,145206,3.73,1,卖出
4113,145209,3.72,42,买入
4114,145212,3.72,13,买入
4115,145215,3.73,843,卖出
4116,145218,3.72,73,买入
4117,145221,3.72,218,买入
4118,145224,3.73,26,卖出
4119,145227,3.73,2071,卖出
4120,145230,3.72,44,买入
4121,145233,3.72,252,买入
4122,145236,3.73,2,卖出
4123,145239,3.72,2,买入
4124,145245,3.72,150,买入
4125,145248,3.72,30,买入
4126,145251,3.72,314,买入
4127,145254,3.72,147,买入
4128,145257,3.72,45,买入
4129,145300,3.72,41,买入
4130,145303,3.73,18,卖出
4131,145306,3.72,93,买入
4132,145309,3.72,100,买入
4133,145312,3.73,14,卖出
4134,145315,3.72,30,买入
4135,145318,3.72,54,买入
4136,145321,3.72,206,买入
4137,145324,3.72,1010,买入
4138,145327,3.72,68,买入
4139,145330,3.73,220,卖出
4140,145333,3.72,24,买入
4141,145336,3.72,152,买入
4142,145339,3.72,14,买入
4143,145342,3.72,20,买入
4144,145345,3.72,66,买入
4145,145348,3.72,10,买入
4146,145351,3.73,1,卖出
4147,145354,3.72,19,买入
4148,145357,3.72,50,买入
4149,145403,3.72,140,买入
4150,145406,3.72,156,买入
4151,145409,3.73,4,卖出
4152,145412,3.72,62,买入
4153,145415,3.72,43,买入
4154,145418,3.72,10,买入
4155,145421,3.73,59,卖出
4156,145430,3.73,127,卖出
4157,145433,3.72,6,买入
4158,145436,3.72,10,买入
4159,145439,3.73,48,卖出
4160,145442,3.72,39,买入
4161,145448,3.72,21,买入
4162,145454,3.73,383,卖出
4163,145457,3.73,74,卖出
4164,145500,3.72,20,买入
4165,145503,3.72,382,买入
4166,145506,3.72,30,买入
4167,145509,3.73,42,卖出
4168,145512,3.72,158,买入
4169,145515,3.72,319,买入
4170,145518,3.72,50,买入
4171,145521,3.72,384,买入
4172,145527,3.72,69,买入
4173,145530,3.72,73,买入
4174,145533,3.72,347,买入
4175,145536,3.73,1,卖出
4176,145539,3.72,13,买入
4177,145542,3.72,260,买入
4178,145545,3.72,226,买入
4179,145548,3.72,224,卖出
4180,145551,3.72,6,买入
4181,145554,3.72,118,买入
4182,145557,3.72,211,买入
4183,145600,3.72,100,买入
4184,145609,3.73,161,卖出
4185,145615,3.72,10,买入
4186,145621,3.73,11,卖出
4187,145624,3.71,19,买入
4188,145627,3.73,252,卖出
4189,145630,3.72,52,买入
4190,145633,3.73,600,卖出
4191,145636,3.71,232,买入
4192,145639,3.72,101,卖出
4193,145642,3.72,186,买入
4194,145645,3.72,523,卖出
4195,145648,3.72,89,买入
4196,145651,3.72,56,买入
4197,145654,3.72,402,买入
4198,145657,3.72,50,买入
4199,145700,3.72,122,买入
4200,150059,3.73,34431,买入

**Comment by jimmysoa** [comment]
这不是标准数据
