### ISSUE TITLE
新股获取失败，new_stocks函数：No tables found matching pattern '.+'

### ISSUE THREAD

**Issue by zjw0358** [waditu/tushare#135]
> > > import tushare as ts
> > > ts.new_stocks()
> > > [Getting data:]#No tables found matching pattern '.+'
> > > # No tables found matching pattern '.+'
> > > # No tables found matching pattern '.+'

**Comment by jimmysoa** [comment]
python和pandas什么版本？

--------------

In [1]: import tushare as ts

In [2]: ts.new_stocks()
[Getting data:]#########Out[2]: 
       code  name   ipo_date issue_date  amount  markets  price     pe  limit  \
0    601127  小康股份 2016-05-31        NaT   14250     4275   5.81  18.19   4.20   
1    300515  三德科技 2016-05-30        NaT    2500     1000   8.57  22.98   1.00   
2    002799  环球印务 2016-05-27        NaT    2500     2250   7.98  22.99   1.00   
3    603131  上海沪工 2016-05-26        NaT    2500     2250  10.09  22.98   1.00   
4    601611  中国核建 2016-05-25        NaT   52500    47250   3.47  15.60  15.70   
5    300516   久之洋 2016-05-24        NaT    3000     2700  22.50  22.98   1.20   
6    603737   三棵树 2016-05-23        NaT    2500     2250  15.94  18.09   1.00   
7    002800  天顺股份 2016-05-19 2016-05-30    1868     1868   7.70  19.77   1.85

**Comment by zjw0358** [comment]
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
pandas    0.18.1
lxml 3.6.0

Python 3.5.1 (default, Apr 18 2016, 11:46:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 
pandas 0.18.1
lxml 3.6.0

**Comment by xwang71785** [comment]
用如下代码下载每个交易股票的当日分笔,也碰到"No tables found matching pattern '.+'"的错误
today = ts.get_today_all()
codelist = today['code']
for ccode in codelist:
    tick = ts.get_today_ticks(ccode)

**Comment by xwang71785** [comment]
Python 3.4
Pandas 0.17.1

**Comment by zjw0358** [comment]
我自己用的osx，部署到国外服务器centos上是好的。我怀疑是电信运营商中途植入广告导致的。

**Comment by esonger** [comment]
我也遇到这个问题了，如何解决
[Getting data:]#No tables found matching pattern '.+'
#No tables found matching pattern '.+'
#No tables found matching pattern '.+'
None

环境
mac os 10.＋
Python 2.7.10
tushare 0.5.0
pandas 0.18.1

**Comment by sherbetme** [comment]
![image](https://user-images.githubusercontent.com/20243038/103207837-489b4c00-493a-11eb-9d7b-b4d943ecd866.png)
linux下遇到返回的数据是nan的问题，需要如何解决

**Comment by sherbetme** [comment]
['300815', '300815', '玉禾田', '2020-01-14', '2020-01-23', '3460.0', '3114.0', '29.55', '22.98', '1.35', '10.224', '0.03']
['688266', '787266', '泽', '', '', '', '', '', '', '', '', '']
linux下new_stocks返回的数据在泽璟制药这票就有问题了，如何解决？
