### ISSUE TITLE
调用ts.get_stock_basics()并转存至mysql时报错，错误代码1170

### ISSUE THREAD

**Issue by xtheo** [waditu/tushare#136]
代码很简单：
`df =  ts.get_stock_basics() #获取所有股票基本信息。
engine = create_engine('mysql://root:1234567890@127.0.0.1/finance_data?charset=utf8')
df.to_sql('stock_basics',engine)
`

运行后报错：
`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'code' used in key specification without a key length") [SQL: u'CREATE INDEX ix_stock_basics_code ON stock_basics (code)']`

后手动在mysql为code加索引：
`alter table stock_basics add index code (code(6))`

并将上文三行代码中最后一行改为：
`df.to_sql('stock_basics',engine,if_exists='append')`

暂时解决问题。

原因应该是，在mysql中，BLOB/TEXT类型字段设置索引时，只能为BLOB/TEXT数据的前N个字符.

**Comment by zjw0358** [comment]
df.to_sql 增加参数 dtype={'code':sqlalchemy.typesVARCHAR(length=6)} 可以解决这个问题

**Comment by ca2ju3** [comment]
from sqlalchemy import create_engine
from sqlalchemy.types import VARCHAR
import tushare as ts

engine =create_engine('mysql+pymysql://root:psw@s1/test?charset=utf8')

df =ts.get_stock_basics()
df.to_sql('stock_basics',engine,if_exists='append',dtype={'code':VARCHAR(length=6)})

**Comment by gongshaojie12** [comment]
这个如何做到插入时更新
