### ISSUE TITLE
2015年之前的利润表返回结果会出现冗余数据

### ISSUE THREAD

**Issue by OracleMachine** [waditu/tushare#1364]
设定报告年份为2014年，
pro.balancesheet(ts_code='600000.SH', period=20141231,
                 fields='ts_code,ann_date,f_ann_date,end_date,report_type,total_share')
返回两行一样的数据：
ts_code	ann_date	f_ann_date	end_date	report_type	total_share
0	600000.SH	20150319	20150319	20141231	1	1.865300e+10
1	600000.SH	20150319	20150319	20141231	1	1.865300e+10

设定报告年份为2015年，
pro.balancesheet(ts_code='600000.SH', period=20151231,
                 fields='ts_code,ann_date,f_ann_date,end_date,report_type,total_share')
这时候正常返回一行数据：
ts_code	ann_date	f_ann_date	end_date	report_type	total_share
0	600000.SH	20160407	20160407	20151231	1	1.865300e+10

用户id 368176

**Comment by jimmysoa** [comment]
如果有修正，数据是可能多条的，实现的是PIT
