### ISSUE TITLE
用ts.get_stock_basics()并转存至sqlite3时报错，

### ISSUE THREAD

**Issue by chansen2000** [waditu/tushare#137]
通过df.to_sql 写入sqlite3，出现错误：
 ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

最后通过转换为 unicode字符解决，但我的问题是，为什么utf8字符不能写入呢，sqlite3字符是支持utf8的，另外，就是能通过dtype指定类型解决吗，谢谢！

**Comment by jimmysoa** [comment]
通过conn的链接设置编码？

**Comment by chansen2000** [comment]
可以啊，sqlite3，能支持编码格式指定吗，谢谢。
