### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by 850977164** [waditu/tushare#1379]
初次使用tushare，调用接口ts.get_hist_data('600848')
报错：
<urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
<urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
<urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
使用的版本为1.2.59
是什么原因呢，求赐教

**Comment by jimmysoa** [comment]
请吃用tushare pro版本，https://tushare.pro
