### ISSUE TITLE
JSONDecodeError when get_hist_data

### ISSUE THREAD

**Issue by reanghect** [waditu/tushare#139]
调用get_hist_data `获取历史数据时，通过urlopen 请求返回值，有时返回值是不完整的。无法正确解析成Json, 会丢掉一半的内容。最终在解析Json 时报错 json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 95299 (char 95298)

**Comment by jimmysoa** [comment]
多试几次，应该是网络问题，另外，报错的是那个代码？

**Comment by reanghect** [comment]
是网络的问题。报错代码出现在 json.loads(lines.decode('utf-8') if ct.PY3 else lines)
其实是由于网络原因导致get_hist_data 里面urlopen(request, timeout = 10).read() 这句返回值不全，read() 不能保证拿到全部response. 建议加一个JSONDecodeError 的exception

**Comment by jimmysoa** [comment]
好
