### ISSUE TITLE
调用 GDP ，利率接口报错

### ISSUE THREAD

**Issue by golangpkg** [waditu/tushare#1391]
/usr/local/lib/python3.6/site-packages/tushare/stock/macro.py in get_ppi()
    226                                     rdint))
    227     text = urlopen(request, timeout=10).read()
--> 228     text = text.decode('utf8','ignore') if ct.PY3 else text
    229     regSym = re.compile(r'\,count:(.*?)\}')
    230     datastr = regSym.findall(text)

**Comment by jimmysoa** [comment]
请使用pro版的接口：https://tushare.pro/document/2?doc_id=227
