### ISSUE TITLE
如何获取3年以上的历史数据？

### ISSUE THREAD

**Issue by kaoiki** [waditu/tushare#142]
通过ts.get_hist_data可以获取股票的历史数据，经过测试可以获取3年的所有数据，如何获取3年以上的数据？

例如今日最旧的数据为2013年6月24日的数据，我想获得更老的数据有无可能？

**Comment by jimmysoa** [comment]
通过get_h_data

**Comment by taanng** [comment]
通过get_h_data 发现报错，麻烦分析下，log如下
C:\Python27\lib\site-packages\tushare\stock\trading.py:441: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort('date', ascending=False)

**Comment by jimmysoa** [comment]
pandas版本的问题，新版会调整好。

**Comment by simonmysun** [comment]
你好，我这里执行
```
df = ts.get_h_data('399300')
```
和
```
df = ts.get_h_data('000300')
```
都得不到任何结果，请问是我自己的问题吗？
