### ISSUE TITLE
合作

### ISSUE THREAD

**Issue by wsf1990** [waditu/tushare#1422]
你好，我们有一款在线数据处理平台：[https://wk.phitrellis.com/](https://wk.phitrellis.com/)，主要实现流程化的表格数据处理。看到贵方平台后，想与贵方建立合作，我们考虑达到的目标是：用户上传一个股票代码excel到我方平台，再选择一个想要的操作，如获取股票实时价格等，点击运行按钮即可得到想要的结果，无需编程等操作，最大程度的方便用户。
希望贵方能够看一下我们的平台，联系方式：support@phitrellis.com

**Comment by jimmysoa** [comment]
谢谢，我先看看学习一下。

**Comment by wulinjie122** [comment]
> 谢谢，我先看看学习一下。

您好，我位置捐赠了200快，但是积分还是没变，13916158084
