### ISSUE TITLE
get_today_ticks函数报错 

### ISSUE THREAD

**Issue by xyooyy** [waditu/tushare#143]
错误1:
df = ts.get_today_ticks('000800')
[Getting data:]####Length mismatch: Expected axis has 15 elements, new values have 7 elements
Length mismatch: Expected axis has 15 elements, new values have 7 elements
Length mismatch: Expected axis has 15 elements, new values have 7 elements
获取失败，请检查网络和URL
[Getting data:]####Length mismatch: Expected axis has 15 elements, new values have 7 elements
Length mismatch: Expected axis has 15 elements, new values have 7 elements
Length mismatch: Expected axis has 15 elements, new values have 7 elements
获取失败，请检查网络和URL
[Getting data:]####Length mismatch: Expected axis has 15 elements, new values have 7 elements
Length mismatch: Expected axis has 15 elements, new values have 7 elements
Length mismatch: Expected axis has 15 elements, new values have 7 elements
获取失败，请检查网络和URL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tushare/stock/trading.py", line 254, in get_today_ticks
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
IOError: 获取失败，请检查网络和URL

python 版本是 2.7.9

**Comment by jimmysoa** [comment]
是在盘中时间获取吗？另外pandas的版本是多少？

In [1]: import tushare as ts

In [2]: df = ts.get_today_ticks('000800')
[Getting data:]##################################################

In [3]: df
Out[3]: 
                    time  price pchange  change  volume  amount type
0    2016-06-24 14:39:33  10.72   -0.19    0.00      23   24656   卖盘
1    2016-06-24 14:39:30  10.72   -0.19   -0.01      46   49312   卖盘
2    2016-06-24 14:39:24  10.73   -0.09    0.00       6    6438   买盘
3    2016-06-24 14:39:06  10.73   -0.09    0.00      20   21460   卖盘
4    2016-06-24 14:39:03  10.73   -0.09    0.00       1    1073   卖盘
5    2016-06-24 14:38:57  10.73   -0.09    0.00      10   10730   买盘
6    2016-06-24 14:38:54  10.73   -0.09    0.00      22   23606   买盘
7    2016-06-24 14:38:45  10.73   -0.09    0.01      15   16095  中性盘
8    2016-06-24 14:38:36  10.72   -0.19   -0.01      34   36448   卖盘
9    2016-06-24 14:38:33  10.73   -0.09    0.01     269  288637   买盘
10   2016-06-24 14:38:30  10.72   -0.19    0.00       1    1072   卖盘

**Comment by xyooyy** [comment]
盘后获取 pandas版本是0.18.1

**Comment by jimmysoa** [comment]
好的，我测试一下新版本运行情况。
