### ISSUE TITLE
数据缺失

### ISSUE THREAD

**Issue by congcong009** [waditu/tushare#1438]
df = pro.index_weight(index_code='399932.SZ')
返回结果为空：

`Empty DataFrame
Columns: [index_code, con_code, trade_date, weight]
Index: []`

**Comment by congcong009** [comment]
继续补充缺失数据
df = pro.index_weight(index_code='399903.SZ')
`Empty DataFrame
Columns: [index_code, con_code, trade_date, weight]
Index: []`

**Comment by congcong009** [comment]
df = pro.index_weight(index_code='990001.csi')
`Empty DataFrame
Columns: [index_code, con_code, trade_date, weight]
Index: []`

**Comment by jimmysoa** [comment]
很多指数的成分是没有的，需要授权。
