### ISSUE TITLE
通过 get_h_data 获取数据后通过 to_json 转成 JSON，日期数据丢失

### ISSUE THREAD

**Issue by kaoiki** [waditu/tushare#145]
代码
#_stockCode 股票编码，从表单提交
#_begin 起始时间，从表单提交
#_end 结束时间，从表单提交
stock_info = ts.get_hist_data(_stockCode,_begin,_end)
stock_info_json = stock_info.to_json(orient='records')

获取数据并转成json后，日期内容丢失（date没有了），命令行下可见。

例子：
_stockCode = 600150
_begin = 2016-06-01
_end = 2016-06-02
返回（json）
[{'open': 22.59, 'volume': 104886.51, 'ma20': 22.037, 'v_ma10': 84625.42, 'v_ma20': 83439.14, 'ma5': 22.31, 'p_change': -0.09, 'high': 22.69, 'close': 22.64, 'turnover': 0.76, 'v_ma5': 102599.78, 'low': 22.35, 'price_change': -0.02, 'ma10': 22.113}, {'open': 22.7, 'volume': 126627.52, 'ma20': 22.085, 'v_ma10': 79972.25, 'v_ma20': 83134.21, 'ma5': 22.136, 'p_change': 0.13, 'high': 22.95, 'close': 22.67, 'turnover': 0.92, 'v_ma5': 95906.62, 'low': 22.56, 'price_change': 0.03, 'ma10': 22.012}]
可见，date的数据没有了。

**Comment by jimmysoa** [comment]
date是index，如果用orient为records模式，可以显性多加一列date, df['date'] = df.index
