### ISSUE TITLE
profit 分配预案 拉取数据全为0

### ISSUE THREAD

**Issue by firstsko** [waditu/tushare#150]
python 2.7
tushare 0.5.0

import tushare as ts

df = ts.profit_data(top=60)
df.sort('shares',ascending=False)

divi  shares 部分 都为0
也没有任何报错

      code          name  year report_date  divi  shares
0   300429  å¼ºåæ°æ  2016  2016-07-07     0       0
1   601222  ææ´è½æº  2016  2016-07-07     0       0
2   002675  ä¸è¯è¯ä¸  2016  2016-07-06     0       0
3   000038     æ·±å¤§é  2016  2016-07-04     0       0
4   300474     æ¯åå¾®  2016  2016-06-30     0       0
5   300499  é«æ¾è¡ä»½  2016  2016-06-30     0       0
6   002695     çä¸ç  2016  2016-06-30     0       0
7   603601  ååç§æ  2016  2016-06-24     0       0
8   002053  äºåçå  2016  2016-06-24     0       0
9   300292  å´éæ§è¡  2016  2016-06-23     0       0
10  300201     æµ·ä¼¦å²  2016  2016-06-23     0       0
11  000626  å¦æéå¢  2016  2016-06-22     0       0
12  002402     åèæ³°  2016  2016-06-20     0       0
13  002256  å½©è¹ç²¾å  2016  2016-06-20     0       0
14  300428  åéæ°æ  2016  2016-06-14     0       0
15  002610  ç±åº·ç§æ  2016  2016-04-22     0       0
16  600299     å®è¿ªè  2016  2016-04-16     0       0

**Comment by jimmysoa** [comment]
制定一下年份试试，我的结果是：

      code  name  year report_date  divi  shares
15  002610  爱康科技  2016  2016-04-22   0.0      30
13  002256  彩虹精化  2016  2016-06-20   0.0      30
6   002695   煌上煌  2016  2016-06-30   1.3      30
9   300292  吴通控股  2016  2016-06-23   0.0      30
1   601222  林洋能源  2016  2016-07-07   2.0      25
0   300429  强力新材  2016  2016-07-07   0.0      21
2   002675  东诚药业  2016  2016-07-06   0.0      20
14  300428  四通新材  2016  2016-06-14   0.0      20
12  002402   和而泰  2016  2016-06-20   0.2      15
10  300201   海伦哲  2016  2016-06-23   0.0      14
7   603601  再升科技  2016  2016-06-24   5.0      12
8   002053  云南盐化  2016  2016-06-24   0.0      10
11  000626  如意集团  2016  2016-06-22   3.3      10
4   300474   景嘉微  2016  2016-06-30   1.8      10
5   300499  高澜股份  2016  2016-06-30   0.0       8
3   000038   深大通  2016  2016-07-04   0.0       6
16  600299   安迪苏  2016  2016-04-16   1.7       0

**Comment by firstsko** [comment]
#!/usr/bin/env python
  import tushare as ts
 
  df=ts.profit_data(top=60,year='2016')
  print df

0   300026  çº¢æ¥è¯ä¸  2016  2016-07-12     0       0
1   600777  æ°æ½®è½æº  2016  2016-07-12     0       0
2   002141  èèè¶å¾®  2016  2016-07-11     0       0
3   002113  å¤©æ¶¦æ°å¨±  2016  2016-07-09     0       0
4   300429  å¼ºåæ°æ  2016  2016-07-07     0       0
5   601222  ææ´è½æº  2016  2016-07-07     0       0
6   002675  ä¸è¯è¯ä¸  2016  2016-07-06     0       0
7   000038     æ·±å¤§é  2016  2016-07-04     0       0
8   300474     æ¯åå¾®  2016  2016-06-30     0       0
9   300499  é«æ¾è¡ä»½  2016  2016-06-30     0       0
10  002695     çä¸ç  2016  2016-06-30     0       0
11  603601  ååç§æ  2016  2016-06-24     0       0
12  002053  äºåçå  2016  2016-06-24     0       0
13  300292  å´éæ§è¡  2016  2016-06-23     0       0
14  300201     æµ·ä¼¦å²  2016  2016-06-23     0       0
15  000626  å¦æéå¢  2016  2016-06-22     0       0
16  002402     åèæ³°  2016  2016-06-20     0       0
17  002256  å½©è¹ç²¾å  2016  2016-06-20     0       0
18  300428  åéæ°æ  2016  2016-06-14     0       0
19  002610  ç±åº·ç§æ  2016  2016-04-22     0       0
20  600299     å®è¿ªè  2016  2016-04-16     0       0

很是奇怪，终端字符编码是utf-8

**Comment by firstsko** [comment]
似乎连获取到的内容都不一样。

**Comment by jimmysoa** [comment]
你的tushare是什么版本？


In [1]: import tushare as ts

In [2]: df = ts.profit_data(year=2016, top=60)
[Getting data:]

In [3]: df
Out[3]: 
      code  name  year report_date  divi  shares
0   300465   高伟达  2016  2016-07-13   0.0      22
1   300026  红日药业  2016  2016-07-12   0.0      20
2   600777  新潮能源  2016  2016-07-12   0.0      28
3   002141  蓉胜超微  2016  2016-07-11   0.0      25
4   002113  天润数娱  2016  2016-07-09   0.0      30
5   300429  强力新材  2016  2016-07-07   0.0      21
6   601222  林洋能源  2016  2016-07-07   2.0      25
7   002675  东诚药业  2016  2016-07-06   0.0      20
8   000038   深大通  2016  2016-07-04   0.0       6
9   300474   景嘉微  2016  2016-06-30   1.8      10
10  300499  高澜股份  2016  2016-06-30   0.0       8
11  002695   煌上煌  2016  2016-06-30   1.3      30
12  603601  再升科技  2016  2016-06-24   5.0      12
13  002053  云南盐化  2016  2016-06-24   0.0      10
14  300292  吴通控股  2016  2016-06-23   0.0      30
15  300201   海伦哲  2016  2016-06-23   0.0      14
16  000626  如意集团  2016  2016-06-22   3.3      10

**Comment by firstsko** [comment]
python 2.7
tushare 0.5.0
很是奇怪，其他都没问题，就这个有问题，源码直接这里copy了过去
>>> df = ts.profit_data(top=60)                                         
[Getting data:]##>>> print df
      code          name  year report_date  divi  shares
0   002798  氓赂?莽??忙麓?氓?路  2015  2016-06-08     0       0
1   603701  氓戮路氓庐?猫?隆盲禄陆  2015  2016-06-02     0       0
2   300509     忙?掳莽戮?忙??  2015  2016-06-01     0       0
3   300511  茅?陋忙娄?莽??莽?漏  2015  2016-05-24     0       0
4   300508  莽禄麓氓庐?猫?隆盲禄陆  2015  2016-05-11     0       0
5   002605  氓搂?猫庐掳忙??氓??  2015  2016-04-30     0       0
6   002366  氓?掳忙碌路忙?赂莽?碌  2015  2016-04-30     0       0
7   002325  忙麓陋忙露?猫?隆盲禄陆  2015  2016-04-30     0       0
8   002312  盲赂?忙鲁掳忙?搂猫?隆  2015  2016-04-30     0       0
9   300318  氓??忙??氓??忙?掳  2015  2016-04-30     0       0
10  000961  盲赂颅氓??氓禄潞猫庐戮  2015  2016-04-30     0       0
11  000938  莽麓芦氓??猫?隆盲禄陆  2015  2016-04-30     0       0
12  000887  盲赂颅茅录?猫?隆盲禄陆  2015  2016-04-30     0       0
13  000690  氓庐?忙?掳猫?陆忙潞?  2015  2016-04-30     0       0
14  000539    莽虏陇莽?碌氓??A  2015  2016-04-30     0       0
15  000402     茅??猫??猫隆?  2015  2016-04-30     0       0
16  000061     氓??盲潞搂氓??  2015  2016-04-30     0       0
17  600686  茅??茅戮?忙卤陆猫陆娄  2015  2016-04-30     0       0
18  600677  猫?陋氓陇漏茅??盲驴隆  2015  2016-04-30     0       0
19  600189  氓??忙??忙拢庐氓路楼  2015  2016-04-30     0       0
20  603223  忙??茅??猫?隆盲禄陆  2015  2016-04-29     0       0
21  603918  茅??忙隆楼盲驴隆忙?炉  2015  2016-04-29     0       0
22  603198  猫驴?茅漏戮猫麓隆茅??  2015  2016-04-29     0       0
23  601021  忙?楼莽搂?猫?陋莽漏潞  2015  2016-04-29     0       0
24  300343  猫??氓??盲潞?猫??  2015  2016-04-29     0       0
25  002680  茅?驴莽??莽??莽?漏  2015  2016-04-29     0       0
26  300429  氓录潞氓??忙?掳忙??  2015  2016-04-29     0       0
27  300287     茅拢?氓?漏盲驴隆  2015  2016-04-29     0       0
28  603077  氓??茅?娄莽??莽?漏  2015  2016-04-29     0       0
29  002624  氓庐?莽戮?莽?炉莽??  2015  2016-04-29     0       0
30  603558  氓?楼莽??茅??氓?垄  2015  2016-04-29     0       0
31  002567     氓??盲潞潞莽楼?  2015  2016-04-29     0       0
32  601985  盲赂颅氓?陆忙?赂莽?碌  2015  2016-04-29     0       0
33  300016  氓??茅??猫?炉盲赂?  2015  2016-04-29     0       0
34  601101  忙??氓??猫?陆忙潞?  2015  2016-04-29     0       0
35  601901  忙?鹿忙颅拢猫炉?氓?赂  2015  2016-04-29     0       0
36  600900  茅?驴忙卤?莽?碌氓??  2015  2016-04-29     0       0
37  600469  茅拢?莽楼?猫?隆盲禄陆  2015  2016-04-29     0       0
38  600031  盲赂?盲赂?茅??氓路楼  2015  2016-04-29     0       0
39  600584  茅?驴莽?碌莽搂?忙??  2015  2016-04-29     0       0
40  600004  莽?陆盲潞?忙?潞氓?潞  2015  2016-04-29     0       0
41  000899  猫碌拢猫?陆猫?隆盲禄陆  2015  2016-04-29     0       0
42  000883  忙鹿?氓??猫?陆忙潞?  2015  2016-04-29     0       0
43  000869       氓录?猫拢?A  2015  2016-04-29     0       0
44  000852  莽?鲁氓??忙?潞忙垄掳  2015  2016-04-29     0       0
45  000816  忙?潞忙?搂氓??盲赂?  2015  2016-04-29     0       0
46  000729  莽??盲潞卢氓?陇茅??  2015  2016-04-29     0       0
47  000709  忙虏鲁茅?垄猫?隆盲禄陆  2015  2016-04-29     0       0
48  000651  忙?录氓??莽?碌氓?篓  2015  2016-04-29     0       0
49  000637  猫??氓??氓庐?氓??  2015  2016-04-29     0       0
50  000616  忙碌路猫?陋忙??猫碌?  2015  2016-04-29     0       0
51  000571    忙?掳氓陇搂忙麓虏A  2015  2016-04-29     0       0
52  000565    忙赂?盲赂?氓鲁隆A  2015  2016-04-29     0       0
53  600825  忙?掳氓??盲录?氓陋?  2015  2016-04-29     0       0
54  600824  莽??忙掳?茅??氓?垄  2015  2016-04-29     0       0
55  600783  茅虏?盲驴隆氓??忙??  2015  2016-04-29     0       0
56  600757  茅?驴忙卤?盲录?氓陋?  2015  2016-04-29     0       0
57  000009  盲赂颅氓?陆氓庐?氓庐?  2015  2016-04-29     0       0
58  600272  氓录?氓录?氓庐?盲赂?  2015  2016-04-29     0       0
59  600295  茅??氓掳?氓陇?忙?炉  2015  2016-04-29     0       0

**Comment by firstsko** [comment]
Centos 6.4 64位，终端编码utf8

**Comment by firstsko** [comment]
拉其他的没问题,代码完全clone的最新版
#!/usr/bin/env python
  import tushare as ts
  df = ts.forecast_data(2016,2)
  print df

(tushare_env) [root@10-10-158-62 iia_data2]# python test.py 
[Getting data:]#######       code  name type report_date  pre_eps              range
0    600322  天房发展   预亏  2016-07-16   0.0295                  0
1    000815  美利纸业   减亏  2016-07-16  -0.4700      66.47%~69.82%
2    600778  友好集团   预亏  2016-07-16   0.2813                  0
3    600586  金晶科技   预盈  2016-07-16  -0.0500                  0
4    600596  新安股份   减亏  2016-07-16  -0.0501                  0
5    600880  博瑞传播   预减  2016-07-16   0.0700                -90
6    000595  宝塔实业   减亏  2016-07-16  -0.1340                  0
7    600965  福成股份   预降  2016-07-16   0.0800              -3.75
8    600984  建设机械   预盈  2016-07-16  -0.1431                  0
9    600048  保利地产   预升  2016-07-16   0.4600               0.12
10   600798  宁波海运   预升  2016-07-16   0.0048                  0
11   600161  天坛生物   预增  2016-07-16   0.1100            70%~80%
12   002735  王子新材   预升  2016-07-15   0.1400             0%~20%
13   600618  氯碱化工   预盈  2016-07-15  -0.0421                  0
14   000561  烽火电子   预增  2016-07-15   0.0100                  0
15   002378  章源钨业   减亏  2016-07-15  -0.0300                  0
16   000525   红太阳   预减  2016-07-15   0.3460             -67.39
17   600269  赣粤高速   预增  2016-07-15   0.1800            60%~80%
18   002483  润邦股份   预增  2016-07-15   0.0800          120%~170%
19   000518  四环生物   预亏  2016-07-15   0.0040                  0
20   000989   九芝堂   预升  2016-07-15   0.2700      29.07%~42.66%
21   002700  新疆浩源   预降  2016-07-15   0.1300          -30%~-10%
22   600108  亚盛集团   预减  2016-07-15   0.0447          -60%~-50%
23   002205  国统股份   预亏  2016-07-15   0.0348                  0
24   000929  兰州黄河   预亏  2016-07-15   0.9009                  0
25   000519  江南红箭   预减  2016-07-15   0.1950    -79.84%~-78.45%
26   000809  铁岭新城   预亏  2016-07-15  -0.0800                  0
27   002010  传化股份   预增  2016-07-15   0.2100          220%~250%
28   000547  航天发展   预增  2016-07-15   0.1600            35%~63%
29   000652  泰达股份   预增  2016-07-15   0.0124                  0
..      ...   ...  ...         ...      ...                ...
343  002618  丹邦科技   预减  2016-07-14   0.1591          -70%~-50%
344  300035  中科电气   预降  2016-07-14   0.0700            -10%~0%
345  603299  井神股份   预减  2016-07-14   0.0800          -87%~-79%
346  300270  中威电子   预升  2016-07-14   0.1100             0%~30%
347  002469  三维工程   预减  2016-07-14   0.1900          -80%~-60%
348  600584  长电科技   预减  2016-07-14   0.1300          -95%~-85%
349  000897  津滨发展   预盈  2016-07-14  -0.0462                  0
350  300389   艾比森   预升  2016-07-14   0.2755            36%~49%
351  300069  金利华电   预增  2016-07-14   0.0600          170%~190%
352  300177   中海达   预增  2016-07-14   0.0251            45%~75%
353  002458  益生股份   预盈  2016-07-14  -0.6800                  0
354  300282  汇冠股份   预增  2016-07-14   0.2024            45%~75%
355  300139  晓程科技   预减  2016-07-14   0.1400         -100%~-80%
356  002385   大北农   预增  2016-07-14   0.0800            70%~80%
357  300294  博雅生物   预增  2016-07-14   0.6200            40%~70%
358  000803  金宇车城   预亏  2016-07-14  -0.0600                  0
359  002645  华宏科技   预增  2016-07-14   0.0077  2387.97%~2802.64%
360  000672  上峰水泥   预减  2016-07-14   0.0700                  0
361  000655  金岭矿业   预亏  2016-07-14  -0.0700        -204%~-180%
362  000952  广济药业   预盈  2016-07-14  -0.0880                  0
363  002252  上海莱士   预降  2016-07-14   0.6100          -24%~-20%
364  000948  南天信息   预亏  2016-07-14  -0.1956                  0
365  300488  恒锋工具   预升  2016-07-14   0.6300             0%~20%
366  000702  正虹科技   预亏  2016-07-14   0.0143                  0
367  000753  漳州发展   预盈  2016-07-14  -0.0550                  0
368  300180  华峰超纤   预降  2016-07-14   0.2100          -50%~-20%
369  000608  阳光股份   预亏  2016-07-14  -0.0200        -922%~-501%
370  300247  乐金健康   预增  2016-07-14   0.0449            30%~60%
371  000627  天茂集团   预盈  2016-07-14  -0.0280                  0
372  300295  三六五网   预升  2016-07-14      NaN                NaN

[373 rows x 6 columns]
