### ISSUE TITLE
指数代码

### ISSUE THREAD

**Issue by pittmiqi** [waditu/tushare#152]
请问下面的指数的code是什么
根据df = ts.get_index() 返回的值如下，但这些code显然是代表深圳股票，不是需要的指数。

0   000001    上证指数  -1.13   4527.396   4476.215   4572.391   4432.904
1   000002    Ａ股指数  -1.13   4744.093   4690.628   4791.534   4645.190
2   000003    Ｂ股指数  -2.15    403.694    395.018    405.795    392.173
3   000008    综合指数   0.79   3724.496   3753.906   3848.575   3695.817
4   000009   上证380  -2.79   7689.128   7474.305   7695.329   7398.911
5   000010   上证180  -1.13  10741.180  10619.610  10863.080  10529.900
6   000011    基金指数  -1.02   7033.291   6961.659   7058.856   6918.273
7   000012    国债指数   0.01    148.626    148.641    148.656    148.510
8   000016    上证50  -0.79   3308.454   3282.330   3370.025   3255.769
9   000017     新综指  -1.13   3826.013   3782.936   3864.307   3746.284

**Comment by jimmysoa** [comment]
？？？

**Comment by ilovewengy** [comment]
我也有类似的问题，可以获得深圳指数数据，比如399006, 399001 等，但无法获得上证指数的历史数据，比如尝试000001,得到的结果是平安银行的数据而不是上证指数的数据，也尝试了使用sh000001,但没这个代码。

**Comment by jimmysoa** [comment]
历史数据用get_h_data获取

**Comment by ilovewengy** [comment]
比如我使用 df=ts.get_h_data("000001") 
获得的是平安银行的历史数据，而不是上证指数的历史数据。请问上证指数的代码是什么呢？
我试过sh000001 但没有这个代码

**Comment by ilovewengy** [comment]
df=ts.get_h_data("sh000001")
会报错，没有这个代码

**Comment by ilovewengy** [comment]
我觉得我找到办法了
应该是 df=ts.get_h_data('000001', index=True) 
但只有一年的数据，更少？

**Comment by ilovewengy** [comment]
解决了，有start和end 参数，多谢！！！
