### ISSUE TITLE
关于票房数据的疑问

### ISSUE THREAD

**Issue by jinchener** [waditu/tushare#153]
请问，票房数据输入的日期返回的是当日票房数据么？
和网站显示不太一样，比如，‘2016-7-9’，实际上是网站上2016-7-10的数据

**Comment by jimmysoa** [comment]
网站接口好像是调整了，默认只能取最近几日，如果是早些前历史就显示最后能取到数据日期的数据。

**Comment by jinchener** [comment]
哦，那就是只能取到近7天的数据了是么
