### ISSUE TITLE
请问能否增加获取各种指标的功能？

### ISSUE THREAD

**Issue by inkcomic** [waditu/tushare#158]
MACD,KDJ等主要指标的分时，日，周，月指标。

**Comment by jimmysoa** [comment]
以后会考虑增加技术指标的计算接口

**Comment by inkcomic** [comment]
谢谢，本来想尝试自己拉取所有的K线数据进行计算的，但是及时的计算所有股票的分时指标数据感觉量也不小。主要是个人分析数据用。如果能够获取到财经平台的各种指标分时日周月那就省去很多计算量了。

**Comment by panruoyu** [comment]
我感觉tuShare就应该定位在“金融数据获取”这个领域里，面太宽反而没有什么意思

在“金融数据获取”这个领域里，tuShare其实也还有很多地方可以发展

**Comment by jimmysoa** [comment]
@panruoyu 对的，谢谢

**Comment by zezhou** [comment]
我觉得在wiki里加一篇说明，教大家怎么用talib + tushare 计算指标就够了

**Comment by jimmysoa** [comment]
@zezhou OK
