### ISSUE TITLE
df = pro.daily()使用offset有数据重复问题

### ISSUE THREAD

**Issue by cgf555** [waditu/tushare#1582]
pro.daily(offset=65000)
pro.daily(offset=70000) 

使用以上参数分别获取数据时，出现重复数据，
如ts_code:601158.SH ，trade_date: 20210813的数据两个参数获取的数据都存在 ，我理解是每次获取5000条数据，在offset不重复时，不应该出现重复的数据 

ID：462913

**Comment by jimmysoa** [comment]
这个接口不支持分页
