### ISSUE TITLE
在使用财务报表接口获取利润表的时候出现了重复的记录和字段缺失

### ISSUE THREAD

**Issue by weiweiwang** [waditu/tushare#1588]
在使用财务报表接口获取利润表的时候出现了重复的记录，资产负债表和现金流量表也有不同程度的类似问题，参看下述获取的记录
[600300.SH.xlsx](https://github.com/waditu/tushare/files/7282560/600300.SH.xlsx)

此外利润表还有如下的问题：
1. 2020年营业总成本和财报的数据不一致，46.33亿   vs 45.94亿
2. 缺少研发费用
3. 缺少财报中其他经营收益中的：资产处置收益，信用减值损失，其他收益
（财报中的数据和东方财富客户端的数据一致）

tushare id：469377

**Comment by jimmysoa** [comment]
udpate_flag=1是更新的数据，update_flag=0是原始数据，研发费用等新会计财务准则的数据会在近期发布，可以加qq群关注更新动态
