### ISSUE TITLE
凤凰财经提供的周K线和月K线的成交量和换手率有错误

### ISSUE THREAD

**Issue by ac0x** [waditu/tushare#16]
和新浪财经，甚至和凤凰财经网站上的数据不一致。

**Comment by wuxianliang** [comment]
请问是哪只股票？哪一周？

**Comment by ac0x** [comment]
比如 sz 000001, 平安银行,  5月15日这一周成交量应该是960亿+，但是接口里是1425亿+

**Comment by jimmysoa** [comment]
我检查一下，你可以先用get_h_data接口来获取和计算，这个接口还是很准的。

**Comment by ac0x** [comment]
日K是对的，就是周K和月K不对，跟踪了一下，凤凰财经的接口就是错的。。。

**Comment by jimmysoa** [comment]
对，我看到了，有些是对的有些有问题。

**Comment by ac0x** [comment]
请问准备怎么解决？

**Comment by jimmysoa** [comment]
暂时只能用get_h_data这个接口，我争取以后不用凤凰财经的数据，换一个质量好的。sina的数据其实很好，只是加密了，我还没时间破解。

**Comment by ac0x** [comment]
好的，辛苦。
点测了几只股票，get_hist_data的日k数据好像是对的。
