### ISSUE TITLE
调用get_h_data('000033')获取000033的行情信息，结果为None。

### ISSUE THREAD

**Issue by MoroJoJo** [waditu/tushare#160]
调用get_h_data('000033')获取000033的行情信息，结果为None。
而调用get_hist_data('000033')获取000033的近行情信息，结果为有数据。

**Comment by jimmysoa** [comment]
确认停牌的问题

**Comment by MoroJoJo** [comment]
设置起始时间，调用get_h_data('000033', start='2000-01-01', end='2015-04-29')返回结果仍然是None

>>> data = ts.get_h_data('000033', start='2000-01-01', end='2015-04-29')
[Getting data:]#############################################################/Users/epic_ios/anaconda/lib/python3.5/site-packages/tushare/stock/trading.py:441: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort('date', ascending=False)
>>> data
>>> print(data)
None
>>>

**Comment by MoroJoJo** [comment]
同样的参数，查000032返回3532条数据
>>> data = ts.get_h_data('000032', start='2000-01-01', end='2015-04-29')
[Getting data:]#############################################################>>> print(len(data))
3532
>>>
