### ISSUE TITLE
老接口今天开始403 forbidden了

### ISSUE THREAD

**Issue by Vector-Cross** [waditu/tushare#1620]
import tushare as ts
a = ts.get_realtime_quotes(['sh'])
print(a)

今天开始403 forbidden了，是老接口停止维护了还是服务器出了问题呀

**Comment by derekgray23** [comment]
I have encountered this problem too.

**Comment by zhangsheng377** [comment]
+1

**Comment by derekgray23** [comment]
tushare 1.2.83 fixed it.

**Comment by Vector-Cross** [comment]
> 1.2.83

thanks, its works for me.
pip install tushare==1.2.83
