### ISSUE TITLE
tick.py编码异常导致导致pyinstaller打包失败

### ISSUE THREAD

**Issue by lxz8999** [waditu/tushare#1639]
![63ede3fdc422769becc764df98dff03](https://user-images.githubusercontent.com/17425395/160320816-fea11597-bd9e-446c-8d04-be55fbfb818d.png)
![d12260c21b5a4e4d6ec15bc3c45e0f8](https://user-images.githubusercontent.com/17425395/160320888-d5e76788-9188-4385-a79c-37d66b34ba7d.png)
IDE打开后需要用GBK重载，然后转utf-8才能正常打包。
版本号是1.2.84

**Comment by jianyuanyang** [comment]
是要吧所有的文件全部打开一次么?

**Comment by lxz8999** [comment]
> 是要吧所有的文件全部打开一次么?

差不多，逐个模块排查定位到tushare，下载tushare源码包逐个文件打开才确定问题

**Comment by jimmysoa** [comment]
升级到最新版
