### ISSUE TITLE
通联数据获取失败

### ISSUE THREAD

**Issue by peterz3g** [waditu/tushare#164]
>>> mkt = ts.Market(); df = mkt.TickRTSnapshot(securityID='000001.XSHE')
>>> df
Empty DataFrame
Columns: [-403:Need privilege]
Index: []

如上，按照文档操作，但没有得到结果．

**Comment by jimmysoa** [comment]
需要购买

**Comment by yssource** [comment]
1. 现在新版的 通联数据还有开发者免费一年的数据吗? 
2. 如何注册成为开发者? 找不到开发者选项了.

**Comment by jimmysoa** [comment]
没有免费了

**Comment by hardywu** [comment]
悲剧

**Comment by yllyx** [comment]
悲剧啊！这些券商是怎么获取这些数据的呢？？？
