### ISSUE TITLE
每日指标-603569.SH-20210402-pb值有误

### ISSUE THREAD

**Issue by ryshi** [waditu/tushare#1644]
每日指标接口
参数如图
<img width="544" alt="image" src="https://user-images.githubusercontent.com/1818419/163503725-14f4c3a1-1776-460d-aa3f-9be34b4f263f.png">

问题数据如图，20210402 ~ 20210416 市净率有误
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1818419/163503818-0f659bbb-88b0-49e6-8aef-5678f4f838ce.png">

id : 356965

**Comment by ryshi** [comment]
`300229.SZ` 的 `2022-04-06 ~ 2022-04-21` 也出现了异常值，看起来这是个普遍存在的问题

<img width="680" src="https://user-images.githubusercontent.com/1818419/164582327-eb305dd1-e4c7-4791-b00a-356392229938.png">

**Comment by jimmysoa** [comment]
财报调整后就会有变化

**Comment by ryshi** [comment]
感觉并不那么简单，如果是财报引发的变化，之后的市净率会一直如此，但有问题的数据变化了10几天后又恢复到变化以前的数据值。尤其 0.02 这样偏离比较严重的数据就更难处理了
