### ISSUE TITLE
基金数据存在赋权因子和交易日线数量对不上

### ISSUE THREAD

**Issue by Tender2233** [waditu/tushare#1648]
例如 515220.SH
日线返回数据中20201029 20200918两个交易日无法查询到赋权因子

**Comment by jimmysoa** [comment]
以交易行情数量为准

**Comment by cty198** [comment]
确实，发现ETF行情数据 在20200918当日缺少复权因子值，该日为交易日，可取得正常的不复权价格，但缺少当日复权因子，希望检查数据源
