### ISSUE TITLE
建议增加分时数据接口

### ISSUE THREAD

**Issue by peterz3g** [waditu/tushare#165]
在股票软件看股的时候，第一页一般都是分时数据．
但是目前没有获取分时数据的接口，历史数据里面也只是到５分钟的Ｋ线．
建议：
增加：１分钟Ｋ线历史查询
增加：当日分时数据的历史查询如：ＸＸＸＸ股，开始时间，结束时间；　返回每一分钟的数据
增加：当日最近一分钟的分时数据实时查询
谢谢

**Comment by jimmysoa** [comment]
谢谢建议，如果有合适的数据源，会增加进来。
