### ISSUE TITLE
get_latest_news(): Error reading content - failed to load HTTP resource

### ISSUE THREAD

**Issue by hiemal** [waditu/tushare#168]
Ubuntu 12.04
Python 3.5 (Anaconda)
system languange: English

import tushare.stock.newsevent as fd
fd.get_latest_news(top=3, show_content=True)

---

line 119: b'Invalid char in CDATA 0x0'
line 119: b'Invalid char in CDATA 0x0'
Error reading file 'http://finance.sina.com.cn/stock/usstock/c/2016-08-10/doc-ifxuxnah3048945.shtml': failed to load HTTP resource

**Comment by jimmysoa** [comment]
编码问题？尝试设置一下编码看
