### ISSUE TITLE
今天基础数据连不上，是什么情况？

### ISSUE THREAD

**Issue by arisliang** [waditu/tushare#1684]
```
pro = ts.pro_api()

#查询当前所有正常上市交易的股票列表

data = pro.stock_basic(exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')
```

> ConnectionError: HTTPConnectionPool(host='api.waditu.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000263BFDA1CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by QuestMi** [comment]
我也是遇到了这个问题.

**Comment by chenditc** [comment]
好像是 api.waditu.com 这个域名挂了

**Comment by chenditc** [comment]
更新 python sdk 就可以了。用新域名 api.tushare.pro

**Comment by arisliang** [comment]
更新了pip，可以了。
