### ISSUE TITLE
大单数据接口无返回数据

### ISSUE THREAD

**Issue by ddxgz** [waditu/tushare#169]
ts.get_sina_dd('******', date='****-**-**') 无返回数据，不知是否新浪那边的接口失效了

**Comment by jimmysoa** [comment]
是怎么调用的？我试了下有数据，你要确认这个股票这一天是否确实有大单

In [2]: ts.get_sina_dd('600848', date='2016-08-12')
Out[2]: 
      code  name      time  price  volume  preprice type
0   600848  上海临港  14:57:41  21.35   42600     21.38   卖盘
1   600848  上海临港  14:56:41  21.39   41500     21.38   买盘
2   600848  上海临港  14:41:59  21.38   63884     21.40   卖盘
3   600848  上海临港  14:33:37  21.44   46100     21.41   买盘
4   600848  上海临港  14:19:50  21.56   72500     21.59  中性盘
5   600848  上海临港  14:19:44  21.59   59300     21.55   买盘
6   600848  上海临港  14:19:05  21.55   65400     21.54   买盘
7   600848  上海临港  14:17:25  21.50   66900     21.48   买盘
8   600848  上海临港  14:16:59  21.44   51200     21.46   卖盘
9   600848  上海临港  14:14:14  21.45  182000     21.43   买盘
10  600848  上海临港  13:57:01  21.35   50500     21.39   卖盘
11  600848  上海临港  13:46:40  21.50   69500     21.40   买盘
12  600848  上海临港  13:45:19  21.50   54200     21.50   买盘
13  600848  上海临港  13:44:59  21.50   71100     21.50   卖盘
14  600848  上海临港  13:44:34  21.54   77600     21.54   卖盘
15  600848  上海临港  13:43:49  21.50   51200     21.45   买盘
16  600848  上海临港  13:40:53  21.58   69800     21.50   买盘
17  600848  上海临港  13:40:19  21.48  109900     21.50   卖盘
18  600848  上海临港  13:39:59  21.49   53800     21.48  中性盘
19  600848  上海临港  13:39:53  21.48   86300     21.48   卖盘
20  600848  上海临港  13:39:04  21.40  107500     21.35   买盘
21  600848  上海临港  13:38:43  21.38   67700     21.32   买盘
22  600848  上海临港  13:37:47  21.30   66300     21.25   买盘
23  600848  上海临港  13:36:17  21.25   50700     21.20   买盘
24  600848  上海临港  13:35:43  21.20   51200     21.15   买盘
25  600848  上海临港  13:32:22  21.00   47300     20.96   买盘
26  600848  上海临港  11:17:52  21.00   66100     20.98   买盘
27  600848  上海临港  09:50:00  20.76   46800     20.74   买盘

In [3]:

**Comment by ddxgz** [comment]
@jimmysoa 
不好意思，是我调用的时候没有检查 vol 的类型，接口正常。谢了！
