### ISSUE TITLE
关于期货数据接口?

### ISSUE THREAD

**Issue by cosnis** [waditu/tushare#17]
我看到有一个版本的提交里写了 "期货实时数据获取"

是指可以在 tushare 里查看 期货的 tick 数据了么?  数据源应该还好, 随便注册个 ctp 就可以用了

但是现在的 methods 里没看到的样子, 是会到下个版本里么?

另外, 如果期货的 methods 和股票的用在一起, 会不会太混乱了.....  希望能分离开..

以及是否能对信息类和数据类的方法分离一下? 

例如: 
ts.info.get_gdp_\* 
ts.stock.get_today
这样子....

**Comment by ideaplat** [comment]
恩，建议搜索vnpy这个开源项目。期货项目暂时停止开发。

**Comment by jimmysoa** [comment]
@cosnis : 目前github里的期货接口只是测试用,以后会提供期货数据的接口.
另外你的建议很好,我会考虑分开实现,包括基金数据等,不会造成混乱,谢谢.

**Comment by cosnis** [comment]
@ideaplat vnpy 看了下, 我自己有用 c++ 实现交易的部分, 现在对数据源的部分更感兴趣

**Comment by jimmysoa** [comment]
谢谢cosnis
