### ISSUE TITLE
基本面数据股票列表中的PE值异常（网络数据源头问题）

### ISSUE THREAD

**Issue by adenly69** [waditu/tushare#170]
Mac OS 10.11.16
Python 2.7.11
System Language: English

**在ipython中执行如下命令**
import tushare as ts
data = ts.get_stock_basics()
data['pe'].sort_values().tail(10)

**返回值：**
Out[25]: 
code
600876     7832.19
300404     7955.13
600462     8455.59
600685     9828.90
000017    10580.38
600217    11587.24
000881    17822.81
000408    27340.45
600561    30918.14
600753    38345.30
Name: pe, dtype: float64

**debug**
看了下代码，发现根源应该是股票列表的源头 http://'http://218.244.146.57/static/all.csv 里的数据本身有问题

**Comment by CaoKang-David** [comment]
我刚拿数据与通达信的比较了下 没问题啊。

**Comment by adenly69** [comment]
@CaoKang-David PE三万多似乎不太合理，另外我是跟雪球上的PE做了下对比，列出来的那几个的确差距很大,比如600753东方银星在雪球上的市盈率是LYR/TTM：**91.99/91.6**1， 咱们tushare返回的如在issue贴出来的是**38345.30**

**Comment by jimmysoa** [comment]
这个数据用的是通达信的数据源，还不太确定他们的计算公式。

**Comment by xungeer** [comment]
@jimmysoa 通达信的PE貌似是按照最近报告期计算的
