### ISSUE TITLE
df.sort方法产生了一个警告

### ISSUE THREAD

**Issue by linwei-yoh** [waditu/tushare#171]
Warning (from warnings module):
  File "D:\Python\lib\site-packages\tushare\stock\trading.py", line 441
    df = df.sort('date', ascending=False)
FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

**Comment by linwei-yoh** [comment]
请问能否升级下。

**Comment by jimmysoa** [comment]
新版本会考虑进来，主要是pandas的版本的变化造成了这个警告。

**Comment by linwei-yoh** [comment]
恩 是的
