### ISSUE TITLE
ts.get_h_data()接口程序返回的数据是未复权的

### ISSUE THREAD

**Issue by lxdatgithub** [waditu/tushare#176]
获取数据的部分代码如下：
```
startDate = str(yearVar) + "-01-01";
endDate = str(yearVar) + "-12-31";
print "start" + startDate;
df = ts.get_h_data(stockID,start=startDate,end=endDate);
df = df.sort_index();
df.to_sql(stockID+"_day_basic",db,if_exists='append');
```
批量获取回到本地数据库后，很多数据都是未复权，
以下是两个图片
000002，万科
![000002](https://cloud.githubusercontent.com/assets/21240922/17968968/61aae4f0-6b02-11e6-866e-8265f5b3c0f6.jpg)
600519，贵州茅台
![600519](https://cloud.githubusercontent.com/assets/21240922/17968970/6a1fcfd8-6b02-11e6-925e-809dbe0960f8.jpg)

PS：非常感谢您提供了Tushare工具，为我的策略分析带来了很大的方便。

**Comment by jimmysoa** [comment]
get_h_data默认是前复权的。

**Comment by lxdatgithub** [comment]
如果分年段获取，不是按照最新的前复权数据获取吗？
获取回来的数据为什么会有很多跳变？

谢谢。

**Comment by lxdatgithub** [comment]
```
a=ts.get_h_data('000002',start='2007-01-01',end='2007-12-31')
b=ts.get_h_data('000002',start='2008-01-01',end='2008-12-31')
c=ts.get_h_data('000002',start='2007-01-01',end='2008-12-31')
```
a:
date	open	high	close	low	volume	amount
**2007-12-28	24.01	24.17	23.54	23.49	114970833.0	3358320329.0
**2007-12-27	22.73	24.14	23.92	22.32	182320973.0	5238361864.0
b:
date	open	high	close	low	volume	amount
2008-01-03	65.99	65.99	64.61	63.52	97292411.0	2758851175.0
2008-01-02	65.81	66.92	66.19	64.38	93879671.0	2719853946.0
c:
date	open	high	close	low	volume	amount
2008-01-03	65.99	65.99	64.61	63.52	97292411.0	2758851175.0
2008-01-02	65.81	66.92	66.19	64.38	93879671.0	2719853946.0
**2007-12-28	66.69	67.14	65.4	65.26	114970833.0	3358320329.0**
**2007-12-27	63.15	67.05	66.46	62.02	182320973.0	5238361864.0**

这是返回的数据
目前存在这样的跳变，请问有没有方法可以消除。

**Comment by lxdatgithub** [comment]
经过测试，分年段测试会有数据的跳变，使用从上市日期到当日下载的方式，复权数据是完整的,没有跳变（ts.get_h_data('000002',start=toMarketDate,end=today))。
背后的原理不懂，希望您能指教分年段下载和全年份下载背后所使用的除权模型差异在哪？

**Comment by jimmysoa** [comment]
分段复权是从end日期往前复权，区别于所有行情软件看到的是从最近一个交易所向前复权。理论上讲，指定日期的复权数据就应该从end日期向前复权，而不是从最近一个交易日开始，如果这样的话就加入了未来数据。

**Comment by lxdatgithub** [comment]
那明白了，非常感谢。
