### ISSUE TITLE
get_today_all无法获取数据，建议添加获取某日全部股票数据接口get_date_all

### ISSUE THREAD

**Issue by applebull** [waditu/tushare#181]
其实有两个问题：
问题1：我在海外，使用get_today_all的时候经常会无法顺利获取数据，尤其是过了北京时间下午时段之后就几乎不可能顺利获取数据，重试一整天都不行，请这个问题是不是仅仅针对海外IP访问tushare的数据服务器才有？如果添加国内的代理服务器的话，哪个网络会比较快？

问题2：建议添加get_date_all下载指定某个日期的全部A股数据，否则按每只个股去补全数据非常慢，需要超过24小时才能下载，会造成数据无法在第二天开盘前实现更新。

谢谢

**Comment by jimmysoa** [comment]
这个数据来自新浪财经，在国外如果能访问这个网站应该就没有问题。

**Comment by applebull** [comment]
访问新浪财经一直都没问题，但最近两周不管get_hist_data还是get_today_all都基本上没法成功下载数据了，不知道是不是需要修改网络延迟或重试次数方面的设置？

**Comment by jimmysoa** [comment]
跟这两个参数关系不大
