### ISSUE TITLE
ts.get_sina_dd 可能缺失记录

### ISSUE THREAD

**Issue by rdchujf** [waditu/tushare#182]
import tushare as ts
df = ts.get_sina_dd('600606', date='2016-09-02', vol=7000) 

可以返回4条记录

```
code    name    time    price   volume  preprice    type
```

0   600606  绿地控股    13:32:18    9.44    753500  9.46    卖盘
1   600606  绿地控股    13:00:08    9.49    773900  9.50    卖盘
2   600606  绿地控股    09:30:07    9.44    1008500 9.44    卖盘
3   600606  绿地控股    09:25:04    9.45    779100  0.00    买盘

但是下面的语句就没有数据返回
df = ts.get_sina_dd('600606', date='2016-09-02', vol=10000) 

按照第一次查询的结果， 应该是有一条记录返回的

**Comment by jimmysoa** [comment]
看了下原因，新浪财经网站上也没有，确实是个问题
