### ISSUE TITLE
get_sina_dd volume数据是不是缺少小数点

### ISSUE THREAD

**Issue by JackLee889** [waditu/tushare#183]
get_sina_dd 返回的volume成交手书是不是缺少小数点啊？

**Comment by jimmysoa** [comment]
没有小数点

**Comment by JackLee889** [comment]
![image](https://cloud.githubusercontent.com/assets/14900718/18340116/b8cd2fee-75d5-11e6-85d0-c96e32eac1de.png)
这个volume明显是成交的股数，但文档里写的是手数
![image](https://cloud.githubusercontent.com/assets/14900718/18340178/2266d856-75d6-11e6-9af1-0355a2c27754.png)

**Comment by jimmysoa** [comment]
最开始是手，后来数据源调整了，没有改文档。。。
