### ISSUE TITLE
大盘实时行情,能不能直接把实时指数加上,涨跌幅精度不够,推算出来的实时指数不够精确

### ISSUE THREAD

**Issue by fg607** [waditu/tushare#185]
```
  code    name  change        open    preclose       close        high  \
```

0   000001    上证指数   -0.55   3095.4269   3095.9543   3078.8548   3101.7922   

用 -0.55%和3095.9543计算出来的实时指数是3078.92..,和3078.85....不一致,因为-0.55精度不够导致的,

所以能否增加实时指数值,或者提高实时涨跌幅的精度,望采纳,谢谢!

**Comment by jimmysoa** [comment]
通过get_realtime_quotes

**Comment by fg607** [comment]
@jimmysoa 看到了,可以解决我的问题,非常感谢!

btw,如果通过get_index()能获取到大盘实时价格和涨跌值也许会更方便一些.
