### ISSUE TITLE
get_hist_data问题多多

### ISSUE THREAD

**Issue by 4ever911** [waditu/tushare#187]
我用get_hist_data 取30分钟K线， 发现数据丢失比较多， 用Sina是可以得到正确的数据的。

如下图：

![error](https://cloud.githubusercontent.com/assets/20335767/18511027/05c66652-7ab4-11e6-98dc-1e17515057ea.png)

9月2日开始就不对了， 中间居然漏掉几天的数据。 这个问题很多人提了， 建议考虑采用Sina的历史数据接口， 不过现在的情况是Sina只能取到最近的一个月左右的交易数据， 30分钟Bar， 200个数据都不到。

**Comment by Wilson-G** [comment]
嘛，可以根据tickdata来自己创建K线，这样可以获得更远日期的数据，可惜这基本上是本地工作，不然我倒是可以贡献代码

**Comment by jimmysoa** [comment]
@4ever911 新版的会替换现有的数据源，质量可以得到提升。
