### ISSUE TITLE
所有股票2016.8.29历史分笔数据缺失

### ISSUE THREAD

**Issue by Wilson-G** [waditu/tushare#188]
貌似是所有股票的8月29日的数据都缺少了，能看看怎么回事如何补全回来么，谢谢

**Comment by jimmysoa** [comment]
8月29号的什么数据？

**Comment by Wilson-G** [comment]
历史分笔数据，get_tick_data

**Comment by cloudseasail** [comment]
貌似有些股票2016-09-01和09-02 也是缺失的
ts.get_tick_data('300360',date='2016-09-01')

**Comment by jimmysoa** [comment]
部分缺失是由于数据源造成，个别缺失的可以私下找我，邮件发送，谢谢。
