### ISSUE TITLE
股票历史数据不准确

### ISSUE THREAD

**Issue by overyu** [waditu/tushare#190]
get_hist_data获取的股票历史数据不准确，比如600008九月21日的收盘价是4.41，但通过该接口是4.40。

**Comment by Wilson-G** [comment]
我猜这个跟k线合成的有关，不同软件上的数据可能偶尔有细小差异，但如果频率不高，差异微小就没啥关系吧

**Comment by jimmysoa** [comment]
这个数据源会在新版替换掉

**Comment by overyu** [comment]
计算是否是涨跌停的时候会出错，新版什么时候发布呢？

**Comment by jimmysoa** [comment]
计算是否涨跌停会出错？什么问题？
