### ISSUE TITLE
是不是可以多找两个 contributor 协助维护项目？

### ISSUE THREAD

**Issue by zezhou** [waditu/tushare#191]
随着用户越来越多，目前就 jimmy 一个人维护，感觉非常受累
是不是可以吸收几个 tushare 的用户作为 contributor，进行日常维护工作和 fix 一些小的bug
jimmy 可以进行code review 和专心规划新功能，减轻 jimmy 的负担
能用 tushare 的用户至少都有动手编程能力吧, 找符合要求的人应该不会很难

**Comment by Wilson-G** [comment]
支持

**Comment by jimmysoa** [comment]
有一个用户创建了一个tushare开发群：246726326，有兴趣的可以加入，提交自己的技术简历。

**Comment by liuguiyangnwpu** [comment]
支持！
