### ISSUE TITLE
最近服务器老是time out？

### ISSUE THREAD

**Issue by Wilson-G** [waditu/tushare#192]
就我一个人出现类似情况么，半天拿不到数据哎
另外k线获取只能获取最近299根，有没有办法获取更多呢？

**Comment by jimmysoa** [comment]
用get_h_data可以去全部

**Comment by happynoom** [comment]
get_h_data如何去大盘指数的全部数据呢

**Comment by jimmysoa** [comment]
ts.get_h_data('399106', index=True) #深圳综合指数
设置开始和结束日期

**Comment by Wilson-G** [comment]
非日线的k呢？我现在都是获取每天的分笔数据，然后自己合成，心累T T

**Comment by jimmysoa** [comment]
高频的还没有，可以线下联系我
