### ISSUE TITLE
The name of a column returned from get_stock_basics() is not consistent with the document

### ISSUE THREAD

**Issue by strongding** [waditu/tushare#194]
The name of one column is "esp" from the results of get_stock_basics, however it is "eps" in the document.

**Comment by jimmysoa** [comment]
是的，这里出了笔误，会修改文档。

**Comment by dreampond** [comment]
不应修改文档，而应修改代码，eps(earning per share)是正确的名称

**Comment by jimmysoa** [comment]
@dreampond 我知道，但是已经很多人在用，如果改了所有人的代码都需要重新调整。所以不改源代码

**Comment by dreampond** [comment]
@jimmysoa 虽然如此，以后的新人不是会继续错下去，越往后越难改正？ 能否保留老字段的同时，提供一个拼写正确的新字段，以便逐步能过渡到正确版本
