### ISSUE TITLE
数据存储 HDF5文件

### ISSUE THREAD

**Issue by arstum** [waditu/tushare#195]
env ：mac + pycharm 2016.2 + python3.5
调用方法：
import tushare as ts
df = ts.get_hist_data('000875')
df.to_hdf('/Users/xxx/Documents/abc/stock-test.h5'','000875')

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: '000875'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

按网站的示例操作，出错了。

**Comment by jimmysoa** [comment]
这个应该是版本的警告，检查一下文件，应该是保存好了。

**Comment by arstum** [comment]
没保存，数据库为空  @jimmysoa

**Comment by arstum** [comment]
实例没问题，是我不懂hdf5，Google了一下，现在可以用了
