### ISSUE TITLE
实时行情 缺失

### ISSUE THREAD

**Issue by arstum** [waditu/tushare#196]
2016年10月05日21:41:34
get_today_all
数据缺失
600230,_ST沧大,600556,ST慧球,600179,_ST黑化,600581,_ST八钢,600346,_ST橡塑,600520,_ST中发,600806,_ST昆机,600866,_ST星湖,600091,ST明科,600539,ST狮头,600817,_ST宏盛,600381,ST春天,600375,_ST星马,600234,_ST山水,600721,_ST百花,600608,ST沪科,600339,_ST天利,600546,_ST山煤,600247,ST成城,601918,_ST新集,600265,_ST景谷,600603,_ST兴业,300208,恒顺众昇,600432,_ST吉恩,600793,ST宜纸,600701,_ST工新,002752,昇兴股份
以上数据和停牌数据都缺失

**Comment by jimmysoa** [comment]
如果是停牌的就没有
