### ISSUE TITLE
Anaconda 安装不上tushare

### ISSUE THREAD

**Issue by luckmoon** [waditu/tushare#198]
![sp161013_120514](https://cloud.githubusercontent.com/assets/12612749/19336373/5dba37d6-913d-11e6-824c-418425af38d9.png)

**Comment by zezhou** [comment]
tushare 并没有提供 conda 安装方式吧

**Comment by jimmysoa** [comment]
应该有conda win64版本的安装

**Comment by Wilson-G** [comment]
pip install 不是很容易装么

**Comment by eyeglasses** [comment]
如果你安装了anaconda，应该有pip，使用pip install tushare就能安装成功。
