### ISSUE TITLE
历史分时数据，ts.get_tick_data('600848',date='日期')，每一天的数据量和时间节点不尽相同。

### ISSUE THREAD

**Issue by wuxianliang** [waditu/tushare#20]
请问：
历史分时数据，ts.get_tick_data('600848',date='日期')，每一天的数据量和时间节点不尽相同。有时相差上千行，是原始数据就是这样的，还是API的数据质量问题？

**Comment by jimmysoa** [comment]
你给我提供一下代码，我确认一下。可以确定的是，TuShare完全是直接获取数据源的，这个接口没有做任何数据处理。

**Comment by wuxianliang** [comment]
```
ts.get_tick_data('601106', date='2013-01-07')
```
1455行
```
ts.get_tick_data('601106', date='2013-01-08')
```
1593行
```
ts.get_tick_data('601106', date='2013-01-09')
```
1685行
```
ts.get_tick_data('601106', date='2015-01-09')
```
2786行

**Comment by wuxianliang** [comment]
如果API数据质量有问题，我们可以购买一套数据存起来，供TuShare用户下载。
例如：从这里 http://www.wstock.net/wstock/database.htm
我没试过，刚刚搜到。

**Comment by jimmysoa** [comment]
嗯，这是一个比较好的途径

**Comment by jimmysoa** [comment]
每一天的数量和时间点肯定是不一样的。
