### ISSUE TITLE
某些股票get_h_data()复权日左右数据计算错误

### ISSUE THREAD

**Issue by dreampond** [waditu/tushare#205]
> > > import tushare as tu
> > > x=tu.get_h_data('600000')
> > > [Getting data:]####>>>
> > > x.ix['2016-06-27':'2016-06-22']
> > >              open   high  close    low      volume       amount
> > > date
> > > 2016-06-27  15.19  15.29  15.21  15.08  19163499.0  292488228.0
> > > 2016-06-24  15.59  15.68  15.18  14.98  30575522.0  470756348.0
> > > 2016-06-23  15.79  15.79  15.61  15.60  12882295.0  203560849.0

然而实际2016--06-23的数据应该是 15.90 15.90. 15.72 15.71

**Comment by zgnecah** [comment]
顶。

如果执行 

`ts.get_h_data('300059',` start='2015-01-01', `end='2016-10-31')`

前复权得到的2015-01-01的数据为

> 2015-01-05  11.07  11.41  11.38  10.08

但在雪球、牛牛等交易软件的前复权数据中，该日数据统一为

> 2015-01-05  11.03  11.37  11.34  10.04 

在精度上面存在误差，但在最近的几个交易日（如2016-10-31这一天）却没有误差。估计是算前复权的时候精度没有处理好，希望楼主关注一下

**Comment by jimmysoa** [comment]
设定了end日期的数据是从end日期开始向前复权的，而行情软件和所有财经网站上的复权都是从最近一个交易日开始的，所以结果不一样。

**Comment by zengyee** [comment]
> 设定了end日期的数据是从end日期开始向前复权的
由于网络的限制， 如果分段采集数据的话，就会出问题， 建议，统一按 _从最近一个交易日开始_ 计算

**Comment by jimmysoa** [comment]
建议使用ts.bar
