### ISSUE TITLE
通联数据读取融资融券函数出错

### ISSUE THREAD

**Issue by iLampard** [waditu/tushare#206]
eq = ts.Equity()

eq.FstTotal(exchangeCD = 'XSHE, XSHG',beginDate = '20161019')

报错
<h1>Bad Message 400</h1><pre>reason: Unknown Version</pre>

请问这是怎么回事呢？ 我的参数应该是对的吧

**Comment by iLampard** [comment]
我知道错误了， 参数的位置不对应， 必须写成 eq.FstTotal(beginDate = '20161020', exchangeCD = 'XSHE')

**Comment by jimmysoa** [comment]
好
