### ISSUE TITLE
建议增加行业及个股历史市盈率统计

### ISSUE THREAD

**Issue by xungeer** [waditu/tushare#208]
看到中证公司网站ftp://115.29.204.48/syl/中提供了自2013年2月19日起的历史行业/个股估值，压缩包里的xls文件提供了如下信息：
![image](https://cloud.githubusercontent.com/assets/23014730/19627545/c3cb111c-997b-11e6-8252-02b2eaa80609.png)
是不是可以增加相应行业及个股市盈率？

**Comment by jimmysoa** [comment]
这个数据已经在采集，新版可以考虑
