### ISSUE TITLE
'float' object has no attribute 'replace'

### ISSUE THREAD

**Issue by jzlikewei** [waditu/tushare#210]
> df = ts.get_today_ticks('600584')
> [Getting data:]############################'float' object has no attribute 'replace'
> 'float' object has no attribute 'replace'
> 'float' object has no attribute 'replace'
> 获取失败，请检查网络和URL

具体出错的部分应该是stock/trading.py里面

**Comment by streamliner18** [comment]
Same here, doesn't work for some stocks

  ts.get_today_ticks('601800')
