### ISSUE TITLE
多线程下get_h_data报错，pointer being freed was not allocated

### ISSUE THREAD

**Issue by Earthson** [waditu/tushare#212]
看起来get_h_data不是线程安全的？

- OS X EI Capitan
- Python 3.5(Anaconda)

**Comment by Earthson** [comment]
看起来似乎是`sys.stdout.write`以及`sys.stdout.flush`可能不是线程安全的。

**Comment by jimmysoa** [comment]
删除试试

**Comment by Earthson** [comment]
跑久了之后还是报错。似乎并不是这里，或者说还有别的地方。

**Comment by carusyte** [comment]
我也有这个问题，除了标题中描述的报错外，还有其他奇奇怪怪的错误。
试过替换get_h_data中用到的urllib（据说不是线程安全），改用urllib3，还是有报错
注释掉sys.stdout.write这些语句也不行
由于对python不熟，始终没有找到问题原因
打算暂时改用multiprocessing试试
