### ISSUE TITLE
历史行情 get_hist_data 不能获取深圳A股2016年11月份的数据，只能获取到10月份前的

### ISSUE THREAD

**Issue by 5354gz** [waditu/tushare#213]
深圳的只能获取到10月28日，上海的正常

**Comment by jimmysoa** [comment]
了解，正在处理。

**Comment by BlackLee** [comment]
同样发现此问题，但不是代码的问题，而是ifeng数据源的问题。
例如 http://finance.ifeng.com/app/hq/stock/sz000534/ ，查看日K，可以发现2016-10-28后面一个数据就到2016-11-02了。

**Comment by jimmysoa** [comment]
@5354gz @BlackLee 可以使用新接口获取数据了： get_k_data

**Comment by 5354gz** [comment]
@jimmysoa 新接口get_k_data如何获取5日、十日的均价，均量，换手率等其他参数？

**Comment by jimmysoa** [comment]
暂时还没添加
