### ISSUE TITLE
分钟级别数据获取错误

### ISSUE THREAD

**Issue by alpha-qi** [waditu/tushare#214]
利用ts.get_hist_data('601766',ktype='30')获取30分钟级别数据，得到的数据截止到10月3号的分钟数据而非当天，换成其他分钟级别，如15分钟，5分钟也是这个问题，并且5分钟级别的index部分错误，开始一段全为00：00：00：。另外建议支持固定时间段分钟数据的支持。

**Comment by jimmysoa** [comment]
嗯嗯

**Comment by jimmysoa** [comment]
建议切换到get_k_data
