### ISSUE TITLE
历史分笔数据都是除权的，有什么办法可以转化成前复权数据

### ISSUE THREAD

**Issue by tingjianlau** [waditu/tushare#215]
通过ts.get_tick_data('600848',date='2014-01-09')接口下载到的分笔交易数据，我对其处理后生成了日线的数据。但由于除权数据存在缺口的问题，影响模型精度，请问有什么方法可以将其转换成前复权数据。如果不能的话，请问怎样处理数据，能够降低缺口数据对模型精度造成的影响。灰常感谢

**Comment by jimmysoa** [comment]
get_h_data

**Comment by tingjianlau** [comment]
@jimmysoa 如果想要用分笔交易数据生成的5分钟线数据，请问在这种情况下，还能有5分钟线的前复权数据吗？

**Comment by jimmysoa** [comment]
@tingjianlau 可以通过新的接口获取数据：get_k_data

**Comment by Wilson-G** [comment]
除权的话是在某日之后的除权，会造成极大的价格变化（>=20%）,所以用get_k_data算出来除权日和除权比例，自己生成的数据相应做变化就好了
