### ISSUE TITLE
to_csv报错

### ISSUE THREAD

**Issue by qbasicnju** [waditu/tushare#218]
使用PyCharm, 有的时候会无法保存为csv格式文件，
import tushare as ts
df=ts.get_h_data('000300',start='2006-01-01',end='2016-11-01')
 df.to_csv('C:/Users/Marcus/Documents/HS300.csv', columns=['open', 'high', 'low', 'close'])

  df.to_csv('C:/Users/Marcus/Documents/HS300.csv', columns=['open', 'high', 'low', 'close'])
AttributeError: 'NoneType' object has no attribute 'to_csv'

**Comment by panins** [comment]
是不是get_h_data函数已经弃用了的缘故？所以返回的是空数据。
[更新日志](http://mp.weixin.qq.com/s?__biz=MzAwOTgzMDk5Ng==&mid=2650833972&idx=1&sn=4de9f9ee81bc8bf85d1e0a4a8f79b0de&chksm=80adb30fb7da3a19817c72ff6f715ee91d6e342eb0402e860e171993bb0293bc4097e2dc4fe9&mpshare=1&scene=1&srcid=1106BPAdPiPCnj6m2Xyt5p2M#wechat_redirect)

**Comment by jimmysoa** [comment]
应该是没有返回值的原因

**Comment by qbasicnju** [comment]
@jimmysoa  是没有返回值，使用沪深300代码000300，没有返回值。 与get_h_data, get_hist_data没有关系
另外，还想请教下怎么让导出的数据时间正序排列？

**Comment by jimmysoa** [comment]
@qbasicnju 用法有问题，应该是这样：
df=ts.get_h_data('000300', index=True, start='2006-01-01',end='2016-11-01')
排序的话，可以调用排序函数

**Comment by qbasicnju** [comment]
@jimmysoa 可以用了，谢谢
