### ISSUE TITLE
可以本地数据库提供数据源吗

### ISSUE THREAD

**Issue by mtaiyi** [waditu/tushare#221]
1、由本地数据库提供模拟的股票交易数据，这个接口有吗？

**Comment by jimmysoa** [comment]
需要推送交易数据到本地数据库？

**Comment by mtaiyi** [comment]
不是，是本地的数据库做模拟的股票数据，不需要连上交易所。Tushare取本地数据库数据

**Comment by zfsamzfsam** [comment]
最好建立本地数据库(使用Mongodb等),由未除权数据序列和除权除息表构成(不需要均线等非基本数据,其他的非基本数据都由计算得到),这样就可以计算得到各个时间周期的复权数据序列了!!!
