### ISSUE TITLE
get_h_data返回的数据的volumn列没有复权

### ISSUE THREAD

**Issue by zhangzheng88** [waditu/tushare#225]
如下这只股票在2016-03-28这一天有拆股，可我通过这个接口获取到的前复权的volumn和不复权的volumn都是一样的，如下所示

`llhddata = ts.get_h_data('002280',drop_factor=False)`

![image](https://cloud.githubusercontent.com/assets/17842829/20256460/af31e76c-aa7e-11e6-93e6-eced7a4b0a3b.png)

`llhddata = ts.get_h_data('002280',autype='None',drop_factor=False)`

![image](https://cloud.githubusercontent.com/assets/17842829/20256532/2355530e-aa7f-11e6-8597-e994ffbd93ca.png)

**Comment by jimmysoa** [comment]
目前数据源没有实现这个功能，还需要重新规划一下数据。

**Comment by zhangzheng88** [comment]
重新规划一下数据是什么意思，是自己实现计算的逻辑吗？
