### ISSUE TITLE
get_k_data数据长度

### ISSUE THREAD

**Issue by fayeshine** [waditu/tushare#226]
get_k_data取历史数据长度最长一年，因此我无法一次取20年全部数据，tushare能否自动实现这个功能？将取20年的数据拆成一年一年的，然后合并，这样方便很多

**Comment by jimmysoa** [comment]
日线有全部数据，可以通过设置start和end日期来取历史

**Comment by fayeshine** [comment]
@jimmysoa 是可以通过start和end，但是长度最多一年，比如我设2007-2015，最后取到的只有2014-2015的

**Comment by jimmysoa** [comment]
@fayeshine 已经修复问题，请升级到最新版
