### ISSUE TITLE
安装报错, 缺少依赖包

### ISSUE THREAD

**Issue by chencoyote** [waditu/tushare#227]
![image](https://cloud.githubusercontent.com/assets/6293606/20290126/1b07816e-ab19-11e6-8681-1d01ae6998e5.png)

requirements.txt 里面只加了 lxml, 但是pandas也是依赖包, 没有加进去, 所以pip安装的时候不会安装

参考  #211

**Comment by jimmysoa** [comment]
建议安装Anaconda

**Comment by liuguiyangnwpu** [comment]
@chencoyote  可以参考这篇文章，其中有各个python软件包的安装链接。
[ANACONDA INSTALL](https://docs.continuum.io/anaconda/install.html)
[Installation of Python, Spyder, Numpy, Sympy, Scipy, Pytest, Matplotlib via Anaconda (2016)](http://www.southampton.ac.uk/~fangohr/blog/installation-of-python-spyder-numpy-sympy-scipy-pytest-matplotlib-via-anaconda.html)

**Comment by xwang71785** [comment]
我安装的时候还提示缺少 Bokeh 和 Astropy
