### ISSUE TITLE
请问能否自动增量插入数据到mysql里面

### ISSUE THREAD

**Issue by iloveyo123u1** [waditu/tushare#23]
非常感谢jim的付出

请问 能否实现：

傻瓜化的配置，比如 只需要配置好mysql帐号密码
然后 让脚本一直运行，自动去服务器拉取数据并存入数据库
第二天 当脚本再次运行，他会自动接着上次  继续拉取数据存入数据库

不会出现重复入库的情况

当然这个需求并不是特别广泛，  （：

谢谢

**Comment by jimmysoa** [comment]
基本上满足你说的这些需求，请看一下文档，如果有问题可以再私信给我。

**Comment by Tony-Wang** [comment]
很好，支持，我也需要这样的功能。
