### ISSUE TITLE
get_k_data获取不复权数据是错误的

### ISSUE THREAD

**Issue by rapidark** [waditu/tushare#230]
不复权是url是：app/kline/kline?_var=
复权用的url是：app/fqkline/get?_var=
指数只能用复权的url获取数据

**Comment by jimmysoa** [comment]
收到，我检查一下确定修复

**Comment by jimmysoa** [comment]
试了一下好像没问题啊：
In [2]: df = ts.get_k_data('300471', start='2015-10-01', end='2015-10-30', autype=None)

In [3]: df
Out[3]: 
          date    open   close    high     low   volume    code
77  2015-10-08   98.56   98.88   99.94   97.00  12182.0  300471
78  2015-10-09   98.89   99.96  100.75   98.00  10081.0  300471
79  2015-10-12  102.10  105.90  107.55  100.09  19942.0  300471
80  2015-10-13   51.88   51.57   52.50   50.56  29714.0  300471
81  2015-10-14   51.27   52.15   52.88   50.21  27304.0  300471
82  2015-10-15   52.05   53.60   53.67   51.10  29348.0  300471
83  2015-10-16   53.89   52.81   54.80   51.22  33211.0  300471
84  2015-10-19   52.33   51.30   52.85   50.40  22066.0  300471
85  2015-10-20   51.25   52.05   52.88   50.88  20669.0  300471
86  2015-10-21   52.20   47.60   53.99   47.35  33197.0  300471
87  2015-10-22   47.78   51.25   51.56   47.78  26557.0  300471
88  2015-10-23   52.00   53.71   54.29   52.00  37111.0  300471
89  2015-10-26   54.63   53.28   54.68   52.68  29924.0  300471
90  2015-10-27   53.28   53.37   53.80   50.05  25293.0  300471
91  2015-10-28   53.00   52.42   54.44   52.00  19699.0  300471
92  2015-10-29   53.10   52.06   53.37   51.60  15405.0  300471
93  2015-10-30   53.00   52.59   53.37   51.70  18103.0  300471


In [4]: df = ts.get_k_data('300471', start='2015-10-01', end='2015-10-30', autype='qfq')

In [5]: df
Out[5]: 
          date    open   close    high     low   volume    code
77  2015-10-08  48.664  48.822  49.345  47.894  12182.0  300471
78  2015-10-09  48.827  49.355  49.745  48.388  10081.0  300471
79  2015-10-12  50.412  52.288  53.103  49.419  19942.0  300471
80  2015-10-13  51.232  50.925  51.844  49.928  29714.0  300471
81  2015-10-14  50.629  51.498  52.219  49.582  27304.0  300471
82  2015-10-15  51.399  52.930  52.999  50.461  29348.0  300471
83  2015-10-16  53.216  52.150  54.115  50.580  33211.0  300471
84  2015-10-19  51.676  50.659  52.189  49.770  22066.0  300471
85  2015-10-20  50.609  51.399  52.219  50.244  20669.0  300471
86  2015-10-21  51.548  47.005  53.315  46.758  33197.0  300471
87  2015-10-22  47.183  50.609  50.916  47.183  26557.0  300471
88  2015-10-23  51.350  53.039  53.611  51.350  37111.0  300471
89  2015-10-26  53.947  52.614  53.997  52.022  29924.0  300471
90  2015-10-27  52.614  52.703  53.128  49.424  25293.0  300471
91  2015-10-28  52.338  51.765  53.760  51.350  19699.0  300471
92  2015-10-29  52.436  51.409  52.703  50.955  15405.0  300471

**Comment by jimmysoa** [comment]
2015-10-13是除权日

**Comment by rapidark** [comment]
你这个默认是前复权了，你取不复权的数据就错了

**Comment by jimmysoa** [comment]
In [2]: df = ts.get_k_data('300471', start='2015-10-01', end='2015-10-30', autype=None)

In [3]: df
Out[3]: 
          date    open   close    high     low   volume    code
77  2015-10-08   98.56   98.88   99.94   97.00  12182.0  300471
78  2015-10-09   98.89   99.96  100.75   98.00  10081.0  300471
79  2015-10-12  102.10  105.90  107.55  100.09  19942.0  300471
80  2015-10-13   51.88   51.57   52.50   50.56  29714.0  300471
81  2015-10-14   51.27   52.15   52.88   50.21  27304.0  300471
82  2015-10-15   52.05   53.60   53.67   51.10  29348.0  300471
83  2015-10-16   53.89   52.81   54.80   51.22  33211.0  300471
84  2015-10-19   52.33   51.30   52.85   50.40  22066.0  300471
85  2015-10-20   51.25   52.05   52.88   50.88  20669.0  300471
86  2015-10-21   52.20   47.60   53.99   47.35  33197.0  300471
87  2015-10-22   47.78   51.25   51.56   47.78  26557.0  300471
88  2015-10-23   52.00   53.71   54.29   52.00  37111.0  300471
89  2015-10-26   54.63   53.28   54.68   52.68  29924.0  300471
90  2015-10-27   53.28   53.37   53.80   50.05  25293.0  300471
91  2015-10-28   53.00   52.42   54.44   52.00  19699.0  300471
92  2015-10-29   53.10   52.06   53.37   51.60  15405.0  300471
93  2015-10-30   53.00   52.59   53.37   51.70  18103.0  300471

哪里是错的？看12号13号

**Comment by cgcsyao** [comment]
date open close high low volume code
77 2015-10-08 48.664 48.822 49.345 47.894 12182.0 300471
78 2015-10-09 48.827 49.355 49.745 48.388 10081.0 300471
这样价格小数点后有三位数的，是正常情况么？
