### ISSUE TITLE
建议get_k_data增加新参数，指定可以获取多少根K

### ISSUE THREAD

**Issue by Wilson-G** [waditu/tushare#234]
在我遍历取股票数据的时候，因为不想全部获取，所以一般会自己设置一下取今天到100天前的日线数据，但有时候发现拿回来的才20多个数据，简直晕菜

原来是股票在这期间会停牌，所以建议增加一个字段count，指定获取多少根K线。然后当count启用的时候，start 和 end不能共存

不过不知道get_k是不是只是处理了下格式然后直接从鹅厂服务器取数据，不知道这样改动大不

**Comment by jimmysoa** [comment]
你可以将start和end范围扩大，然后根据你的条件过滤就行。
