### ISSUE TITLE
安装时报这个故障 

### ISSUE THREAD

**Issue by longshaof** [waditu/tushare#237]
Collecting tushare
  Using cached tushare-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code -9 in /tmp/pip-build-jMpnj4/tushare/

lxml (3.5.0) 
pandas (0.17.1) 
这两个依赖包已经装好了

**Comment by zezhou** [comment]
出错信息太少了, 从给的信息里看不出问题在哪

**Comment by CaosBad** [comment]
我在使用本地测试环境和 leancloud 引擎的时候发现依赖安装出现了问题 ，有人在 [这里](https://forum.leancloud.cn/t/leancloud-importerror-no-module-named-lxml-html/12256/7)
给出了解决方法

**Comment by jimmysoa** [comment]
重新下载安装一下 ，我删了一下代码

**Comment by CaosBad** [comment]
好的，感谢及时回复~ 🙂
