### ISSUE TITLE
TraderAPI 的问题

### ISSUE THREAD

**Issue by 4ever911** [waditu/tushare#238]
1. 在Buy下单时，等待比较久才返回True或者False， 能否做成异步马上返回， 后面需要结果再去查询结果就好。通过position也能判断，组塞不大好操作。

2.我在取消委托的时候出错，但是实际上看委托列表，该笔委托已经被取消了。

请看我整个流程的截图
<img width="1139" alt="screen shot 2016-11-30 at 2 02 21 pm" src="https://cloud.githubusercontent.com/assets/20335767/20741554/04af2a40-b706-11e6-9c0a-a112959d2484.png">

**Comment by jimmysoa** [comment]
收到
