### ISSUE TITLE
get_stock_basics()的新股BUG

### ISSUE THREAD

**Issue by panins** [waditu/tushare#239]
在通过get_stock_basics()获得时发现，esp的值是0.000㈡，多了个符号。

name                   平治信息
industry                互联网
area                     浙江
pe                        0
outstanding               0
totals                    0
totalAssets         20065.5
liquidAssets          16996
fixedAssets          103.33
reserved            1189.55
reservedPerShare          0
esp                  0.000㈡
bvps                      0
pb                        0
timeToMarket              0
undp                8891.62
perundp                   0
rev                       0
profit                    0
gpr                   30.22
npr                    15.7
holders                   0
Name: 300571, dtype: object

**Comment by jimmysoa** [comment]
已修正，谢谢。

**Comment by jimmysoa** [comment]
已修正，谢谢。

**Comment by jimmysoa** [comment]
已修正，谢谢。
