### ISSUE TITLE
get_k_data获取5，15，30分钟数据出错

### ISSUE THREAD

**Issue by tingjianlau** [waditu/tushare#240]
`ts.get_k_data('300471', start='2015-10-01', end='2015-10-30', autype=None, ktype='5')`
**返回如下，无论参数start和end设置成何值，获取到的数据都是在11/25-12/02之间的数据**
date   open  close   high    low  volume    code
0    **2016-11-25** 10:15  48.29  48.39  48.49  48.22  1482.0  300471
1    2016-11-25 10:20  48.39  48.50  48.59  48.35   998.0  300471
2    2016-11-25 10:25  48.50  48.46  48.58  48.46  1273.0  300471
3    2016-11-25 10:30  48.46  48.40  48.55  48.38  1815.0  300471
4    2016-11-25 10:35  48.40  48.80  48.80  48.40  2400.0  300471
5    2016-11-25 10:40  48.80  48.90  48.94  48.80  1293.0  300471
6    2016-11-25 10:45  48.90  48.76  48.95  48.76   733.0  300471
7    2016-11-25 10:50  48.76  48.77  48.85  48.76   298.0  300471
8    2016-11-25 10:55  48.77  48.85  48.94  48.77   559.0  300471
9    2016-11-25 11:00  48.85  48.97  49.00  48.85   526.0  300471
10   2016-11-25 11:05  48.97  48.99  49.07  48.97   477.0  300471
11   2016-11-25 11:10  48.99  48.83  48.99  48.80   447.0  300471
12   2016-11-25 11:15  48.83  48.92  48.92  48.79   250.0  300471
13   2016-11-25 11:20  48.92  48.77  48.95  48.77   260.0  300471
14   2016-11-25 11:25  48.77  48.99  49.03  48.77   596.0  300471
15   2016-11-25 11:30  48.99  49.03  49.09  48.99   131.0  300471
16   2016-11-25 13:05  49.03  49.00  49.11  48.90   585.0  300471
17   2016-11-25 13:10  49.00  48.90  49.00  48.89   160.0  300471
18   2016-11-25 13:15  48.90  48.80  48.90  48.78   388.0  300471
19   2016-11-25 13:20  48.80  48.77  48.85  48.77   292.0  300471
20   2016-11-25 13:25  48.77  48.81  48.85  48.76   586.0  300471
21   2016-11-25 13:30  48.81  48.98  48.99  48.81   275.0  300471
22   2016-11-25 13:35  48.98  48.87  49.00  48.87   513.0  300471
23   2016-11-25 13:40  48.87  48.80  48.94  48.80   559.0  300471
24   2016-11-25 13:45  48.80  48.80  48.89  48.80   248.0  300471
25   2016-11-25 13:50  48.80  48.85  48.89  48.80   204.0  300471
26   2016-11-25 13:55  48.85  49.28  49.28  48.85   414.0  300471
27   2016-11-25 14:00  49.28  49.20  49.36  49.15   877.0  300471
28   2016-11-25 14:05  49.20  49.20  49.39  49.20   530.0  300471
29   2016-11-25 14:10  49.20  49.20  49.31  49.15   501.0  300471
..                ...    ...    ...    ...    ...     ...     ...
220  2016-12-01 14:05  48.37  48.32  48.37  48.31   132.0  300471
221  2016-12-01 14:10  48.32  48.30  48.38  48.30   452.0  300471
222  2016-12-01 14:15  48.30  48.29  48.30  48.24   261.0  300471
223  2016-12-01 14:20  48.29  48.25  48.29  48.21   217.0  300471
224  2016-12-01 14:25  48.25  48.32  48.32  48.25   162.0  300471
225  2016-12-01 14:30  48.32  48.34  48.40  48.32   176.0  300471
226  2016-12-01 14:35  48.34  48.34  48.40  48.34   185.0  300471
227  2016-12-01 14:40  48.34  48.36  48.40  48.34   304.0  300471
228  2016-12-01 14:45  48.36  48.29  48.36  48.24   321.0  300471
229  2016-12-01 14:50  48.29  48.31  48.35  48.23   576.0  300471
230  2016-12-01 14:55  48.31  48.45  48.47  48.31   569.0  300471
231  2016-12-01 15:00  48.45  48.48  48.48  48.40   403.0  300471
232  2016-12-02 09:35  48.49  48.45  48.50  48.31   707.0  300471
233  2016-12-02 09:40  48.45  48.45  48.48  48.36   221.0  300471
234  2016-12-02 09:45  48.45  48.55  48.55  48.40   864.0  300471
235  2016-12-02 09:50  48.55  48.40  48.55  48.40   580.0  300471
236  2016-12-02 09:55  48.40  48.25  48.40  48.10   862.0  300471
237  2016-12-02 10:00  48.25  48.25  48.26  48.18   656.0  300471
238  2016-12-02 10:05  48.25  48.30  48.33  48.20   374.0  300471
239  2016-12-02 10:10  48.30  48.10  48.30  48.05   712.0  300471
240  2016-12-02 10:15  48.08  48.06  48.15  48.05  1118.0  300471
241  2016-12-02 10:20  48.06  48.00  48.15  48.00   674.0  300471
242  2016-12-02 10:25  48.00  47.89  48.00  47.82  1355.0  300471
243  2016-12-02 10:30  47.89  47.85  47.97  47.80  1076.0  300471
244  2016-12-02 10:35  47.85  47.58  47.90  47.50  1544.0  300471
245  2016-12-02 10:40  47.58  47.60  47.61  47.53   812.0  300471
246  2016-12-02 10:45  47.60  47.55  47.65  47.55   792.0  300471
247  2016-12-02 10:50  47.55  47.61  47.70  47.55   517.0  300471
248  2016-12-02 10:55  47.61  47.52  47.69  47.50   690.0  300471
249  **2016-12-02** 10:59  47.52  47.56  47.56  47.52   274.0  300471

**Comment by jimmysoa** [comment]
分钟线数据只能取最近的历史数据，暂时不能提供更长历史的数据。
