### ISSUE TITLE
get_h_data 返回的date字段的类型问题

### ISSUE THREAD

**Issue by pcCoCo** [waditu/tushare#242]
df = ts.get_h_data(doc['code'],start=bgdate,end=tdate)
df['date'] = df.index 
kdata_col.insert(json.loads(df.to_json(orient='records').decode("GBK").encode("UTF-8")))

导入日期到mongodb之后是NumberLong类型
{"volume" : 41584240, "high" : 9.24, "amount" : 383425740, "low" : 9.2, "date" : NumberLong("1479254400000"), "close" : 9.23, "open" : 9.23 }

请问该如何转化为'YYYY-MM-DD'的形式

**Comment by jimmysoa** [comment]
可以先借助一下baidu的力量
