### ISSUE TITLE
期货的历史分笔数据

### ISSUE THREAD

**Issue by slashqiang** [waditu/tushare#243]
请问现在有api可以支持期货的历史分笔数据(tick)吗，或者短期一点的k线数据也可以（如1min, 5min等）？

tushare.get_tick_data()和新增加的tushare.get_k_data()似乎都只支持个股和指数。

**Comment by jimmysoa** [comment]
期货的分笔暂时还木有。。。。

**Comment by zhuo2015** [comment]
最近在搞上期的CTP，总结就是感谢waditu啊，让数据获取如此的简单，期望推出期货的接口

**Comment by jimmysoa** [comment]
哈哈，好的
