### ISSUE TITLE
鹅厂的创业板、中小板指成交量、成交额有问题

### ISSUE THREAD

**Issue by westsource** [waditu/tushare#246]
鹅厂的创业板、中小板指成交量、成交额有问题。例如，2016年12月6日，创业板的成交量为2874万手，成交额为682.7亿。但鹅厂的数值分别为973万手，212.1亿。

**Comment by westsource** [comment]
已经报给鹅厂，不知道啥时候能修复

**Comment by jimmysoa** [comment]
辛苦
