### ISSUE TITLE
forecast_data

### ISSUE THREAD

**Issue by Bruce-li-92** [waditu/tushare#248]
ts.forecast_data(2016,3)
[Getting data:]##Length mismatch: Expected axis has 9 elements, new values have 6 elements

cons.py 文件确实只定义了6个参数。

**Comment by RickyShiJs** [comment]
How to fix it？

**Comment by jimmysoa** [comment]
In [1]: import tushare as ts

In [2]: ts.forecast_data(2016, 3)
[Getting data:]###################################Out[2]: 
        code  name type report_date  pre_eps            range
0     603819  神力股份   预升  2016-10-31   0.3800     -5.51%~3.35%
1     603987   康德莱   预升  2016-10-31   0.4400      -1.5%~8.87%
2     300563  神宇股份   预升  2016-10-31   0.4200     5.45%~13.41%
3     603336  宏辉果蔬   预升  2016-10-31   0.4400      1.47%~3.75%
4     603633  徕木股份   预增  2016-10-31   0.0000          69%~78%
5     300566  激智科技   预升  2016-10-31   0.6600            12.54
6     002821   凯莱英   预增  2016-10-31   0.9100     39.9%~74.87%
7     002505  大康农业   预增  2016-10-28   0.0050  480.48%~519.18%
8     600959  江苏有线   预升  2016-10-27   0.2500             9.17



我估计是操作系统或者其他版本的原因。

**Comment by zhnlk** [comment]
mac v0.7.7复现
