### ISSUE TITLE
缺失半年数据

### ISSUE THREAD

**Issue by markovyao** [waditu/tushare#250]
前辈  采用df = ts.get_k_data('002008',start='2007-03-01', end='2016-08-14',autype='qfq')   获取数据出现问题  另外好几个其他股票都是在某年的6月30日后缺失半年数据
	date	open	close	high	low	volume	pct_change
707	2010-06-25	7.47	7.53	7.68	7.4	177076.04	0.005340453938584844
708	2010-06-28	7.52	7.15	7.57	7.08	202568.81	-0.050464807436918946
709	2010-06-29	7.16	6.74	7.19	6.64	300672.58	-0.05734265734265731
710	2010-06-30	6.69	6.79	6.85	6.57	114059.18	0.007418397626112627
711	2011-01-04	13.74	14.695	14.916	13.501	524498.0	1.1642120765832105
712	2011-01-05	14.573	14.175	14.867	14.144	430648.0	-0.03538618577747532
713	2011-01-06	14.089	14.022	14.726	13.973	358382.0	-0.0107936507936508
714	2011-01-07	13.777	14.101	14.34	13.593	231972.0	0.005634003708458124

**Comment by jimmysoa** [comment]
In [3]: ts.get_k_data('002008',start='2010-06-01', end='2011-02-14',autype='qfq')
Out[3]: 
           date    open   close    high     low     volume    code
98   2010-06-01   6.797   6.674   6.950   6.521  207036.89  002008
99   2010-06-02   6.613   6.901   6.901   6.539  126428.54  002008
100  2010-06-03   6.944   6.950   7.146   6.907  225978.38  002008
101  2010-06-04   6.919   7.366   7.372   6.919  322269.60  002008
102  2010-06-07   7.176   7.360   7.458   7.146  321978.63  002008
103  2010-06-08   7.348   7.433   7.568   7.305  231536.74  002008
104  2010-06-09   7.538   7.544   7.605   7.421  233817.55  002008
105  2010-06-10   7.525   7.593   7.740   7.495  242898.12  002008
106  2010-06-11   7.611   7.482   7.684   7.354  203222.60  002008
107  2010-06-17   7.531   7.305   7.593   7.293  195581.57  002008
108  2010-06-18   7.274   7.017   7.397   6.895  225307.90  002008
109  2010-06-21   6.980   7.219   7.237   6.937  137639.65  002008
110  2010-06-22   7.219   7.317   7.433   7.164  142992.92  002008
111  2010-06-23   7.286   7.531   7.593   7.231  189722.44  002008
112  2010-06-24   7.470   7.489   7.574   7.427  108645.16  002008
113  2010-06-25   7.470   7.525   7.684   7.397  177076.04  002008
114  2010-06-28   7.519   7.152   7.568   7.078  202568.81  002008
115  2010-06-29   7.164   6.735   7.195   6.644  300672.58  002008
116  2010-06-30   6.693   6.791   6.852   6.570  114059.18  002008
117  2010-07-01   6.742   6.846   6.937   6.735  108871.51  002008
118  2010-07-02   6.846   6.803   6.907   6.539  111425.47  002008
119  2010-07-05   6.791   6.864   6.913   6.674  116380.45  002008
120  2010-07-06   6.846   6.974   7.042   6.797  176096.47  002008
121  2010-07-07   6.974   6.974   7.029   6.846  112895.30  002008
122  2010-07-08   7.011   6.803   7.029   6.791  108579.89  002008
123  2010-07-09   6.870   7.195   7.250   6.803  222634.56  002008
124  2010-07-12   7.127   7.397   7.470   7.127  206533.00  002008
125  2010-07-13   7.342   7.476   7.531   7.244  221161.26  002008
126  2010-07-14   7.531   7.397   7.593   7.348  254988.89  002008
127  2010-07-15   7.348   7.164   7.513   7.152  187689.76  002008

**Comment by jimmysoa** [comment]
并没有问题啊
