### ISSUE TITLE
get_k_data 去数据有错误， 只能取到2016-06-30

### ISSUE THREAD

**Issue by iorilu** [waditu/tushare#252]
In [46]: dd = ts.get_k_data('000001',start='2015-01-01')

In [47]: dd
Out[47]: 
           date    open   close    high     low     volume    code
0    2015-01-05  10.846  10.867  11.043  10.582  2860436.0  000001
1    2015-01-06  10.751  10.704  11.118  10.548  2166421.0  000001
2    2015-01-07  10.555  10.500  10.738  10.378  1700120.0  000001
3    2015-01-08  10.514  10.148  10.561  10.107  1407714.0  000001
4    2015-01-09  10.107  10.229  10.765   9.978  2508500.0  000001
5    2015-01-12  10.087  10.019  10.209   9.836  1553290.0  000001
6    2015-01-13   9.937   9.958  10.107   9.910   816874.0  000001
7    2015-01-14  10.025  10.046  10.310   9.971  1263029.0  000001
8    2015-01-15  10.073  10.412  10.412   9.978  1242170.0  000001
9    2015-01-16  10.446  10.426  10.595  10.297  1555846.0  000001
10   2015-01-19   9.503   9.381   9.883   9.381  2137123.0  000001
11   2015-01-20   9.381   9.381   9.537   9.198  1491018.0  000001
12   2015-01-21   9.415   9.781   9.903   9.327  1940530.0  000001
13   2015-01-22   9.727   9.700   9.849   9.605  1255016.0  000001
14   2015-01-23   9.741   9.768   9.924   9.700  1459181.0  000001
15   2015-01-26   9.741   9.727   9.795   9.605  1057605.0  000001
16   2015-01-27   9.734   9.490   9.747   9.381  1339494.0  000001
17   2015-01-28   9.408   9.537   9.700   9.361  1240877.0  000001
18   2015-01-29   9.374   9.429   9.503   9.327  1016753.0  000001
19   2015-01-30   9.449   9.449   9.578   9.334   930116.0  000001
20   2015-02-02   9.225   9.245   9.361   9.191   860932.0  000001
21   2015-02-03   9.347   9.462   9.490   9.239   883349.0  000001
22   2015-02-04   9.496   9.300   9.524   9.293   807623.0  000001
23   2015-02-05   9.700   9.354   9.788   9.334  1913729.0  000001
24   2015-02-06   9.286   9.164   9.462   9.089  1030408.0  000001
25   2015-02-09   9.157   9.171   9.279   8.967   946586.0  000001
26   2015-02-10   9.150   9.340   9.374   9.103   724875.0  000001
27   2015-02-11   9.347   9.313   9.395   9.279   554349.0  000001
28   2015-02-12   9.327   9.401   9.429   9.239   608715.0  000001
29   2015-02-13   9.449   9.462   9.618   9.388   887743.0  000001
..          ...     ...     ...     ...     ...        ...     ...
334  2016-05-18   8.447   8.455   8.472   8.349   534150.0  000001
335  2016-05-19   8.431   8.414   8.472   8.414   170777.0  000001
336  2016-05-20   8.406   8.455   8.480   8.365   206703.0  000001
337  2016-05-23   8.480   8.439   8.488   8.414   323646.0  000001
338  2016-05-24   8.431   8.381   8.439   8.365   259294.0  000001
339  2016-05-25   8.414   8.398   8.439   8.365   204235.0  000001
340  2016-05-26   8.390   8.390   8.431   8.349   261396.0  000001
341  2016-05-27   8.390   8.431   8.447   8.365   222818.0  000001
342  2016-05-30   8.414   8.439   8.439   8.373   380946.0  000001
343  2016-05-31   8.422   8.661   8.677   8.422   946467.0  000001
344  2016-06-01   8.628   8.603   8.661   8.570   556750.0  000001
345  2016-06-02   8.595   8.587   8.603   8.554   293036.0  000001
346  2016-06-03   8.595   8.620   8.636   8.546   423389.0  000001
347  2016-06-06   8.628   8.628   8.644   8.578   338332.0  000001
348  2016-06-07   8.636   8.636   8.644   8.603   229282.0  000001
349  2016-06-08   8.652   8.620   8.652   8.587   268188.0  000001
350  2016-06-13   8.587   8.480   8.595   8.480   344816.0  000001
351  2016-06-14   8.488   8.537   8.546   8.472   273637.0  000001
352  2016-06-15   8.480   8.570   8.603   8.472   378172.0  000001
353  2016-06-16   8.570   8.570   8.600   8.530   386670.0  000001
354  2016-06-17   8.570   8.580   8.610   8.540   315173.0  000001
355  2016-06-20   8.590   8.600   8.600   8.560   270731.0  000001
356  2016-06-21   8.610   8.610   8.650   8.580   380749.0  000001
357  2016-06-22   8.600   8.730   8.730   8.580   478002.0  000001
358  2016-06-23   8.670   8.660   8.700   8.630   335614.0  000001
359  2016-06-24   8.640   8.570   8.700   8.520   427664.0  000001
360  2016-06-27   8.570   8.610   8.640   8.540   325214.0  000001
361  2016-06-28   8.580   8.630   8.640   8.560   336519.0  000001
362  2016-06-29   8.630   8.690   8.690   8.620   369611.0  000001
363  2016-06-30   8.690   8.700   8.740   8.660   362204.0  000001

而且有的股票数据又不一样， 比如000002， 只能到2015-12-18ts
226  2015-12-08  17.180  17.056  17.344  16.701  1529886.0  000002
227  2015-12-09  17.228  18.764  18.764  17.094  3598519.0  000002
228  2015-12-10  18.803  18.755  20.501  18.255  3067374.0  000002
229  2015-12-11  18.371  19.100  19.522  18.025  2035008.0  000002
230  2015-12-14  18.812  19.273  19.657  18.246  1392194.0  000002
231  2015-12-15  18.812  20.233  20.597  18.812  1673876.0  000002
232  2015-12-16  19.801  19.378  20.146  19.206  1185363.0  000002
233  2015-12-17  19.561  21.317  21.317  19.532  2583392.0  000002
234  2015-12-18  21.500  23.448  23.448  20.789  2238984.0  000002

**Comment by ellot** [comment]
/util/dateu.py的114行有错，2改为1，你可以自己改一下。
或者不要加start这个参数了。

**Comment by jimmysoa** [comment]
tushare升级到最新版

**Comment by ellot** [comment]
我刚试了试0.6.3，还是有这个错误的。

**Comment by jimmysoa** [comment]
我再看看
