### ISSUE TITLE
get_k_data 返回大量重复数据

### ISSUE THREAD

**Issue by iorilu** [waditu/tushare#254]
对'date'字段做索引, 然后使用df.index.get_duplicates(), 可以看重复数据

**Comment by iorilu** [comment]
In [60]: df = ts.get_k_data('000001', start='2015-01-01')

In [61]: df.date.is_unique
Out[61]: False

In [65]: len(df.date.unique())
Out[65]: 478

In [66]: len(df.date)
Out[66]: 598

**Comment by iorilu** [comment]
#252 

vvv/util/dateu.py的114行有错，2改为1/util/dateu.py的114行有错，2改为1

按这个改了, 又有了重复数据,

**Comment by ellot** [comment]
如果指定start或者end，作者默认一年半请求一次（1月1日到次年6月30日），每次最多380行数据，不知道为什么这样设定，所以要作者大的修改。
简单的办法就是不要指定star这个参数。

**Comment by huan-zhou** [comment]
这个问题还有一个现象, 当请求很多数据时, 会看到如下情况:
......
2364,2013-06-28,5.295,5.557,5.652,5.184,926643.0,000001
2365,2014-01-02,6.755,6.817,6.856,6.716,489910.0,000001
......
2727,2015-06-30,11.115,11.936,11.936,10.984,2548103.0,000001
2728,2016-01-04,9.851,9.276,9.875,9.219,563497.0,000001

每隔一段, 数据就少了整整半年!

**Comment by huan-zhou** [comment]
@jimmysoa 
```
 enddate = str(year+1) + '-12-30'
```
12月31号呢?

**Comment by jimmysoa** [comment]
不好意思，手快了。已经修复
