### ISSUE TITLE
 ts.guba_sina无法返回content内容，get_notices()返回不了数据

### ISSUE THREAD

**Issue by sucof** [waditu/tushare#255]
如题，get_notices()返回不了个股信息，guba_sina无法返回具体内容数据

**Comment by ryh95** [comment]
有些是日期里面没有数据
比如
2016 12 18 000002 没有新闻所以get_notices()没有返回数据

**Comment by sucof** [comment]
好像是lxml库有问题，例如http://www.baidu.com就没问题，而新浪股吧的url就会有问题，例如http://guba.sina.com.cn/?s=thread&bid=9279&tid=1377705&pid=1&dpc=1，会发生
Error reading file 'http://guba.sina.com.cn/?s=thread&bid=9279&tid=1377705&pid=1&dpc=1': failed to load HTTP resource错误，下面是写的测试程序
import lxml.html
from lxml import etree
def _guba_content(url):
    try:
        html = lxml.html.parse(url)
        # res = html.xpath('//div[@class=\"ilt_p\"]/p')
        # if ct.PY3:
        #     sarr = [etree.tostring(node).decode('utf-8') for node in res]
        # else:
        #     sarr = [etree.tostring(node) for node in res]
        # sarr = ''.join(sarr).replace('&#12288;', '')#.replace('\n\n', '\n').
        # html_content = lxml.html.fromstring(sarr)
        # content = html_content.text_content()
        # ptime = html.xpath('//div[@class=\"fl_left iltp_time\"]/span/text()')[0]
        # rcounts = html.xpath('//div[@class=\"fl_right iltp_span\"]/span[2]/text()')[0]
        # reg = re.compile(r'\((.*?)\)')
        # rcounts = reg.findall(rcounts)[0]
        # return [content, ptime, rcounts]
        return html
    except Exception as e:
        print e
        return ['', '', '0']

# import urllib2
# from lxml import etree
#
# url = "http://guba.sina.com.cn/?s=thread&bid=9279&tid=1377705&pid=1&dpc=1"
#
# html = urllib2.urlopen(url)
#
# root = etree.parse(html)
# print html
# print root
print _guba_content("http://guba.sina.com.cn/?s=thread&bid=9279&tid=1377705&pid=1&dpc=1")
#print _guba_content("http://www.baidu.com")    成功
