### ISSUE TITLE
get_notices() IndexError: list index out of range

### ISSUE THREAD

**Issue by ryh95** [waditu/tushare#256]
如图，这里没有try catch 所以有的时候没有新闻就会出错
![image](https://cloud.githubusercontent.com/assets/8979086/21311297/6c386de6-c621-11e6-9368-d6670c97873d.png)
这里没有th/a/，所以就出错了
![image](https://cloud.githubusercontent.com/assets/8979086/21311329/8e5fb154-c621-11e6-8c67-e1ddfcba499f.png)
希望能尽快修复

**Comment by jimmysoa** [comment]
收到
