### ISSUE TITLE
new_stocks 报错

### ISSUE THREAD

**Issue by sinall** [waditu/tushare#257]
[Getting data:]#No tables found matching pattern '.+'
#No tables found matching pattern '.+'
#No tables found matching pattern '.+'

**Comment by jimmysoa** [comment]
python是什么版本？


In [3]: ts.new_stocks()
[Getting data:]############Out[3]: 
       code  name    ipo_date  issue_date  amount  markets  price     pe  \
0    002839  张家港行  2017-01-12         NaN   18076     5416   4.37  14.64   
1    603037  凯众股份  2017-01-10         NaN    2000     2000  16.01  22.98   
2    300593   新雷能  2017-01-04         NaN    2889     1156   0.00   0.00   
3    603690  至纯科技  2017-01-03         NaN    5200     2080   0.00   0.00   
4    002824  和胜股份  2017-01-03         NaN    3000     1200   0.00   0.00   
5    603639   海利尔  2016-12-30         NaN    3000     1200   0.00   0.00   
6    300580   贝斯特  2016-12-30         NaN    5000     1500   9.59  22.98   
7    603628  清源股份  2016-12-29         NaN    6845     2738   0.00   0.00

**Comment by sinall** [comment]
环境是Mac。

$ python3
Python 3.5.2 (default, Nov 14 2016, 17:06:46) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tushare as ts
>>> ts.new_stocks()
[Getting data:]#No tables found matching pattern '.+'
#No tables found matching pattern '.+'
#No tables found matching pattern '.+'

**Comment by sinall** [comment]
$ python2
Python 2.7.12 (default, Nov 14 2016, 16:45:06) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tushare as ts
>>> ts.new_stocks()
[Getting data:]#No tables found matching pattern '.+'
#No tables found matching pattern '.+'
#No tables found matching pattern '.+'

**Comment by streamliner18** [comment]
linux上也出这个问题了……Python 3.5.1, Pandas 0.19.2, Tushare 0.7.7
