### ISSUE TITLE
INDEX_COLS少了"open"列

### ISSUE THREAD

**Issue by hecor** [waditu/tushare#26]
INDEX_COLS少了"open"列，另外，不建议get_index函数里修改amount：
df['amount'] = df['amount'] / 100000000，保留原数据比较好。

**Comment by jimmysoa** [comment]
好的，感谢 很好的建议。

**Comment by hecor** [comment]
非常好的project，谢谢你的贡献～

**Comment by jimmysoa** [comment]
@hecor open列已经添加并提交到github, 关于总成交金额我想了下还是以亿为单位吧,否则数据长度太大了.

**Comment by hecor** [comment]
OK， thanks～
