### ISSUE TITLE
关于龙虎榜的数据

### ISSUE THREAD

**Issue by whiletrue2009** [waditu/tushare#266]
提个建议
http://stock.finance.qq.com/cgi-bin/sstock/q_lhb_xx_js?c=000559&b=20140228&l=070001

这种怎么没有呢？

觉得还是挺有用处的

**Comment by jimmysoa** [comment]
我查查有没有加上，如果没有的话可以加上，谢谢。

**Comment by kedaio** [comment]
从文档以及billboard.py的源码来看这个功能还没实现. 我在找东财的api借口,希望可以实现这个功能~
