### ISSUE TITLE
get_stock_basics获取的股票列表转成json后没有code字段

### ISSUE THREAD

**Issue by hgs1** [waditu/tushare#267]
获取数据，存入mongodb，代码如下。
```python
import json
from pymongo import MongoClient
import tushare as ts

db = MongoClient('my_mongodb_url')
collection = db.my_database
df = ts.get_stock_basics()
collection.insert(json.loads(df.to_json(orient='records')))
```
数据成功获取并存入了数据库，如下图
![image](https://cloud.githubusercontent.com/assets/4284926/21590166/311aa026-d134-11e6-8d5c-2581777b3457.png)

但问题是并没有code（股票代码）字段，请问是什么原因。

更新：
看了下这个方法源码https://github.com/waditu/tushare/blob/master/tushare/stock/fundamental.py
```python
def get_stock_basics():
    request = Request(ct.ALL_STOCK_BASICS_FILE)
    text = urlopen(request, timeout=10).read()
    text = text.decode('GBK')
    text = text.replace('--', '')
    df = pd.read_csv(StringIO(text), dtype={'code':'object'})
    df = df.set_index('code')  # why do this?
    return df
```
将code设为了索引，所以数据列中就不在存在code列了？
可以不以像其他接口一样，用递增自然数做索引，将code恢复成数据列？

**Comment by jimmysoa** [comment]
获得df后，可以先处理一下后再入库

**Comment by Mount565** [comment]
这个方法返回的dataframe有问题，我也遇到类似问题，报KeyError: 'code'
