### ISSUE TITLE
get_k_data 的end设定当天无效

### ISSUE THREAD

**Issue by jsonseng** [waditu/tushare#275]
通过新接口获取历史数据的时候，如果设定了start，end。end如果是当前2017-01-24，但是返回的数据最后一天是2017-01-23，会缺少一天，如果只是设定了start，没有end，也会存在这个问题

**Comment by jimmysoa** [comment]
升级到最新版再试试看

**Comment by windskysolo** [comment]
最新版本也有上述问题，当周期指定为天时，指定起始日期，不设定end，返回的没有最后一天的数据，我用浏览器试了下URL，确实没有最后一天 的数据，但是15分钟数据可以正常获取

**Comment by 7forz** [comment]
今天也发现了这个问题，如果不指定start和end就能获取到今天的数据；指定了start就获取不到今天的

**Comment by 9590** [comment]
这个问题最后怎么解决呢？

**Comment by 7forz** [comment]
我把stock\trading.py中的 enddate = str(year+1) + '-12-31' 改成 enddate = '' 好像就没问题了
