### ISSUE TITLE
get_area_classified()    获取地域分类数据 报warning

### ISSUE THREAD

**Issue by wmsby** [waditu/tushare#278]
get_area_classified()    获取地域分类数据
C:\ProgramData\Anaconda3\lib\site-packages\tushare\stock\classifying.py:93: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort('area').reset_index(drop=True)

版本：
ts.__version__： 0.6.8
pd.__version__：0.19.2

这个改一下应该比较容易。

**Comment by jimmysoa** [comment]
是的，新版的pandas换了用法
