### ISSUE TITLE
30分钟线只有最近2个月的吗？

### ISSUE THREAD

**Issue by xgdgsc** [waditu/tushare#28]
ind_data = ts.get_hist_data('sh', ktype='30', start='2012-06-25', end='2015-06-24')
最早的2015-04-22 13:30:00

**Comment by jimmysoa** [comment]
对，目前数据源只提供这么多。可以通过get_tick_data之后用pandas来计算30分钟k线

**Comment by seasonhuang** [comment]
请问30分钟k线是怎么计算的？边界值怎么取？
