### ISSUE TITLE
上证指数历史分笔部支持吗？

### ISSUE THREAD

**Issue by maxmingbo** [waditu/tushare#283]
显示当天没有数据
`ts.get_tick_data('sh',date='2017-02-17')`

`ts.get_hist_data('sh',ktype='5')`
 也只能获取最近几天的数据，

我想要最近3年的历史分笔数据，5分钟均值，或者15,30分钟均值的历史数据该怎么办呀？

**Comment by jimmysoa** [comment]
线上没有，可线下联系
