### ISSUE TITLE
get_k_data 获取60分钟数据有问题啊

### ISSUE THREAD

**Issue by xingfukun** [waditu/tushare#285]
df = tu.get_k_data('002043',start='2017-02-01',end='2017-02-10',ktype='60')
                 date   open  close   high    low  volume    code
0    2016-11-24 10:30  13.40  13.39  13.47  13.36   30543  002043
1    2016-11-24 11:30  13.39  13.37  13.42  13.36   18685  002043
2    2016-11-24 14:00  13.37  13.36  13.41  13.35   23144  002043
3    2016-11-24 15:00  13.36  13.29  13.40  13.27   45936  002043
4    2016-11-25 10:30  13.35  13.02  13.35  12.82   68408  002043
5    2016-11-25 11:30  13.02  13.16  13.17  13.02   20207  002043
6    2016-11-25 14:00  13.16  13.13  13.17  13.06   13301  002043
7    2016-11-25 15:00  13.13  13.15  13.22  13.12   26956  002043
8    2016-11-28 10:30  13.16  13.29  13.35  13.16   29052  002043
9    2016-11-28 11:30  13.29  13.28  13.30  13.25   10977  002043
10   2016-11-28 14:00  13.28  13.22  13.29  13.21   16095  002043
11   2016-11-28 15:00  13.22  13.17  13.23  13.10   39279  002043
12   2016-11-29 10:30  13.18  13.11  13.18  13.08   28306  002043
13   2016-11-29 11:30  13.11  13.06  13.12  13.02   28160  002043
14   2016-11-29 14:00  13.06  13.03  13.07  13.00   24720  002043
15   2016-11-29 15:00  13.03  12.94  13.03  12.93   41117  002043
16   2016-11-30 10:30  12.91  12.77  12.91  12.61   57500  002043
17   2016-11-30 11:30  12.77  12.71  12.79  12.70   19796  002043
18   2016-11-30 14:00  12.71  12.74  12.79  12.69   14504  002043
19   2016-11-30 15:00  12.74  12.73  12.78  12.71   24554  002043
20   2016-12-01 10:30  12.65  12.74  12.84  12.65   18183  002043
21   2016-12-01 11:30  12.74  12.72  12.74  12.72   10437  002043
22   2016-12-01 14:00  12.72  12.71  12.76  12.70   15410  002043
23   2016-12-01 15:00  12.71  12.69  12.74  12.67   28779  002043
24   2016-12-02 10:30  12.69  12.81  12.97  12.69   46522  002043
25   2016-12-02 11:30  12.81  12.72  12.82  12.71   19212  002043
26   2016-12-02 14:00  12.72  12.68  12.72  12.66   26513  002043
27   2016-12-02 15:00  12.68  12.68  12.69  12.65   20405  002043
28   2016-12-05 10:30  12.70  12.75  12.87  12.50   31145  002043
29   2016-12-05 11:30  12.75  12.68  12.76  12.66    9990  002043
..                ...    ...    ...    ...    ...     ...     ...
204  2017-02-13 10:30  12.01  11.86  12.09  11.81   34271  002043
205  2017-02-13 11:30  11.86  11.87  11.98  11.84   15019  002043
206  2017-02-13 14:00  11.87  11.91  11.95  11.87   15454  002043
207  2017-02-13 15:00  11.90  12.09  12.11  11.89   43155  002043
208  2017-02-14 10:30  12.05  12.07  12.30  11.93   32591  002043
209  2017-02-14 11:30  12.07  12.12  12.13  12.00   16477  002043
210  2017-02-14 14:00  12.12  12.02  12.13  12.00    9460  002043
211  2017-02-14 15:00  12.02  12.03  12.08  12.00   16261  002043
212  2017-02-15 10:30  12.09  11.94  12.09  11.93   21637  002043
213  2017-02-15 11:30  11.94  11.97  11.98  11.90   11949  002043
214  2017-02-15 14:00  11.97  11.88  11.98  11.86   23723  002043
215  2017-02-15 15:00  11.88  11.77  11.88  11.61   54391  002043
216  2017-02-16 10:30  11.87  11.99  12.07  11.77   47820  002043
217  2017-02-16 11:30  11.99  12.12  12.15  11.96   38121  002043
218  2017-02-16 14:00  12.12  11.99  12.13  11.97   14652  002043
219  2017-02-16 15:00  11.99  11.97  12.00  11.92   17143  002043
220  2017-02-17 10:30  12.09  11.87  12.13  11.80   37123  002043
221  2017-02-17 11:30  11.87  11.85  11.88  11.80   15024  002043
222  2017-02-17 14:00  11.85  11.83  11.85  11.71   17202  002043
223  2017-02-17 15:00  11.83  11.79  11.90  11.78   15552  002043
224  2017-02-20 10:30  11.79  11.89  11.89  11.73   16503  002043
225  2017-02-20 11:30  11.88  11.97  12.00  11.84   19776  002043
226  2017-02-20 14:00  11.97  12.46  12.51  11.97  180270  002043
227  2017-02-20 15:00  12.46  12.40  12.46  12.36   74900  002043
228  2017-02-21 10:30  12.45  13.26  13.35  12.34  253213  002043
229  2017-02-21 11:30  13.26  13.01  13.26  12.97   60992  002043
230  2017-02-21 14:00  13.01  12.90  13.04  12.75   47128  002043
231  2017-02-21 15:00  12.90  12.80  12.98  12.79   43628  002043
232  2017-02-22 10:30  12.63  12.81  12.95  12.63   83381  002043
233  2017-02-22 11:30  12.81  12.75  12.95  12.75   42356  002043

[234 rows x 7 columns]

**Comment by jimmysoa** [comment]
分钟数据只有最近两周的，设置日期没有用
