### ISSUE TITLE
get_k_data 在0.6.8本中5分钟k线数据只能获取最近一周的是为什么

### ISSUE THREAD

**Issue by phoenixzxj** [waditu/tushare#288]
get_k_data 在0.6.8本中5分钟k线数据只能获取最近一周的是为什么

**Comment by suqi** [comment]
对, 看了下, get_hist_data也是这样的问题, 拿一周以前的数据直接返回空了

![image](https://cloud.githubusercontent.com/assets/1326887/23287606/6cd2eb82-fa79-11e6-9901-888a8c746924.png)

**Comment by suqi** [comment]
@phoenixzxj  请问是不是历史旧版本里是可以拿到全部的?

**Comment by jimmysoa** [comment]
分钟线只有近期的，没有全部历史
