### ISSUE TITLE
ts.new_stocks() 返回错误

### ISSUE THREAD

**Issue by fuermosi777** [waditu/tushare#29]
错误信息为
`#No tables found matching pattern '.+'`

**Comment by jimmysoa** [comment]
@fuermosi777  升级一下TuShare的版本看？我刚测了没问题的

**Comment by fuermosi777** [comment]
谢谢回复！我刚升级了一下，可是还是失败，贴上截图供您参考。
![screen shot 2015-06-26 at 12 08 41 pm](https://cloud.githubusercontent.com/assets/7303373/8381817/2272cd26-1bfc-11e5-8d66-eb9e0eed22c5.png)

**Comment by jimmysoa** [comment]
加我QQ：52799046，有时间了我看看。

**Comment by fuermosi777** [comment]
提交了一个pull request，有时间您可以看一看 https://github.com/waditu/tushare/pull/33
