### ISSUE TITLE
ts.guba_sina() 股吧数据获取报错

### ISSUE THREAD

**Issue by zjuguxi** [waditu/tushare#295]
版本：tushare 0.6.9，python 3.6
调用guba_sina()会报错，情况如下:

In [2]: ts.guba_sina()
list index out of range

**Comment by jimmysoa** [comment]
In [1]: import tushare as ts

In [2]: ts.guba_sina()
Out[2]: 
                    title         ptime  rcounts
0              题材股的春天就要来了       今天15:34  53285.0
1         沪弱深强   围绕两会挖掘机会       今天15:14  25972.0
2   一白酒股放着空间还很大 ST板块可以淘淘金         24分钟前  12126.0
3              注意冲高后的振荡出现       今天15:28  16064.0
4             千亿资金欲抢购这一板块       今天15:39  65111.0
5       十三五旅游公共服务规划发布 概念股       今天15:09  26007.0
6       我国军费首超万亿 纯正军工股受青睐       今天15:38  25020.0
7           资金监测及涨跌异动点评参考  03月05日 22:29  49574.0
8   医药板块或迎中长期机会 布局主题基金正当时       今天15:31  27925.0
9            明天还会有一个回调的动作                    0.0
10       压力的形成就是筹码高位套牢的区域                    0.0
11        想借着妖股赚钱 小心被妖怪带走                    0.0
12              必须紧抓大方向思维                    0.0
13          两会期间那类股可能更受关注                    0.0
14        逢会必跌的魔咒未必会在这届实现                    0.0
15             目前盘面分化特别严重                    0.0
16           沪指60分钟仍有下行意愿                    0.0

**Comment by ichao1214** [comment]
我第一次出现了同样的错误，后来重新卸载安装tushare出现了以下情况：
`ts.guba_sina()
Empty DataFrame
Columns: [title, ptime, rcounts]
Index: []`
