### ISSUE TITLE
get_industry_classified()内容未更新

### ISSUE THREAD

**Issue by phoenixzxj** [waditu/tushare#296]
![image](https://cloud.githubusercontent.com/assets/19839217/23691987/ecd76524-0406-11e7-985a-3ad5c2462d51.png)
![image](https://cloud.githubusercontent.com/assets/19839217/23692002/09429efe-0407-11e7-9847-03b88bd35879.png)
get_stock_basics中行业与get_industry_classified中内容不符。第二个感觉更新不及时。

**Comment by Rockyzsu** [comment]
这个是读取一个csv文件的。 这个文件的更新频率比较慢。

**Comment by jimmysoa** [comment]
tushare升级到最新版就可以了，数据源地址已经更换。
