### ISSUE TITLE
获取基本面数据的几个接口返回的数据有重复和遗漏

### ISSUE THREAD

**Issue by bluescorpio1107** [waditu/tushare#297]
version: 0.6.9, python3.5
使用get_report_data(2016,1)返回的数据有不少重复数据，如下：
        name   eps  eps_yoy   bvps   roe  epcf  net_profits  profits_yoy  \
code                                                                       
000001  平安银行  0.43     4.88  11.71  3.70  4.14    608600.00         8.12   
000002   万科A  0.08    27.12   9.12  0.83 -0.97     83323.29        28.14   
000004  国农科技 -0.03    28.96    NaN -2.98   NaN      -239.25        29.07   
000006  深振业A  0.04   -75.77    NaN  1.11   NaN      4880.83       -75.79   
000008  神州高铁  0.00   -96.21    NaN  0.24   NaN      1159.26       -79.46   
000008  神州高铁  0.00   -96.21    NaN  0.24   NaN      1159.26       -79.46   
000010  美丽生态 -0.04   978.38    NaN -1.51   NaN     -3270.67      1407.81   
000010  美丽生态 -0.04   978.38    NaN -1.51   NaN     -3270.67      1407.81   
000011  深物业A  0.00    66.67    NaN  0.03   NaN        57.70        61.92   
000012   南玻A  0.10   152.53    NaN  2.57   NaN     20483.55       149.19   
000014  沙河股份 -0.02 -1511.76    NaN -0.68   NaN      -484.91     -1541.46   
000017  深中华A  0.00   -40.00    NaN  1.24   NaN        14.64       -46.26   
000019  深深宝A -0.02   -35.13    NaN -0.66   NaN      -618.31       -35.11   
000020  深华发A  0.00    -5.56    NaN  0.15   NaN        46.99        -8.19   
000020  深华发A  0.00    -5.56    NaN  0.15   NaN        46.99        -8.19   
000022  深赤湾A  0.19    18.24    NaN  2.69   NaN     12122.10        18.17   
000022  深赤湾A  0.19    18.24    NaN  2.69   NaN     12122.10        18.17  

000008 、000010 、000020  、000022  等都重复了，也有一些漏掉了，如000009没有数据。而且每次执行，参数一致的情况下返回的数据中重复的位置都不一样。其他获取基本面的接口也有这个问题。

**Comment by Rockyzsu** [comment]
的确是，这个函数是有问题。 重复和遗漏。
tushare版本 0.75， python=2.7

数据遗漏比较多。

**Comment by v5r10** [comment]
确实有这个问题，导致每次运行结果都不一样，没发用。希望能尽快解决一下

**Comment by v5r10** [comment]
补充一下，每次返回结果的条数是固定的，但有时候会有重复的条目，一旦有重复，就意味着有的条目被遗漏丢失了

**Comment by v5r10** [comment]
我写个循环调用get_report_data，取2016年4季度的数据，每次返回结果，重复的量大概在几百条左右，所以，遗漏的量大概也是几百条
