### ISSUE TITLE
get_today_all 太慢了，为什么不直接一次返回所有？

### ISSUE THREAD

**Issue by 4ever911** [waditu/tushare#301]
默认是翻页，每页80个这样取，太慢了。

为什么不直接一次取所有的信息， 

http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData?num=10000&node=hs_a

比如把num设置为10000，直接返回所有的列表。

**Comment by jimmysoa** [comment]
以更新,谢谢!

**Comment by paulzhou2004** [comment]
这个已经新浪已经改成每页最多显示100只股票记录了。而且不能用程序直接去访问，不然会被新浪安全系统拦截，认为是爬虫之类的攻击.
