### ISSUE TITLE
企鹅厂修改了数据格式， 现在get_k_data报错，数据也不对

### ISSUE THREAD

**Issue by 4ever911** [waditu/tushare#303]
一个小时前我取的数据还是对的，就在这个小时， 那边修改了数据结构。 

在生成dataframe时参数没对上， 

我直接把url丢到浏览器里面看数据， 发现数据也不大对， qfq作为参数返回也是没复权数据。

**Comment by ryankomodo** [comment]
顶

**Comment by 4ever911** [comment]
企鹅自己的主页以及子选股app都有问题， web页上，前复权选项是灰色的， 点几下后，又亮了，但是没效果。 app上显示数据也是错的。  感觉是后端在修改数据结构，可能还没搞好就放出来了，也没通知别的部门做修改。

**Comment by 4ever911** [comment]
也可能是后端的bug，看过两天他们是否修改好。

**Comment by jimmysoa** [comment]
可以了

**Comment by 4ever911** [comment]
tushare 这边没问题， 不过取回来的数据还是没有复权的数据， 好像要根据amount和turnover来计算才行，不知道企鹅那边是怎么考虑的。

**Comment by 4ever911** [comment]
好了

**Comment by iorilu** [comment]
好像企鹅又改回去了, 晕死啊

**Comment by jimmysoa** [comment]
好了，更新到最新版。
