### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by henan715** [waditu/tushare#304]
您好，我在参照您的教程中：
`
df = ts.get_hist_data('600848')
engine = create_engine('mysql://tianchi:123456@127.0.0.1/Finance?charset=utf8')
df.to_sql('hist_data', engine)
`
时，出现了如下异常：
`
    raise errorvalue
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'date' used in key specification without a key length") [SQL: u'CREATE INDEX ix_hist_data_date ON hist_data (date)']
`
搜索后得知是在字段类型上面有点小问题，不知道您有没有遇到过这个问题？谢谢～

**Comment by jimmysoa** [comment]
index=False

**Comment by ycooi** [comment]
这样就没index了。。日期都没掉了
