### ISSUE TITLE
broker_tops函数很不稳定

### ISSUE THREAD

**Issue by lsptb** [waditu/tushare#307]
大家好，
broker_tops函数很不稳定，使用过程中，试过很多次，偶尔才能返回数据。有谁用过么？如何让这个函数稳定返回值呢？谢谢。

**Comment by lsptb** [comment]
大概看了一下函数的原型，这个函数是从网页上直接获取数据的，是不是因为频繁访问网络端口，会被屏蔽，所以才导致这个函数很难返回值？

**Comment by jimmysoa** [comment]
是的
