### ISSUE TITLE
ts.get_k_data出错

### ISSUE THREAD

**Issue by ranyangpj** [waditu/tushare#308]
ts.get_k_data(‘000672’, start = ‘1996-12-18’, retry_count = 5)

显示错误 IndexError: list index out of range

**Comment by ranyangpj** [comment]
['300490', '601607', '300479', '300223', '601700', '002578', '002316', '000156', '300420', '000638', '000672', '000622', '000719', '000498', '000757', '300212', '600485', '000333', '600094', '000403', '000536', '000681', '000529', '300276', '002745', '000017', '002282', '601168', '000916', '000557', '600875', '000584', '300271', '000620', '600705', '000863', '000776', '000750', '000038', '000688', '002162', '601005', '600406', '000670', '000517', '600681', '000912', '000033', '002132', '000516', '600400', '002129', '000903', '600673', '002113', '600173', '000050', '000829', '600145', '600649', '000029', '000716', '600645', '000697', '600636', '000693', '600556', '000682']

这些股票都出现同样的问题，只能获取最近今年的数据，获取全部数据的话就报错。其他股票都正常

**Comment by jimmysoa** [comment]
开始日期要设置对了

**Comment by ranyangpj** [comment]
开始时间设置错了吗，000672上市日期是1996年12月18日啊，是直接从列表取得上市日期，大部分股票都没有问题

**Comment by ranyangpj** [comment]
重新试过了，000672从96年07年获取数据正常，近期的数据也正常。但08年后很长一段时间获取不到数据，报错
