### ISSUE TITLE
get_k_data 数据不准啊

### ISSUE THREAD

**Issue by cosnis** [waditu/tushare#309]
In [26]: print ts.get_k_data('000001', '2016-04-14', '2016-04-15')
          date   open  close   high    low    volume    code
67  2016-04-14  8.931  8.899  8.948  8.858  323646.0  000001
68  2016-04-15  8.899  8.931  8.981  8.866  497224.0  000001

In [27]: print ts.get_hist_data('000001', '2016-04-14', '2016-04-15')
             open   high  close    low     volume  price_change  p_change  
date
2016-04-15  10.84  10.94  10.88  10.80  497224.03          0.04      0.37
2016-04-14  10.88  10.90  10.84  10.79  323646.31          0.03      0.28

**Comment by jimmysoa** [comment]
这两个数据一个是前复权，一个是未复权的。
