### ISSUE TITLE
ts.get_stock_basics() 返回 Connection refused 错误

### ISSUE THREAD

**Issue by Bearzeng** [waditu/tushare#315]
Log 如下：

In [11]: ts.get_stock_basics()
---------------------------------------------------------------------------
URLError                                  Traceback (most recent call last)
<ipython-input-11-bafd9613283b> in <module>()
----> 1 ts.get_stock_basics()

/home/xzeng/Projects/scf/bear_space/walleQuant/tushare/stock/fundamental.pyc in get_stock_basics(date)
     52     datepre = '' if date is None else wdate[0:4] + wdate[4:6] + '/'
     53     request = Request(ct.ALL_STOCK_BASICS_FILE%(datepre, '' if date is None else wdate))
---> 54     text = urlopen(request, timeout=10).read()
     55     text = text.decode('GBK')
     56     text = text.replace('--', '')

/usr/lib64/python2.7/urllib2.pyc in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    152     else:
    153         opener = _opener
--> 154     return opener.open(url, data, timeout)
    155 
    156 def install_opener(opener):

/usr/lib64/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    427             req = meth(req)
    428 
--> 429         response = self._open(req, data)
    430 
    431         # post-process response

/usr/lib64/python2.7/urllib2.pyc in _open(self, req, data)
    445         protocol = req.get_type()
    446         result = self._call_chain(self.handle_open, protocol, protocol +
--> 447                                   '_open', req)
    448         if result:
    449             return result

/usr/lib64/python2.7/urllib2.pyc in _call_chain(self, chain, kind, meth_name, *args)
    405             func = getattr(handler, meth_name)
    406 
--> 407             result = func(*args)
    408             if result is not None:
    409                 return result

/usr/lib64/python2.7/urllib2.pyc in http_open(self, req)
   1228 
   1229     def http_open(self, req):
-> 1230         return self.do_open(httplib.HTTPConnection, req)
   1231 
   1232     http_request = AbstractHTTPHandler.do_request_

/usr/lib64/python2.7/urllib2.pyc in do_open(self, http_class, req, **http_conn_args)
   1198         except socket.error, err: # XXX what error?
   1199             h.close()
-> 1200             raise URLError(err)
   1201         else:
   1202             try:

URLError: <urlopen error [Errno 111] Connection refused>

In [12]:

**Comment by Mount565** [comment]
被目标主机盯上了。 我这里也经常报错。 

urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

**Comment by ChenJinCan** [comment]
我这里也报错

**Comment by ChenJinCan** [comment]
http://218.244.146.57/static/all.csv      218.244.146.57这个网站链接不上了

**Comment by littleDing** [comment]
同样的报错，看起来像是拉取一些基本信息用的，有备用的主机吗？

**Comment by ChenJinCan** [comment]
这个需要问一下作者了,我已经联系作者了，不过还没有回复

**Comment by jimmysoa** [comment]
正在解决，阿里云服务器的问题

**Comment by jimmysoa** [comment]
可以了
