### ISSUE TITLE
获取指数数据报错

### ISSUE THREAD

**Issue by lynic** [waditu/tushare#32]
get_h_data('000300', start='2000-01-01'， index=True)
返回网络错误。

sr/lib/python2.7/site-packages/tushare/stock/trading.pyc in get_h_data(code, start, end, autype, index, retry_count, pause)
    363             ct._write_console()
    364             df = _parse_fq_data(_get_index_url(index, code, qt), index,
--> 365                                 retry_count, pause)
    366             data = data.append(df, ignore_index=True)
    367     if len(data) == 0 or len(data[(data.date>=start)&(data.date<=end)]) == 0:

/usr/lib/python2.7/site-packages/tushare/stock/trading.pyc in _parse_fq_data(url, index, retry_count, pause)
    481         else:
    482             return df
--> 483     raise IOError(ct.NETWORK_URL_ERROR_MSG)
    484 
    485 

IOError: 获取失败，请检查网络和URL

如果只获取最近的数据则没问题。

版本0.3.4

**Comment by ylc0sky** [comment]
150开头的分级基金的数据都有，可是502开头的好像都没有

**Comment by jimmysoa** [comment]
@ylc0sky 等我有时间看看，另外分级基金目前只支持150

**Comment by lynic** [comment]
修改
tushare/stock/trading.py L468
解决开始日期设置得太早的问题。

             else:
                 sarr = [etree.tostring(node) for node in res]
             sarr = ''.join(sarr)
+            if index and not sarr:
+                return pd.DataFrame()
             df = pd.read_html(sarr, skiprows = [0, 1])[0]
             if len(df) == 0:
                 return pd.DataFrame()

**Comment by 4tified** [comment]
lynic,

do you mean we should completelyreplace those 3 lines with: 

if index and not sarr:
      return pd.DataFrame() 
df = pd.read_html(sarr, skiprows = [0, 1])[0] 
if len(df) == 0: 
      return pd.DataFrame()
      
or should we just add 

if index and not sarr:
      return pd.DataFrame() 

in between 'else:' lines and the ' df = pd.read_html(sarr, skiprows = [0, 1])[0]' lines?
