### ISSUE TITLE
get_tick_data存在数据缺失如何解决？例如300531 2016年9月2日的tick数据取不到

### ISSUE THREAD

**Issue by phoenixzxj** [waditu/tushare#321]

**Comment by zz090923610** [comment]
这些有一部分缺失的原因是。。。。新浪上提供的当天数据有缺失。。。但是另一部分缺失是当天数据可网页浏览但是下载接口处缺失。总的来说是新浪的锅。。。建议自己写一个数据对齐，比如日线里有某日的数据，tick上缺了，就把日线的那天数据也删掉吧。。。我觉得缺这么几天也无甚大碍。

**Comment by jimmysoa** [comment]
正解

**Comment by cassc** [comment]
@phoenixzxj 
有的数据新浪在确实没有，但有的在新浪的明细表是可以下的，比如下面这个地址：
http://market.finance.sina.com.cn/downxls.php?date=2016-09-02&symbol=sz300531

不知可否加到接口里
