### ISSUE TITLE
get_k_data取新股数据出错

### ISSUE THREAD

**Issue by iorilu** [waditu/tushare#323]
比如002774

只用代号是可以取， 但是加上start时间就出错

`

In [10]: ts.get_k_data('002774', start='2010-01-01', end='2017-03-28')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-8de521da9844> in <module>()
----> 1 ts.get_k_data('002774', start='2010-01-01', end='2017-03-28')

/home/guryun/deploy/venv/local/lib/python2.7/site-packages/tushare/stock/trading.pyc in get_k_data(code, start, end, ktype, autype, index, retry_count, pause)
    673                                        symbol, code,
    674                                        index, ktype,
--> 675                                        retry_count, pause),
    676                            ignore_index=True)
    677     if ktype not in ct.K_MIN_LABELS:

/home/guryun/deploy/venv/local/lib/python2.7/site-packages/tushare/stock/trading.pyc in _get_k_data(url, dataflag, symbol, code, index, ktype, retry_count, pause)
    705                 js = json.loads(lines[0])
    706                 dataflag = dataflag if dataflag in list(js['data'][symbol].keys()) else ct.TT_K_TYPE[ktype.upper()]
--> 707                 if len(js['data'][symbol][dataflag][0]) == 6:
    708                     df = pd.DataFrame(js['data'][symbol][dataflag],
    709                                   columns = ct.KLINE_TT_COLS_MINS)

IndexError: list index out of range
`

**Comment by jimmysoa** [comment]
次新股确实有点问题，我看看怎么处理。

**Comment by lizhi2013** [comment]
谢谢

**Comment by lizhi2013** [comment]
今天测试了一下好像可以了

**Comment by cryptogun** [comment]
同样出错:
```
  File "D:\Users\wo\Desktop\stockenv\lib\site-packages\tushare\stock\trading.py", line 712, in _get_k_data
    if len(js['data'][symbol][dataflag][0]) == 6:
IndexError: list index out of range
```
看了一下，因为选定的时间区间数据是空的。比如创业板综合399102，在07年到08年之间没有月线。新浪财经网站上最早的数据是2010年。
[399102 2007-2008](http://web.ifzq.gtimg.cn/appstock/app/fqkline/get?_var=kline_day2007&param=sz399102,month,2007-01-01,2008-12-31,640,&r=0.42232801680085454)
结果：
```
"data":{"sz399102":{"month":[]
```
`month`（dataflag）里面没有东西，所以不能`[0]`
应该对这种情况进行处理，比如造一个空的`df`返回。
