### ISSUE TITLE
get_stock_basics() 获取股本数据计量单位错误

### ISSUE THREAD

**Issue by zjuguxi** [waditu/tushare#325]
In [49]: ts.get_stock_basics('20161123').loc['000001']['outstanding']
Out[49]: 146.31

In [50]: ts.get_stock_basics('20161122').loc['000001']['outstanding']
Out[50]: 146310.0

In [51]: ts.get_stock_basics('20161121').loc['000001']['outstanding']
Out[51]: 1463118.0

测试了几只股票，都有这种问题
规则如下：
2016-08-09 至 2016-11-21 ：outstanding以万为单位
2016-11-22 ：outstanding以十万为单位
2016-11-23 至今 ：outstanding以亿为单位

目前文档中是以亿为标准，需要对历史数据进行处理

**Comment by jimmysoa** [comment]
确实，因为数据源的调整，单位进行了变更

**Comment by zjuguxi** [comment]
对了jimmy，还发现缺失以下交易日的get_stock_basics数据
'20160810', '20160819', '20160922', '20161010', '20161205', '20170117', '20170331'

只是提一下，这个应该不是很重要哈
