### ISSUE TITLE
新人问个问题

### ISSUE THREAD

**Issue by RicharZ006** [waditu/tushare#327]
print ts.get_today_all() 或者 print ts.get_k_data(code='600000'), 打印不完整啊，
27    603908   牧高笛         -8.409   63.39   68.96   69.95   63.05       69.21   
28    603903  中持股份          1.523   45.32   45.00   48.98   44.50       44.64   
29    603901  永创智能         -1.320   14.20   14.35   14.59   14.12       14.39   
...      ...   ...            ...     ...     ...     ...     ...         ...   
3093  000035  中国天楹          0.390    7.72    7.69    7.75    7.58        7.69   
3094  000034  神州数码          0.000    0.00    0.00    0.00    0.00       24.45   
3095  000032  深桑达Ａ          0.000    0.00    0.00    0.00    0.00       15.71   
 
这些......省略的内容怎么显示出来呢？

**Comment by Wilson-G** [comment]
要啥显示啥，要不然你就导出成xls格式自己慢慢看，获取到的东西是python里的pandas格式，咋个操作pandas你可以网上搜索。其实这个工具主要用来做计算分析的，基本不会关心这种几千行中具体某一行的数据，因为这些数据就是传统软件里的K线数据，要可视化你看同花顺之类的就好了

**Comment by RicharZ006** [comment]
Thanks, Wilson.
