### ISSUE TITLE
get_hist_data不返回最重要的指标turnover了

### ISSUE THREAD

**Issue by skyskyhu** [waditu/tushare#330]
turnover换手率是研究股票最重要的指标 请问怎么把这么重要的指标去掉了

**Comment by cassc** [comment]
凤凰财经的接口出现问题了，它的网页(http://finance.ifeng.com/app/hq/stock/sh601991/)日线也未显示换手率。不知道有没有替代的接口，或用已有数据自己计算？

**Comment by jimmysoa** [comment]
可能在调整，之前也出现过，后来就好了。
