### ISSUE TITLE
get_today_all 返回股票数据缺失

### ISSUE THREAD

**Issue by foxbupt** [waditu/tushare#336]
使用get_today_all接口 获取当日交易所有股票的行情数据时，发现缺少一些股票的行情数据，代码举例如下：
| 000001 | 平安银行     |
| 000002 | 万 科Ａ      |
| 000008 | 神州高铁     |
| 000009 | 中国宝安     |

**Comment by jimmysoa** [comment]
你用的tushare是哪个版本？

**Comment by foxbupt** [comment]
使用的版本是 0.6.8

**Comment by jimmysoa** [comment]
升级到最新版

**Comment by heamon7** [comment]
同样遇到这个问题，已经升级到最新版 0.7.5。
比如今天 2017-05-11 ，用 get_today_all() 获取到的所有股票数只有 3120 只，而现在总股票数量应该已经超过了 3200 只了

**Comment by jimmysoa** [comment]
这个问题我已经确认了，我再做一次升级吧
