### ISSUE TITLE
[Feature request] 接口调用时，允许用户传递timeout参数

### ISSUE THREAD

**Issue by kawing-chiu** [waditu/tushare#341]
目前各个接口在网络请求时均默认`timeout = 10`，调用接口时用户无法设置timeout。建议在各个接口中添加`timeout=` keyword argument，由用户指定timeout。这一参数对于实时行情接口尤其重要。

**Comment by kawing-chiu** [comment]
Why is this closed? The issue is not yet solved.

**Comment by jimmysoa** [comment]
不好意思，因为同样的问题很多，我统一处理。
