### ISSUE TITLE
ts.get_stock_basics() 中的市盈率的来源是哪里？和市面常见的行情软件有比较大的出入

### ISSUE THREAD

**Issue by Rockyzsu** [waditu/tushare#347]
你好，ts.get_stock_basics 的数据是从一个ip的服务器下载下来的（all.csv） 请问这些数据的来源是在哪里？感觉和市面常见的行情软件有比较大的出入。

还有这个文件多久会更新一次？ 看着好像几天才会更新一次。

**Comment by jimmysoa** [comment]
是动态市盈率。每天更新，请把tushare升级到最新版
