### ISSUE TITLE
请问get_k_data() 每天几点更新当天的结果？ 收盘后指数的结果出来了，而一般个股的就还没出来

### ISSUE THREAD

**Issue by Rockyzsu** [waditu/tushare#349]
RT。
    df=ts.get_k_data(code='000001',index=True,start='2017-03-01')
    print df

指数的很快就获取到当天的结果，而非指数的数据还是在昨天的

**Comment by mowujilun** [comment]
我也是这样，把start参数去掉，能得到今日数据，一旦架上start，只能得到昨天往后的数据！
