### ISSUE TITLE
获取 get_h_data 数据出错

### ISSUE THREAD

**Issue by nooperpudd** [waditu/tushare#35]
data = get_h_data(code=code, end="2015-07-01")

2015-07-01  14.35  14.59  13.92  13.74  183540608  2629096448
2015-06-30  13.54  14.54  14.54  13.38  254810320  3572978432
....

结果会出现超过7月-1号的数据

**Comment by jimmysoa** [comment]
@nooperpudd  结果中会包含end的日期

**Comment by nooperpudd** [comment]
@jimmysoa  问题是end 是 7月1日，为什么会有6约30号以后的

**Comment by fuermosi777** [comment]
end 7月1号 当然会包括7月1号之前的 6月30是在7月1号之前 所以会被包括进去啊 @nooperpudd

**Comment by gclsoft** [comment]
@jimmysoa 我怎么是end有写今天的日期, 但是没打开今天的数据,已过3点收盘的
