### ISSUE TITLE
最近用get_k_data 获取的个股 如果在停牌时间内 出现IndexError: list index out of range

### ISSUE THREAD

**Issue by Rockyzsu** [waditu/tushare#351]
选一个目前停牌的个股，start的时间在停牌之后就会出现这个问题。 我以前没遇到过，是不是最近升级了的问题。 tushare版本0.7.4

 File "/Users/rocky/Data/program/base_function/tushare_function.py", line 344, in check_k_data
    df_x=ts.get_k_data(code=each_code,start='2017-03-01')
  File "/Users/rocky/Library/Python/2.7/lib/python/site-packages/tushare/stock/trading.py", line 675, in get_k_data
    retry_count, pause), 
  File "/Users/rocky/Library/Python/2.7/lib/python/site-packages/tushare/stock/trading.py", line 707, in _get_k_data
    if len(js['data'][symbol][dataflag][0]) == 6:
IndexError: list index out of range

**Comment by Rockyzsu** [comment]
这个问题在 0.7.1上不会出现，一旦把版本升级到0.7.4 后就出现了。 同样的代码。

**Comment by aweiu** [comment]
我的0.7.1也还是有这个问题。。

**Comment by Rockyzsu** [comment]
@aweiu 我试过几次，71时可以。
你确认一下你的tushare的版本用的是71 ？ 一些ide工具会仍然链接到最新的版本的。

**Comment by aweiu** [comment]
@RobotJiang 是的，我确定。
`import tushare as ts; print(ts.__version__)`
返回的就是0.7.1

**Comment by jimmysoa** [comment]
试试0.7.5

**Comment by aweiu** [comment]
@jimmysoa 谢谢回复。试了，还是一样报错。可能真得和tushare没关系吧。
我用的依赖它的插件是[funcat](https://github.com/cedricporter/funcat)
它获取最新数据用的是tushare，然后一执行就报错

**Comment by Rockyzsu** [comment]
@aweiu 我目前在获取get_k_data设置了异常处理。 可以避免程序退出。

**Comment by Rockyzsu** [comment]
@jimmysoa  0.75 现在正常了。 返回的是一个empty dataframe
