### ISSUE TITLE
tushare新版本提供业绩快报的接口吗？

### ISSUE THREAD

**Issue by phoenixzxj** [waditu/tushare#352]

**Comment by jimmysoa** [comment]
有

In [2]: ts.forecast_data(2017, 1)
[Getting data:]##########################Out[2]: 
        code   name type report_date  pre_eps              range
0     002501   利源精制   预升  2017-04-20   0.1000             5%~25%
1     002693   双成药业   减亏  2017-04-20  -0.0300                  0
2     002337   赛象科技   减亏  2017-04-20  -0.0100                  0
3     603007   花王股份   预增  2017-04-20   0.0000                486
4     600188   兖州煤业   预增  2017-04-20   0.0503          580%~600%
5     600958   东方证券   预增  2017-04-20   0.0800              99.55
6     000887   中鼎股份   预升  2017-04-20   0.2100            30%~40%
7     002035   华帝股份   预增  2017-04-20   0.1300            50%~70%
8     600121  *ST郑煤   预盈  2017-04-20  -0.1192                  0
9     601126   四方股份   预减  2017-04-20   0.0122               -296

**Comment by phoenixzxj** [comment]
好的，感谢感谢！


发自网易邮箱大师
在2017年04月19日 23:03，Jimmy 写道：

有

In [2]: ts.forecast_data(2017, 1)
[Getting data:]##########################Out[2]:
code name type report_date pre_eps range
0 002501 利源精制 预升 2017-04-20 0.1000 5%~25%
1 002693 双成药业 减亏 2017-04-20 -0.0300 0
2 002337 赛象科技 减亏 2017-04-20 -0.0100 0
3 603007 花王股份 预增 2017-04-20 0.0000 486
4 600188 兖州煤业 预增 2017-04-20 0.0503 580%~600%
5 600958 东方证券 预增 2017-04-20 0.0800 99.55
6 000887 中鼎股份 预升 2017-04-20 0.2100 30%~40%
7 002035 华帝股份 预增 2017-04-20 0.1300 50%~70%
8 600121 *ST郑煤 预盈 2017-04-20 -0.1192 0
9 601126 四方股份 预减 2017-04-20 0.0122 -296

**Comment by Felix-mrf** [comment]
这个接口我测试好像数据不全，似乎是遇到一个特殊中文字出现问题
002752（昇兴股份）和300208（恒顺众昇），都是“昇”这个字卡住了？

ts.forecast_data(2017, 2)
……
227  600665   天地源   预盈  2017-04-28  -0.0675                   0
228  600475  华光股份   预增  2017-04-28   0.2016                   0
229  600306   商业城   预盈  2017-04-28  -0.4400                   0
230  002329  皇氏集团   预升  2017-04-28   0.1205              0%~30%
231  002542  中化岩土   预升  2017-04-28   0.0500             10%~30%
232  002761   多喜爱   预降  2017-04-28   0.0800           -45%~-15%
233  002467   二六三   预降  2017-04-28   0.1100           -70%~-40%
234  002752   NaN  NaN         NaN      NaN                 NaN

ts.forecast_data(2017, 1)
……
650  300284    苏交科   预升  2017-04-07   0.1000           0%~10%
651  300171    东富龙   预降  2017-04-07   0.1385        -40%~-20%
652  300619    金银河   预盈  2017-04-07  -0.1400                0
653  300155    安居宝   预亏  2017-04-07  -0.0200                0
654  300185   通裕重工   预升  2017-04-07   0.0100          20%~50%
655  300208    恒顺众  NaN         NaN      NaN              NaN

**Comment by jimmysoa** [comment]
@Felix-mrf 很有可能，谢谢。你先调一下本地的编码格式是否可以，我再测一下我的方法

**Comment by Felix-mrf** [comment]
仔细跟踪了一下，昇这个字应该是gbk编码才有的字，gb2312没有，但是网页给的编码是gb2312，好像lxml.html.parse解析就出问题了，应该需要加一下encoding='gbk'来解决

parser = etree.HTMLParser(encoding='gbk')
html = lxml.html.parse('http://vip.stock.finance.sina.com.cn/q/go.php/vFinanceAnalyze/kind/performance/index.phtml?s_i=&s_a=&s_c=&s_type=&reportdate=2017&quarter=2&p=4&num=60',parser=parser)

**Comment by Felix-mrf** [comment]
0   600701   工大高新  预增  2017-04-28  2017-06-30   
1     2375   亚厦股份  预升  2017-04-28  2017-06-30   
2     2324    普利特  预升  2017-04-28  2017-06-30   
3     2005   德豪润达  预升  2017-04-28  2017-06-30   
4   600628    新世界  预增  2017-04-28  2017-06-30   
5     2161    远望谷  预亏  2017-04-28  2017-06-30   
6     2356   赫美集团  预升  2017-04-28  2017-06-30   
7     2071   长城影视  预升  2017-04-28  2017-06-30   
8     2061   江山化工  预增  2017-04-28  2017-06-30   
9   600815  *ST厦工  预盈  2017-04-28  2017-06-30   
10  600793   宜宾纸业  预亏  2017-04-28  2017-06-30   
11  600749   西藏旅游  预亏  2017-04-28  2017-06-30   
12  600618   氯碱化工  预增  2017-04-28  2017-06-30   
13  600293   三峡新材  预增  2017-04-28  2017-06-30   
14  600803   新奥股份  预增  2017-04-28  2017-06-30   
15  601028   玉龙股份  预警  2017-04-28  2017-06-30   
16  603007   花王股份  预增  2017-04-28  2017-06-30   
17  600997   开滦股份  预升  2017-04-28  2017-06-30   
18  601898   中煤能源  预升  2017-04-28  2017-06-30   
19  601208   东材科技  预增  2017-04-28  2017-06-30   
20  603738   泰晶科技  预增  2017-04-28  2017-06-30   
21  603993   洛阳钼业  预增  2017-04-28  2017-06-30   
22  603800   道森股份  预盈  2017-04-28  2017-06-30   
23  603799   华友钴业  预盈  2017-04-28  2017-06-30   
24     166   申万宏源  预警  2017-04-28  2017-06-30   
25     750   国海证券  预警  2017-04-28  2017-06-30   
26  600093   易见股份  预增  2017-04-28  2017-06-30   
27  600410   华胜天成  预盈  2017-04-28  2017-06-30   
28  600160   巨化股份  预增  2017-04-28  2017-06-30   
29     695   滨海能源  预亏  2017-04-28  2017-06-30   
30    2213    特尔佳  预减  2017-04-28  2017-06-30   
31    2737   葵花药业  预升  2017-04-28  2017-06-30   
32    2458   益生股份  预亏  2017-04-28  2017-06-30   
33    2748   世龙实业  预增  2017-04-28  2017-06-30   
34    2165    红宝丽  预降  2017-04-28  2017-06-30   
35    2640    跨境通  预增  2017-04-28  2017-06-30   
36    2093   国脉科技  预增  2017-04-28  2017-06-30   
37    2460   赣锋锂业  预增  2017-04-28  2017-06-30   
38    2462    嘉事堂  预升  2017-04-28  2017-06-30   
39  600209   罗顿发展  预亏  2017-04-28  2017-06-30   
40  600230   沧州大化  预盈  2017-04-28  2017-06-30   
41  600152   维科精华  预盈  2017-04-28  2017-06-30   
42    2575   群兴玩具  预亏  2017-04-28  2017-06-30   
43    2433    太安堂  预升  2017-04-28  2017-06-30   
44    2758   华通医药  预升  2017-04-28  2017-06-30   
45    2396   星网锐捷  预升  2017-04-28  2017-06-30   
46    2629   仁智股份  减亏  2017-04-28  2017-06-30   
47    2545   东方铁塔  预增  2017-04-28  2017-06-30   
48    2297   博云新材  减亏  2017-04-28  2017-06-30   
49    2027   分众传媒  预升  2017-04-28  2017-06-30   
50    2112   三变科技  预亏  2017-04-28  2017-06-30   
51  600665    天地源  预盈  2017-04-28  2017-06-30   
52  600475   华光股份  预增  2017-04-28  2017-06-30   
53  600306    商业城  预盈  2017-04-28  2017-06-30   
54    2329   皇氏集团  预升  2017-04-28  2017-06-30   
55    2542   中化岩土  预升  2017-04-28  2017-06-30   
56    2761    多喜爱  预降  2017-04-28  2017-06-30   
57    2467    二六三  预降  2017-04-28  2017-06-30   
58    2752   昇兴股份  预降  2017-04-28  2017-06-30   
59    2716   金贵银业  预增  2017-04-28  2017-06-30   

测试可以抓到这个002752了
