### ISSUE TITLE
get_k_data 中不能获取sz50,zz500等指数数据、

### ISSUE THREAD

**Issue by wyywyp** [waditu/tushare#353]
如题：get_k_data 中不能获取sz50,zz500等指数数据；
只能获取HS300的数据，
或者有别的方法可以获取到sz50,zz500的数据吗？

**Comment by jimmysoa** [comment]
需要指定指数的代码，如下中证500：

In [1]: import tushare as ts
In [2]: df = ts.get_k_data('000905', index=True)
In [3]: df
Out[3]: 
           date     open    close     high      low       volume      code
0    2014-09-09  4672.11  4701.70  4701.94  4643.38   89284306.0  sh000905
1    2014-09-10  4686.12  4709.91  4713.96  4662.18   86187344.0  sh000905
2    2014-09-11  4707.04  4704.94  4762.13  4670.64   97669705.0  sh000905
3    2014-09-12  4698.11  4756.95  4757.04  4689.63   78550025.0  sh000905
4    2014-09-15  4759.77  4807.56  4810.07  4752.85   92873064.0  sh000905
5    2014-09-16  4809.44  4645.55  4816.32  4643.86  117310229.0  sh000905
6    2014-09-17  4649.61  4686.05  4686.39  4604.67   86276129.0  sh000905
7    2014-09-18  4679.11  4719.01  4719.58  4663.15   77913057.0  sh000905
8    2014-09-19  4718.78  4758.73  4762.17  4705.09   73891425.0  sh000905
9    2014-09-22  4753.79  4694.23  4753.79  4682.62   77667073.0  sh000905
10   2014-09-23  4693.37  4754.47  4754.47  4692.90   71679128.0  sh000905
11   2014-09-24  4746.62  4815.71  4816.18  4733.56   84890143.0  sh000905
12   2014-09-25  4826.98  4814.73  4861.80  4797.27   92339396.0  sh000905
13   2014-09-26  4803.44  4829.94  4833.80  4787.31   72968523.0  sh0

**Comment by wyywyp** [comment]
嗯 好，谢谢
