### ISSUE TITLE
get_tick_data 不能获取2016-11-25的分笔数据

### ISSUE THREAD

**Issue by 308576950** [waditu/tushare#354]
用get_tick_data不能获取2016-11-25号的数据 为什么？ 这天是周五啊

**Comment by cassc** [comment]
像是新浪接口出问题了，很多日期都有问题

http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_Transactions.getAllPageTime?date=2016-11-23&symbol=sh600011 返回

`({__ERROR:"MYSQL",__ERRORNO:1146})`
