### ISSUE TITLE
get_report_data返回的dataframe里code是数字型的，导致以0开头的code只剩下后面几位。

### ISSUE THREAD

**Issue by hecor** [waditu/tushare#36]
get_report_data返回的dataframe里code是数字型的，导致以0开头的code只剩下后面几位。

**Comment by jimmysoa** [comment]
已经修复，提交到github上了。

**Comment by hecor** [comment]
good job ~ 话说觉得新浪的数据参差不齐，不如雪球的数据规范和完整。比如各种财务数据。

**Comment by jimmysoa** [comment]
雪球数据有些也是新浪的

**Comment by lubia** [comment]
我也遇到好几个接口code格式不一样，有些是完整的，比如000200有些是去零的比如200，能否统一成6位样式

**Comment by jimmysoa** [comment]
@lubia 已经修复

**Comment by jimmysoa** [comment]
@lubia 已经修复
