### ISSUE TITLE
get_report_data 获取的report_date只有月日，有点难以明白到底是哪年的数据

### ISSUE THREAD

**Issue by yanghui1228** [waditu/tushare#361]
建议把report_date格式改为YYYY-MM-DD

**Comment by jimmysoa** [comment]
是按季度分的

**Comment by yanghui1228** [comment]
看到大多数还是按季度分的，但是有些股票在上市日期前面几个季度出现，有点奇怪。当然最近几年的数据还可以。前面几年的数据差点

yang.hui@icloud.com

On 2 May 2017, at 4:57 PM, Jimmy <notifications@github.com> wrote:

是按季度分的
