### ISSUE TITLE
希望新的版本tradeAPI支持打新功能

### ISSUE THREAD

**Issue by gorf** [waditu/tushare#366]
感谢作者做出这么好的东西。我的效率大大提高，我甚至因为这个把自己和亲友的户头都迁移到中信建投了。中信建投应该给作者提成才对。
如题：希望新的版本tradeAPI支持打新功能。

**Comment by jimmysoa** [comment]
打新的应该也可以吧，同正常买股票，获取到新股申购码就行吧

**Comment by gorf** [comment]
那样还是不够方便。

**Comment by 4ever911** [comment]
中信建投做了一个新的web页面，更简洁， 不知道能不能支持？ 因为老版本函数在调用时比较慢

https://e.csc108.com/jy/main

**Comment by jimmysoa** [comment]
@gorf 有什么建议吗？加我个人微信：jimmysoa ,谢谢

**Comment by jimmysoa** [comment]
@4ever911 非常好，谢谢，有时间了研究一下

**Comment by gorf** [comment]
@4ever911 是不是新开一贴？
