### ISSUE TITLE
IN ts.get_h_data: AttributeError: 'DataFrame' object has no attribute 'sort'

### ISSUE THREAD

**Issue by fishinbox** [waditu/tushare#367]
`>>>ts.get_h_data(code='601111', start=start, end=end, autype='qfq')`

`[Getting data:]#`

`\Anaconda2\envs\py35\lib\site-packages\pandas\core\internals.py:3224: FutureWarning: Passing in 'datetime64' dtype with no frequency is deprecated and will raise in a future version. Please pass in 'datetime64[ns]' instead.`
`  return self.apply('astype', dtype=dtype, **kwargs)`
`Traceback (most recent call last):`

`  File "<ipython-input-2-40c998cd1973>", line 4, in <module>`
`    data = ts.get_h_data(code='601111', start=start, end=end, autype='qfq')`

`  File "\Anaconda2\envs\py35\lib\site-packages\tushare\stock\trading.py", line 447, in get_h_data`
`    df = df.sort('date', ascending=False)`

`  File "\Anaconda2\envs\py35\lib\site-packages\pandas\core\generic.py", line 2970, in __getattr__`
`    return object.__getattribute__(self, name)`

`AttributeError: 'DataFrame' object has no attribute 'sort'`

With Pandas:
`>>>pd.__version__`
`'0.20.1'`

**Comment by jimmysoa** [comment]
还没测过0.20的版本，我找个时间试试看。应该是排序功能不兼容了

**Comment by fericwang** [comment]
DataFrame的sort方法已经被重命名为sort_index

**Comment by jimmysoa** [comment]
请升级到最新版
