### ISSUE TITLE
怎么获得期货如IF1507的即时数据?

### ISSUE THREAD

**Issue by gclsoft** [waditu/tushare#37]

**Comment by gclsoft** [comment]
http://quote.futures.hexun.com/IF1508.shtml
能不能支持这种期货?

**Comment by xgdgsc** [comment]
可以用http://www.myquant.cn/的API

**Comment by jimmysoa** [comment]
import tushare as ts

mkt = ts.Market()
df = mkt.FutureBarsOneDay('IF1509', date='20150916')
