### ISSUE TITLE
TradeAPI 交易出错

### ISSUE THREAD

**Issue by 4ever911** [waditu/tushare#372]
client.buy('600678', price=12.05, amount=5000)

{"result":"false","msgMap":{"errorMsg":"<br/>For input string: \"400.0\""}}

**Comment by 4ever911** [comment]
并且是等很久，buy这个函数大概超过5秒才返回， 一直卡住。。。。。
我记得以前买很快的，也就是几十ms

**Comment by jimmysoa** [comment]
有时候周末或者收盘后是不行的，我以前也遇到过。

**Comment by 4ever911** [comment]
并不是周末啊
