### ISSUE TITLE
tushare中如何获得 归属于母公司所有者的净利润

### ISSUE THREAD

**Issue by braindevices** [waditu/tushare#376]
这个分季度数据对于计算PE非常重要，网上扒下来的PE通常都是错误的
而且好像没见到有历史PE数据
所以必须得到这个`归属于母公司所有者的净利润`的数据，我找了半天好像没看到有呢, 实际上sina上有这个数据的。

**Comment by jimmysoa** [comment]
把链接发给我看看怎么加，jimmysoa@sina.cn，谢谢
