### ISSUE TITLE
查询成交结果重复

### ISSUE THREAD

**Issue by gorf** [waditu/tushare#378]
ordersno         matchcode   trddate matchtime stkcode stkname bsflagState  \
0     1531  0104000000174316  20170522    092500  000338    潍柴动力        证券卖出   
1   220667  0104000008362448  20170522    134330  000338    潍柴动力        证券买入   
2     1531  0104000000174316  20170522    092500  000338    潍柴动力        证券卖出   
3   220667  0104000008362448  20170522    134330  000338    潍柴动力        证券买入   

  orderprice matchprice orderqty matchqty matchamt  
0     10.530     10.960      300      300  3288.00  
1     10.960     10.960      300      300  3288.00  
2     10.530     10.960      300      300  3288.00  
3     10.960     10.960      300      300  3288.00  
如上，版本是0.7.7

**Comment by jimmysoa** [comment]
哪个接口？

**Comment by gorf** [comment]
中信建投的
