### ISSUE TITLE
get_tick_data无法获取数据

### ISSUE THREAD

**Issue by ashtonhong** [waditu/tushare#379]
get_tick_data这个方法，无法获取数据

**Comment by jimmysoa** [comment]
报这种问题，需要更详细的说明，不然不知道是什么情况


n [5]: ts.get_tick_data('600848', date='2017-05-24')
Out[5]: 
          time  price change  volume  amount type
0     15:00:00  16.82     --       0       0   卖盘
1     15:00:00  16.82  -0.03       0       0   卖盘
2     15:00:00  16.85     --       0       0   买盘
3     14:59:54  16.85     --      24   40440   买盘
4     14:59:48  16.85     --      20   33700   买盘
5     14:59:45  16.85     --      32   53920   买盘
6     14:59:42  16.85   0.01      10   16850   买盘
7     14:59:39  16.84  -0.01       5    8420   卖盘
8     14:59:36  16.85     --       0       0   买盘
9     14:59:33  16.85   0.02      10   16850   买盘
10    14:59:30  16.83     --      23   38708   卖盘
11    14:59:27  16.83  -0.02     100  168299   卖盘
12    14:59:24  16.85     --       3    5055   买盘
13    14:59:21  16.85     --       9   15165   买盘
14    14:59:18  16.85  -0.01      58   97730  中性盘
15    14:59:06  16.86     --       0       0   买盘
16    14:59:03  16.86   0.04     501  844686   卖盘
17    14:58:54  16.82     --       0       0   卖盘
18    14:58:51  16.82     --       0       0   卖盘
19    14:58:48  16.82  -0.06      20   33640   卖盘
20    14:58:45  16.88   0.02       8   13504   买盘
21    14:58:39  16.86   0.04      20   33720   买盘
22    14:58:36  16.82  -0.01     204  343128   卖盘
23    14:58:33  16.83     --       0       0   卖盘
24    14:58:30  16.83  -0.05     300  504899   卖盘
25    14:58:09  16.88     --      10   16880   买盘
26    14:58:06  16.88     --      30   50640   买盘
27    14:58:03  16.88   0.05       5    8440   买盘
28    14:58:00  16.83  -0.05      90  152311   卖盘
29    14:57:54  16.88   0.03      11   18568   卖盘
...        ...    ...    ...     ...     ...  ...
1604  09:33:12  17.36  -0.04     122  211792   卖盘
1605  09:33:09  17.40     --       1    1739   卖盘
1606  09:33:06  17.40  -0.01       2    3479   卖盘
1607  09:33:03  17.41     --       9   15669   卖盘
1608  09:32:48  17.41   0.01       2    3482   买盘
1609  09:32:32  17.40     --       7   12179   买盘
1610  09:32:29  17.40   0.04       2    3479   买盘
1611  09:32:23  17.36     --       5    8680   卖盘
1612  09:32:17  17.36  -0.04       3    5208   卖盘
1613  09:32:11  17.40     --       2    3479   买盘
1614  09:32:08  17.40   0.04       2    3479   买盘
1615  09:31:56  17.36     --       4    6944   买盘
1616  09:31:53  17.36     --       1    1736   买盘
1617  09:31:47  17.36     --       2    3472   买盘
1618  09:31:38  17.36     --       2    3472   买盘
1619  09:31:32  17.36     --       2    3472   买盘
1620  09:31:29  17.36   0.01      19   32984   卖盘
1621  09:31:11  17.35   0.01       3    5205   买盘
1622  09:31:08  17.34  -0.01       8   13872   卖盘
1623  09:30:59  17.35  -0.01       2    3470  中性盘
1624  09:30:50  17.36   0.02       2    3472   买盘
1625  09:30:44  17.34  -0.02      52   90168   买盘
1626  09:30:41  17.36     --       0       0   买盘
1627  09:30:26  17.36   0.13       4    6944   买盘
1628  09:30:23  17.23  -0.13       2    3980   卖盘
1629  09:30:08  17.36   0.19      20   34720   买盘
1630  09:30:05  17.17  -0.03     106  182002   卖盘
1631  09:30:02  17.20     --      10   17200   买盘
1632  09:29:00  17.20     --       0       0   买盘
1633  09:25:01  17.20   17.2      91  156520   买盘

[1634 rows x 6 columns]

In [6]:

**Comment by ashtonhong** [comment]
>>> ts.get_tick_data('600848', date='2017-05-24')
HTTP Error 456:
HTTP Error 456:
HTTP Error 456:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\tushare\stock\trading.py", line 167, in get_tick_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)


测试了网络是正常的，不知道为什么在我这里调用会这样？

**Comment by jimmysoa** [comment]
网络被禁了？

**Comment by phoenixzxj** [comment]
我也遇到了跟楼主一样的问题，是因为被防火墙禁了吗？

**Comment by phoenixzxj** [comment]
但是有的时候又能调的出来，感觉像是服务器端不是很稳定啊

**Comment by DatumWorld** [comment]
这几天同样出现这个问题HTTP Error 456。现象为就最开始能读取一两次数据，之后提示HTTP Error 456，进tushare调试，返回异常；将请求地址复制到浏览器显示“新浪安全拦截”结果页面。猜想服务器不稳定或者做限制了。改成单线程访问结果一样。

**Comment by phoenixzxj** [comment]
日线数据都是正常的，按道理也没必要单独限制tick数据吧

**Comment by pakchoiko** [comment]
更新了0.7.9之后还是一直显示HTTP Error 456:

**Comment by zjujjm** [comment]
https://github.com/waditu/tushare/issues/38

**Comment by zjujjm** [comment]
遇到同样的情况，似乎是新浪检测IP了

**Comment by lynic** [comment]
也遇到一样的问题，难道是新浪作了限制？

**Comment by jimmysoa** [comment]
新增了两个数据源，通过src设置，tt=腾讯，nt=网易，默认是sn新浪

**Comment by phoenixzxj** [comment]
腾讯的数据源好像不是很完整，我调14年的tick数据有些调不出来

**Comment by phoenixzxj** [comment]
有什么方法能够解决新浪的数据源问题吗？感觉它家的目前最靠谱。

**Comment by jimmysoa** [comment]
数据问题不是很大，sina只是多了一些成交量为0的tick

**Comment by clockzhong** [comment]
完了，我也遇到同样的问题了。无论是腾讯的，网易的还是新浪的，只要每过五，六秒调一次这个API，我的IP就会被禁止，这两天刚刚变得这样的。估计这些公司不允许我们这么干了，咋办啊？好难搞到数据的，还有什么手段可以得到Tick数据吗？
