### ISSUE TITLE
get_tick_data 数据来源

### ISSUE THREAD

**Issue by seasonhuang** [waditu/tushare#38]
请问get_tick_data的数据是在哪个网页爬到的？

**Comment by jimmysoa** [comment]
sina财经

**Comment by seasonhuang** [comment]
http://market.finance.sina.com.cn/downxls.php?date=2015-06-01&symbol=600848 是不是这个链接，打开提示无数据，是不是格式错了？

**Comment by seasonhuang** [comment]
http://market.finance.sina.com.cn/downxls.php?date=2015-06-01&symbol=sh600848
少了个sh 这样就可以了。话说这个接口好像没上证指数、沪深300的？

**Comment by seasonhuang** [comment]
http://finance.sina.com.cn/realstock/company/sh000001/hisdata/2015/07.js
发现这个接口有分时数据，但是需要破解。这个请问你研究过吗

**Comment by seasonhuang** [comment]
已经解出来了，但是发现跟同花顺有小数点的误差，这个数据是哪个比较准的？

**Comment by jimmysoa** [comment]
@seasonhuang 很难完全一样，各个券商行情软件的有时候都有一些差异

**Comment by seasonhuang** [comment]
这样子，多谢回答

**Comment by zhuchiheng** [comment]
@seasonhuang 能请教一下那个分时数据的格式吗？

**Comment by zjujjm** [comment]
遇到同样的情况，似乎是新浪检测IP访问了
