### ISSUE TITLE
前复权计算法则

### ISSUE THREAD

**Issue by phoenixzxj** [waditu/tushare#381]
兔君，日线的前复权是乘以前复权因子直接取小数点后前三位吗？

**Comment by pakchoiko** [comment]
@phoenixzxj 请问哪里能够获得前复权因子呢?能告诉我吗?谢谢!

**Comment by jimmysoa** [comment]
通过设置参数drop_factor=False可获得因子

**Comment by phoenixzxj** [comment]
@pakchoiko 有两种思路，如果你知道股票具体的除权登记日，你可以使用ohlc中任意一个量，用复权价除以未复权价。还有以前tushare提供通联的免费接口，它好像提供具体的复权因子，但是准不准确就不知道了。

**Comment by pakchoiko** [comment]
非常感谢上面两位的回答,都很实用!

**Comment by Gabrielvon** [comment]
大家好，

请问一下怎么获取除权生效日呢？tushare有直接的接口吗？

**Comment by run27017** [comment]
> 通过设置参数drop_factor=False可获得因子

pro.daily 设置 drop_factor 无效果。
