### ISSUE TITLE
get_stock_basics()报错 KeyError: 'code'

### ISSUE THREAD

**Issue by phoenixzxj** [waditu/tushare#388]

**Comment by jimmysoa** [comment]
希望问题描述（错误信息）更详细一点，或者，升级到最新版应该就可以了。

**Comment by phoenixzxj** [comment]
已经试过升级了，现在是0.7.9，还是不行，我贴个图
![image](https://cloud.githubusercontent.com/assets/19839217/26823561/a8ff92ba-4ae0-11e7-889a-7e8598762cc8.png)

**Comment by Loohaze** [comment]
![image](https://cloud.githubusercontent.com/assets/18029266/26827320/40654074-4aef-11e7-8c5e-a3892df8439b.png)
爬下来的数据 标签变成中文的了, set_index('code') 会报错 
把code 直接改成代码就还可以用
不过还是修复吧…

**Comment by jimmysoa** [comment]
昨天数据生产过程疏忽了，后来已经修复
