### ISSUE TITLE
2017年6月7日(今天)的get_today_all缺少数据

### ISSUE THREAD

**Issue by zhangcx93** [waditu/tushare#394]
现在是2017年6月7日19点,至少有以下51个代码的股票今天用ts.get_today_all()获取不到数据.而其中绝大部分都是开盘了的(不开盘其实也应该有数据才对),使用master版本的代码.
另外如果使用0.7.9的版本,这个接口今天只能获取到100多支股票的数据,之前都是好的.
```

000069
000063
000090
000156
000033
000023
000004
000048
000039
000157
000022
000002
000055
000151
000155
000034
000010
000050
000029
000043
000042
000045
000150
000007
000049
000061
000059
000046
000018
000012
000066
000056
000001
000159
000021
000025
000088
000070
000158
000030
000031
000058
000153
000014
000028
000026
000011
000016
000020
000036
000032
000005
000062
000096
000089
000006
000027
000035
000068
000008
000078
000100
000099
000037
000019
000060
000040
000009
000017
000038
000065
```

另外,我今天在用pip更新tushare的时候报错:

    Traceback (most recent call last):
      File "/tmp/pip-build-5m2r76qy/tushare/tushare/futures/domestic.py", line 16, in <module>
        from urllib.request import urlencode
    ImportError: cannot import name 'urlencode'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5m2r76qy/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-build-5m2r76qy/tushare/tushare/__init__.py", line 117, in <module>
        from tushare.futures.domestic import (get_cffex_daily, get_czce_daily,
      File "/tmp/pip-build-5m2r76qy/tushare/tushare/futures/domestic.py", line 19, in <module>
        from urllib2 import urlopen, Request
    ImportError: No module named 'urllib2'

然后我去看了下代码貌似master里的domestic.py的代码和pip上0.8.0的代码不一致.master上是好的,请在pip上发布新版本.(也就是说现在pip直接装的tushare在python3上根本无法安装)

还有就是建议get_k_data这个接口能够在当日收盘以后就更新数据,而不要等第二天.如果原始接口没有更新,那么可以用实时数据接口的数据和历史数据拼接.

**Comment by kenneth** [comment]
今天确实获取不到数据，我也发现了。  get_today_all是一个核心接口，获取不到数据怎么玩？

**Comment by zhangcx93** [comment]
6月8号收盘,以上提到的股依然没有数据

**Comment by jimmysoa** [comment]
升级到最新版
