### ISSUE TITLE
get_k_data('600919',ktype='5') 5分钟数据获取有bug

### ISSUE THREAD

**Issue by hardy110** [waditu/tushare#397]
get_k_data(stock,ktype='5') 无法指定开始结束时间，获取的是固定（280）的值，我在测试发下，一般下午的时候，获取的是280个值

269  2017-06-09 14:10  9.39   9.37  9.39  9.37   7646.0  600919
270  2017-06-09 14:15  9.39   9.37  9.39  9.37   3924.0  600919
271  2017-06-09 14:20  9.37   9.38  9.39  9.37   3650.0  600919
272  2017-06-09 14:25  9.39   9.37  9.39  9.37   5569.0  600919
273  2017-06-09 14:30  9.37   9.38  9.39  9.37   6955.0  600919
274  2017-06-09 14:35  9.38   9.39  9.39  9.37   7846.0  600919
275  2017-06-09 14:40  9.39   9.38  9.39  9.36   6424.0  600919
276  2017-06-09 14:45  9.38   9.36  9.38  9.36   7866.0  600919
277  2017-06-09 14:50  9.36   9.38  9.38  9.36  11361.0  600919
278  2017-06-09 14:55  9.38   9.38  9.39  9.37  14078.0  600919
279  2017-06-09 15:00  9.38   9.38  9.38  9.37  11406.0  600919

[280 rows x 7 columns]

但是我在凌晨左右获取的值 只有232个：
                     ds     y
217 2017-06-08 13:50:00  9.36
218 2017-06-08 13:55:00  9.35
219 2017-06-08 14:00:00  9.37
220 2017-06-08 14:05:00  9.40
221 2017-06-08 14:10:00  9.38
222 2017-06-08 14:15:00  9.38
223 2017-06-08 14:20:00  9.38
224 2017-06-08 14:25:00  9.38
225 2017-06-08 14:30:00  9.38
226 2017-06-08 14:35:00  9.37
227 2017-06-08 14:40:00  9.40
228 2017-06-08 14:45:00  9.40
229 2017-06-08 14:50:00  9.39
230 2017-06-08 14:55:00  9.38
231 2017-06-08 15:00:00  9.39

麻烦查下原因吧。

**Comment by jimmysoa** [comment]
分钟数据只有最近几天的，设置start日期参数是无效的。
