### ISSUE TITLE
[新功能]送配方案列表和中报列表

### ISSUE THREAD

**Issue by wuxianliang** [waditu/tushare#4]
高送转和中报，都是可能热炒的概念。

研究高送转操作手法，需要一个可以及时更新的，包含送配方案（比例）、除权登记日（包括历史的）、除权日、股票代码和股票名称的列表。

最终我们可以这样检索，等于1（10送10）的，2008年1-3月除权的，股票代码。

中报也类似，股票代码、（预计）披露日期、预增（降）、百分数。

务必包含历史，便于研究炒作的方向和力度

印象中上半年炒高送转，下半年炒中报。

**Comment by jimmysoa** [comment]
好的，争取发布下一个版本的时候加上这些功能。

**Comment by jimmysoa** [comment]
高送转已经可以通过以下方法查询到：
       df = ts.profit_data(top=60)
       df[df.shares>=10] #10送10
 
业绩预告：
ts.forecast_data(2014,4) #2014年年报，3-三季度业绩预告，2-中报，1-一季度预告
返回的数据包括：
        code,代码
        name,名称
        type,业绩变动类型【预增、预亏等】
        report_date,发布日期
        pre_eps,上年同期每股收益
        range,业绩变动范围

**Comment by wuxianliang** [comment]
谢谢

**Comment by skytalemcc** [comment]
好棒
