### ISSUE TITLE
get_stock_basics()（股票列表）获取到的数据是否存在问题呢？

### ISSUE THREAD

**Issue by dongbaao** [waditu/tushare#402]
举个例子：
code='603203' name='快克股份' 这条记录。
其totalAssets（总资产）为31503.91万，即3.15亿
其bvps（每股净资）为3.53元
其totals（总股本）为0.92亿股
所以净资产=bvps*totals=3.24亿元
所以这里，净资产3.24亿>总资产3.15亿了。
我们都知道：净资产=总资产-负债 。
从证券软件上，我们可以查到其负债率为：11.3%，就是说公司确实是有负债的。那么净资产应该比总资产小才对。
所以这个数据是不是有问题？

**Comment by dongbaao** [comment]
我发现我下载的数据和你看到的不一样。我今天又重新调用了一遍ts.get_stock_basics()，发现数据还是和上次获取到的一样，和你看到的不一样。这是什么原因呢？
code 	name	industry	area	pe	        outstanding	totals	totalAssets\	
603203	快克股份	专用机械	江苏	64.01	0.23	                0.92          31503.91	

liquidAssets	fixedAssets	reserved	reservedPerShare	esp	         bvps     pb\	
24610.15	        3820.6	        5890.22	0.64	                        0.749        3.53	     18.11

timeToMarket	undp	perundp	rev	profit	gpr	   npr	holders\
20161108	8814.1	0.96	        0	0	        56.1	   32.82	25385

**Comment by jimmysoa** [comment]
get_stock_basics每天都会更新一次，有些财务方面的数据应该是不变的。

**Comment by dongbaao** [comment]
那我这儿获取到的数据确实和Felix-mrf贴出来的不一样呀。这个啥原因呢
