### ISSUE TITLE
get_today_all函数中的per换成pe_ttm

### ISSUE THREAD

**Issue by Felix-mrf** [waditu/tushare#403]
目前在做量化交易的时候，发现tushare的pe有两个
1、一个是股票列表get_stock_basics，里面是动态市盈率，但是这个市盈率偏差很大
2、另一个就是get_today_all函数，这个per具体是什么是什么市盈率，不知道是否可以告知？我仔细对比了一下好像不是pe_ttm，好像也不是静态市盈率，整体比较偏低
建议可以换成pe_ttm，虽然这个也有些问题，但总体上来说比上面两个靠谱太多了@jimmysoa

**Comment by jimmysoa** [comment]
目前一个用的是通达新的数据源，一个是新浪财经的数据源，通达信的应该是TTM的逻辑。

**Comment by Felix-mrf** [comment]
1、get_stock_basics里面是按照季度*4算的动态市盈率，这个跟软件一致，比较好理解。看源码这个应该是用的通达信
2、get_today_all里面的per比软件和网站上的pe_ttm要小一些，应该不是pe_ttm，这个是从新浪数据抓出来的
{symbol:"sh603999",code:"603999",name:"读者传媒",trade:"21.600",pricechange:"0.170",changepercent:"0.793",buy:"21.610",sell:"21.620",settlement:"21.430",open:"21.250",high:"21.620",low:"21.050",volume:2056849,amount:44003109,ticktime:"15:00:00",per:74.483,pb:3.752,mktcap:622080,nmc:248832,turnoverratio:1.78546}
这里读者传媒per 74.48，而新浪财经上面显示读者财经的pettm为71.75，不同的股票差距不一样，有点不清楚具体是什么引起的

**Comment by Felix-mrf** [comment]
仔细对了几个，差距不是特别大，先将就用吧，只是不清楚这个到底是什么pe
