### ISSUE TITLE
get_today_all无法获取全部股票信息

### ISSUE THREAD

**Issue by lydonlee** [waditu/tushare#404]
2017/6/16日测试，get_today_all函数中使用的这两个网址无法获取全部股票信息，请看下是否需要更换其他网址？
http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData?num=10000&node=hs_a
http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData?num=10000&node=shfxjs

**Comment by jimmysoa** [comment]
请将tushare升级到最新版。
