### ISSUE TITLE
TradeAPI 为什么提交明文密码也可以登陆成功? 抓IE包发现是加密处理的密码呀？

### ISSUE THREAD

**Issue by 4ever911** [waditu/tushare#413]
TradeAPI 里面， 我抓包看web页面登陆提交时密码是安全输入控件处理过的， 每次都不一样，

为什么 tushare里面 直接传递明文密码给服务器， 也可以登陆呢？

是不是正好碰巧服务器那边可能有判断是否是明文？ 感觉服务器这个处理很奇怪啊，

**Comment by jimmysoa** [comment]
明文可以

**Comment by kenshinzh** [comment]
TradeAPI 支持哪些券商啊?

**Comment by jimmysoa** [comment]
目前只有中信建投一家
