### ISSUE TITLE
get_tick_data报网络错误

### ISSUE THREAD

**Issue by xushenkun** [waditu/tushare#424]
默认用sn数据，经常报HTTP Error 456，获取失败，请检查网络和URL，错误。

**Comment by Rockyzsu** [comment]
[Getting data:]###########Error reading file 'http://vip.stock.finance.sina.com.cn/quotes_service/view/vMS_tradedetail.php?symbol=sz000066&date=2017-07-14&page=11': failed to load external entity "http://vip.stock.finance.sina.com.cn/quotes_service/view/vMS_tradedetail.php?symbol=sz000066&date=2017-07-14&page=11"


如果多线程获取，我的偶尔会出错。

**Comment by tombluemoon** [comment]
@xushenkun 请给到再具体点的信息

**Comment by tombluemoon** [comment]
@Rockyzsu 同时并发过多，新浪会阻断你的部分请求

**Comment by jimmysoa** [comment]
设置一下src参数，可以随机切换数据源
