### ISSUE TITLE
get_k_data设置了ktype之后，起始日期的设置失效

### ISSUE THREAD

**Issue by wsrhp** [waditu/tushare#429]
比如，设置了起始日期是2017-07-17，但数据返回的仍然是从2017-07-03开始
ts.get_k_data('000001', start='2017-07-17', end='2017-07-18', ktype='5')
如果不加ktype，默认日K线，则正常。

**Comment by tombluemoon** [comment]
除了日k线，其他的都是返回所有值，没有时间范围控制。

**Comment by jimmysoa** [comment]
分钟线只有最近几日的数据，所以没有让日期区间生效
