### ISSUE TITLE
get_realtime_quotes通过控制台调用，每次结果都一样？ 不是实时数据吗？

### ISSUE THREAD

**Issue by ZeeRoc** [waditu/tushare#430]
![image](https://user-images.githubusercontent.com/13727732/28308419-bb025420-6bd8-11e7-93f3-b3e6e9de312d.png)

中间调用间隔时间大概5-10秒，但是每次结果都一样？ 是什么原因？

**Comment by tombluemoon** [comment]
大哥，收盘了么？

**Comment by ddsxkdd** [comment]
我也出现了这个问题，近段时间都是这样，更新到0.8.4也没用，调用时间肯定是在开盘的时候

**Comment by ZeeRoc** [comment]
今天下午又正常了

**Comment by tombluemoon** [comment]
@ddsxkdd 麻烦请截个日志图

**Comment by ddsxkdd** [comment]
截几个日志，可以看一下，前段时间没啥问题，近段时间变成这样了，date是当天的，但是time很奇怪，然后其他数据一直都没有变化，不过下午的有些日志没有纪录，可以再观察一段时间
<img width="1418" alt="2017-07-19 9 21 43" src="https://user-images.githubusercontent.com/8245293/28369163-6651faa6-6cc9-11e7-8468-85d2c135caed.png">
<img width="1417" alt="2017-07-19 9 22 47" src="https://user-images.githubusercontent.com/8245293/28369182-719c271a-6cc9-11e7-8200-b320ad413dcd.png">
<img width="1422" alt="2017-07-19 9 23 54" src="https://user-images.githubusercontent.com/8245293/28369192-7872b478-6cc9-11e7-96a6-c832ab0cf777.png">

**Comment by jimmysoa** [comment]
15：05，收盘以后当然一样的
