### ISSUE TITLE
新浪股票行业分类数据获取不全

### ISSUE THREAD

**Issue by algony-tony** [waditu/tushare#433]
ind01 = tus.get_industry_classified()
ind01.shape
现在这样获取数据只有 2373 个股票, 实际今天已经有 3300+ 支股票.

是 classifying.py 文件里这个函数取的数据不全
  def _get_detail(tag, retry_count=3, pause=0.001)
比如行业 "生物制药" 生成的链接是这样的
'http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData?page=1&num=1000&sort=symbol&asc=1&node=new_swzz&symbol=&_s_r_a=page'

它这个链接一个 page 里面至多只有 100 条数据, 这里 num 应该是超过 100 就按照 100 处理里, 可能还是需要多取几个 page 才能把数据取全.

**Comment by jimmysoa** [comment]
tushare升级到新版就可以了，取了get_stock_basics的数据，老版本的数据源已经不更新。
