### ISSUE TITLE
请问 ts 是否支持普通基金的历史数据？

### ISSUE THREAD

**Issue by jetorz** [waditu/tushare#436]
get_k_data 里面有 index 参数，
设置为 TRUE 的时候是股指，
我用来获取一些指数型基金的信息；
设置为 FALSE 的时候是股票……
这就囧了，
我要是想获取一些基金的历史数据怎么办呢？

之所以有这个需求，
是因为我想比较一下各种投资方式到底哪个比较好。
用 matplotlib 绘图，可以看出很明显的趋势。
现在先获取了一些不同的指数，
比较出了有一些指数的确比另外一些指数要好；
但想比较优选出来的基金和指数的时候，
却没有办法获取基金的信息了……

ts 支持基金的历史交易数据么？

**Comment by jimmysoa** [comment]
目前只能获得分级基金的历史数据
