### ISSUE TITLE
web.ifzq.gtimg.cn上数据疑似有缺失

### ISSUE THREAD

**Issue by fduxiao** [waditu/tushare#439]
[ts.get_k_data](https://github.com/waditu/tushare/blob/master/tushare/stock/trading.py#L619)('600016', '2007-09-04', '2007-09-04')发现无数据，而当天任意股票对数据均缺失，仅有指数数据，跟进源代码发现从http://web.ifzq.gtimg.cn/appstock/app/fqkline/get?_var=kline_dayqfq2007&param=sh600016,day,2007-01-01,2008-12-31,640,qfq&r=0.14717337880617885 上下载数据的时候唯独缺少这一天，并且在其它的数据来源上可以查到如搜狐财经上 http://q.stock.sohu.com/hisHq?code=cn_600016&start=20070903&end=20070905&stat=1&order=D&period=d

**Comment by krizex** [comment]
确实这个查询有问题，所以我一般都是拿完整的数据下来自己做过滤。
为什么关掉这个问题？这个接口废弃了吗？
