### ISSUE TITLE
tushare-0.8.4 执行 get_today_all()报错

### ISSUE THREAD

**Issue by lwzswufe** [waditu/tushare#443]
错误内容如下：
urllib.error.HTTPError: HTTP Error 456:
执行ts.get_latest_news()
错误内容如下：
<urlopen error [Errno 11001] getaddrinfo failed>
电脑系统win10， python版本3.5.2, 网络环境正常

**Comment by jimmysoa** [comment]
最近网络受到了限制

**Comment by BMR731** [comment]
所以可以用的爬取频率是多少啊
