### ISSUE TITLE
get_concept_classified()报错

### ISSUE THREAD

**Issue by leiliuliulei** [waditu/tushare#446]
在0.8.4版本下执行get_concept_classified()后报错，具体错误见下。

ts.__version__
Out[3]: '0.8.4'

c = ts.get_concept_classified()
[Getting data:]###############################----------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-12aab80fc4ca> in <module>()
----> 1 c = ts.get_concept_classified()

C:\Program Files\Anaconda3\lib\site-packages\tushare\stock\classifying.py in get_concept_classified()
     72     for row in df.values:
     73         rowDf =  _get_detail(row[0])
---> 74         rowDf['c_name'] = row[1]
     75         data.append(rowDf)
     76     data = pd.concat(data,ignore_index=True)

TypeError: 'NoneType' object does not support item assignment

**Comment by tlhbjfunny** [comment]
同问，包括get_industry_classified()也报错。没有概念分类数据，板块选取数据的操作、分析都进行不了了。

**Comment by algony-tony** [comment]
现在我这边是可以下的了

**Comment by tlhbjfunny** [comment]
我这边还是不行啊，这个问题到底是抓取数据的问题还是别的啥问题啊？

**Comment by tlhbjfunny** [comment]
发现一个技巧，如果在抓取过程中，IE进入新浪财经概念板块，隔几秒人工刷新一下页面，则能够获取成功。是不是服务器端拒绝造成的抓取不成功呢？

**Comment by algony-tony** [comment]
应该是接口的问题， 可能sina那边觉得你下得太多了， 你浏览器访问下这个网址看看 http://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php

**Comment by tlhbjfunny** [comment]
获取的时候我不停刷新新浪财经，就成功获取了。是不是要调整哪个参数，让新浪不会认为频繁访问？

**Comment by leiliuliulei** [comment]
能不能这样：tushare每天只访问一次新浪财经，获取数据之后保存在自己的数据库上。然后每次大家查询时都访问tushare的数据库

**Comment by algony-tony** [comment]
你可以自己写个函数， 自己下载一份数据到本地， 每次使用时判断下文件的更新时间， 超过一个时长就去网上重新下载一份否则就使用本地已有的数据。

**Comment by tlhbjfunny** [comment]
每天都需更新

**Comment by Matrixio** [comment]
同样的问题，偶尔能成功，大部分时间都不行。

**Comment by kernel8liang** [comment]
版本0.87，同样的问题

**Comment by jimmysoa** [comment]
升级到0.9.0

**Comment by kernel8liang** [comment]
升了，还是一样的问题

**Comment by jimmysoa** [comment]
确定是新浪做了限制，新版考虑更换新的数据源，谢谢。
