### ISSUE TITLE
Import lxml.html 出错

### ISSUE THREAD

**Issue by hart02** [waditu/tushare#45]
谢谢你的开源tushare，第一次运行时报错：在spyder下运行调用任何tushare 公式都报错

例如 import tushare as ts 
      ts.get_area_classified()

File "C:\Anaconda\lib\site-packages\tushare\stock\trading.py", line 13, in <module>
    import lxml.html
ImportError: No module named html

但在powershell 里面 进入python 然后 import lxml.html 成功不报错。
pip list 里显示有  lxml (3.4.4)

第一次用Python， 不知是不是我设置问题。

**Comment by jimmysoa** [comment]
需要安装lxml依赖包

**Comment by xgdgsc** [comment]
@jimmysoa 像lxml和pandas这样的依赖应该写到setup.py的install_requires里面。

**Comment by xgdgsc** [comment]
还有xlrd
