### ISSUE TITLE
已经无法批量通过get_tick_data获取数据了

### ISSUE THREAD

**Issue by clockzhong** [waditu/tushare#450]
总是得到这个错误：
[Getting data:][Getting data:]HTTP Error 456: 
HTTP Error 456: 
HTTP Error 456: 
无论是腾讯的，网易的还是新浪的，只要每过五，六秒调一次这个API，我的IP就会被禁止，这两天刚刚变得这样的。估计这些公司不允许我们这么干了，咋办啊？好难搞到数据的，还有什么手段可以得到Tick数据吗？
不管我怎么更新IP，似乎都不行了。怎么办啊》

**Comment by jimmysoa** [comment]
等着开新接口，或者用代理IP吧

**Comment by clockzhong** [comment]
好了，自己把代码改了改，加了代理了，用几百个代理还是可以开几百个线程了。

**Comment by zhenjieliang** [comment]
@clockzhong 可以把你改的代码发上来吗？你使用的代理ip屏蔽了就好。
另外，如果我想把全部历史tick数据都下载下来，为了避开456错误，大概需要多少个代理ip？

**Comment by clockzhong** [comment]
@zhenjieliang 代码没整理，发上来太难看了，我是直接改挖地兔源代码的，直接使用urllib2的代理设置：
opener = urllib2.build_opener(proxy_setting)
然后改today_ticks()函数，你稍微读一读jimmy的code吧，他写的逻辑很清晰，很容易懂。
至于下载全部历史ticks，我还是建议在市场上买更快，要想避开456错误，不仅要用更多的代理，你还得放慢访问频率，估计全下载下来要几个月。

**Comment by zhenjieliang** [comment]
好的，谢谢！
主要是想省钱。我之前找了一个叫预测者的网站，上面的报价是每一年的数据是300元，要想买十年的数据就得三千了（没错，就是发一个文件链接，这个链接就得三千块）。
你那边有更好的报价的吗？

打扰了，谢谢你的指点！


2017-11-15 17:00 GMT+08:00 clockzhong <notifications@github.com>:

**Comment by clockzhong** [comment]
如果你真的是想利用这些数据在股市上挣钱的话，但又觉得3000块贵的话，最好就不要干了。
买数据的时候最要紧的考虑不是数据的价格，而是数据的内容，如果数据内容不是你需要的，不能帮你挣到钱，再便宜又有什么用，如果能给你挣年化哪怕15%的收益，三万块都很便宜了。
如果你只是想玩玩，那就随便你了。凡事都以自己的目标为参照，而不是在外物间相互做比较。
这只是我的建议。

**Comment by zhenjieliang** [comment]
呵呵，你自己是学生的时候也是这样掏出三千块买一份学习数据不眨眼，不想从别的途径去获得的吗，是的话只能说咱俩财富值有差距
不得不说，你的话在有能力追求时间和效率的中产阶级里是天然正确的，我无法反驳。


2017-11-17 19:43 GMT+08:00 clockzhong <notifications@github.com>:

**Comment by zhenjieliang** [comment]
你在嘲讽我的时候，自己不也是想通过代理ip来快速获得免费的数据吗？


2017-11-19 14:04 GMT+08:00 zj liang <zjliangcn@gmail.com>:

**Comment by clockzhong** [comment]
对不起，如果你觉得我是在嘲讽你，那我收回我的说法。建议是别人的，选择是自己的。
