### ISSUE TITLE
get_h_data 部分股票代码返回HTTP Error 456

### ISSUE THREAD

**Issue by happy6666** [waditu/tushare#451]
```
import tushare
tushare.get_h_data('603776',autype=None,start='2017-08-17',end='2017-08-17')
#正常
tushare.get_h_data('000678',autype=None,start='2017-08-17',end='2017-08-17')
#报错
```
返回HTTP Error 456
tushare 版本 0.8.0
请问是什么原因？

**Comment by pyzhangxiang** [comment]
我也一样，这几天都这样，升级了新版本还是这样

**Comment by jimmysoa** [comment]
数据源最近可能做了限制，再想想办法看

**Comment by jzlikewei** [comment]
应该是user-agent 的问题，我创建了一个pull requests 应该解决这个问题了 [https://github.com/waditu/tushare/pull/452](https://github.com/waditu/tushare/pull/452)
欢迎去[https://github.com/jzlikewei/tushare](https://github.com/jzlikewei/tushare) 试用一下

**Comment by YangJunTao** [comment]
楼上的，No module named lxml.html  是怎么回事啊

**Comment by markovyao** [comment]
@jzlikewei    多谢，你的方案可行，但是还是会出现HTTP Error 456，应该是sina封锁爬虫

**Comment by jzlikewei** [comment]
@markovyao 尝试着增加一下请求间隔吧，如果数据量大的话，可能还是要考虑增加IP代理

**Comment by happy6666** [comment]
还可以捕捉下IOError 暂停10分钟后再继续调用就正常了，应该就是数据源限制

**Comment by clockzhong** [comment]
没戏了，新浪封机器爬虫了。如果我要是提供一个付费服务，你们会使用吗？一个月多少钱可以接受？
