### ISSUE TITLE
get_report_data的历史数据存在缺失和重复问题

### ISSUE THREAD

**Issue by rexuedeliulianjun** [waditu/tushare#460]
开发者您好，昨天在用get_report_data(2017,1)取一季度财务报表的时候，发现返回的数据很多duplicate。drop以后发现只剩下2000多行数据，即只有2000多只股票有一季报，考虑到两市3000多只股票，相当于其中大量数据丢失了。个人猜测bug的出现可能是因为这些重复数据的问题。希望能够得到解决，谢谢！
附上代码：
import tushare as ts
df3=ts.get_report_data(2017,1)
df4=ts.get_report_data(2017,2)
df3=df3.drop_duplicates()
df4=df4.drop_duplicates()
df3.to_excel(r'c:\report2017_1.xlsx')
df4.to_excel(r'c:\report2017_2.xlsx')

**Comment by jimmysoa** [comment]
收到，搞定了再发布。

**Comment by shaolinbit** [comment]
是的，我看epcf很多股票都是读取不到的，不知道咋回事，但是通过同花顺等炒股软件可以看到

**Comment by hj2016** [comment]
中报获取去重后还有两个不一样的数据，更新的是最新0.9.2版本
319,603716,塞力斯,0.73,-23.16,,4.31,,3712.85,2.72,10转4,08-30,2017-2
485,603716,塞力斯,0.73,-23.16,,4.31,,3712.85,2.72,,08-30,2017-2

**Comment by rebuca** [comment]
开发者您好，0.9.9版本上此问题依然存在。一分钟内先后两次调用get_report_data(2015,4)，返回的数据不一致。
