### ISSUE TITLE
get_k_data取数据传入日期，取不到当天

### ISSUE THREAD

**Issue by KingCrab1990** [waditu/tushare#462]
ts.get_k_data(‘000001’, start=‘2017-09-01’, end=‘2017-09-05’)，取到的09-01和09-04的数据，end换成‘2017-09-06’结果一样，如果改成ts.get_k_data(‘000001’) 数据最后一条是09-05的数据。代码运行时间：2017-09-05 15:34:00

**Comment by smallevil** [comment]
我也遇到这个问题了.

写日期,是取不到的.必须等到过完夜里12点才行.马上就可以取到了.
取周也是一样,写当天的,仔细对比后,发现还是前一天的,必须过完12点.

另外,如果类型取的是60分钟的,那就没问题了.可以取到当天的.

**Comment by jimmysoa** [comment]
升级到最新版0.9.8,可以用ts.bar获得更稳定的数据

**Comment by smallevil** [comment]
ts.bar是什么接口??
没看到文档里有呀

**Comment by jimmysoa** [comment]
请看“挖地兔”公众号里的文章

**Comment by arisliang** [comment]
请问在哪篇文章有?
