### ISSUE TITLE
install tushare in leancloud console errors

### ISSUE THREAD

**Issue by poetlife** [waditu/tushare#471]
`The command '/bin/sh -c /opt/pyenv/shims/pip install
-r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple' returned a non-zero code: 1:
Requirement already satisfied: gevent<2.0.0,>=1.0.2 in /opt/pyenv/versions/3.6.1/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: gevent-websocket<1.0.0,>=0.9.5 in /opt/pyenv/versions/3.6.1/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Collecting leancloud<3.0.0,>=2.0.0 (from -r requirements.txt (line 3))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/14/65/3c4a6064c46f2387491de50187e85fd33c417ebd9f923971b9fd048273bf/leancloud-2.0.0.tar.gz
Collecting Werkzeug<1.0.0,>=0.11.11 (from -r requirements.txt (line 4))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/97/02/306e0d57fdbf467ec1c763bc1757ec6ba20b1332e0ea7e49111533d71d1c/Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
Collecting Flask<1.0.0,>=0.10.2 (from -r requirements.txt (line 5))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/77/32/e3597cb19ffffe724ad4bf0beca4153419918e7fa4ba6a34b04ee4da3371/Flask-0.12.2-py2.py3-none-any.whl (83kB)
Collecting Flask-Sockets<1.0,>=0.1 (from -r requirements.txt (line 6))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/62/a1/2295e41c32f591093cce519282ceeb6a968945bf497faa83a124e206aa26/Flask_Sockets-0.2.1-py2.py3-none-any.whl
Collecting lxml==3.8.0 (from -r requirements.txt (line 7))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0a/75/d54af657adc8625aa950ae7be4e4f33ef2b5014380556790fc6c7b7d095d/lxml-3.8.0-cp36-cp36m-manylinux1_x86_64.whl (7.3MB)
Collecting beautifulsoup4==4.6.0 (from -r requirements.txt (line 8))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
Collecting Flask-Bootstrap==3.3.7.1 (from -r requirements.txt (line 9))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/53/958ce7c2aa26280b7fd7f3eecbf13053f1302ee2acb1db58ef32e1c23c2a/Flask-Bootstrap-3.3.7.1.tar.gz (456kB)
Collecting Flask-Login==0.4.0 (from -r requirements.txt (line 10))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5a/14/364597ec0dd5490eb4443adae60b35088a6b7d466a9f7c8dacbe259477b5/Flask_Login-0.4.0-py2.py3-none-any.whl
Collecting tushare==0.8.6 (from -r requirements.txt (line 11))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/77/d6/904b4852d22085401776ad42c95e4179786d0483cc2b6c418bc0040ce040/tushare-0.8.6.tar.gz (97kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p6ksb_tt/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-build-p6ksb_tt/tushare/tushare/__init__.py", line 6, in <module>
        from tushare.stock.trading import (get_hist_data, get_tick_data,
      File "/tmp/pip-build-p6ksb_tt/tushare/tushare/stock/trading.py", line 13,
in <module>
        import lxml.html
    ModuleNotFoundError: No module named 'lxml'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-p6ksb_tt/tushare/`

**Comment by jimmysoa** [comment]
pip install lxml

**Comment by poetlife** [comment]
Actually I install lxml first .
and BS4 works well in the platform.
so I mean: the problem may be the setup.py
`import tushare`
