### ISSUE TITLE
ts.get_hist_data 是否可以增加MA60的数据？

### ISSUE THREAD

**Issue by MickyLam21** [waditu/tushare#479]
现在ts.get_hist_data只能抓取到MA5/MA10/MA20的数据，能否增添MA60的数据？

**Comment by jimmysoa** [comment]
可以自己添加，tushare提供了MA函数，或者用新街口ts.bar，支持任意ma频度

**Comment by jimmysoa** [comment]
@ilaowu 先要建立连接 ，ts.get_apis()
