### ISSUE TITLE
get_stock_basics() 最近返回403 forbidden错误

### ISSUE THREAD

**Issue by lynic** [waditu/tushare#48]
/usr/lib64/python2.7/urllib2.pyc in _call_chain(self, chain, kind, meth_name, _args)
    380             func = getattr(handler, meth_name)
    381 
--> 382             result = func(_args)
    383             if result is not None:
    384                 return result

/usr/lib64/python2.7/urllib2.pyc in http_error_default(self, req, fp, code, msg, hdrs)
    529 class HTTPDefaultErrorHandler(BaseHandler):
    530     def http_error_default(self, req, fp, code, msg, hdrs):
--> 531         raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    532 
    533 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

**Comment by yankuangshi** [comment]
今天我也测试了`get_stock_basics`函数，同样返回错误信息403 forbidden。查了在线文档，说是以读取`data/all.csv`文件来实现的，但是我在`data`文件夹里面并没有找到csv文件（没有发现任何默认文件），不知道该错误是否由这个所引起的。

**Comment by jimmysoa** [comment]
这个接口今天中午的时候关闭了，购买了阿里的OSS服务，但是最近老有恶意调用的，而阿里又不做限制，造成了费用很快被用完。

**Comment by yankuangshi** [comment]
@jimmysoa 多谢! 请问那个csv更新频率如何？每天都会更新吗？

**Comment by jimmysoa** [comment]
基本上是，偶尔没空就晚几天，只要没有新股发行，影响都不是很大。

**Comment by yankuangshi** [comment]
@jimmysoa 多谢！
