### ISSUE TITLE
ts.bar() 返回的开盘等价格为字符串类型??

### ISSUE THREAD

**Issue by smallevil** [waditu/tushare#480]
我利用这个接口返回的数据类型是str
如果要用talib计算,还要再转成float64才行.

其他的接口都已经是float64了,这个是专门这样设计的??
是否可以直接返回float64类型的数据呢??

另外,我测试了一下,好像,只是好像,bar这个接口,比get_k_data这个要慢一点点.不知道是不是我的错觉.
我测试都是同样的得到从2017-01-01开始到当天的数据

**Comment by jimmysoa** [comment]
应该是要统一的，bar现在还不是正式发布，所以会做一些调整。响应慢一点确实有可能

**Comment by jimmysoa** [comment]
code       object
open      float64
close     float64
high      float64
low       float64
vol       float64
amount    float64
