### ISSUE TITLE
ts.bar 出现重复数据

### ISSUE THREAD

**Issue by smallevil** [waditu/tushare#482]
ts.bar('603186', end_date='2017-09-29', ktype='D', adj='qfq')
当使用这条语句时,2017-01-03出现了两条

但是
ts.bar('603186', end_date='2017-09-29', ktype='D')
这样的话,就没事,不会重复

**Comment by jimmysoa** [comment]
还能重现吗？我确认一下是否是复权的时候出现了重复

**Comment by jimmysoa** [comment]
我刚运行了几次都没有出现重复的

**Comment by smallevil** [comment]
不应该呀,我这边必现的问题,
就是我上边写的代码,完全复制运行就会出现.print后最后两行是重复的.
刚才又试了一下,还是这样,暂时只发现这一只股票这样
另外,已经确定版本是最新的了.

上传几次截图都上完失败.
我放七牛了.
你看一下我的截图吧.

http://7rflim.com1.z0.glb.clouddn.com/603186.jpg

**Comment by jimmysoa** [comment]
测试几次无法重现
