### ISSUE TITLE
get_day_all 数据问题

### ISSUE THREAD

**Issue by 1987zfp** [waditu/tushare#484]
版本0.9.2
# code, name, date, open, close, high, low, volume, pre_close, cp
'603999', '读者传媒', '2017-08-30', '0', '10.16', '0', '0', '0', '10.16', '0.00'
当天并没有停牌

这类缺失的问题数据很多
# date, count(0)
'2017-07-03', '280'
'2017-07-04', '280'
'2017-07-05', '277'
'2017-07-06', '280'
......
'2017-09-04', '305'
'2017-09-05', '362'
'2017-09-06', '425'
'2017-09-07', '428'
'2017-09-08', '480'
'2017-09-11', '501'
'2017-09-12', '517'
'2017-09-13', '526'
'2017-09-14', '531'
'2017-09-15', '562'
'2017-09-18', '580'
'2017-09-19', '244'
'2017-09-20', '316'
'2017-09-21', '588'
'2017-09-22', '472'
'2017-09-25', '229'
'2017-09-26', '223'
'2017-09-27', '227'
'2017-09-28', '226'
'2017-09-29', '737'

对比 http://www.iwencai.com 搜 停牌状态，数量上差别较大，一般平均每日停牌的是200多
300以上的应该是有问题的，csv文件里面已经缺失了
希望能看看

**Comment by jimmysoa** [comment]
这个问题是之前导出的时候服务器的问题，后来的数据好很多。
