### ISSUE TITLE
关于新接口ts.bar中 adj='qfq'的问题

### ISSUE THREAD

**Issue by smallevil** [waditu/tushare#490]
下午3点收盘后,
ts.bar('300153', ktype='30min', adj='qfq')
如果运行这个,会报错
如果去掉adj参数,就会显示出来了,而且当天的都有数据

ts.bar('300153', ktype='D', adj='qfq')
如果运行这个,
只能显示到前一天,
但去掉adj参数,则可以把当天的显示出来.

这个前复权的参数,要怎么用?
或者说,几点之后才能用??

**Comment by jimmysoa** [comment]
下午5点多吧

**Comment by smallevil** [comment]
这个时间还能提前么??
不复权的话,收盘后马上就可以拿到了.
但是复权就等有点久了,这样我自己的一些计算操作,都要往后推两个小时才能开始.
:(

**Comment by jimmysoa** [comment]
不复权应该没问题

**Comment by smallevil** [comment]
不复权是没问题,
但是,因为不复权,当遇到派发之类的造成价格具大波动时,所有指标参数就全都没法看了.

**Comment by zengyee** [comment]
哪有关于 ts.bar() 的文档或代码？

**Comment by jimmysoa** [comment]
@smallevil当日的复权数据要收盘后5点左右才能，可以设置end_date小于今日
