### ISSUE TITLE
ts.bar对于停盘股票的数据有问题

### ISSUE THREAD

**Issue by smallevil** [waditu/tushare#494]
000806
这支股票
已经停了2个月了.
但是,每天用ts.bar得到时,都会有一个当日数据,而这个当日数据与停盘前一天的数据完全一样,成交量和金额不同.然后等第二天时,就又变成第二天的日期了.

**Comment by jimmysoa** [comment]
是的,停牌的股票就是这个情况,暂时还没有别的办法.
