### ISSUE TITLE
bar与get_k_data速度对比

### ISSUE THREAD

**Issue by smallevil** [waditu/tushare#495]
ts.bar('', ktype='30min', start_date='')[::-1]
ts.get_k_data('', ktype='30', start='')

190个股票循环一遍

get_k_date用时15秒
bar用时427秒

瞬间无爱了
:(

不知道是不是因为bar接口还没正式发布,优化还没到位??
bar很好用,特别是开盘能显示当天数据,很爽,不过有点太慢了.

**Comment by jimmysoa** [comment]
这个版本属于测试性质, 还没有考虑性能,等正式发布
