### ISSUE TITLE
如何获取市值？

### ISSUE THREAD

**Issue by Hobart-Liu** [waditu/tushare#497]
请教一下，如果获取股票的历史市值？

**Comment by jimmysoa** [comment]
get_today_all

**Comment by Hobart-Liu** [comment]
jimmy, 比如我要取2年前的市值，若该股票有过转增，增发，计算市值好像缺少点数据。

**Comment by jimmysoa** [comment]
市值按流通市值和总市值来提供，你要自己单独计算？

**Comment by Hobart-Liu** [comment]
哦，当然不希望自己计算。我想了解的是当日交易的股票数目占流通总股票数目的百分比。好像目前只有自己算。所以问到历史市值。当日交易的股票数目是可以通过volume获取，但是当日的总流通数目好像不知道。

**Comment by jimmysoa** [comment]
get_stock_basic里有
