### ISSUE TITLE
请教能否获得历史每天的市盈率和市净率

### ISSUE THREAD

**Issue by DBDB666** [waditu/tushare#498]
请教能否获得历史每天的市盈率和市净率，或者还是需要结合报表的数据自己算？

**Comment by jimmysoa** [comment]
get_stock_basics，通过设置date参数

**Comment by williamjie** [comment]
df = ts.get_stock_basics()
		pe = df.ix['000776']['pe']
		pb = df.ix['000776']['pb']
		xxx= df.ix['000776']['20170508']
		print 'GetPEPB pe:',pe,' pb:',pb,' xxx:',xxx

报错误KeyError: '20170508' ，是否最新接口不支持获取时间呢；

df.ix['000776']获取到的内容
GetPEPB xy: name                       广发证券
industry                     证券
area                         广东
pe                        15.78
outstanding               59.19
totals                    76.21
totalAssets         3.62411e+07
liquidAssets                  0
fixedAssets             84083.4
reserved            3.18641e+06
reservedPerShare           4.18
esp                       0.835
bvps                      10.97
pb                          1.6
timeToMarket           19970611
undp                2.56337e+06
perundp                    3.36
rev                       -2.07
profit                     2.95
gpr                           0
npr                        42.8
holders                  147318

**Comment by jimmysoa** [comment]
YYYY-MM-DD格式，后面我改一下代码，两种格式都支持吧
