### ISSUE TITLE
ts.bar() 返回「服务器连接为空，请通过ts.get_apis()获取」

### ISSUE THREAD

**Issue by park** [waditu/tushare#499]
ts.bar() 返回
`服务器连接为空，请通过ts.get_apis()获取`

**Comment by jimmysoa** [comment]
先通过ts.get_apis()获取

**Comment by park** [comment]
调用 ts.get_apis()，报错
`AttributeError: module 'tushare' has no attribute 'get_apis'`

**Comment by jimmysoa** [comment]
@park 还没升级,我再发一版就好了

**Comment by zengyee** [comment]
怎么通过 ts.get_apis()获取 ？
