### ISSUE TITLE
get_profit_data returns nothing

### ISSUE THREAD

**Issue by zxdvd** [waditu/tushare#5]
I found that get_profit_data only returns column titles.
It seems that "html = lxml.html.parse(url)" in "_get_profit_data" doesn't get the full cotent of page. And it triggered a excetion.
**Simple test**
    url = 'http://vip.stock.finance.sina.com.cn/q/go.php/vFinanceAnalyze/kind/profit/index.phtml?s_i=&s_a=&s_c=&reportdate=2014&quarter=1&p=29&num=60'
    html = lxml.html.parse(url)
    xtrs = html.xpath("//table[@class=\"list_table\"]/tr")
    for trs in xtrs:
        code = trs.xpath('td[1]/a/text()')[0]
        name = trs.xpath('td[2]/a/text()')[0]
        roe = trs.xpath('td[3]/text()')
        print(code, name, roe)

And I could escape this by get the content via requests.get and then use lxml parse it.

**Comment by jimmysoa** [comment]
Actually,I changed the function get_profit_data to profit_data in reference.py file, and this API doesn't release yet, you can  have a glance at  https://github.com/waditu/tushare/blob/master/tushare/stock/reference.py

**Comment by ideaplat** [comment]
pic_fun.py
Traceback (most recent call last):
  File "E:/github/tushare/tushare/util/pic_fun.py", line 81, in <module>
    pic_cvt()
  File "E:/github/tushare/tushare/util/pic_fun.py", line 72, in pic_cvt
    stderr=subprocess.STDOUT)
  File "D:\python\lib\subprocess.py", line 710, in __init__
    errread, errwrite)

**Comment by jimmysoa** [comment]
You can remove this file from the package.

**Comment by ideaplat** [comment]
i need this file to get some data
