### ISSUE TITLE
写到MySQL报1170错误

### ISSUE THREAD

**Issue by fly2win2015** [waditu/tushare#50]
这几天试了一下，将数据获取后逐一写到本地数据库，有发现部分数据会报错，不晓得大家有没有遇到。
举个例子：
df = ts.get_stock_basics() #获取所有股票列表
将这个数据写到数据库时，运行时错误代码：
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'code' used in key specification without a key length") [SQL: u'CREATE INDEX ix_hist5_code ON hist5 (code)']

在抓取
df = ts.get_index() #大盘行情 
这个不报错

平台 OSX 10.10.4 Python:2.7 MYSQL:5.6.26

**Comment by mxcanfly** [comment]
自己手动往表里加个自增主键试试

**Comment by cxfksword** [comment]
sqlalchemy导入mysql生成的text类型不支持索引导致的，导入前重置下索引就可以了
```
df = df.reset_index()
```

**Comment by fly2win2015** [comment]
谢谢 @cxfksword 

搞定了

**Comment by MagicWeirdo** [comment]
@cxfksword 我的没用是怎么回事？
