### ISSUE TITLE
ts.get_hist_data('600848',ktype='W')   ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by CoderDream** [waditu/tushare#500]
> ts.get_hist_data('600848',ktype='W')

获取周k线数据 , 抛错：

版本：
> 
C:\Users\Admin>pip list
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
bs4 (0.0.1)
certifi (2017.7.27.1)
chardet (3.0.4)
colorama (0.3.9)
decorator (4.1.2)
Django (1.11.6)
enum34 (1.1.6)
idna (2.6)
ipython (5.5.0)
ipython-genutils (0.2.0)
lxml (4.1.0)
numpy (1.13.3)
pandas (0.20.3)
pathlib2 (2.3.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
Pygments (2.2.0)
python-dateutil (2.6.1)
pytz (2017.2)
requests (2.18.4)
scandir (1.6)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.11.0)
traitlets (4.3.2)
tushare (0.9.9)
urllib3 (1.22)
wcwidth (0.1.7)
wheel (0.30.0)
win-unicode-console (0.5)

> Traceback

 (most recent call last):
  File "D:\Java\GitHub\tushare_demo\tushare_demo\__init__.py", line 46, in <module>
    ts.get_hist_data('600848',ktype='W') 
  File "D:\Python27\lib\site-packages\tushare\stock\trading.py", line 74, in get_hist_data
    js = json.loads(lines.decode('utf-8') if ct.PY3 else lines)
  File "D:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ichao1214** [comment]
这里是应该是没有获取到数据，和 ifeng 网站访问状态有关。600848 上市至今有一千多条周线数据，可以缩小时间跨度获取。

**Comment by CoderDream** [comment]
公司有上网策略，有些网站不能访问；

很奇怪的是：
ts.get_realtime_quotes(STOCK) 访问正常
ts.get_hist_data(STOCK) 访问失败

难道这两个方法访问的是不同的网站？

**Comment by jimmysoa** [comment]
是的，不同的网站
