### ISSUE TITLE
能否读取全球指数，比如德国指数

### ISSUE THREAD

**Issue by lightjl** [waditu/tushare#501]
`ts.get_hist_data('DAX30')` 或 `ts.get_hist_data('GDAXI')` 均读不出来
[德国DAX30(GDAXI)](http://quote.eastmoney.com/gb/zsDAX.html)
请问怎么读取全球指数指标？

**Comment by jimmysoa** [comment]
暂时还没有，以后可以加上

**Comment by park** [comment]
@lightjl 
这个可以通过quandl实现，很多指数都是免费的

**Comment by jimmysoa** [comment]
@park 赞
