### ISSUE TITLE
关于ts.get_k_data有start参数时不能返回当天数据的问题。

### ISSUE THREAD

**Issue by Statham-stone** [waditu/tushare#503]
print ts.get_k_data("000001").tail()
print ts.get_k_data("000001",start="2017-10-22")

结果

           date   open  close   high    low     volume    code
636  2017-10-20  11.59  11.48  11.59  11.41   461808.0  000001
637  2017-10-23  11.39  11.19  11.40  11.15  1074465.0  000001
638  2017-10-24  11.20  11.39  11.42  11.18   618871.0  000001
639  2017-10-25  11.36  11.27  11.37  11.25   418573.0  000001
640  2017-10-26  11.25  11.18  11.32  11.12   928996.0  000001
           date   open  close   high    low     volume    code
194  2017-10-23  11.39  11.19  11.40  11.15  1074465.0  000001
195  2017-10-24  11.20  11.39  11.42  11.18   618871.0  000001
196  2017-10-25  11.36  11.27  11.37  11.25   418573.0  000001

可以看出，第二个结果中，并没有10月26日的数据

**Comment by xirain** [comment]
我这边也是一样的。
如果默认的话，可以获取全部的 包含当天的
如果加上时间的话，当天的就拿不到

**Comment by jimmysoa** [comment]
建议用ts.bar
