### ISSUE TITLE
【疑问】bar接口中，股票代码超过6位的时候会自动截取前6位数字的设计不知是否合理？

### ISSUE THREAD

**Issue by OneGIl** [waditu/tushare#508]
比如股票代码是6000185（手抖多打了个0），tushare会自动查询600018这支股票的数据。
不知道这么设计的优点是什么？ 不应该是直接报错才对吗？ 纯疑问，bar接口的出现实在太棒了！

**Comment by jimmysoa** [comment]
纯属巧合
