### ISSUE TITLE
【疑问】有关ts.is_holiday()函数中，数据源更新及时性的问题。

### ISSUE THREAD

**Issue by OneGIl** [waditu/tushare#509]
无聊翻了翻代码，发现了这个函数，而且对于自动化更新数据是非常有用的，但发现里面的数据源来自tushare官网的静态文件（？ 我瞎猜是静态文件）。 不知道这个文件是手动更新的还是通过程序自动拉取的？ 如果是手动更新的话，会不会出现时及时性的问题？比如明年1月1日的时候，程序是否能正确判断交易日。

嗯，就这个疑问。
最后，感谢tushare！

**Comment by ichao1214** [comment]
一般做法是国务院每年年底出下一年的节假日安排，接着交易所就会出下一年的交易日，这个时效性基本不用考虑

**Comment by jimmysoa** [comment]
如@ichao1214 所讲，正解。
