### ISSUE TITLE
遇到的2个问题，一个是新接口，无法断连，一个是大单数据的问题。麻烦有空处理下，谢谢。

### ISSUE THREAD

**Issue by hardy110** [waditu/tushare#511]
1：新版本（1.0和1.1）接口，cons = ts.get_apis()，是长连接，只要一调用，就无法正常关闭程序。需要强制kill程序。
2：get_sina_dd 函数获取大单数据有重复现象，麻烦查下原因。
参考示例：
stock是300706 ，日期是'2017-11-03'，获取的数据中 09:35的数据明显重复了。
>>> df3 = ts.get_sina_dd(stock, date=date, vol=vol)
>>> df3[df3.time=='09:35:09']
       code name      time  price  volume  preprice type
216  300706  阿石创  09:35:09  79.98   14000     79.69   买盘
217  300706  阿石创  09:35:09  79.98   14000     79.69   买盘

**Comment by jimmysoa** [comment]
假设是循环取数据所设置，后面版本我加一个退出属性吧。

**Comment by williamjie** [comment]
无法退出这问题，程序“kill -9 pid ” 即可。

**Comment by jimmysoa** [comment]
新版已经增加了关闭功能， ts.close_apis(cons)
