### ISSUE TITLE
分红数据查询

### ISSUE THREAD

**Issue by xheke** [waditu/tushare#513]
1，
分红数据怎么查询？

0.8.8 2017/08/29
    新增分红送股数据（包含历史）

2，
接口 profit_data 返回错误：

[Getting data:]Error reading file 'http://quotes.money.163.com/data/caibao/fpyg.html?reportdate=2017&sort=declaredate&order=desc&page=0': failed to load external entity "http://quotes.money.163.com/data/caibao/fpyg.html?reportdate=2017&sort=declaredate&order=desc&page=0"
Error reading file 'http://quotes.money.163.com/data/caibao/fpyg.html?reportdate=2017&sort=declaredate&order=desc&page=0': failed to load external entity "http://quotes.money.163.com/data/caibao/fpyg.html?reportdate=2017&sort=declaredate&order=desc&page=0"
Error reading file 'http://quotes.money.163.com/data/caibao/fpyg.html?reportdate=2017&sort=declaredate&order=desc&page=0': failed to load external entity "http://quotes.money.163.com/data/caibao/fpyg.html?reportdate=2017&sort=declaredate&order=desc&page=0"
Traceback (most recent call last):
  File "D:/python-prj/www/finsina.py", line 21, in <module>
    df = ts.profit_data(top=60, year=2017)
  File "C:\Users\kehe\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\reference.py", line 66, in profit_data
    df, pages = _dist_cotent(year, 0, retry_count, pause)
  File "C:\Users\kehe\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\reference.py", line 153, in _dist_cotent
    raise IOError(ct.NETWORK_URL_ERROR_MSG)    
OSError: 获取失败，请检查网络.

**Comment by jimmysoa** [comment]
1、profit_divis
2、这个问题不知道是不是python版本问题，请在python2.7下试试
