### ISSUE TITLE
why con?

### ISSUE THREAD

**Issue by Hobart-Liu** [waditu/tushare#520]
May I know why new interface introduced a new element ts.get_apis()?
Does that mean we can set different attribute on connections, like proxy?

**Comment by Hobart-Liu** [comment]
另外，如果频繁申请get_apis()有问题吗？

**Comment by YourDaddyIsHere** [comment]
其实我觉得频繁申请啥都会有问题...会被ban IP

**Comment by Hobart-Liu** [comment]
所以想搞明白这个get_api()是干嘛用的，如果需要全局唯一，也是可以的，否则就用的时候申请一个。 目前我在做调试的时候常常发现退不干净，是不是因为没又释放这个conn? python 没有显式的释放，tushare 貌似也没又提供释放的命令。。。

**Comment by jimmysoa** [comment]
全局使用，不要重复连接。

**Comment by Hobart-Liu** [comment]
现在碰到问题，一旦申请，如果python 程序结束，这个连接也不退出

**Comment by Hobart-Liu** [comment]
貌似网络一旦出了故障，该链接可能无法自我修复
