### ISSUE TITLE
600559前复权日线周线数据，返回数据值错误

### ISSUE THREAD

**Issue by xinqianli** [waditu/tushare#528]
get_k_data和get_hist_data默认获取600559老白干酒，2015-06-26 high_price:58.725

58.725不对，既不是前复权数据，也不是不复权数据。

通达信上前复权为39.53，不复权为99.49

代码：
<pre>
        code = '600599'
        dt = ts.get_k_data(code, ktype='W', autype='qfq', start='2015-06-01')
        if dt is not None:
            dt.to_csv('./data/' + code + '.tsv', sep='\t', encoding='utf-8')
</pre>
返回数据：
[600599.txt](https://github.com/waditu/tushare/files/1484725/600599.txt)

**Comment by pakchoiko** [comment]
复权的开始日期不同呗

**Comment by jimmysoa** [comment]
尝试用ts.bar接口来对比，更wind数据一致
