### ISSUE TITLE
bar获取分钟数据每次都不一样？

### ISSUE THREAD

**Issue by ghhhfq** [waditu/tushare#529]
使用
ts.bar('000001', cons, start_date='2017-11-16', end_date='2017-11-17', freq='5min', asset='E', adj=None, retry_count=5)
获取5分钟数据时，发现每次获取的都有不一样的地方，
例如，下面分别是9次调用上面语句得到第一行数据，其中只有两次一样，其它都不一样：
#2017-11-17 15:00:00 	000001 	13.17 	13.18 	13.18 	13.15 	41202.0 	54285568.0
#2017-11-17 15:00:00 	000001 	13.17 	13.18 	13.18 	13.15 	44571.0 	58720768.0      
#2017-11-17 15:00:00 	000001 	13.17 	13.18 	13.18 	13.15 	44236.0 	58279680.0
#2017-11-17 15:00:00 	000001 	13.18 	13.18 	13.18 	13.15 	42242.0 	55655424.0
#2017-11-17 15:00:00 	000001 	13.17 	13.18 	13.18 	13.15 	44236.0 	58279680.0
#2017-11-17 15:00:00 	000001 	13.16 	13.18 	13.18 	13.15 	43943.0 	57894144.0
#2017-11-17 15:00:00 	000001 	13.16 	13.18 	13.18 	13.15 	43943.0 	57894144.0
#2017-11-17 15:00:00 	000001 	13.16 	13.18 	13.18 	13.15 	44492.0 	58616832.0
#2017-11-17 15:00:00 	000001 	13.17 	13.18 	13.18 	13.15 	44236.0 	58279680.0
获取1，15，30，60分钟也有类似的情况
版本信息：
Python 3.6.3
pandas version: 0.21.0
tushare version: 1.0.4
请看看是什么问题？ 谢谢！

**Comment by jimmysoa** [comment]
还能重现吗？我测试了几次都是正常的

**Comment by ghhhfq** [comment]
可以重现
每次调用bar前，如果都调用了cons = ts.get_apis()，会有这个问题
如果只调用一次cons = ts.get_apis()，好像是正常的
![stock_test](https://user-images.githubusercontent.com/22128489/33007955-f7223c82-ce0b-11e7-8353-cf48aec60756.png)
![stock_test1](https://user-images.githubusercontent.com/22128489/33007963-fca09618-ce0b-11e7-8c69-f717c167be44.png)

**Comment by jimmysoa** [comment]
本来就不应该每次都创建连接

**Comment by ghhhfq** [comment]
在一个程序里获取数据时，确实只应该创建一次连接
但一个程序在不同时间时，被多次运行来获取了数据，就相当于上面的情况了，会导致比如今天和昨天，或者上午和下午，分别运行同一个程序获取到的5min数据有不一样
