### ISSUE TITLE
002839 数据有误

### ISSUE THREAD

**Issue by dongtianyi** [waditu/tushare#530]
![image](https://user-images.githubusercontent.com/2805621/33002756-26bd517c-cdf1-11e7-98cd-adab0a95c8ae.png)
![image](https://user-images.githubusercontent.com/2805621/33002781-46c32384-cdf1-11e7-88b0-96ed61216747.png)
整个数据感觉都不太对.

**Comment by jimmysoa** [comment]
再找一个数据源对比，或者你用ts.bar接口

**Comment by dongtianyi** [comment]
用 ts.bar接口试了一下, 是正确的. 
ts.bar的使用文档, 在那里?
我是连蒙带猜的试了一下 😓

**Comment by jimmysoa** [comment]
目前发在公众号“挖地兔”里的，以后会发布新的网页
