### ISSUE TITLE
使用pip install Tushare 安装，无法import

### ISSUE THREAD

**Issue by hfghgakjd** [waditu/tushare#537]
这是什么原因？有人能帮忙解决一下吗？

**Comment by jialin1981** [comment]
你看看是不是你系统环境的问题，我也遇到过此问题，我当时在macOS下之前那了2.X和3.X的python，后来又装了anaconda，Anaconda自带一套Python，结果我在系统2.X下pip安装的就不能用。希望对你有帮助！

**Comment by jimmysoa** [comment]
如果安装成功了，应该就是环境变量的问题，没找对Python环境。
