### ISSUE TITLE
您好，get_k_data 时间参数没传进去

### ISSUE THREAD

**Issue by mcze333** [waditu/tushare#540]
您好，get_k_data函数调用并打印如下：
        sxdata = ts.get_k_data(code,start='2017-05-01',end='2017-11-29',ktype='60')
	print(sxdata)

结果显示起始日期是2017-06-05，结束日期是2017-12-04（昨日），如附件
![1](https://user-images.githubusercontent.com/23115165/33589942-ea1b7dc6-d9b6-11e7-8b00-fa0b4b1d8563.PNG)
![2](https://user-images.githubusercontent.com/23115165/33589947-efb64e5a-d9b6-11e7-88c8-116cb19431b3.PNG)

**Comment by jimmysoa** [comment]
分钟数据只有最近两周的，建议用ts.bar
