### ISSUE TITLE
请问是否有期货品种指数数据？

### ISSUE THREAD

**Issue by jianfly** [waditu/tushare#542]
请问是否有期货品种指数数据？

**Comment by jimmysoa** [comment]
有的，比如RBL9

**Comment by super-wcg** [comment]
你好，请问铜的指数数据的symbol字符串是什么？

**Comment by super-wcg** [comment]
@jimmysoa

**Comment by jianfly** [comment]
应该是CUL9

**Comment by super-wcg** [comment]
@jimmysoa 在获取期货数据时，报错如下：Traceback (most recent call last):
  File "C:/Users/Changgang/PycharmProjects/untitled1/test.py", line 48, in <module>
    df = ts.bar('CUL9', conn=ts.get_apis(), start_date='2017-10-20', end_date='2018-01-18', freq='1M', asset='X')
  File "D:\Anaconda2\lib\site-packages\tushare\stock\trading.py", line 1030, in bar
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
IOError: 获取失败，请检查网络.
这是什么原因

**Comment by jianfly** [comment]
我是可以的，你看下tushare的版本升级了没，然后获取的时候有时候是会连接不是，多刷几次就有了。另外你可以换日线试试有没有问题

**Comment by jimmysoa** [comment]
1min not 1M
