### ISSUE TITLE
ts.bar()取A股后复权数据出现month must be in 1..12错误

### ISSUE THREAD

**Issue by lushengsheng** [waditu/tushare#544]
引起错误的个股是：600664,600665

重现：
>>> df=ts.bar('600665',conn=cc)
month must be in 1..12
month must be in 1..12
month must be in 1..12
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\tushare\stock\trading.py", line 928, in bar
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络.

**Comment by jimmysoa** [comment]
这个问题我先关了，跟你问的另外一个问题应该是同一原因

**Comment by Earthson** [comment]
应该是某些行情服务器的问题，换个服务器可能就是正常的

**Comment by shiquanwang** [comment]
我也在使用bar接口获取600664,600665的日线数据时遇到同样的问题。
