### ISSUE TITLE
沪市B股获取出错

### ISSUE THREAD

**Issue by gclsoft** [waditu/tushare#55]
http://vip.stock.finance.sina.com.cn/corp/go.php/vMS_FuQuanMarketHistory/stockid/900901.phtml?year=2015&jidu=1
http://vip.stock.finance.sina.com.cn/corp/go.php/vMS_FuQuanMarketHistory/stockid/200418.phtml?year=2015&jidu=1
等等都出错了,当前价格为零点几,但复权价都几百的, 造成
`df = ts.get_h_data('900901', start='2015-08-01', end=endDate)` 在这里出错了:
`if ((float(rt['high']) == 0) & (float(rt['low']) == 0)):``

```
pydev debugger: starting
[Getting data:]Traceback (most recent call last):
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/pydevd.py", line 1479, in <module>
    debugger.run(setup['file'], None, None)
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/pydevd.py", line 1125, in run
    pydev_imports.execfile(file, globals, locals)  #execute the script
  File "/Users/apple/node/undo4096/tool/stock/winBuy.py", line 75, in <module>
    df = ts.get_h_data('900901', start='2015-08-01', end=endDate)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tushare-0.3.4-py2.7.egg/tushare/stock/trading.py", line 392, in get_h_data
    if ((float(rt['high']) == 0) & (float(rt['low']) == 0)):
TypeError: 'NoneType' object has no attribute '__getitem__'
```

但深市B股就ok, 要怎么解决?

**Comment by gclsoft** [comment]
def _code_to_symbol(code):
    """
        生成symbol代码标志
    """
    if code in ct.INDEX_LABELS:
        return ct.INDEX_LIST[code]
    else:
        if len(code) != 6 :
            return ''
        else:
            strs='sh%s'%code if code[:1] in ['9', '6'] else 'sz%s'%code
            #print strs
            return strs
是9 和6 吧

**Comment by emptist** [comment]
```
def _code_to_symbol(code):
    """
        生成symbol代码标志
    """
    if code in ct.INDEX_LABELS:
        return ct.INDEX_LIST[code]
    else:
        if len(code) != 6 :
            return ''
        else:
            return 'sh%s'%code if code[:1] in ['5', '6','9'] else 'sz%s'%code
```

**Comment by jimmysoa** [comment]
done.
