### ISSUE TITLE
get_hs300s()  等几个接口无法使用了

### ISSUE THREAD

**Issue by kanghua309** [waditu/tushare#551]
报错 <urlopen error ftp error: [Errno ftp error] 550 /webdata/000300closeweight.xls: No such file or directory.>
修复一下吧

**Comment by jimmysoa** [comment]
已修复

**Comment by pakchoiko** [comment]
兔哥真棒

**Comment by qixiang109** [comment]
又不行了。<urlopen error ftp error: [Errno ftp error] 550 /webdata/000300closeweight.xls: No such file or directory.>
是数据源换路径了吧？我自己从网页上下了这个文件没问题。

**Comment by jimmysoa** [comment]
tushare升级到最新版就好了
