### ISSUE TITLE
get_profit_data接口数据有重复

### ISSUE THREAD

**Issue by stocktest** [waditu/tushare#559]
In [2]: ts.__version__
Out[2]: '1.0.7'

In [3]:

In [3]: df = ts.get_profit_data(2016,4)
[Getting data:]##########################################################
In [4]: df.code[df.code.duplicated()]
Out[4]:
420     002285
1620    002822
1680    300515
1681    300089
1860    603030
1861    600026
2041    300041
2940    600527
Name: code, dtype: object

In [5]: df[df.code=='002285']
Out[5]:
       code name    roe  net_profit_ratio  gross_profit_rate  net_profits  \
419  002285  世联行  17.83             11.91            27.8315     747.2152
420  002285  世联行  17.83             11.91            27.8315     747.2152

        eps  business_income   bips
419  0.3653        6269.9213  3.066
420  0.3653        6269.9213  3.066

In [6]: df[df.code=='002822']
Out[6]:
        code  name   roe  net_profit_ratio  gross_profit_rate  net_profits  \
1619  002822  中装建设  8.07               5.8            16.1624     156.1832
1620  002822  中装建设  8.07               5.8            16.1624     156.1832

**Comment by JaysonAlbert** [comment]
基本面那几个都有问题，好像只有一个是没问题的。最近在换新接口了，新街口是没问题的，据说

**Comment by stocktest** [comment]
基本面新接口？哪个？出来了么

**Comment by JaysonAlbert** [comment]
据说在写新的tushare，还没有发布

**Comment by bombhero** [comment]
df = ts.get_profit_data(2016,4).drop_duplicates()
Above can solve your issue.

**Comment by xuyaoGitHub** [comment]
不光是重复数据的问题，好多股票数据缺失了。所以drop duplicates并不能解决

**Comment by jimmysoa** [comment]
等待新数据源吧
