### ISSUE TITLE
to_sql方法没有股票代码

### ISSUE THREAD

**Issue by lbp0200** [waditu/tushare#56]
我想把历史数据，报价及交易数据保存到数据库，发现报价保存是没有股票代码的，这样就无法区分具体是哪支股票的价格了

**Comment by beswarm** [comment]
daily_bars = ts.get_h_data(code,  retry_count=4, pause=30)
    if daily_bars is not None:
        daily_bars['code'] = np.repeat(code, len(daily_bars))
        daily_bars.to_sql('day_k_data', engine, index_label='date', if_exists='append')

**Comment by lbp0200** [comment]
非常感谢，我晚上试试。另我发现现在不能获取所有股票信息了，403forbidden，我还是另开一贴好了。
