### ISSUE TITLE
ts.get_hs300s() 无法使用

### ISSUE THREAD

**Issue by kanghua309** [waditu/tushare#560]
请修复一下吧

**Comment by qzm** [comment]
<img width="359" alt="screen shot 2017-12-21 at 11 52 54" src="https://user-images.githubusercontent.com/2801450/34239896-7f81a288-e645-11e7-933d-b1ea7cee1fc1.png">
一切正常，可以使用

**Comment by jimmysoa** [comment]
升级到最新版就可以了
