### ISSUE TITLE
urlopen error timed out

### ISSUE THREAD

**Issue by iorilu** [waditu/tushare#561]
现在很容易爆超时错啊, 你们怎么处理的, 如果大量更新数据
是get_k_data报错

**Comment by bombhero** [comment]
You can try to set retry_count more than 3. Such as
import tushare as ts
ts.get_k_data("000001", retry_count=10).

Another possibility is you call get_k_data in multi-process at the same time. Then the gtimg.cn might reject some requests if too many requests from the same IP address.

**Comment by iorilu** [comment]
@bombhero thanks , that's a way to solve this.
