### ISSUE TITLE
get_stock_basics() 的栏位 code有错位，放到了name上面

### ISSUE THREAD

**Issue by XH888** [waditu/tushare#563]

**Comment by bombhero** [comment]
Could you show more detail? I test it just now.

         name industry area      pe  outstanding  totals  totalAssets  \
code                                                                    
600025   华能水电     水力发电   云南   42.07        18.00  180.00  16657994.00   
600917   重庆燃气     供气供热   重庆   42.29        15.56   15.56    840338.88

**Comment by XH888** [comment]
我是搞错啦。就是介绍写的是code是名称。 用ts.get_stock_basics().index就好
