### ISSUE TITLE
关于获取A股实时数据,性能上的建议

### ISSUE THREAD

**Issue by CodeNewman** [waditu/tushare#566]
我看源码发现, tushare针对A股数据, 底层调用的是通达信的pytdx接口(https://github.com/rainx/pytdx)
每次传参, 获取数据条数默认800条, 是静态值. 这就导致, 当我们对实时响应性能有要求时, tushare返回数据会很慢, 例如, 我们只要2条数据, 然而tushare还是会先从pytdx获取800条数据, 然后将2条数据返回给我们.

建议, 将800静态值改成变量, 直接外部传参可配置. 这样当上层需要几条数据, 直接就从pythx中获取几条数据就可以了.

**Comment by jimmysoa** [comment]
建议很好
