### ISSUE TITLE
get_hist_data()  获取数据时有时候会丢失一段时间的数据

### ISSUE THREAD

**Issue by lemonaha** [waditu/tushare#574]
版本已经是最新的了
  
例如直接从2016年7月到2015年12月

  | 2016/7/8
  | 2016/7/7
  | 2016/7/6
  | 2016/7/5
  | 2016/7/4
  | 2015/12/21
  | 2015/12/18
  | 2015/12/17
  | 2015/12/16
  | 2015/12/15
  | 2015/12/14
  | 2015/12/11

**Comment by jimmysoa** [comment]
建议用ts.bar
