### ISSUE TITLE
能否提供每个报告期末的股本数据

### ISSUE THREAD

**Issue by euyuil** [waditu/tushare#586]
根据文档 http://tushare.org/fundamental.html 我可以通过 ts.get_stock_basics() 知道一个公司当前的总股本数和流通股本数，但实际上这个数据有可能会随报告期的变化而变动的。希望能够通过某个接口，获得报告期末的股本数。

**Comment by jimmysoa** [comment]
股权变动的历史，数据接口tushare已经有了，只是因为服务器压力暂时还没有公布，我们会择机发布，谢谢您。
