### ISSUE TITLE
get_day_all 数据缺失2017-06-23 的数据

### ISSUE THREAD

**Issue by fangwa** [waditu/tushare#587]
get_day_all 数据缺失2017-06-23 的数据，当天是交易日，调用返回HTTP Error 404: Not Found

**Comment by lightjl** [comment]
[等待新数据源吧](https://github.com/waditu/tushare/issues/559)

**Comment by jimmysoa** [comment]
谢谢，之前的数据还在补，这个接口从6月底才开始有数据的
