### ISSUE TITLE
创业板指 和 中小板指 获取数据的报错问题

### ISSUE THREAD

**Issue by GreadLoveJM** [waditu/tushare#589]
您好，我看了一下是cons.py 文件中的
第70行 FOR_CLASSIFY_B_COLS = ['date', 'code','name']静态变量的问题，
改成FOR_CLASSIFY_B_COLS = [ 'code','name']  在本地可以跑通了。
希望建议对您有用

**Comment by jimmysoa** [comment]
忘了发布到git了，已经在pypi上发布
