### ISSUE TITLE
OSError: 获取失败，请检查网络和URL  问题 

### ISSUE THREAD

**Issue by ecnuforever** [waditu/tushare#59]
版本：0.3.6
使用ts.get_hist_data('sh')
显示：<urlopen error timed out>
OSError: 获取失败，请检查网络和URL
网络应该是ok的，因为ts.get_today_all()等都能正常运作。

**Comment by jimmysoa** [comment]
凤凰财经的网络昨天有点不稳定

**Comment by FayolChang** [comment]
我也遇到了这个错误，尤其是不过是用的是 get_h_data 函数，当开始时间设置的比较早时，会遇到这个错误，如果取近期的则没有影响。
