### ISSUE TITLE
日行情里居然没有加一个昨日收盘价

### ISSUE THREAD

**Issue by beebon** [waditu/tushare#594]
除了日行情，其他周期行情里应该也没有前交易周期的收盘价，这样统计涨幅啥的也相当不方便哟，能否在新的接口上加上这个字段

**Comment by pakchoiko** [comment]
伪需求

**Comment by beebon** [comment]
数据库设计范式还有三种，适当的冗余一些字段谈不上什么伪需求，优矿的行情数据也是有的，简单说我要计算当天涨幅这个不算是伪需求吧，又或者有更快更好的办法可以计算该值

**Comment by lynink** [comment]
从数据方面来看 tushare只提供最原始的数据，当日的数据获取不可能包含前一日的数据.  扩展字段可以根据原始数据自行添加并计算，而不是加到底层库中

**Comment by jimmysoa** [comment]
有道理，但是满足用户需求的问题我们会好好考虑，谢谢各位。
