### ISSUE TITLE
tushare.get_latest_news() 函数中， 当返回数据中包含’=’， 数据处理出现问题

### ISSUE THREAD

**Issue by yxakuo** [waditu/tushare#598]
tushare.get_latest_news() 函数中， 当返回数据中包含’=’的时候， 数据处理会出现问题， 返回 EOL while scanning string literal 错误（在处理返回的字符串中，引号没有成对出现）， 这是因为返回的数据中包含了用于分割数据的‘=’
        data_str = urlopen(request, timeout=10).read()
        data_str = data_str.decode('GBK')
        data_str = data_str.split('=', **maxsplit=1**)[1][:-1]
这样处理可以应付这个问题

**Comment by yxakuo** [comment]
示例数据：
{channel : {title : "证券",id : "46",cType : "col",url : "http://finance.sina.com.cn/stock/index.shtml"},title : "最贵新股=最烂新股？养元饮品上市次日便跳水跌停",url : "http://finance.sina.com.cn/stock/s/2018-02-13/doc-ifyrpeie2522238.shtml",type : '1',pic : '',time : 1518500476}

**Comment by jimmysoa** [comment]
赞，已修复。谢了
