### ISSUE TITLE
如何获取个股不同时间的基本面数据？

### ISSUE THREAD

**Issue by xanderqian2010** [waditu/tushare#599]
刚学习了一个月，看到抓取基本面数据时总是抓取所有股票某一时间的数据，
想问下怎么实现只抓取个股的不同时间的基本面数据，比如某只股票的历史五年的Eps数据。谢谢

**Comment by leiliuliulei** [comment]
你用基本面那几个函数获取的就是全部时间的，包括历史的。比如get_balance_sheet()，拿到的结果就是好多年的数据。
