### ISSUE TITLE
前复权 函数 测试有bug

### ISSUE THREAD

**Issue by buptlishantao** [waditu/tushare#6]
cannot convert the series to <type 'float'>

**Comment by jimmysoa** [comment]
你用的pandas是什么版本？这个bug在pandas0.13 / 14 / 15下我都试过的。另外，可以把你的获取到的error信息贴上来我看看

**Comment by buptlishantao** [comment]
0.13版本，这个函数有时候没问题。不过程序爬取的网页数据应该不全。

error信息如下：



在 2015年4月4日，下午4:23，Jimmy <notifications@github.com> 写道：

**Comment by jimmysoa** [comment]
error log没贴上？没看到啊

**Comment by jimmysoa** [comment]
默认是一年的数据，如果想要其它时间的历史数据，可是设定start和end日期。复权接口提供从上市以来所有数据。

**Comment by buptlishantao** [comment]
贴上了啊，有qq之类的联系方式吗？详聊
在 2015年4月5日，下午12:18，Jimmy <notifications@github.com> 写道：

**Comment by jimmysoa** [comment]
52799046
