### ISSUE TITLE
quotes函数有bug

### ISSUE THREAD

**Issue by iLampard** [waditu/tushare#600]
https://github.com/waditu/tushare/blob/master/tushare/stock/trading.py

def quotes(symbols, conn=None, asset='E', market=[], retry_count = 3):

line 1059
`df = xapi.to_df(api.get_instrument_quote(mkcode, code))`
应该为 
`df = xapi.to_df(xapi.get_instrument_quote(mkcode, code))`

如何复制错误
api = ts.get_apis()
ts.quotes(['IH1802', 'IH1803'], conn=api, asset='X')

报的错是IOError: 获取失败，请检查网络，实际上是1059行报错， api没有get_instrument_quote这个方法

**Comment by jimmysoa** [comment]
谢谢，已修复，后面再提交到git
