### ISSUE TITLE
get_balance_sheet()报错——urllib.error.HTTPError: HTTP Error 456

### ISSUE THREAD

**Issue by leiliuliulei** [waditu/tushare#601]
ts.__version__
Out[8]: '1.1.5'

然后尝试获取财务数据，遇到下面问题：

n = ts.get_balance_sheet('000888')
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-7-d4d674271bf1> in <module>()
----> 1 n = ts.get_balance_sheet('000888')

C:\Program Files\Anaconda3\lib\site-packages\tushare\stock\fundamental.py in get_balance_sheet(code)
    468     if code.isdigit():
    469         request = Request(ct.SINA_BALANCESHEET_URL%(code))
--> 470         text = urlopen(request, timeout=10).read()
    471         text = text.decode('GBK')
    472         text = text.replace('\t\n', '\r\n')

C:\Program Files\Anaconda3\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    161     else:
    162         opener = _opener
--> 163     return opener.open(url, data, timeout)
    164 
    165 def install_opener(opener):

C:\Program Files\Anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    470         for processor in self.process_response.get(protocol, []):
    471             meth = getattr(processor, meth_name)
--> 472             response = meth(req, response)
    473 
    474         return response

C:\Program Files\Anaconda3\lib\urllib\request.py in http_response(self, request, response)
    580         if not (200 <= code < 300):
    581             response = self.parent.error(
--> 582                 'http', request, response, code, msg, hdrs)
    583 
    584         return response

C:\Program Files\Anaconda3\lib\urllib\request.py in error(self, proto, *args)
    508         if http_err:
    509             args = (dict, 'default', 'http_error_default') + orig_args
--> 510             return self._call_chain(*args)
    511 
    512 # XXX probably also want an abstract factory that knows when it makes

C:\Program Files\Anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    442         for handler in handlers:
    443             func = getattr(handler, meth_name)
--> 444             result = func(*args)
    445             if result is not None:
    446                 return result

C:\Program Files\Anaconda3\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    588 class HTTPDefaultErrorHandler(BaseHandler):
    589     def http_error_default(self, req, fp, code, msg, hdrs):
--> 590         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    591 
    592 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 456: 

是不是新浪对获取频率进行了限制？这个问题出现在我尝试连续获取多个公司的财务数据时，大概超过30个后会出错。解决方案的考虑，供探讨：

1. 换一个数据来源。目前我不知道哪里有不受限的来源，大家谁知道的请回复提供一下。BTW，巨潮资讯网现在提供财务数据下载，csv格式的。但经尝试同样会限制访问频率

2. 看其他issue几乎都是针对交易数据的，是否使用财务数据接口的人不多？如果不多的话是否方便提前抓取财务数据（用网络爬虫），然后放在米哥的服务器上 :)  ，因为财务数据每年只用更新4次。

我的微信：kangfu646610, 邮箱：124440646@qq.com , 米哥或其他人如果希望探讨更好的财务数据来源，欢迎随时联系。

**Comment by jimmysoa** [comment]
财务数据会出新版，未来tushare会提供自己采集的数据，不再用网络财经的数据，谢谢。
