### ISSUE TITLE
是否能提供内盘和外盘数据，新浪有计算好的，省的获取tick再计算一遍了

### ISSUE THREAD

**Issue by zjqzero** [waditu/tushare#603]
如题，根据成交明细自己计算太耗费资源了

**Comment by jimmysoa** [comment]
get_day_all有这个数据

**Comment by zjqzero** [comment]
是内盘和外盘，这个接口没有这个数据，如图：
![image](https://user-images.githubusercontent.com/12052416/36775180-f1d6482a-1c9b-11e8-84f3-861d979ab66c.png)

**Comment by jimmysoa** [comment]
get_day_all的字段：code 代码, name 名称, p_change 涨幅%,
price 现价, change 涨跌, open 今开, high 最高,
low 最低, preprice 昨收, pe 市盈(动),
volratio 量比, turnover 换手%, range 振幅%%,
volume 总量, selling 内盘, buying 外盘,
amount 总金额, totals 总股本(万), industry 细分行业,
area 地区, floats 流通股本(万), fvalues 流通市值,
abvalues AB股总市值, avgprice 均价, strength 强弱度%
activity 活跃度, avgturnover 笔换手, attack 攻击波%,
interval3 近3月涨幅 ，interval 近6月涨幅


内盘、外盘都有的

**Comment by zjqzero** [comment]
好的，多谢；
原来我在官方文档里没找到get_day_all，以为是get_today_all
