### ISSUE TITLE
shibor_data 接口返回值为 None

### ISSUE THREAD

**Issue by YikaJ** [waditu/tushare#604]
Shibor 的数据失效了，返回的是 None，可以麻烦看看吗，谢谢

**Comment by jimmysoa** [comment]
收到，我确认一下

**Comment by jimmysoa** [comment]
In [4]: ts.shibor_data(2017)
Out[4]:
          date      ON      1W      2W      1M      3M      6M      9M      1Y
0   2017-01-03  2.2090  2.5890  2.8170  3.3126  3.2813  3.3037  3.3310  3.3833
1   2017-01-04  2.1720  2.5450  2.8050  3.3223  3.2912  3.3094  3.3391  3.3904
2   2017-01-05  2.1300  2.4740  2.7920  3.3578  3.3384  3.3450  3.3670  3.4311
3   2017-01-06  2.1120  2.4410  2.7820  3.4101  3.4388  3.4380  3.4413  3.4882
4   2017-01-09  2.0940  2.4100  2.7650  3.4738  3.5152  3.5093  3.4962  3.5329
5   2017-01-10  2.0960  2.3990  2.7620  3.5314  3.5526  3.5481  3.5247  3.5533
6   2017-01-11  2.1040  2.3900  2.7530  3.5662  3.5853  3.5809  3.5495  3.5674
7   2017-01-12  2.1030  2.3940  2.7430  3.6387  3.6536  3.6201  3.5720  3.5838
8   2017-01-13  2.1040  2.3980  2.7626  3.6718  3.6874  3.6461  3.5872  3.6014
9   2017-01-16  2.1420  2.4239  2.7815  3.6852  3.7018  3.6617  3.5968  3.6102
10  2017-01-17  2.2563  2.4666  2.8076  3.7116  3.7222  3.6812  3.6117  3.6321

In [5]: ts.shibor_data(2018)
Out[5]:
         date      ON      1W      2W      1M      3M      6M      9M      1Y
0  2018-01-02  2.6570  2.8390  3.9430  4.7430  4.8040  4.8310  4.7150  4.7470
1  2018-01-03  2.5635  2.7850  3.8700  4.6220  4.7300  4.7830  4.7110  4.7360
2  2018-01-04  2.5050  2.7600  3.8020  4.4760  4.6870  4.7380  4.7020  4.7286
3  2018-01-05  2.4840  2.7450  3.7490  4.3756  4.6637  4.7118  4.6990  4.7249
4  2018-01-08  2.4610  2.7370  3.7200  4.2886  4.6594  4.7052  4.6989  4.7200
5  2018-01-09  2.5290  2.7440  3.6980  4.2209  4.6570  4.7026  4.6970  4.7200
6  2018-01-10  2.6430  2.7760  3.7060  4.1821  4.6607  4.6990  4.6970  4.7200
7  2018-01-11  2.8320  2.8320  3.7760  4.1632  4.6701  4.7049  4.7017  4.7230
8  2018-01-12  2.8300  2.8640  3.8080  4.1134  4.6791  4.7085  4.7052  4.7233
9  2018-01-15  2.7940  2.8600  3.8160  4.0904  4.6830  4.7139  4.7116  4.7253
10 2018-01-16  2.7850  2.8790  3.8280  4.0941  4.6843  4.7124  4.7142  4.7296
11 2018-01-17  2.7650  2.8780  3.8370  4.0905  4.6935  4.7133  4.7165  4.7320
12 2018-01-18  2.7655  2.8780  3.8430  4.0921  4.7044  4.7154  4.7237  4.7332
13 2018-01-19  2.8360  2.8910  3.8460  4.1113  4.7115  4.7216  4.7274  4.7384
14 2018-01-22  2.7710  2.8890  3.8540  4.1122  4.7122  4.7272  4.7318  4.7429
15 2018-01-23  2.6020  2.8630  3.8600  4.1123  4.7163  4.7278  4.7322  4.7423


没有问题哇
