### ISSUE TITLE
ts.get_industry_classified('sw') 申万行业获取不对

### ISSUE THREAD

**Issue by yangym2011** [waditu/tushare#605]
获取申万行业分类，返回[7628 rows x 3 columns]，首先行数不对从申万官网获取为3508；其次，存在一只股票分属多个行业的情况（如下神舟高铁为例，申万官方分类为机械设备，通过接口返回了4个分类！）

神州高铁 | 有色金属
神州高铁 | 休闲服务
神州高铁 | 机械设备
神州高铁 | 运输设备

**Comment by jimmysoa** [comment]
跟另外一个issue一样的问题 #596
