### ISSUE TITLE
Python 3.6 不兼容

### ISSUE THREAD

**Issue by YikaJ** [waditu/tushare#609]
用 Anaconda 切换版本后发现 Python 3.6 不兼容，而 Python 3.5 是可以正常使用的。

**Comment by jimmysoa** [comment]
目前有些接口暂时不支持3.6，后面再实现

**Comment by rock177486** [comment]
在 3.6.8 下安装后，好像没有任何api可以使用，包括 verison、set_token、pro_api

**Comment by jimmysoa** [comment]
应该是没有安装成功吧 @rock177486

**Comment by rock177486** [comment]
安装信息
pip install -U tushare
Collecting tushare
Requirement already satisfied, skipping upgrade: lxml>=3.8.0 in c:\programdata\anaconda3\lib\site-packages (from tushare) (4.3.2)
Requirement already satisfied, skipping upgrade: pandas>=0.18.0 in c:\programdata\anaconda3\lib\site-packages (from tushare) (0.24.1)
Requirement already satisfied, skipping upgrade: msgpack>=0.5.6 in c:\programdata\anaconda3\lib\site-packages (from tushare) (0.6.1)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from tushare) (2.21.0)
Requirement already satisfied, skipping upgrade: pyzmq>=16.0.0 in c:\programdata\anaconda3\lib\site-packages (from tushare) (18.0.0)
Requirement already satisfied, skipping upgrade: simplejson>=3.16.0 in c:\programdata\anaconda3\lib\site-packages (from tushare) (3.16.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.18.0->tushare) (2.8.0)
Requirement already satisfied, skipping upgrade: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.18.0->tushare) (2018.9)
Requirement already satisfied, skipping upgrade: numpy>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.18.0->tushare) (1.16.2)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->tushare) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->tushare) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->tushare) (2.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->tushare) (2019.3.9)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas>=0.18.0->tushare) (1.12.0)
Installing collected packages: tushare
Successfully installed tushare-1.2.21

**Comment by jimmysoa** [comment]
tushare.__version__
