### ISSUE TITLE
中证指数成分股

### ISSUE THREAD

**Issue by Hobart-Liu** [waditu/tushare#612]
目前的成分股是新浪的，貌似很久没有维护了，数据有点过期，比如300，好几个代码都不存在了。
能否提供从中证的下载页面下载成分股列表。

http://www.csindex.com.cn/zh-CN/downloads/indices?lb=%E5%85%A8%E9%83%A8&xl=1

**Comment by jimmysoa** [comment]
之前也是中证指数的，我确认一下数据

**Comment by Hobart-Liu** [comment]
临时解决可以直接用pandas.read_excel(url, dtype=object)来下载.

**Comment by jimmysoa** [comment]
升级到最新版
