### ISSUE TITLE
有些股票无法读取到当日交易情况

### ISSUE THREAD

**Issue by smallevil** [waditu/tushare#614]
比如:
603988
603986

都有一个共同点就是之前都有过一段时间的停盘.

是我调用错了?还是数据更新没跟上?
使用的这个函数get_hist_data

**Comment by zz090923610** [comment]
get_hist_data 貌似有不少股票数据更新不上来。比如603208就没有出来3月1日以后的。貌似df直接就出不来。。

**Comment by yanghui1228** [comment]
601958 后面的code都不能拿到hist data，601958前面的可以，是不是数据出了问题

**Comment by jasonkoo** [comment]
我最近遇到了同样的问题，我大概统计了一下，目前A股上市公司有3500家左右，停牌的有大概300家，每天应该能够获得3200家左右的数据，但是我只能拿到2800多家，少了有四百多家。

**Comment by arisliang** [comment]
找到了
