### ISSUE TITLE
保存到SQL时,怎样可以增加股票的Code作为一个Field同时保存到数据库吗?

### ISSUE THREAD

**Issue by ZhiliangLin** [waditu/tushare#616]
#存入数据库
df.to_sql('tick_data',engine)
希望可以保存到数据库时,把该股票的Code也记录下来,可以怎样做?只能在表名记录吗?

**Comment by jimmysoa** [comment]
哪个接口？这个df 的 code是index吧？可以先手动加一列code，或者从index转过来

**Comment by ZhiliangLin** [comment]
我刚找到之前有一个回答.
<img width="841" alt="2018-03-10 9 53 58" src="https://user-images.githubusercontent.com/15247459/37237042-3df08aae-2449-11e8-963d-7457c923d7ec.png">
应该是这样? thx
