### ISSUE TITLE
可转债的数据来自证券之星，不过数据中的marketprice在盘后也是昨天的数据

### ISSUE THREAD

**Issue by Rockyzsu** [waditu/tushare#622]
RT，一般几点后会有更新？

**Comment by jimmysoa** [comment]
一般晚上才有更新

In [21]: df = ts.new_cbonds()

In [22]: df.head()
Out[22]:
    bcode bname   scode sname   xcode  amount  marketprice  convprice  \
0  128038  利欧转债  002131  利欧股份  072131   21.98          NaN       2.76
1  128037  岩土转债  002542  中化岩土  072542    6.04          NaN       8.05
2  127006  敖东转债  000623  吉林敖东  070623   24.13          NaN      21.12
3  127005  长证转债  000783  长江证券  070783   50.00          NaN       7.60
4  128036  金农转债  002548   金新农  072548    6.50          NaN       9.72

   firstdayprice    ipo_date issue_date ballot return  perreturn
0            NaN  2018-03-22        NaN    NaN    NaN        NaN
1            NaN  2018-03-15        NaN  0.09%    NaN     110.95
2            NaN  2018-03-13        NaN  0.12%    NaN      80.80
3            NaN  2018-03-12        NaN    NaN    NaN        NaN
4            NaN  2018-03-09        NaN  0.05%    NaN        NaN

**Comment by billionair123** [comment]
大神好，有转债的函数合集吗？
