### ISSUE TITLE
在命令行测试执行如下命令，得出的数据与指定时间不符，有哪写错了吗，还是是接口本身的问题

### ISSUE THREAD

**Issue by beebon** [waditu/tushare#624]
CMD下执行如下，为啥出现了2017年的数据？

>>> import tushare as ts
>>> df = ts.get_k_data('002635',**start='2016-10-01', end='2016-10-31'**,ktype='60')
>>> df
                 date   open  close   high    low    volume    code
0    2017-09-14 14:00  38.99  39.00  39.42  38.86    5513.0  002635
1    2017-09-14 15:00  39.00  38.95  39.17  38.81    7610.0  002635
2    2017-09-15 10:30  38.93  39.46  40.01  38.78   30271.0  002635
3    2017-09-15 11:30  39.46  39.41  39.76  39.30   11751.0  002635
4    2017-09-15 14:00  39.41  39.30  39.48  39.28    6153.0  002635
5    2017-09-15 15:00  39.30  39.55  39.55  39.11    9061.0  002635
6    2017-09-18 10:30  39.22  39.48  39.60  38.80   20107.0  002635
7    2017-09-18 11:30  39.48  39.55  39.79  39.44   12160.0  002635
8    2017-09-18 14:00  39.55  39.99  39.99  39.55    9779.0  002635
9    2017-09-18 15:00  39.99  40.26  40.39  39.92   21254.0  002635
10   2017-09-19 10:30  40.00  38.83  40.22  38.75   19096.0  002635
11   2017-09-19 11:30  38.83  39.10  39.27  38.83   14323.0  002635
12   2017-09-19 14:00  39.10  38.95  39.13  38.82    9497.0  002635
13   2017-09-19 15:00  38.95  39.20  39.26  38.80   19969.0  002635
14   2017-09-20 10:30  38.66  38.90  39.10  38.54    9237.0  002635
15   2017-09-20 11:30  38.90  38.80  39.04  38.40   13126.0  002635
16   2017-09-20 14:00  38.80  39.16  39.16  38.72    4365.0  002635
17   2017-09-20 15:00  39.16  38.70  39.18  38.58    7670.0  002635
18   2017-09-21 10:30  38.70  37.96  38.70  37.75   21940.0  002635
19   2017-09-21 11:30  37.96  37.98  38.35  37.94    5692.0  002635
20   2017-09-21 14:00  37.98  37.73  38.00  37.68   11868.0  002635
21   2017-09-21 15:00  37.73  37.63  38.09  37.63   11505.0  002635
22   2017-09-22 10:30  37.30  38.32  38.79  37.30   15657.0  002635
23   2017-09-22 11:30  38.32  38.10  38.50  37.90    4916.0  002635
24   2017-09-22 14:00  38.10  38.20  38.20  37.69    4612.0  002635
25   2017-09-22 15:00  38.20  38.63  38.77  38.19   13976.0  002635
26   2017-09-25 10:30  38.58  37.84  38.58  37.02   22619.0  002635
27   2017-09-25 11:30  37.84  37.51  37.85  37.40    7414.0  002635
28   2017-09-25 14:00  37.51  36.92  37.75  36.89   15310.0  002635
29   2017-09-25 15:00  36.92  36.75  37.09  36.54   20456.0  002635
..                ...    ...    ...    ...    ...       ...     ...
452  2018-03-07 14:00  23.51  23.56  23.58  23.26   35047.0  002635
453  2018-03-07 15:00  23.56  23.54  23.63  23.44   33375.0  002635
454  2018-03-08 10:30  23.64  23.36  23.65  23.25   48472.0  002635

**Comment by jimmysoa** [comment]
这个接口取分钟数据时，date参数无效，因为只能去最近的分钟数据，每次取都是最新的。 另外可以试试ts.bar接口，分钟数据稍微多一些
