### ISSUE TITLE
指数数据下载

### ISSUE THREAD

**Issue by Hobart-Liu** [waditu/tushare#631]
我在下载行业指数数据的时候发现有的有，有的没有。这是因为数据源不支持，还是因为其他的原因？

如支持的有：
000928, 000931, 000934

不支持的有：
000930， 000936， 000809

**Comment by jimmysoa** [comment]
df = ts.bar('000930', conn=cons, asset='X', market=62)
In [6]: df.head()
Out[6]:
              code         open        close         high          low   vol
datetime
2018-03-21  000930  3147.237549  3137.112061  3173.643311  3129.635010  2881
2018-03-20  000930  3126.353760  3144.169434  3147.170410  3115.794922  2390
2018-03-19  000930  3146.508789  3143.422119  3161.686279  3133.103760  2354
2018-03-16  000930  3168.237061  3148.015869  3176.184082  3147.729980  2299
2018-03-15  000930  3156.253662  3167.947021  3171.323242  3145.591309  2659

**Comment by Hobart-Liu** [comment]
哇，现在基本都可以工作了。
除了这3个：399701， 399702， 399703. 
错误描述为
index 0 is out of bounds for axis 0 with size 0

注： 有asset='index'这三个可以。但是很多其他指数不行，用了X后，基本都可以了，就这三个不行。

**Comment by Hobart-Liu** [comment]
另： market=62是啥意思啊

**Comment by jimmysoa** [comment]
这是个代码，可以不用理会

**Comment by Hobart-Liu** [comment]
asset='index' 和 asset='X' 拿到的数据是不同的，
比如300, 用asset='index' 拿到的数据是对的，而 asset='X' 拿到的数据很怪。 

哪些指数是可以用X， 哪些是可以用index?

**Comment by Hobart-Liu** [comment]
下图是asset='X' 拿到的300 的图形，明显不对

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10845063/37877012-30397e94-3087-11e8-8cdd-e362ac649313.png">

**Comment by Hobart-Liu** [comment]
asset='index' 的300 的图形才是正确的。
<img width="640" alt="image" src="https://user-images.githubusercontent.com/10845063/37877027-731b7618-3087-11e8-8648-431b08f1067f.png">
