### ISSUE TITLE
get_profit_data接口文档和注释中对净利润的单位说明有误

### ISSUE THREAD

**Issue by xuxic** [waditu/tushare#632]
文档中和注释里都是这么写的：
net_profits,净利润(万元)

然而实测发现，这个数据应该是以百万为单位的，实际效果如下：
sqlite> select * from get_profit_data_2017_3 where code='002508';
88|002508|老板电器|20.18|19.25|56.0668|960.4336|1.012|4987.9296|5.2558
第七个字段960.4336就是9.6亿。

同时实测发现，get_report_data得到的净利润的数据是以万为单位的，效果如下：
sqlite> select * from get_report_data_2017_3 where code='002508';
2385|002508|老板电器|1.01|5.21||22.21||96043.36|36.95||10-26
第九个字段96043.36就是9.6亿，这个确实是以万为单位的，文档和注释里没有写错。

**Comment by jimmysoa** [comment]
收到，这个问题新网页统一再处理，谢谢。
