### ISSUE TITLE
使用bar函数有获取同一股票1min数据有问题15min数据无问题

### ISSUE THREAD

**Issue by pythonwood** [waditu/tushare#636]
tushare (1.1.0)

获取*ST建峰  000950是1min数据有问题但15min数据无问题，返回了空DataFrame 
（类似还有600806-*ST昆机， 600432-*ST吉恩  等等）

![screenshot - 2018 03 25 - 17 30 44](https://user-images.githubusercontent.com/5157880/37873587-4a662cfc-3052-11e8-8734-7a650ad4e6b4.png)

In [6]: shyf
Out[6]: 
Empty DataFrame
Columns: [code, open, close, high, low, vol, amount]
Index: []

**Comment by jimmysoa** [comment]
这个股票是停牌了很久的股票，而分钟数据现在线上还没有全部历史数据，所以取不到数据。
