### ISSUE TITLE
复权数据有误！

### ISSUE THREAD

**Issue by wilon** [waditu/tushare#637]
```python
import tushare as ts

df = ts.get_hist_data('300104', start='2017-03-01', end='2018-03-01')
df.to_csv("300104.csv")
```

**上面代码获取的默认前复权的数据，可是下载下来却是未复权的数据。**

![image](https://user-images.githubusercontent.com/7512755/37959768-75d6a534-31e6-11e8-8d23-45de227e2046.png)

**Comment by jimmysoa** [comment]
这个接口没有复权，复权请用ts.bar(xxxxxxxx, adj='qfq')

**Comment by wilon** [comment]
其他有复权的接口都没有 ma5 等数据啊 @jimmysoa
