### ISSUE TITLE
历史股票数据不全

### ISSUE THREAD

**Issue by jasonkoo** [waditu/tushare#639]
最近试用tushare筛选一些股票，我主要是先调用ts.get_stock_basics()获取股票列表，然后遍历这个列表中的每一只股票，调用ts.get_hist_data('603686',start='2018-03-30',end='2018-03-30')获取当天收盘后的每一只股票的数据，我发现目前A股上市公司有3500家左右，停牌的大概有300家，遍历完应该能够拿到3200只股票的数据，但我只拿到2800多只，少了有近400只。比如我示例中的603686就没有，能否将这缺少的400多家数据补全？

**Comment by jimmysoa** [comment]
最近数据源有些调整，建议先用ts.bar接口更稳妥

**Comment by zhuchong79** [comment]
目前发现少了520个个股的hist数据。没有发现ts.bar()接口
