### ISSUE TITLE
凤凰网只提供最近350条数据吗？

### ISSUE THREAD

**Issue by sc08d30** [waditu/tushare#649]
get_hist_data获取日K线能获取350条足够了，但是获取5分钟K线也只能获取350条。把网址打出来是凤凰网提供的接口，网址没有拼接开始结束日期两个参数，且只能获取最近350条，相当于只能获取最近7天的5分钟K线，有什么解决办法吗？

**Comment by jimmysoa** [comment]
换ts.bar稍微多一些，如果要全部历史，可以微信找我。
