### ISSUE TITLE
ts.get_hist_data 的结果里怎么没有date字段，get_stock_basics结果少了code

### ISSUE THREAD

**Issue by oliversegal6** [waditu/tushare#658]
df = ts.get_hist_data('303')
    for k in df:
        print(k)

结果里没有date
open
high
close
low
volume
price_change
p_change
ma5
ma10
ma20
v_ma5
v_ma10
v_ma20
turnover

**Comment by jimmysoa** [comment]
在index里

**Comment by oliversegal6** [comment]
谢谢，找到了。 不过页面上的API文档好像不是最新的
