### ISSUE TITLE
ts.shibor_data() is not functional

### ISSUE THREAD

**Issue by allaster** [waditu/tushare#666]
cant obtain shibor data through ts.shibor_data() function.

**Comment by jimmysoa** [comment]
升级到最新版就可以了

**Comment by jimmysoa** [comment]
In [2]: import tushare as ts

In [3]: df = ts.shibor_data()

In [4]: df.tail()
Out[4]:
         date     ON     1W     2W     1M     3M     6M     9M     1Y
92 2018-05-17  2.597  2.803  3.649  3.831  4.101  4.194  4.306  4.366
93 2018-05-18  2.563  2.768  3.656  3.833  4.147  4.202  4.309  4.370
94 2018-05-21  2.527  2.756  3.669  3.832  4.151  4.207  4.309  4.371
95 2018-05-22  2.525  2.755  3.673  3.838  4.160  4.207  4.307  4.371
96 2018-05-23  2.530  2.752  3.679  3.841  4.173  4.211  4.309  4.373
