### ISSUE TITLE
get_k_data 获得的复权数据不准确，与get_h_data不同

### ISSUE THREAD

**Issue by cynthiatokay** [waditu/tushare#669]
使用get_k_data 获得的复权数据不准确，经对比和get_h_data获得的数据不一样。get_h_data和新浪的数据一样。get_k_data获取的是其他数据源的数据吗？

ts.get_h_data('600004', autype='hfq',start='2018-01-01', end='2018-01-03')

             open   high  close    low      volume       amount
date                                                           
2018-01-03  37.55  37.55  37.45  37.07  15046954.0  222055580.0
2018-01-02  37.27  37.58  37.45  36.92  13127900.0  193508326.0

ts.get_k_data('600004', start='2018-01-01', end='2018-01-03', autype='hfq')

         date    open   close    high     low    volume    code
0  2018-01-02  31.106  31.254  31.359  30.810  131279.0  600004
1  2018-01-03  31.338  31.254  31.338  30.937  150469.0  600004

**Comment by jimmysoa** [comment]
两个数据源的算法应该是不一致的，对照一下新浪和腾讯财经的这两个数据。
