### ISSUE TITLE
请问有没有关于量比指标的API?

### ISSUE THREAD

**Issue by DaiyangLiu** [waditu/tushare#673]
我在tushare的API文档上找了很久，没找到，是不是这一版本还没有关于量比指标的API？

我在https://mp.weixin.qq.com/s?__biz=MzAwOTgzMDk5Ng==&mid=2650833972&idx=1&sn=4de9f9ee81bc8bf85d1e0a4a8f79b0de&chksm=80adb30fb7da3a19817c72ff6f715ee91d6e342eb0402e860e171993bb0293bc4097e2dc4fe9&mpshare=1&scene=1&srcid=1106BPAdPiPCnj6m2Xyt5p2M#wechat_redirect
里面看到说未来的计划是“3、提供包括涨跌幅、换手率、量比在内的衍生数据列或者函数接口。”

谢谢。

**Comment by jimmysoa** [comment]
ts.bar有量比
