### ISSUE TITLE
 _code_to_symbol无法判断可转债代码是沪市深市

### ISSUE THREAD

**Issue by lwhuq** [waditu/tushare#678]
可否添加可转债沪市深市判断到_code_to_symbol，改动如下，谢谢。
	def _code_to_symbol(code):
	    '''
	        生成symbol代码标志
	    '''
	    if code in INDEX_LABELS:
	        return INDEX_LIST[code]
	    else:
	        if len(code) != 6 :
	            return code
	        else:
	            return 'sh%s'%code if code[:1] in ['5', '6', '9'] **or code[:2] in ['11', '13']** else 'sz%s'%code

**Comment by jimmysoa** [comment]
已经添加，等下版发布
