### ISSUE TITLE
python3 环境pip更新失败

### ISSUE THREAD

**Issue by windend** [waditu/tushare#679]
File "/private/tmp/pip-install-9y7cej54/tushare/tushare/stock/minsdata.py", line 86
        print df
               ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(df)?

**Comment by simon82** [comment]
太巧了，刚刚遇到同样的问题。

**Comment by nasyxx** [comment]
这是一个很奇怪的事情，为什么会有这样的一个文件呢？我在它的源码中并没有找到这个文件

**Comment by nasyxx** [comment]
所以，我想最简单的解决方案是

先卸载: `pip uninstall tushare`

再重新安装: `pip install tushare -U`

**Comment by windend** [comment]
@simon82 @nasyxx 卸载重装是可以解决问题，不过上个更新包里并没有这个错误，怀疑打包的时候报的错误

**Comment by jimmysoa** [comment]
已经修复，1.2.3
