### ISSUE TITLE
是否含有挖矿插件？

### ISSUE THREAD

**Issue by EMDCYY** [waditu/tushare#681]
安装了tushare 1.2.3后，运行一个含有 import tushare的python script速度很慢，既不报错，也无输出，且不停止，同时CPU利用率立刻上跳至99%。

如果打开terminal，运行一些含有tushare的python语句，则有输出，但速度仍然很慢，且CPU仍然跳至99%，并且程序不会停止。

想请问一下，是否是因为含有挖矿插件？是否可以通过付费的方式，获得无挖矿插件的版本？

**Comment by jimmysoa** [comment]
跟挖矿没有半毛钱关系，代码是开源的，你可以自己看代码

**Comment by jimmysoa** [comment]
用的是哪个接口？还是说用了包含了tushare的第三方工具？
