### ISSUE TITLE
【Bug】bar函数问题，查询 etf 时，date 为空，无datetime这个 key 错误

### ISSUE THREAD

**Issue by morningtzh** [waditu/tushare#682]
文件 tushare/stock/trading.py 852行
data['datetime'] = data['datetime'].apply(lambda x: str(x[0:10]))

data 为空，因此datetime  这个 key找不到。

测试代码：
import tushare as ts
conn = ts.get_apis()
ts.bar("100032",conn=conn, freq="D")

**Comment by FuhuaWei** [comment]
import tushare as ts
conn = ts.get_apis()
df = ts.bar('股票代码',conn=cons, freq='D')
print(df)
#上面的代码是可以操作的，但是如果你要除了股票以外的数据，比如etf或者期货的，就会报错，估计是数据源的问题

**Comment by jimmysoa** [comment]
asset='X'

**Comment by haithink** [comment]
> import tushare as ts
> conn = ts.get_apis()
> df = ts.bar('股票代码',conn=cons, freq='D')
> print(df)
> #上面的代码是可以操作的，但是如果你要除了股票以外的数据，比如etf或者期货的，就会报错，估计是数据源的问题

的确如此，ETF无法获取数据
