### ISSUE TITLE
get_hist_data中的turnover字段没有了

### ISSUE THREAD

**Issue by HakanaiYume** [waditu/tushare#683]
貌似六月份开始这个字段就没有了，因为有程序需要这个字段，发现六月开始程序就不正常了。
能不能把这个字段加回去啊。

**Comment by jimmysoa** [comment]
用ts.bar

**Comment by HakanaiYume** [comment]
用ts.bar不行啊
报错如下：
服务器连接为空，请通过ts.get_apis()获取
![image](https://user-images.githubusercontent.com/26223151/41331841-c01e7b8a-6f0d-11e8-8483-5d4a2040eeee.png)

**Comment by HakanaiYume** [comment]
ts.bar里面也没有turnover这个字段
![image](https://user-images.githubusercontent.com/26223151/41332096-facb6f8a-6f0e-11e8-905d-40061cd9271b.png)

**Comment by bigbao9494** [comment]
我也发现最新的确定没有turnover了，不知道 为什么要取消这个，这个数据挺重要的啊

**Comment by jimmysoa** [comment]
ts.bar
