### ISSUE TITLE
002908的日数据有误

### ISSUE THREAD

**Issue by arisliang** [waditu/tushare#684]
比如2018-06-07, 新浪上给的开盘价38.3, 最高38.3, 最低38.0, 收盘38.3.
而get_k_data里面给的数据则是38.101, 38.101, 37.802, 38.101. 与上面的数据不符.

另外, 为什么数据还有3位小数的?

version: 1.2.4

**Comment by jimmysoa** [comment]
是否设置了复权？

**Comment by arisliang** [comment]
我的代码是:
`ts.get_k_data('002908', start='2018-06-06', end='2018-06-08')`

**Comment by jimmysoa** [comment]
默认是前复权，这样写就符合你的一致性了：

In [9]: dd =ts.get_k_data('002908', start='2018-06-06', end='2018-06-08', autype=None)

In [10]: dd
Out[10]:
           date   open  close  high    low    volume    code
102  2018-06-06  33.95  34.82  35.0  33.01   49613.0  002908
103  2018-06-07  38.30  38.30  38.3  38.00   67140.0  002908
104  2018-06-08  38.00  39.05  41.0  37.13  166006.0  002908
