### ISSUE TITLE
为什么有的股票使用get_hist_data查不到数据啊

### ISSUE THREAD

**Issue by AshZh** [waditu/tushare#687]
![image](https://user-images.githubusercontent.com/17118540/41577367-077e167e-73bf-11e8-8731-14df417ccd58.png)
以上是代码和结果截图，使用jupyter，tushare 1.2.4版。
代码如下：
tmp=ts.get_hist_data('002494', start='2010-11-02',end='2011-02-02')
print(tmp)

但是这些数据如果是使用get_h_data()方法就能够查询到数据。

**Comment by jimmysoa** [comment]
是的，这个接口只有最近3年，用下面你提到的接口，或者ts.bar
