### ISSUE TITLE
基本面数据中考虑添加“业绩快报”（数据源：新浪财经）

### ISSUE THREAD

**Issue by zbclove** [waditu/tushare#688]
建议在基本面数据接口中添加“业绩快报”季度数据接口。
数据源来自新浪财经，与盈利能力，营运能力等为并列关系。
由于“总资产”的季度数据不在其他项目中体现，所以建议添加该接口。

**Comment by jimmysoa** [comment]
收到

**Comment by zbclove** [comment]
感谢！
