### ISSUE TITLE
get_k_data如果设置start, 就拿不到今天的数据

### ISSUE THREAD

**Issue by arisliang** [waditu/tushare#691]
如https://github.com/waditu/tushare/issues/349 所说, 如果去掉start, 就可以拿到今天的数据.

**Comment by wangchengrong** [comment]
同提问

**Comment by arisliang** [comment]
@ppuserxu 不对，因为不指定start就可以拿到今天的数据。

**Comment by wemissxxx** [comment]
问题仍然没有解决

**Comment by ppuserxu** [comment]
This is a old api and i am using new api now,you can find new detail info if you login in tushare main web site.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wemissxxx"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月24日(星期四) 下午2:21
收件人:&nbsp;"waditu/tushare"<tushare@noreply.github.com&gt;;
抄送:&nbsp;"无语"<34656952@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [waditu/tushare] get_k_data如果设置start, 就拿不到今天的数据 (#691)




问题仍然没有解决

**Comment by jimmysoa** [comment]
请使用pro版的行情接口
