### ISSUE TITLE
get_k_data 在阿里云上报 urlopen error timed out

### ISSUE THREAD

**Issue by firefenta** [waditu/tushare#696]
完全相同的代码，在本地（两台PC，不同的网络环境）运行都没有问题，在阿里云上运行了两个多月了也没有问题，7月2日开始报“urlopen error timed out”错误，将重试次数放到10次，还是十次timed out。之前是1.1.6版本，出错之后升级到1.2.4，还是一样的问题。

**Comment by cnchenji** [comment]
我也遇到同样问题。

**Comment by jimmysoa** [comment]
限制了吧，再等等pro版

**Comment by firefenta** [comment]
pro版大概啥时候能推出啊，人民群众都盼着呢……

**Comment by corder-ybh** [comment]
腾讯云也是无法使用

**Comment by realamd** [comment]
阿里云依然不能用，有其他接口可以代替么

**Comment by jerrylee529** [comment]
这个问题能解决不？

**Comment by jerrylee529** [comment]
似乎是云服务器无法访问url
curl http://web.ifzq.gtimg.cn/                                                                                       
curl: (7) Failed to connect to web.ifzq.gtimg.cn port 80: Connection timed out

**Comment by jerrylee529** [comment]
还有，get_k_data是不是有bug？以下输入参数end是"2018-05-27"，但是最后的url中是2019-12-31。
data = ts.get_k_data("601398", start="2018-01-01", end="2018-05-27")
http://web.ifzq.gtimg.cn/appstock/app/fqkline/get?_var=kline_dayqfq2018&param=sh601398,day,2018-01-01,2019-12-31,640,qfq&r=0.84442361806770209
<urlopen error timed out>

**Comment by Ming-Lei** [comment]
我也碰见这个问题了，怎么解决啊

**Comment by ELI95** [comment]
阿里云服务器为什么无法使用此接口？

**Comment by jimmysoa** [comment]
pro版可以了哦，https://tushare.pro
