### ISSUE TITLE
请教 tick data 中“买盘/卖盘/中性盘”的判断方法

### ISSUE THREAD

**Issue by philipchung007** [waditu/tushare#7]
get_tick_data()返回数据的type列，买盘/卖盘/中性盘 的判断标准具体是什么？

**Comment by jimmysoa** [comment]
数据由sina财经提供，至于卖卖类型的判断我大概知道些，私下可交流一下。

**Comment by gdshen** [comment]
请问一下，比如type列里面显示“买盘”，因为数据的间隔是有好几秒的，在这几秒里面一个卖盘都没有么？

**Comment by jimmysoa** [comment]
这一笔里面包含了买卖，但是以最后一笔作为成交方向的判断。最精准的还需要L2数据

**Comment by gdshen** [comment]
明白啦，谢谢楼上
