### ISSUE TITLE
sort is deprecated

### ISSUE THREAD

**Issue by soarowl** [waditu/tushare#70]
D:\Miniconda3\lib\site-packages\tushare-0.4.1-py3.5.egg\tushare\stock\trading.py:439: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort('date', ascending=False)

**Comment by xlbaojun** [comment]
df = ts.get_h_data('002337',start='2015-01-01',end='2015-03-16') 
df = ts.get_h_data('002337')
有同样的问题
