### ISSUE TITLE
ts.get_stock_basics()函数返回的数据有问题

### ISSUE THREAD

**Issue by yujun1214** [waditu/tushare#701]
ts.get_stock_basics()函数返回的数据有问题，比如000333美的集团的上市日期是20130918，但是ts返回的是19931112。

**Comment by jimmysoa** [comment]
美的集团的前生美的电器,1993年上市

**Comment by yujun1214** [comment]
你说的很对，但是美的电器的股票代码是000527，美的集团的代码是000333。如果用000333代码去读取2013年9月18日之前的行情数据，是读不到的。所以建议ts.get_stock_basics()函数的返回数据增加一个“退市日期”字段。

**Comment by yujun1214** [comment]
类似的还有三六零（601360）借壳江南嘉捷（601313），也是这个问题。
