### ISSUE TITLE
能否加入个股的历史资金流向

### ISSUE THREAD

**Issue by sebaifcm** [waditu/tushare#704]
记得以前sina有个股的超大、大、中、小单的每日流入流出的数据，现在没有了，现在像东方财富这种网站提供的都是净量和净占比，意义就不大了。

不知道兔兄能否找个资源把这个加上？可能分析起来挺有意思的。

**Comment by sebaifcm** [comment]
另外不知道是否有可能取到历史的个股的流通股本和总股本？

**Comment by jimmysoa** [comment]
pro版数据可以获取历史股本信息：https://tushare.pro/document/2?doc_id=32
资金流向目前需要通过tick数据自己计算，未来pro会直接提供
