### ISSUE TITLE
top10_holders 返回的数据帧有问题

### ISSUE THREAD

**Issue by lidanger** [waditu/tushare#706]
df = ts.top10_holders('000007', 2017, 2)
结果df内容：
(      quarter    amount  changed  props
3  2017-06-30  15765.10  5255.03  45.50,        quarter                                name     hold  h_pro sharetype  \
30  2017-06-30                        北京泓钧资产管理有限公司  4685.85  13.53      流通A股   
31  2017-06-30                                 练卫飞  3750.00  10.82     限售流通股   
32  2017-06-30                  深圳前海圆融通达投资企业(有限合伙)  2570.83   7.42      流通A股   
33  2017-06-30          华宝信托有限责任公司－“华宝丰进”32号单一资金信托  1380.81   3.99      流通A股   
34  2017-06-30                                 陈卓婷  1349.39   3.89      流通A股   
35  2017-06-30                          广州博融投资有限公司   604.68   1.75      流通A股   
36  2017-06-30  陕西省国际信托股份有限公司－陕国投·持盈5号证券投资集合资金信托计划   434.39   1.25      流通A股   
37  2017-06-30                         北京电子城有限责任公司   361.50   1.04      流通A股   
38  2017-06-30                                  陆炜   327.19   0.94      流通A股   
39  2017-06-30                                 阳德惠   300.46   0.87      流通A股   

     status  
30  1561.95  
31     1250  
32  856.944  
33  460.271  
34  449.796  
35  201.561  
36  144.796  
37    120.5  
38  109.065  
39  100.155  )

**Comment by jimmysoa** [comment]
请切换到pro数据：https://tushare.pro/document/2?doc_id=61
