### ISSUE TITLE
get_tick_data  失效

### ISSUE THREAD

**Issue by do1234521** [waditu/tushare#710]
今天 get_tick_data 函数一直失效，是api接口的问题吗

**Comment by hellobiek** [comment]
数据源改成tt就可以了。

**Comment by do1234521** [comment]
@hellobiek 请问如何修改

**Comment by wintonzheng** [comment]
新浪服务器下线了？

**Comment by wintonzheng** [comment]
@do1234521 `get_tick_data(code=xxx, date=xxx, src='tt')

**Comment by do1234521** [comment]
测试了一晚上tt源，也不稳定，并且似乎数据不全，希望能解决下数据源的问题

**Comment by lmx99** [comment]
现在有解决的吗？

**Comment by lmx99** [comment]
tt 也不行啊

**Comment by panzhenfu** [comment]
现在怎么获取历史分笔数据，怎么解决？有什么替代方式？

**Comment by jimmysoa** [comment]
src有两个数据源，先暂时切换吧
