### ISSUE TITLE
df = ts.get_tick_data('600848',date='2014-01-09')接口失效？？

### ISSUE THREAD

**Issue by panzhenfu** [waditu/tushare#715]
df = ts.get_tick_data('600848',date='2014-01-09')获取不到数据了，我试着打开源码的链接也没有获得数据

**Comment by ifzz** [comment]
sina tick已经下线

**Comment by lmx99** [comment]
tt 也不行返回none

**Comment by lmx99** [comment]
ts.get_tick_data(code='600848', date='2014-01-09', src='tt')

**Comment by hellobiek** [comment]
tt也很坑爹。部分有，部分没有。

**Comment by do1234521** [comment]
[https://github.com/waditu/tushare/issues/710](url) 已经讨论过，tt的数据很不全，现在问题挺难解决的，不知道有没有其他数据提供商

**Comment by lmx99** [comment]
或者自己解析网页

**Comment by zhangyishi** [comment]
sina永久不提供了吗。？

**Comment by zhangyishi** [comment]
Sina永久不提供了？
