### ISSUE TITLE
建议增加按日期获取所有股票数据

### ISSUE THREAD

**Issue by bobowang5** [waditu/tushare#72]
get_today_all() 只能获取当天所有股票数据，建议增加按日期获取所有股票数据

**Comment by jimmysoa** [comment]
这个功能可以调取tushare里通联数据的接口实现

**Comment by bobowang5** [comment]
通联数据试用一年后就要缴费了吗？还是会跟通联有更进一步的合作？

**Comment by jimmysoa** [comment]
应该会继续免费

**Comment by zz** [comment]
通联貌似不免费了，看来还是不靠谱
