### ISSUE TITLE
get_k_data 五分钟线在2018-07-30 14:50-15:00成交量数据大量为负数

### ISSUE THREAD

**Issue by latifrons** [waditu/tushare#720]
ifzq.gtimg.cn 数据源上有问题，估计也没法修，大家使用的时候注意一下，即使不是负数，量也不对。

285  2018-07-30 14:40  9153.88  9141.22    ...     9139.74   4759286.0  sz399001
286  2018-07-30 14:45  9141.22  9171.08    ...     9141.22  11444580.0  sz399001
287  2018-07-30 14:50  9171.08  9177.38    ...     9169.58  19680972.0  sz399001
288  2018-07-30 14:55  9177.38  9141.12    ...     9120.16 -27678762.0  sz399001
289  2018-07-30 15:00  9141.12  9145.93    ...     9136.26  -1907090.0  sz399001

**Comment by jimmysoa** [comment]
ts.bar会好一些
