### ISSUE TITLE
抓取业绩主表时数据不全

### ISSUE THREAD

**Issue by freeitaly** [waditu/tushare#73]
抓取业绩主表时数据不全
每次抓取后的  得到的股票数量都不一样，但是都远远少于2700，接近2000

问题是sina数据默认按 发布日期排序的问题
在con里Report_url 添加 &order=netprofit字段或者任一排序字段可以解决

**Comment by Wenice** [comment]
我这里数量都对啊， 你哪个时间有问题？

**Comment by freeitaly** [comment]
In [8]: a = ts.get_report_data(2015,3)
[Getting data:]###############################################

In [9]: len(a)
Out[9]: 2009

In [10]: a = ts.get_report_data(2015,3)
[Getting data:]###############################################

In [11]: len(a)
Out[11]: 2006

In [12]: a = ts.get_report_data(2015,3)
[Getting data:]###############################################

In [13]: len(a)
Out[13]: 1911

不是某个时间有问题，是所有时间都有问题
每次抓取后的行数都不一样，原因就是我主贴里指出的

在con.py里Report_URL添加 &order=code字段或者netprofit等任一排序字段可以解决

**Comment by freeitaly** [comment]
抓取的股票数量应该是2780，缺的有点多,要不也不会注意到
