### ISSUE TITLE
获取大盘及指数类数据时，价格和实际的指数如何对应？

### ISSUE THREAD

**Issue by xialingge** [waditu/tushare#730]
在使用接口获取大盘或指数类股票，比如000001或000906，得到的开盘价、收盘价并不是实际的点数，这个是什么原因呢？有什么换算规则吗？

**Comment by jimmysoa** [comment]
哪个接口？ 你可以用ts.bar接口

**Comment by xialingge** [comment]
ts.get_hist_data接口，比如我ts.get_hist_data('000001',start='2018-08-24', end='2018-08-24')，得到的open，high，close，low列的值分别为9.31  10.28  10.03  9.29，并不是实际的大盘点数，试了ts.bar，一样的效果

**Comment by 0kai** [comment]
@xialingge 这是没玩过股票吗，000001是平安银行

**Comment by xialingge** [comment]
@0kai 000001.SZ是平安银行，000001.SH是上证指数啊，所以如果我要查000001.SH的数据，code应该传什么呢？

**Comment by 0kai** [comment]
@xialingge tushare貌似暂时不支持吧，好像有的接口是要传sh而不是000001.SH

**Comment by jimmysoa** [comment]
指数： 
ts.bar('000001', conn=cons, asset='INDEX') 
或者 
ts.get_k_data(‘000001', index=True)

**Comment by xialingge** [comment]
@jimmysoa thanks
