### ISSUE TITLE
get_basics() 增加一个code 参数

### ISSUE THREAD

**Issue by haotianteng** [waditu/tushare#732]
你好，请问能不能将 get_basics()增加一个可选的股票代码参数，可以是一个股票代码的list，只抓取指定list里面股票的数据，或者能否使得get_k_data 也返回这只股票的基本面参数，比如市净率和市盈率？

谢谢

**Comment by jimmysoa** [comment]
可以通过df来过滤

**Comment by haotianteng** [comment]
但是get_basics() 还是依然会每次都抓取所有股票的信息？这样子如果想获得一只股票的历史基本面信息就太慢了
