### ISSUE TITLE
数据缺失问题

### ISSUE THREAD

**Issue by northcheng** [waditu/tushare#733]
无意中发现, 对比聚宽获取的股票数据, tushare有缺失数据的情况, 以601318中国平安为例:

同样获取从2007-03-01至2018-08-29的数据, 聚宽返回2805条, tushare返回2734条,
其中tushare缺失的天数包括但不限于
[Timestamp('2007-03-19 00:00:00'),
 Timestamp('2007-06-07 00:00:00'),
 Timestamp('2007-09-04 00:00:00'),...

代码如下:
`
from jqsdk import *
import tushare as ts

# 获取股票信息
sec_info = get_security_info('601318.XSHG')

# tushare数据
ts_data = ts.get_k_data(code='601318',start=sec_info.start_date.strftime('%Y-%m-%d'), end='2018-09-01')
# 转化为时间序列
ts_data = util.df_2_timeseries(ts_data, 'date')

# 聚宽数据
jq_data = get_price('601318.XSHG', start_date=sec_info.start_date.strftime('%Y-%m-%d'), end_date='2018-09-01')

# 对比两个平台的记录数
len(ts_data), len(jq_data)

# 查看tushare缺失的记录在哪些天
[x for x in jq_data.index.tolist() if x not in ts_data.index.tolist()]
`

**Comment by zhangdichina** [comment]
如何退订这个邮件列表呢

发自我的 iPad

在 2018年8月29日，上午9:06，northcheng <notifications@github.com<mailto:notifications@github.com>> 写道：


无意中发现, 对比聚宽获取的股票数据, tushare有缺失数据的情况, 以601318中国平安为例:

同样获取从2007-03-01至2018-08-29的数据, 聚宽返回2805条, tushare返回2734条,
其中tushare缺失的天数包括但不限于
[Timestamp('2007-03-19 00:00:00'),
Timestamp('2007-06-07 00:00:00'),
Timestamp('2007-09-04 00:00:00'),...

代码如下:
`
from jqsdk import *
import tushare as ts

获取股票信息

sec_info = get_security_info('601318.XSHG')

tushare数据

ts_data = ts.get_k_data(code='601318',start=sec_info.start_date.strftime('%Y-%m-%d'), end='2018-09-01')

转化为时间序列

ts_data = util.df_2_timeseries(ts_data, 'date')

聚宽数据

jq_data = get_price('601318.XSHG', start_date=sec_info.start_date.strftime('%Y-%m-%d'), end_date='2018-09-01')

对比两个平台的记录数

len(ts_data), len(jq_data)

查看tushare缺失的记录在哪些天

[x for x in jq_data.index.tolist() if x not in ts_data.index.tolist()]
`

**Comment by northcheng** [comment]
我也不知道😂

发自我的 iPhone

**Comment by jimmysoa** [comment]
可以用pro版的接口，未来数据接口都用tushare自己的数据源。 https://tushare.pro/document/2?doc_id=27 ，可能两次取到数据。
