### ISSUE TITLE
pro.forecast和pro.express返回数据有误

### ISSUE THREAD

**Issue by mfkvfn** [waditu/tushare#734]
pro.forecast(end_date='20171231')
中返回的数据的报告期全是20171231
pro.forecast(end_date='20170930')
中返回的数据的报告期有的是20171231有的是20170930
pro.forecast(end_date='20170630')
中返回的数据的报告期有的是20171231有的是20170630

应该每个结果里只包含1种报告期。
上面3个参数值只是举例，实情上传入任何end_date参数，结果集中80%以上都会出现2种报告期的数据。

pro.express也有类似的问题

**Comment by jimmysoa** [comment]
这个接口后来是调整了参数设置，不能只输入end_date
