### ISSUE TITLE
Pycharm ImportError: No module named tushare

### ISSUE THREAD

**Issue by shuijinliuxi** [waditu/tushare#74]
import tushare
print tushare.**version**

我是新手，这样应该怎么处理呢，是MAC上的

**Comment by denglj** [comment]
看清楚pycharm所使用的python解释器，是否与你安装tushare的对应。

比如常见的情况，如你系统中存在多个版本的python。你在系统中用pip install 安装了包，默认安装到了pip所在的解释器环境下，比如python3. 而你pycharm却使用的是python2的解释器，当然就找不到。

如果理不清关系，非要用pycharm作为IDE的话，那就用pycharm中自带的python包安装功能去安装，而不是在系统中用pip/setuptools去安装。

**Comment by jimmysoa** [comment]
@denglj 解释的很到位，谢谢！

**Comment by GeekHades** [comment]
在PyCharm 重新安装一次
