### ISSUE TITLE
tushare.pro.client.DataApi的tcp接口如何使用？

### ISSUE THREAD

**Issue by Silver-Fang** [waditu/tushare#741]
>>> from tushare.pro import client
>>> from tushare.util import upass
>>> token=upass.get_token()
>>> pro=client.DataApi(token,protocol='tcp')
>>> pro.daily_basic(ts_code='000001.sz',start_date='19910403',end_date='20180902')
这样似乎不对，取不到数据，还是说这个功能还在开发？

**Comment by jimmysoa** [comment]
暂时没有开放
