### ISSUE TITLE
ImportError No module named MySQLdb

### ISSUE THREAD

**Issue by seamanshen** [waditu/tushare#75]
Python 3.5 : Anaconda3-2.4.0-Windows-x86.exe 
when execute  -----------------

from sqlalchemy import create_engine
import tushare as ts

df = ts.get_tick_data('600848', date='2014-12-22')
engine = create_engine('mysql://user:passwd@127.0.0.1/db_name?charset=utf8')

it report "ImportError No module named MySQLdb" ; 

from python-mysql website , it only support 2.7 version , so what can i do ?

**Comment by denglj** [comment]
you can use [mysqlclient](https://github.com/PyMySQL/mysqlclient-python) instead. it support py3.
after installed :
```python
>>> import MySQLdb
>>>
```
have a good day !
