### ISSUE TITLE
get_realtime_quotes 返回值的类型

### ISSUE THREAD

**Issue by chrjxj** [waditu/tushare#750]
现在 get_realtime_quotes 返回 df中的数字其实都是字符串类型。建议数字直接返回成浮点数。

如下，无论 df 是否转换成records, 其中的bid/ask price/vol 都是字符串。
```
        df = ts.get_realtime_quotes(context.universe)
        records = df.to_dict('records')
```

**Comment by jimmysoa** [comment]
暂时先用pandas的功能转一下dtype吧
