### ISSUE TITLE
架构改进建议

### ISSUE THREAD

**Issue by dindom999** [waditu/tushare#751]
作为4年多来的老用户，今天在Ipython里试用了一下新的PRO版本，发现一个小不便：当
`pro = ts.pro_api()`
之后，开始使用pro，但pro.(Tab)之后，没有显示任务代码提示。在接口和参数众多的情况下，这是很不友好的。后来我粗略翻看了一下代码，发现pro是一个实例

https://github.com/waditu/tushare/blob/b4be26992671b4cc810a4fc3d1c259db8b2fc54b/tushare/pro/data_pro.py#L20

这种方式应该有可以改进的空间，比如把pro跟旧版本并行
`import tushare as ts`
`import tushare.pro as pro`

**Comment by jimmysoa** [comment]
新版和旧版是兼容的，新版API由于是动态API，所以暂时还不能通过TAB的方式调出，未来我们会加强文档和api搜索功能，谢谢建议。
