### ISSUE TITLE
pro.suspend()用久了会挂

### ISSUE THREAD

**Issue by lushengsheng** [waditu/tushare#753]
两三百个循环后挂住了：
for c in codes:
  df=pro.suspend(ts_code=c)
  df.to_csv(fn)
  time.sleep(0.5)

**Comment by jimmysoa** [comment]
挂是报了什么错误还是什么？

**Comment by lushengsheng** [comment]
suspend()永远不返回。强制关闭进程重新运行正常，但是过一段时间会重复出现问题。建议设置超时返回错误代码，或者抛出异常

**Comment by lushengsheng** [comment]
发现daily()也会出现调用不返回问题，超时设置还是必须的

**Comment by jimmysoa** [comment]
高频调取，多线程都会被限制
