### ISSUE TITLE
出错 AttributeError: 'NoneType' object has no attribute 'head'

### ISSUE THREAD

**Issue by jzhuang88** [waditu/tushare#757]
使用以下代码时

import tushare as ts
df = ts.get_tick_data('600848',date='2014-01-09')
df.head(10)

出现下列错误

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-96c85d3996b8> in <module>()
      1 import tushare as ts
      2 df = ts.get_tick_data('600848',date='2014-01-09')
----> 3 df.head(10)
      4 print(df)

AttributeError: 'NoneType' object has no attribute 'head'

**Comment by jimmysoa** [comment]
太久远的历史目前不提供了，另外要设置src参数等于tt

**Comment by jzhuang88** [comment]
请问怎么设这个SRC？能给个例子吗？谢谢

**Comment by jimmysoa** [comment]
源代码里有注明
