### ISSUE TITLE
get_hs300s提示404 Not found

### ISSUE THREAD

**Issue by StockSoft** [waditu/tushare#76]
In [22]: ts.__version__
Out[22]: '0.3.8'

In [24]: ts.get_hs300s()
HTTP Error 404: Not Found

**Comment by jimmysoa** [comment]
升级一下

**Comment by jimmysoa** [comment]
In [5]: ts.get_hs300s()
Out[5]: 
       code   name        date  weight
0    000001   平安银行  2015-09-01    0.76
1    000002    万科Ａ  2015-09-01    1.58
2    000009   中国宝安  2015-09-01    0.15
3    000024   招商地产  2015-09-01    0.38
4    000027   深圳能源  2015-09-01    0.15
5    000039   中集集团  2015-09-01    0.19
6    000046   泛海控股  2015-09-01    0.17
7    000060   中金岭南  2015-09-01    0.16
8    000061  农 产 品  2015-09-01    0.15
9    000063   中兴通讯  2015-09-01    0.45
10   000069   华侨城Ａ  2015-09-01    0.34
