### ISSUE TITLE
daily返回的数据包含停牌日期的

### ISSUE THREAD

**Issue by GavinGavinNo1** [waditu/tushare#763]
因为包含停牌日的数据，导致顺序计算macd等指标的时候出错。（虽然有办法解决，通过判断这天是不是停牌，但是不太友好）。

eg: 000001.SZ 2004-06-30 是停牌日，但是daily返回会包含这天数据。

**Comment by jimmysoa** [comment]
目前停牌日期是跟随了停牌前一个交易日的数据，后面我再确认是否删除。
