### ISSUE TITLE
新浪股票新闻取不到数据了，get_latest_news(), list index out of range

### ISSUE THREAD

**Issue by cywxf** [waditu/tushare#765]
新浪股票新闻取不到数据了
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tushare as ts
>>> ts.get_latest_news()
list index out of range
>>>

**Comment by foxaaa** [comment]
我也遇到了这个问题，是不是这个接口准备下线了呢

**Comment by jimmysoa** [comment]
尽快修复，另外，新闻接口也会迁移到pro版，同时提供历史数据。

**Comment by mickyss** [comment]
迁移到pro版是指社区版不再有这个数据了吗

**Comment by jimmysoa** [comment]
Pro的数据更有保证，服务更可靠，一年后老版将不再维护。

**Comment by aaronyunzhao** [comment]
@jimmysoa 您好，请问该issue是否还会修复？

**Comment by jimmysoa** [comment]
org版本不做修复，请使用pro新闻数据：https://tushare.pro/document/2?doc_id=143
