### ISSUE TITLE
get_hist_data 60分钟级数据 没有2018-10-11日的数据

### ISSUE THREAD

**Issue by martinrises** [waditu/tushare#769]
![image](https://user-images.githubusercontent.com/6435523/46843346-e7443c80-ce04-11e8-8686-110aeca0174e.png)

**Comment by martinrises** [comment]
get_k_data 使用正常

**Comment by jimmysoa** [comment]
这个接口的数据源不太好，建议切换到ts.bar或Pro版的pro_bar未来的分钟接口（目前分钟还没开放，只有daily）

**Comment by matols** [comment]
> 这个接口的数据源不太好，建议切换到ts.bar或Pro版的pro_bar未来的分钟接口（目前分钟还没开放，只有daily）

啥时候开放分钟级数据了呢？
