### ISSUE TITLE
【需求】【港股】持股变化分析

### ISSUE THREAD

**Issue by azalpy** [waditu/tushare#770]
核心要点：
通过各大 **市场参与者** 的 **持股变化** 数据反应出一个股票宏观的持仓数据。

技术点：
1. 识别市场参与者
2. 获取并分析持股变化数据

参考：
http://sc.hkexnews.hk/TuniS/www.hkexnews.hk/sdw/search/searchsdw_c.aspx

输入 0700 后，可以看到数据里有 市场参与者（可以通过港交所获取完整的参与者列表） 和 持股数据，每支股票的数据可以放到pandas里，然后多个日期的数据进行 输出 或者 展示（可以参考类似http://echarts.baidu.com/examples/editor.html?c=line-stack 这样的多折现）

tushare.pro 账号：azalpy@foxmail.com

**Comment by jimmysoa** [comment]
收到，我们会统一规划和采集输出，谢谢，积分已赠送到账户。

**Comment by rockyzhaohui** [comment]
这个数据可以自己抓下来
