### ISSUE TITLE
需求：数据注明时效性

### ISSUE THREAD

**Issue by ZhYong10** [waditu/tushare#772]
接口数据请注明时效性。
需求举例
```pro.daily```：盘后16点更新。盘中不存在当日数据。
```ts.bar(freq='1min')```：盘中实时更新
```pro.daily_basic```：盘后15:30点更新，可能不更新。（我其实不知道这个接口是什么时候更新，是否一定会每天更新）

备注时效性，方便用户实践调用策略。
比如：
```pro.daily```：16点前不保证数据存在。因而推荐用户在16点后，仅调用一次入库即可。
```ts.bar(freq='1min')```：盘中可实时取用，无需等待盘后。若盘中
```pro.daily_basic```：不承诺数据时效，因而用户可以调用，但仅供参考。

综上：
承诺时效性的数据，请备注时效性，比如：盘后16点、盘中延时2分钟内、每周收盘后，等等。
不承诺时效性的数据，请备注，比如随机更新、随心情更新、开发中暂不承诺时效性、视服务器压力情况暂不承诺时效性，等等。

时效性检验与变更：
时效性BUG：时效性满足后，数据未生成。比哪盘后16点未能获取到当日行情，可能是pro服务有误，可报BUG。
时效性变更：时效性变更后，修改接口说明。比如原定于每天16点更新的行情，因服务器压力，改为承诺每天16:30后更新。用户在16:30前不要再调用服务。

**Comment by jimmysoa** [comment]
行情的意见修正，加了更新时间，以后新上接口会提示。
