### ISSUE TITLE
daily_basic换手率turnover_rate与其他接口不同

### ISSUE THREAD

**Issue by Allen-Cee** [waditu/tushare#774]
如600267在20180928的换手率为1.80%
daily_basic的turnover_rate为3.1213
bar的tor为1.8
day_all的turnover为1.8

请问是有误还是算法/数据源不同？

**Comment by jimmysoa** [comment]
本接口有两个指标：
turnover_rate | float | 换手率
turnover_rate_f | float | 换手率（自由流通股）
