### ISSUE TITLE
安装tushare提示No module named 'lxml'

### ISSUE THREAD

**Issue by sirs05** [waditu/tushare#78]
安装lxml提示缺另一个组件。。另一个组件装不上。。

**Comment by sirs05** [comment]
另一个组件是libxml2

**Comment by holsety** [comment]
mac 下使用 
brew install libxml2
brew install libxslt

ubuntu 下使用
apt-get install libxml2-dev libxslt1-dev python-dev

[refer](http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu)
