### ISSUE TITLE
fina_indicator接口数据错误

### ISSUE THREAD

**Issue by MrLpk** [waditu/tushare#780]
pro.fina_indicator(ts_code='600519.SH', start_date='20080101', end_date='20141231')
会出现如下数据
            ts_code  ann_date  end_date    eps  dt_eps
......
27  600519.SH  20080313  20071231   3.00    3.00
28  600519.SH  20080313  20061231   1.64    1.64  
27和28中间缺少06年季报数据
但是pro.fina_indicator(ts_code='600519.SH', start_date='20060101', end_date='20121231')则不会

**Comment by jimmysoa** [comment]
单次调取有条数限制，可以把start和end访问缩小一点

**Comment by MrLpk** [comment]
应该不是条数问题
pro.fina_indicator(ts_code='600519.SH', start_date='20080101', end_date='20081231')
API写了条数限制是30个，上面的语句查询一年，返回5条，但在3和4中间仍然少了季报数据，而且2006年的年报在2008年公布也不太对啊
     ts_code  ann_date  end_date   eps    
0  600519.SH  20081027  20080930  3.33    
1  600519.SH  20080828  20080630  2.37  
2  600519.SH  20080422  20080331  0.93  
3  600519.SH  20080313  20071231  3.00   
4  600519.SH  20080313  20061231  1.64
