### ISSUE TITLE
income 数据记录错误

### ISSUE THREAD

**Issue by swuecho** [waditu/tushare#786]
![image](https://user-images.githubusercontent.com/666683/47616404-2a85f700-daf7-11e8-89f8-7da7d69b3d5b.png)

如上图，这个估计是数据源的错误？能否告知数据源在哪？

**Comment by swuecho** [comment]
![image](https://user-images.githubusercontent.com/666683/47616485-5e155100-daf8-11e8-98fc-376e6dcbd277.png)

**Comment by swuecho** [comment]
另外，ts_code 和 end_date 是否可以作为unique  constraint？

感觉一个时间段应该只有一个报告？

**Comment by jimmysoa** [comment]
可能要确认一下是否有修正

**Comment by jimmysoa** [comment]
看了一下，这个股票2017年一季度有过一次修正，ebit，息税前利润数据不一样。
