### ISSUE TITLE
部分股票日线数据缺失

### ISSUE THREAD

**Issue by jcchao** [waditu/tushare#787]
查询条件：
ts_api.daily(ts_code=ts_code, start_date='20080901', end_date='20180901')
缺失的股票日线数据：
['300760.SZ', '603790.SH', '601162.SH', '603297.SH', '603583.SH', '603810.SH', '300749.SZ', '300748.SZ', '002937.SZ', '002935.SZ', '601577.SH', '002940.SZ', '300694.SZ', '002938.SZ', '002936.SZ']
这些ts_code的数据在上述条件下查不到。

tushare id: 534056680@qq.com

**Comment by jimmysoa** [comment]
都是新股吧？这个时间点还没上市
