### ISSUE TITLE
建议：将pro接口返回的日线数据日期格式恢复成yyyy-mm-dd

### ISSUE THREAD

**Issue by wupeng606** [waditu/tushare#789]
米哥 你好，

有点纳闷为什么 pro 接口为什么不继续使用原来的数据中的日期格式：yyyy-mm-dd。
强烈建议使用原来的格式。
我特别查询了一下，财经接口，包括google API, yahoo API, 包括tushare原来的数据格式用的都是YYYY-MM-DD 的格式。而且yyyy-mm-dd 是唯一认可的ISO国际标准。zipline/pyalgotrade 接受的日期标准也是yyyy-mm-dd。

pro 接口改变了日期格式，还有股票代码改成这种格式: "600001.SH ", 原来的代码更新的工作量也会比较多。

请原谅，我没有看到这么改的好处，个人认为这么改只有坏处。

个人意见，希望能够被采纳！

另外： "600001.SH " 建议也恢复成之前的格式，如果一定需要区分，可以考虑加一个”类别“字段。

**Comment by jimmysoa** [comment]
日期格式我们最后统一为数字代码的日期，对业务没有影响
