### ISSUE TITLE
基金数据如何获取？如何检索高送转的股票？

### ISSUE THREAD

**Issue by bannychen1983** [waditu/tushare#79]

**Comment by jimmysoa** [comment]
基金数据目前可以通过tushare调用通联数据实现，获取高送转股票如下：
df = ts.profit_data(2015)

     code  name  year report_date  divi  shares
0   600705  中航资本  2015  2015-12-11   0.9       0
1   002730  电光科技  2015  2015-12-10   0.0      12
2   000566  海南海药  2015  2015-12-10   0.0      10
3   300066  三川股份  2015  2015-12-09   0.5      15
4   002654  万润科技  2015  2015-12-08   0.5      20
5   002418  康盛股份  2015  2015-12-08   1.0      20
6   000838  财信发展  2015  2015-12-08   0.0      25
7   300094  国联水产  2015  2015-12-07   0.0      12
8   002584  西陇科学  2015  2015-12-01   1.0      15
9   002622  永大集团  2015  2015-12-01   0.0      10
10  603703  盛洋科技  2015  2015-11-25   0.0      15
11  002536  西泵股份  2015  2015-11-24   2.0      20
12  002555  顺荣三七  2015  2015-11-20   1.0      10
13  603885  吉祥航空  2015  2015-10-31   6.0      10
14  600763  通策医疗  2015  2015-10-31   0.0      10

**Comment by bannychen1983** [comment]
many thanks
