### ISSUE TITLE
ts.pro_bar(freq='1MIN')返回None

### ISSUE THREAD

**Issue by qualg** [waditu/tushare#791]
In [47]: dt = ts.pro_bar(pro_api=pro, ts_code='000001.SZ', start_date='20181001'
    ...: , end_date='20181011', adj='qfq', freq='D')

In [48]: dt
Out[48]: 
              ts_code trade_date   open   high    low  close  pre_close  \
trade_date                                                                
20181011    000001.SZ   20181011  10.05  10.16   9.70   9.86      10.45   
20181010    000001.SZ   20181010  10.54  10.66  10.38  10.45      10.56   
20181009    000001.SZ   20181009  10.46  10.70  10.39  10.56      10.45   
20181008    000001.SZ   20181008  10.70  10.79  10.45  10.45      11.05   

            change  pct_change         vol       amount  
trade_date                                               
20181011     -0.59     -5.6459  1995143.83  1994186.611  
20181010     -0.11     -1.0417   995200.08  1045666.180  
20181009      0.11      1.0526  1064084.26  1117946.550  
20181008     -0.60     -5.4299  1686358.52  1793455.283  

In [49]: dt = ts.pro_bar(pro_api=pro, ts_code='000001.SZ', start_date='20181001'
    ...: , end_date='20181001', adj='qfq', freq='1min')

In [50]: dt

In [51]:

**Comment by jimmysoa** [comment]
pro版还没有上线分钟数据，谢谢。
