### ISSUE TITLE
stock_basic函数获得的结果不全

### ISSUE THREAD

**Issue by zhanguoce** [waditu/tushare#792]
ts_code
0     000001.SZ
1     000002.SZ
2     000004.SZ
3     000005.SZ
4     000006.SZ
5     000007.SZ
6     000008.SZ
7     000009.SZ
8     000010.SZ
9     000011.SZ
10    000012.SZ
11    000014.SZ
12    000016.SZ
13    000017.SZ
14    000018.SZ
15    000019.SZ
16    000020.SZ
17    000021.SZ
18    000022.SZ
19    000023.SZ
20    000025.SZ
21    000026.SZ
22    000027.SZ
23    000028.SZ
24    000029.SZ
25    000030.SZ
26    000031.SZ
27    000032.SZ
28    000034.SZ
29    000035.SZ
...         ...
3526  603936.SH
3527  603937.SH
3528  603938.SH
3529  603939.SH
3530  603955.SH
3531  603958.SH
3532  603959.SH
3533  603960.SH
3534  603963.SH
3535  603966.SH
3536  603968.SH
3537  603969.SH
3538  603970.SH
3539  603976.SH
3540  603977.SH
3541  603978.SH
3542  603979.SH
3543  603980.SH
3544  603985.SH
3545  603986.SH
3546  603987.SH
3547  603988.SH
3548  603989.SH
3549  603990.SH
3550  603991.SH
3551  603993.SH
3552  603996.SH
3553  603997.SH
3554  603998.SH
3555  603999.SH

[3556 rows x 1 columns]

**Comment by jimmysoa** [comment]
不知道你说的不全是什么

**Comment by Lawrence1108** [comment]
获取时若没有指定fields 默认回返回 "ts_code","symbol", "name","area","industry", "market", "list_date"这7个字段的数据，若需要获取所有字段的数据 需指定	
"fields":"ts_code,symbol,name,area,industry,fullname,enname,market,exchange,curr_type,list_status,list_date,delist_date,is_hs"

**Comment by jimmysoa** [comment]
@Lawrence1108 赞

**Comment by Lawrence1108** [comment]
> @Lawrence1108 赞

能获得积分么？谢谢米哥，哈哈 id:215781
