### ISSUE TITLE
能否提供Level-2的历史tick data？

### ISSUE THREAD

**Issue by philipchung007** [waditu/tushare#8]

**Comment by ideaplat** [comment]
level-2需要对接ctp，股票的还不稳定，期货的需要收费

**Comment by jimmysoa** [comment]
目前还不能提供，level-2是收费数据，tushare所有的数据都是免费提供的。

**Comment by tommford1990** [comment]
怎么可以下载历史期货数据？

import tushare as ts
ts.get_hist_data('IC1607')

四大期货交易所的‘exchangeCD’ 是什么？我知道一个是"CCFX"

谢
