### ISSUE TITLE
能不能不要 write_console ?

### ISSUE THREAD

**Issue by emptist** [waditu/tushare#80]
比如下載數據時, 就會寫 [Downloading data]### 
這些很煩,因為 stdout 經常要用到. 提示沒有必要的時候不需要弄.
從nodejs讀取 Python Shell 輸出的JSON時,就很麻煩 

這些提示對程序員有用嗎?
浪費了整個下午才發現問題,乾脆全部把源代碼改了,統統pass

個人認為作為庫的話,出錯時揭示即可(用sys.stderr),其他提示是應用層面的事情.

**Comment by chinawrj** [comment]
搞个参数，quiet=1
