### ISSUE TITLE
fund_daily返回了错误数据

### ISSUE THREAD

**Issue by chenyizhe** [waditu/tushare#800]
df = pro.fund_daily(trade_date='20080102')
df.loc[df['ts_code']=='150001!1.SZ']
以上命令返回了如下数据：
67  150001!1.SZ   20080102  1.408     ...          0.5722  551447.01  77407.7552

代码ts_code有错误，应该是6位+.SZ的，中间有感叹号！

ID：13632771963

**Comment by jimmysoa** [comment]
已处理
