### ISSUE TITLE
指数（000300.SH）成分权重数据不能获取

### ISSUE THREAD

**Issue by leonfeng2010** [waditu/tushare#801]
除了000300.SH，其他中证500、创业板指成分权重数据获取正常。

以下是获取000300.SH的过程
df = pro.index_weight(index_code='000300.SH', start_date='20180102', end_date='20181102')

tushare ID:  leonfeng2010

**Comment by jimmysoa** [comment]
月度指数，请把时间跨度调到一个月或以上

**Comment by jimmysoa** [comment]
月度数据

**Comment by leonfeng2010** [comment]
> 月度指数，请把时间跨度调到一个月或以上

我给的时间跨度是10个月的。不过问题已解决，不能用000300.SH，而用399300.SZ即可。

**Comment by hardywu** [comment]
@jimmysoa  碰到同样问题。 000300.SH 获取不到数据。

**Comment by hkg36** [comment]
这开发的态度真实差，眼睛瞎的，要不国内的平台都是一样垃圾我都想投诉了
