### ISSUE TITLE
资金流向接口有异常数据，moneyflow_hsgt

### ISSUE THREAD

**Issue by LeoZeda** [waditu/tushare#804]
通过http请求接口moneyflow_hsgt，时间在
`   "start_date": "20171228",
    "end_date": "20180103"`
之间有异常数据返回， 如下图。

![image](https://user-images.githubusercontent.com/8565999/47996651-2fb8f680-e134-11e8-9d2f-7871e80ef46a.png)

欢迎奖励积分
邮箱：max_lzd@163.com

**Comment by jimmysoa** [comment]
已修复，积分已到帐
