### ISSUE TITLE
初次安装时不会默认安装bs4

### ISSUE THREAD

**Issue by xyx518809** [waditu/tushare#807]
ubuntu 18.04
python 3.6.6
问题:
        新装的系统,安装tushare后,编写范例代码,
        报错:No module named 'bs4'
        安装bs4后解决
        好像在随便哪个文件里 import bs4 就可以解决
tushare id 小徐竹子

**Comment by krizex** [comment]
https://github.com/waditu/tushare/pull/735 修复了这个问题

**Comment by krizex** [comment]
#735

**Comment by jimmysoa** [comment]
1.2.16版本已经修正
