### ISSUE TITLE
daily数据缺失

### ISSUE THREAD

**Issue by Allen-Cee** [waditu/tushare#808]
调用`pro.daily(ts_code='000025.SZ')`时返回数据有缺失。

验证发现缺少2001-11-12以前数据，相应`ts.bar('000025', conn = cons)`可以获得全部数据，建议进行交叉验证并补全缺失数据。

另外，`ts.tick`数据在较早时间的缺失也较多，希望能够补全，或尽快推出新接口。感谢！

用户ID：18810818218

**Comment by jimmysoa** [comment]
默认有条数限制,可以通过start_date/end_date指定获取到那段时间的
