### ISSUE TITLE
tick数据错误

### ISSUE THREAD

**Issue by Allen-Cee** [waditu/tushare#812]
调用ts.tick('000735', conn = cons, date = '2010-04-07')时返回数据部分错误。

验证发现13:05-13:14分价格数据从9元突变为3000多元。

另外，`ts.tick`数据在较早时间的缺失也较多，希望能够补全，或尽快推出新接口。感谢！

用户ID：18810818218

**Comment by jimmysoa** [comment]
这个是网络数据,目前我不能控制质量,另外,我并没有重现这个问题.
