### ISSUE TITLE
trade_cal

### ISSUE THREAD

**Issue by AZhenWang** [waditu/tushare#814]
获取交易日历的这个接口：trade_cal
pro = ts.pro_api()
pro.trade_cal(exchange='', start_date='', end_date='')

当开始时间穿空字符串‘’时，获取到的日历最多只到20180506，返回的数据就在原来的20180516。多次尝试的结果都是1万条数据，难道限制了这个交易日历最多返回1万条吗？

**Comment by jimmysoa** [comment]
是的,最好是写入日期吧
