### ISSUE TITLE
index_dailybasic 数据错误

### ISSUE THREAD

**Issue by hellobiek** [waditu/tushare#816]
上交所的数据：http://www.sse.com.cn/market/stockdata/overview/day/
对比2018-11-07的数据
tushare 获取的数据：
<img width="391" alt="tushare" src="https://user-images.githubusercontent.com/2854520/48244735-2674a600-e422-11e8-881b-4a838d899ee3.png">

其中
上交所的数据
<img width="897" alt="default" src="https://user-images.githubusercontent.com/2854520/48244745-2c6a8700-e422-11e8-91b8-dae631a0b76e.png">

可以到total_mv（总市值）的差距非常大，希望能确认下数据源。

**Comment by jimmysoa** [comment]
包含了暂停上市的数据，我们确认一下看哪种最好，谢谢。
