### ISSUE TITLE
访问次数限制Exception，希望能够有个专门的Exception，方便捕获处理和等待重试

### ISSUE THREAD

**Issue by dearpanan** [waditu/tushare#818]
现状：
line 75, in req_http_api
    raise Exception(result['msg'])
Exception: 抱歉，您每分最多访问该接口80次:-(，详情访问：https://tushare.pro/document/1?doc_id=108。

建议：raise 类似ReqFreException这里特殊异常，方便处理。
 raise ReqFreException(result['msg'])

----------------------------
tushare-id，18502719062

**Comment by zhouguangfu** [comment]
直接修改client.py的代码对该异常进行捕获即可

**Comment by jimmysoa** [comment]
下一版我们处理一下
