### ISSUE TITLE
问题: pro接口股票行情返回条数和复权因子不一致

### ISSUE THREAD

**Issue by iorilu** [waditu/tushare#820]
复权因子数据返回更多, 应该是复权因子接口返回数据没有去掉股票停牌日期

能否调整为一致呢, 因为复权因子下载后一般要和股票数据进行合并

当然自己合并也可以, 如果一致更好

社区id: 128728

**Comment by jimmysoa** [comment]
请以股票行情为主，可以merge的时候设置how=‘left'（行情df）
