### ISSUE TITLE
fina_indicator 部分股票同一报告期有两条几乎相同的记录

### ISSUE THREAD

**Issue by frederichchen** [waditu/tushare#821]
代码如下：
df = pro.query('fina_indicator',ts_code='600031.SH', start_date='20161231', end_date='20171231')

会得到下面的结果
     ts_code  ann_date  end_date     eps  dt_eps     ...       tr_yoy   or_yoy  q_sales_yoy  q_op_qoq  equity_yoy
0  600031.SH  20180417  20171231  0.2733  0.2674     ...      64.6691  64.6691      49.8586  -40.0886     12.2382
1  600031.SH  20180417  20171231  0.2733  0.2674     ...      64.6691  64.6691      49.8586  -40.0886     12.2382
2  600031.SH  20171031  20170930  0.2360  0.2360     ...      70.7680  70.7680      69.8668   20.6102      6.5863
3  600031.SH  20171031  20170930  0.2360  0.2360     ...      70.7680  70.7680      69.8668   20.6102      6.5863
4  600031.SH  20170830  20170630  0.1510  0.1510     ...      71.1913  71.1913      64.0524  -30.4894      3.4780
5  600031.SH  20170830  20170630  0.1510  0.1510     ...      71.1913  71.1913      64.0524  -30.4894      3.4780
6  600031.SH  20170428  20170331  0.0970  0.0970     ...      79.3752  79.3752      79.3752    2.0916     -0.5390
7  600031.SH  20170428  20161231  0.0267  0.0267     ...      -0.8107  -0.8107      37.5913  845.9780     -3.0798

经仔细核对第0行和第1行，发现除了 bps 和 bps_yoy 两个字段的值不同，其余字段均相同。比较第2行和第3行，第4行和第5行也有同样的情况，再往前的 end_date 为 20170331 和 20161231 的则只有一条记录，不知道有两条记录的情况是什么原因造成的？

我的 tushare pro 的 ID 是： frederichchen@163.com

**Comment by jimmysoa** [comment]
数据是Point IN time模式，没有问题
