### ISSUE TITLE
pro_bar接口返回的复权后数据,只有open,high,low,close是复权的, 其他的都还是未复权数据

### ISSUE THREAD

**Issue by SunYusheng** [waditu/tushare#822]
例如获取000001.SZ 1998年hfq数据, 接口返回的数据为:
` {}"ts_code" : "000001.SZ", "trade_date" : "19980327", "open" : 444.96, "high" : 459.72, "low" : 443.27, "close" : 453.18, "pre_close" : 21.15, "change" : 0.34, "pct_change" : 1.61, "vol" : 41937, "amount" : 89629.4968 }`
而pre_close应为446.01, 等等.

id=131486

**Comment by jimmysoa** [comment]
pre_close并没有加到复权数据里，我加一下吧
