### ISSUE TITLE
关于股票信息能否增加流通市值、总市值这样的数据

### ISSUE THREAD

**Issue by kksskkss** [waditu/tushare#823]
如题。关于股票信息能否增加流通市值、总市值这样的数据。现在感觉信息太少

**Comment by jimmysoa** [comment]
已经有了的，daily_basic


名称 | 类型 | 描述
-- | -- | --
ts_code | str | TS股票代码
trade_date | str | 交易日期
close | float | 当日收盘价
turnover_rate | float | 换手率
turnover_rate_f | float | 换手率（自由流通股）
volume_ratio | float | 量比
pe | float | 市盈率（总市值/净利润）
pe_ttm | float | 市盈率（TTM）
pb | float | 市净率（总市值/净资产）
ps | float | 市销率
ps_ttm | float | 市销率（TTM）
total_share | float | 总股本 （万）
float_share | float | 流通股本 （万）
free_share | float | 自由流通股本 （万）
total_mv | float | 总市值 （万元）
circ_mv | float | 流通市值（万元）

**Comment by kksskkss** [comment]
谢谢您的回复，谢谢您给的积分。~~~~~~
看来还是我不太适应新版的这个接口，我在继续多熟悉一下。
祝好！




450816204@qq.com
 
发件人： Jimmy
发送时间： 2018-11-13 17:34
收件人： waditu/tushare
抄送： kksskkss; Author
主题： Re: [waditu/tushare] 关于股票信息能否增加流通市值、总市值这样的数据 (#823)
已经有了的，daily_basic
名称
类型
描述
ts_code str TS股票代码 
trade_date str 交易日期 
close float 当日收盘价 
turnover_rate float 换手率 
turnover_rate_f float 换手率（自由流通股） 
volume_ratio float 量比 
pe float 市盈率（总市值/净利润） 
pe_ttm float 市盈率（TTM） 
pb float 市净率（总市值/净资产） 
ps float 市销率 
ps_ttm float 市销率（TTM） 
total_share float 总股本 （万） 
float_share float 流通股本 （万） 
free_share float 自由流通股本 （万） 
total_mv float 总市值 （万元） 
circ_mv float 流通市值（万元）
