### ISSUE TITLE
使用pro_bar获取前复权行情，获取的数据都未复权

### ISSUE THREAD

**Issue by xuecn** [waditu/tushare#824]
使用pro_bar获取前复权行情，获取的数据都未复权，和日线数据一致，无复权

直接运行官网的示例，获取的前复权数据也是未复权，烦请协查

tushare账户：xuxue04403@163.com

**Comment by jimmysoa** [comment]
这要看看是否有复权，另外，怎么使用请把代码发出来。

**Comment by xuecn** [comment]
> 这要看看是否有复权，另外，怎么使用请把代码发出来。
代码:
import tushare as ts
api = ts.pro_api('47ae0390a428efd1cfee7592150b9f28ad8c5ff841d624457999e5a8')
df = ts.pro_bar(pro_api=api, ts_code='000001.SZ', adj='qfq', start_date='20180101', end_date='20181011')
data_qfq = df.ix[1:100,[1,2,3,4,5,6]]
print(data_qfq)

**Comment by xuecn** [comment]
![default](https://user-images.githubusercontent.com/44995619/48696062-cd73f180-ec1b-11e8-935f-c93b0638d4e9.png)

**Comment by xuecn** [comment]
> 这要看看是否有复权，另外，怎么使用请把代码发出来。

以上是代码和运行结果的截图，请查看并帮忙解决，谢谢

**Comment by jimmysoa** [comment]
本来就是这个数据哇，你有没有对照别的数据

**Comment by xuecn** [comment]
> 本来就是这个数据哇，你有没有对照别的数据


![tim 20181121144255](https://user-images.githubusercontent.com/44995619/48823464-e5727f00-ed9b-11e8-9031-696b1cf451bf.png)

比对过，这个获取到的就是日线数据，根本不是前复权数据
这段代码实际上就是官网上提供的示例代码，以上为官网截图，请查看

**Comment by jimmysoa** [comment]
你去通达信或者其他行情软件对比一下，这段时间的前复权。但是所有行情软都是以最近一天交易日开始复权的，而Tushare是从end_date日期开始的，要注意一下

**Comment by IMYin** [comment]
前复权数据无法获取。我对照了同花顺中的数据，虽然adj参数的值为'qfq'，但是获取到的数据依然是未赋权的。
![image](https://user-images.githubusercontent.com/11770037/50088422-f77dfb00-023d-11e9-91cd-6fb5a06f8889.png)

![image](https://user-images.githubusercontent.com/11770037/50088439-01076300-023e-11e9-9a41-09c573d39834.png)
