### ISSUE TITLE
关于通过Matlab SDK获取数据报错以及解决方法

### ISSUE THREAD

**Issue by North24** [waditu/tushare#825]
使用语句以下语句获取日线数据时会报错：元胞内容引用自非元胞数组对象，出错 pro_api/query (line 98)
                    data = cat(2, results.data.items{:})';
df_dailyadd = api.query('daily', 'ts_code', '000029.SZ', 'start_date', '20181112', 'end_date', '20181114');

原因是股票'000029.SZ'自2016年开始已经停盘，api.query无法获取数据，results.data.items为空，建议改为如下：
                da = results.data.items;
                [Na,~] = size(da);
                if Na>0
                    data = cat(2, results.data.items{:})';
                    data = cell2table(data, 'VariableNames', index);
                end
tushare账户：15850560204

**Comment by jimmysoa** [comment]
我把Matlab的SDK源代码上传到github吧，大家一起维护
