### ISSUE TITLE
通过http获取daily数据异常

### ISSUE THREAD

**Issue by huxiba** [waditu/tushare#826]
curl -X POST -d '{"api_name": "daily", "token","474b55fa90681a402fec61dbc042203e8dxxxxx", "params":{"trade_date":"20181114"}, "fields":"ts_code,trade_date,close"}' http://api.tushare.pro
返回
{"request_id": "c1bb27d0e81211e8aa6cd00dd36710041542202789212392", "code": -1000, "msg": "\u7cfb\u7edf\u5185\u90e8\u9519\u8bef", "data": null}%

而调用stock_basic 则正常。

tushare 账号:huxiba

**Comment by jimmysoa** [comment]
"token","474b55fa90681a402fec61dbc042203e8dxxxxx", 中间应该是：

**Comment by JCYoky** [comment]
> "token","474b55fa90681a402fec61dbc042203e8dxxxxx", 中间应该是：

msg内容是系统内部错误，这种情况下是否应该提示参数错误？
希望能有更加详细的调用参数文档。
