### ISSUE TITLE
函数get_nav_open错误

### ISSUE THREAD

**Issue by lhloki** [waditu/tushare#827]
比如调用get_nav_open(fund_type='equity')会出错，错误原因是return pd.concat(fund_dfs, ignore_index=True)这一句需要的是一个list，而你给出的是一个DataFrame。我的修改是：
fund_dfs = []
        for page in range(1, pages+1):
            fund_dfs.append(_parse_fund_data(ct.SINA_NAV_DATA_URL %
                                       (ct.P_TYPE['http'], ct.DOMAINS['vsf'],
                                        ct.NAV_OPEN_KEY[fund_type],
                                        ct.NAV_OPEN_API[fund_type],
                                        page,
                                        limit_cnt,
                                        ct.NAV_OPEN_T2[fund_type],
                                        ct.NAV_OPEN_T3)))

        return pd.concat(fund_dfs, ignore_index=True)

我的tushare登录是手机号13127900572

**Comment by jimmysoa** [comment]
请使用Pro版的及基金数据，https://tushare.pro/document/2?doc_id=18
