### ISSUE TITLE
如何取得股票相应的前十大股东名单和比例

### ISSUE THREAD

**Issue by aryada** [waditu/tushare#83]
没有找到取得股票相应的前十大股东名单和比例的接口，请大家赐教.

**Comment by jimmysoa** [comment]
目前还没有，下一个版本争取加进来。
BTW，有没有好一点的数据源？

**Comment by skytalemcc** [comment]
可以尝试一下 同花顺的数据源 PC版的软件 F10做的不错。和网页版的是同一个数据源
发自 网易邮箱大师
在2015年12月22日 09:19，Jimmy 写道:

目前还没有，下一个版本争取加进来。
BTW，有没有好一点的数据源？
