### ISSUE TITLE
利润表/资产负债表/现金流量表 建议采用列表类型

### ISSUE THREAD

**Issue by sprlee1975** [waditu/tushare#830]
现在的方式如果增减项次会造成程序的修改，而且分析使用也不灵活。
建议另提供一个返回方式：
输出:

ts_code | str | TS股票代码
ann_date | str | 公告日期
f_ann_date | str | 实际公告日期
end_date | str | 报告期
comp_type | str | 公司类型：1一般工商业 2银行 3保险 4证券
report_type | str | 报表类型：见下方详细说明

report_code| str | 报表类型：见下方详细说明
amount float 金额

**Comment by sprlee1975** [comment]
注册emal: sprlee@qq.com

**Comment by jimmysoa** [comment]
没有懂什么意思，如果没有理解错的话，你可以看一下文档里的 fields参数
