### ISSUE TITLE
get_k_data的一个bug

### ISSUE THREAD

**Issue by sngyai** [waditu/tushare#831]
您好，我在使用的过程中遇到了一个问题：get_k_data不是用start参数时候是能拿到最后一天的数据的；使用start参数就拿不到最后一天的数据了，请问这是tushare的问题，还是我使用的方式有问题呢，万分感谢！
>>> ts.get_k_data("000001")
           date    open   close    high     low     volume    code
0    2016-04-06   8.502   8.534   8.558   8.446   435259.0  000001
1    2016-04-07   8.534   8.430   8.542   8.430   377719.0  000001
2    2016-04-08   8.398   8.414   8.494   8.359   376553.0  000001
3    2016-04-11   8.438   8.534   8.597   8.438   786386.0  000001
..          ...     ...     ...     ...     ...        ...     ...
637  2018-11-14  10.530  10.440  10.550  10.420   774239.0  000001
638  2018-11-15  10.440  10.620  10.640  10.420   901461.0  000001
639  2018-11-16  10.610  10.570  10.720  10.490  1059592.0  000001
640  2018-11-19  10.570  10.850  10.880  10.570  1360887.0  000001

[641 rows x 7 columns]
>>> 
>>> 
>>> ts.get_k_data("000001", start='2018-11-16')
           date   open  close   high    low     volume    code
212  2018-11-16  10.61  10.57  10.72  10.49  1059592.0  000001
>>>

**Comment by jimmysoa** [comment]
本接口不再维护，行情请用pro版接口。https://tushare.pro
