### ISSUE TITLE
some problem about R packages 

### ISSUE THREAD

**Issue by wulixin** [waditu/tushare#833]
Use R  Tusahre package get data , I find your data type and data columns is not very humanly same with many famous  finance packages data type , I am writing a new packages for a stocks analysis and portfolio analysis , and report autoML.

**Comment by jimmysoa** [comment]
这个问题我们也发现了，修复后但是提交到CRAN还没通过

**Comment by wulixin** [comment]
谢谢，总的来说R packages 还是有很大的提升空间的，昨晚我获取stocks_basic数据的时候发现出现了NA缺失值导致获取的表数据错位了，是因为有增加了新的股票导致的原因吗？
