### ISSUE TITLE
pro.fina_indicator里面没有inv_turn存货周转率

### ISSUE THREAD

**Issue by zhuang86123** [waditu/tushare#835]
pro.fina_indicator里面没有inv_turn存货周转率
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-f69772b0f14c> in <module>()
----> 1 df = pro.fina_indicator(ts_code='600271.SH')[['ts_code','end_date','gross_margin','profit_dedt','npta','roe_waa','roa','current_ratio','quick_ratio','ar_turn','assets_turn','debt_to_assets','inv_turn']]

D:\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2680         if isinstance(key, (Series, np.ndarray, Index, list)):
   2681             # either boolean or fancy integer index
-> 2682             return self._getitem_array(key)
   2683         elif isinstance(key, DataFrame):
   2684             return self._getitem_frame(key)

D:\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_array(self, key)
   2724             return self._take(indexer, axis=0)
   2725         else:
-> 2726             indexer = self.loc._convert_to_indexer(key, axis=1)
   2727             return self._take(indexer, axis=1)
   2728 

D:\Anaconda3\lib\site-packages\pandas\core\indexing.py in _convert_to_indexer(self, obj, axis, is_setter)
   1325                 if mask.any():
   1326                     raise KeyError('{mask} not in index'
-> 1327                                    .format(mask=objarr[mask]))
   1328 
   1329                 return com._values_from_object(indexer)

KeyError: "['inv_turn'] not in index"

13524438551

**Comment by jimmysoa** [comment]
有些指标默认是输出的，需要你指定到fields参数里才可以
