### ISSUE TITLE
有新三板的数据接口吗

### ISSUE THREAD

**Issue by bannychen1983** [waditu/tushare#84]

**Comment by jimmysoa** [comment]
还没有，行情？基本面？

**Comment by bannychen1983** [comment]
基本面

**Comment by larryisthere** [comment]
同求，主要是行情数据，然后逐步再完善基本面。

**Comment by tj0120** [comment]
去离开大陆好多年了，不过我可问问我同事，之前 我是大陆那边的技术负责。

**Comment by mandyzore** [comment]
嗨，我这儿有新三板基本面的api: http://open.memect.cn/, 服务还在完善，不过基本数据可用

**Comment by larryisthere** [comment]
好赞啊，稍后试一下！希望可以贡献代码
Aha <notifications@github.com>于2016年7月4日 周一下午12:18写道：

**Comment by astwyg** [comment]
虽然tushare目前还没有三板数据, 但是neeq官网不限制爬虫, 随便爬, 参考代码:
[抓新三板所有公司年报](https://github.com/astwyg/stock_analysis/blob/master/utils/get_all_neeq_annual_report.py)
