### ISSUE TITLE
现金流(cashflow)数据不准确

### ISSUE THREAD

**Issue by just-a-stone** [waditu/tushare#841]
### 获取美的年报净利润为例：

```
args = {
    'ts_code': '000333.SZ',
}

df = pro.cashflow(**args)
cols = ['ts_code', 'ann_date', 'f_ann_date', 'end_date', 'comp_type', 'report_type']

print(df[df.end_date.str.endswith('1231')][['end_date', 'net_profit']])
```

**结果如下：**
    end_date    net_profit
5   20171231  1.861119e+10
9   20161231  1.586191e+10
13  20151231  1.362466e+10
17  20141231  1.164633e+10
21  20131231  8.297496e+09
25  20121231  6.140890e+09
29  20111231  6.651873e+09
33  20101231  6.460832e+09
37  20091231           NaN
41  20081231  2.658407e+09
45  20071231  2.616900e+09
47  20061231  1.596834e+09
48  20061231  1.596834e+09
49  20051231  8.186003e+08
50  20041231  5.492982e+08

可以发现：

1. 06年数据有两条（47、48）
2. 09年数据缺失

-------------------------------------------------

tushare id    215557

**Comment by jimmysoa** [comment]
1、目前的规则是PIT机制，也就是只要有任意一个指标被修正过都会有两条记录，注意观察update_flag字段0和1的区别，000333股票2016年年报中，FREE_CASHFLOW有修正。
2、净利润，应该去查利润表INCOME接口
