### ISSUE TITLE
关于daily_basic获取的pe都是正数的问题

### ISSUE THREAD

**Issue by kksskkss** [waditu/tushare#843]
#df = pro.query('daily_basic', ts_code='', trade_date='20181122',fields='ts_code,close,turnover_rate,volume_ratio,pe,pe_ttm,pb,total_mv,circ_mv')

获取到的所有pe均为正数，但是一般的软件都会显示很多股票的pe是负数。请问这是为啥？
我的注册tushare的手机号码：13018076482

**Comment by jimmysoa** [comment]
负数的PE没有意义,如果低于0,我们设置成了NULL,所以你看不到负数的PE
