### ISSUE TITLE
请问日线行情的权限是怎样划分的呢

### ISSUE THREAD

**Issue by sngyai** [waditu/tushare#845]
抱歉，您每分钟最多访问该接口200次，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。
请问日线行情的权限是怎样划分的呢，看了文档只提到了最低积分要求
A股3000多只股票，每分钟200次完全不够用啊～

**Comment by jimmysoa** [comment]
是最低分值没问题，也就是其实是不需要积分的，注册了就能用，但是最低分值的有次数限制，为了防止非正常调取数据。

**Comment by sngyai** [comment]
多谢您的回复，不过我不是很明白“防止非正常调取数据”的意思。
我是想使用api.pro_bar每天盘后获取所有股票日K的更新，然后存盘到hdf5文件，我现在是每个股票扫一遍，start_date等于hdf5文件里面的最后一条数据的trade_date。
之前都是很好的，就是这几天突然就不能用了，我这中情况算是“非正常调取数据”吗，如果是的话用什么办法比较合适呢？
再次感谢！

**Comment by liyanglzu** [comment]
访问接口的频率太高了，试一下异常捕获。一旦捕获到这个异常，sleep个几秒钟。这也是为了减少服务器压力？？？

**Comment by sngyai** [comment]
> 访问接口的频率太高了，试一下异常捕获。一旦捕获到这个异常，sleep个几秒钟。这也是为了减少服务器压力？？？

是每获取一只股票行情都要sleep一下吗，那3000多只股全部更新一遍要花好久的吧 ～

**Comment by liyanglzu** [comment]
> > 访问接口的频率太高了，试一下异常捕获。一旦捕获到这个异常，sleep个几秒钟。这也是为了减少服务器压力？？？
> 
> 是每获取一只股票行情都要sleep一下吗，那3000多只股全部更新一遍要花好久的吧 ～
我们以150/分钟为例，4000/150~=30。异常的时候这样处理。对于单日的话，可以选择df = pro.daily(trade_date='20190301')

**Comment by sngyai** [comment]
> > > 访问接口的频率太高了，试一下异常捕获。一旦捕获到这个异常，sleep个几秒钟。这也是为了减少服务器压力？？？
> > 
> > 
> > 是每获取一只股票行情都要sleep一下吗，那3000多只股全部更新一遍要花好久的吧 ～
> > 我们以150/分钟为例，4000/150~=30。异常的时候这样处理。对于单日的话，可以选择df = pro.daily(trade_date='20190301')

那就是说拉一次要半小时呀

**Comment by liyanglzu** [comment]
> > > > 访问接口的频率太高了，试一下异常捕获。一旦捕获到这个异常，sleep个几秒钟。这也是为了减少服务器压力？？？
> > > 
> > > 
> > > 是每获取一只股票行情都要sleep一下吗，那3000多只股全部更新一遍要花好久的吧 ～
> > > 我们以150/分钟为例，4000/150~=30。异常的时候这样处理。对于单日的话，可以选择df = pro.daily(trade_date='20190301')
> 
> 那就是说拉一次要半小时呀

积分超过5000不受此限制，积分最快的获取方法，捐赠
