### ISSUE TITLE
[Bug]停复牌信息存在duplicates

### ISSUE THREAD

**Issue by araura2000** [waditu/tushare#850]
ID: araura@126.com

df = pro.suspend(ts_code='', suspend_date='20181119', resume_date='', fiedls='')
df[df['ts_code']=='002193.SZ']
或者
df = pro.suspend(ts_code='', suspend_date='20181120', resume_date='', fiedls='')
df[df['ts_code']=='601600.SH']
其中，第二个案例返回：

ts_code	suspend_date	resume_date	suspend_reason
35	601600.SH	20181120	None	重要事项未公告
37	601600.SH	20181120	20181121	重要事项未公告

这样看来，我有点怀疑数据甚至可能存在更新历史数据的情况。
https://tushare.pro/register?reg=126473

**Comment by jimmysoa** [comment]
这是公告不规范的问题，不能算是重复吧
