### ISSUE TITLE
新接口end_date='2018-12-01'出来数据只能到20171231

### ISSUE THREAD

**Issue by Sunnyfo** [waditu/tushare#854]
df = pro.daily(ts_code=stock_pool[i], start_date=start_dt, end_date='20181201')
发现一个bug，end_date='2018-12-01'出来数据只能到20171231，中间没有 - 这个杠的才是正常输入时间的数据。
用官网提供的例子跑了一下，发现了这个问题。
ID：217185

**Comment by jimmysoa** [comment]
目前tushare pro支持的日期格式是yyyymmdd，暂时还没有实现通用识别的
