### ISSUE TITLE
资金流向接口moneyflow_hsgt缺少20181126，20181130的数据

### ISSUE THREAD

**Issue by LeoZeda** [waditu/tushare#858]
资金流向接口moneyflow_hsgt缺少20181126，20181130的数据。
http://api.tushare.pro，请求参数如下：
`
{   

	"token": "",  
	"api_name": "moneyflow_hsgt",  
	"params": {  
		"start_date": "20181123",  
		"end_date": "20181203"  
	}
}
`

欢迎奖励积分
邮箱：max_lzd@163.com

**Comment by jimmysoa** [comment]
如果是港股不交易，就没有数据

**Comment by jimmysoa** [comment]
数据已修复，积分以到帐，谢谢。
