### ISSUE TITLE
pro_bar函数形参问题

### ISSUE THREAD

**Issue by wsmswsms** [waditu/tushare#864]
pro_bar 形参不带factors因子数据
但是函数原型里面的注释包含了factors：
def pro_bar(ts_code='', pro_api=None, start_date=None, end_date=None, freq='D', asset='E', 
           exchange='',
           adj = None,
           ma = [],
           contract_type = '',
           retry_count = 3):
    """
    BAR数据
    Parameters:
    ------------
    ts_code:证券代码，支持股票,ETF/LOF,期货/期权,港股,数字货币
    start_date:开始日期  YYYYMMDD
    end_date:结束日期 YYYYMMDD
    freq:支持1/5/15/30/60分钟,周/月/季/年
    asset:证券类型 E:股票和交易所基金，I:沪深指数,C:数字货币,FT:期货 FD:基金/O期权/H港股/中概美国/中证指数/国际指数
    exchange:市场代码，用户数字货币行情
    adj:复权类型,None不复权,qfq:前复权,hfq:后复权
    ma:均线,支持自定义均线频度，如：ma5/ma10/ma20/ma60/maN
    **factors因子数据，目前支持以下两种：**
        vr:量比,默认不返回，返回需指定：factor=['vr']
        tor:换手率，默认不返回，返回需指定：factor=['tor']
                    以上两种都需要：factor=['vr', 'tor']
    retry_count:网络重试次数
    
    Return
    ----------

ID:18651515075

**Comment by jimmysoa** [comment]
factor目前暂时没有集成过来，在每日指标接口里：https://tushare.pro/document/2?doc_id=32
