### ISSUE TITLE
建议：资产负债表、利润表、现金流量表等数据接口中增加版本信息

### ISSUE THREAD

**Issue by jameslee529sh** [waditu/tushare#865]
财政部几乎每年都会对会计政策微调，当前接口要兼容所有年份的报表易致混淆。建议在接口中增加版本信息，以2018年为主，并清楚表明可以后向兼容到哪一年。更早年份的报表，可用不同版本对应。
多谢你们工作。

ID: jameslee529@163.com

**Comment by jimmysoa** [comment]
好的，我们研究一下，谢谢。
