### ISSUE TITLE
ts.tick('10001557', conn, date=today_date)不工作

### ISSUE THREAD

**Issue by Suckhard** [waditu/tushare#870]
如题。自从12月3日因为ETF分红除权，导致50ETF期权新挂了合约后（例如新挂的50ETF沽12月2500，10001557），一直无法用ts.tick('10001557', conn, date=today_date) 调取：返回的值一直是None，而非当日的tick表。而同样的接口（ts.tick)在对于已经存续（但是调整了）的期权合约，是正常的：例如调整后的50ETF沽12月2500A，10001323。
这个问题已经持续了14天了（半个月了）。烦请解决。
附：tushare社区id号：125839。
谢谢

**Comment by jimmysoa** [comment]
老版本的这个接口目前暂时无法解决，或许等Pro版的tick吧
