### ISSUE TITLE
daily()和pro_bar()函数返回数据按照从晚到早排序，很不方便

### ISSUE THREAD

**Issue by finlab** [waditu/tushare#874]
一般使用习惯都是早期数据在前，晚期数据在后，可是tushare正好相反。

虽然客户端从新排序也很简单，但毕竟有开销。

能否再服务端按照正常的ascending顺序返回数据？ 

tushareId：OOAA

**Comment by jimmysoa** [comment]
Tushare的排序规则都是倒序

**Comment by finlab** [comment]
可是大家在使用时都是用升序，很少用降序的，接口设计应该符合多数人的习惯。
