### ISSUE TITLE
pro_bar获取周、月数据时，缺少最近一条周、月数据

### ISSUE THREAD

**Issue by jiangge** [waditu/tushare#884]
df=ts.pro_bar(ts_code='600221.SH',  end_date='20190101', pro_api=pro, freq='W')
df.sort_values(by='trade_date')
输出： 
......
3    600221.SH   20181130   2.01   2.04   2.09  1.99       2.01    0.00   
2    600221.SH   20181207   2.03   2.05   2.09  2.01       2.01    0.02   
1    600221.SH   20181214   1.99   2.01   2.04  1.97       2.03   -0.04   
0    600221.SH   20181221   1.90   1.98   1.99  1.90       1.99   -0.09   

df=ts.pro_bar(ts_code='600221.SH',  end_date='20190101', pro_api=pro, freq='M')
df.sort_values(by='trade_date')
输出： 
.......
3    600221.SH   20180831   2.04  2.45   2.45  2.03       2.44   -0.40   
2    600221.SH   20180930   2.06  2.03   2.11  1.95       2.04    0.02   
1    600221.SH   20181031   1.94  2.03   2.03  1.75       2.06   -0.12   
0    600221.SH   20181130   2.01  1.94   2.20  1.93       1.94    0.07

**Comment by jimmysoa** [comment]
周已经好了，月度数据在调整，好了通知
