### ISSUE TITLE
data_pro 文件中第88行  data[col] = data[col] * data['adj_factor'] / float(fcts['adj_factor'][0])

### ISSUE THREAD

**Issue by xnsua** [waditu/tushare#885]
问题1：该行在data为空dataframe的时候fcts['adj_factor'][0]会抛出 index out of bounds 异常。这里是正常情况应该返回空 dataframe。
问题2：后面的代码处理并打印了异常，不重新抛出，导致调用者不知道出现了什么错误（可以看到打印的错误，但是无法根据异常情况进行相应的处理）。建议把异常重新抛出给调用者处理。

**Comment by jimmysoa** [comment]
收到，下一版处理。
