### ISSUE TITLE
[BUG]PRO通用行情数据指数分钟线调用出错

### ISSUE THREAD

**Issue by flamehe** [waditu/tushare#886]
调用方式:
df = ts.pro_bar(pro_api=api, ts_code='000001.SH', asset='I', start_date='20180101', end_date='20181011', freq='60')
期望返回：上证指数2018年1月1日至10月11日的60分钟行情数据
实际返回：
local variable 'data' referenced before assignment
None
出错版本：1.2.18 环境:python3
Tushare账号: flamepjlh#163.com

**Comment by jimmysoa** [comment]
您好，目前分钟数据只对少数人开放
