### ISSUE TITLE
001872  招商港口   只有6天的数据

### ISSUE THREAD

**Issue by moonlit77** [waditu/tushare#887]
pro = ts.pro_api()
df = ts.pro_bar(pro_api=pro, ts_code='001872.SZ', adj='qfq', start_date='', end_date='')
返回只有6天的数据，26-12月-18 之前的都没有了。

ts_pro账号： p33306308@126.com

**Comment by jimmysoa** [comment]
合并上市出了新代码，老数据有旧代码获取

**Comment by wangyaochong** [comment]
如果把这支股票当新的处理，那001872的stock_basic的上市日期也应该要修改啊，我在本地校验数据时获取到k线数据只有20条，但是stock_basic里面的上市日期是19930505，对于这种情况，我该怎么校验数据是否齐全呢？
