### ISSUE TITLE
无法获取旧的hs_const数据

### ISSUE THREAD

**Issue by ProV1denCEX** [waditu/tushare#891]
对api hs_const
即使设定 is_new 为 0
获取到的数据仍然是 is_new = 1的数据

**Comment by jimmysoa** [comment]
现在还不行吗？我测试了是木有问题的：

pro.hs_const(hs_type='SH', is_new='0')

       ts_code hs_type   in_date  out_date is_new
0    600561.SH      SH  20141117  20150612      0
1    600871.SH      SH  20150331  20180328      0
2    600468.SH      SH  20141117  20170609      0
3    600097.SH      SH  20141117  20141212      0
4    600490.SH      SH  20141215  20161212      0
5    600743.SH      SH  20141117  20181214      0
6    600985.SH      SH  20141117  20151211      0
7    600523.SH      SH  20141117  20151211      0
8    600833.SH      SH  20141117  20151211      0
9    600773.SH      SH  20141117  20171208      0
10   600715.SH      SH  20180611  20181214      0
11   600551.SH      SH  20141117  20181214      0
12   600831.SH      SH  20141117  20180608      0
13   600959.SH      SH  20151214  20170609      0
14   600527.SH      SH  20141117  20170609      0
15   601360.SH      SH  20141117  20170609      0
16   601118.SH      SH  20141117  20180608      0
17   600108.SH      SH  20141117  20161209      0
18   600405.SH      SH  20141117  20180608      0
19   600268.SH      SH  20141117  20151211      0
20   600260.SH      SH  20141117  20151211      0
21   600251.SH      SH  20141117  20171208      0
22   600449.SH      SH  20141117  20161212      0
23   600686.SH      SH  20161212  20170609      0
24   603168.SH      SH  20141215  20181214      0

**Comment by ProV1denCEX** [comment]
可以了，原来0和1是str。。。
