### ISSUE TITLE
pro adj_factor 2018年10月10日及2018年10月29日部分股票复权因子错误

### ISSUE THREAD

**Issue by shiziye** [waditu/tushare#894]
错误数据如下，其中AdjFactorChange=T日AdjFactor/T-1日AdjFactor，对应股票交易日没有除权除息情况

XrCode | Date | AdjFactorChange
000601.XSHE | 2018-10-10 | 0.999896
603600.XSHG | 2018-10-10 | 0.999630
603595.XSHG | 2018-10-10 | 0.999287
600812.XSHG | 2018-10-10 | 0.999747
600809.XSHG | 2018-10-10 | 0.999770
600386.XSHG | 2018-10-10 | 0.999816
600346.XSHG | 2018-10-10 | 0.999854
600185.XSHG | 2018-10-10 | 0.999861
600062.XSHG | 2018-10-10 | 0.999867
300493.XSHE | 2018-10-10 | 0.999607
300473.XSHE | 2018-10-10 | 0.999038
603969.XSHG | 2018-10-10 | 0.999770
300176.XSHE | 2018-10-10 | 0.999781
300091.XSHE | 2018-10-10 | 0.999917
002789.XSHE | 2018-10-10 | 0.999417
002539.XSHE | 2018-10-10 | 0.999825
002526.XSHE | 2018-10-10 | 0.999832
002367.XSHE | 2018-10-10 | 0.999855
000950.XSHE | 2018-10-10 | 0.999573
000850.XSHE | 2018-10-10 | 0.999874
603988.XSHG | 2018-10-10 | 0.999667
600145.XSHG | 2018-10-29 | 0.999869
002408.XSHE | 2018-10-29 | 0.999834
002369.XSHE | 2018-10-29 | 0.999767
002075.XSHE | 2018-10-29 | 0.999644
000666.XSHE | 2018-10-29 | 0.999370
300108.XSHE | 2018-10-29 | 0.999837

**Comment by jimmysoa** [comment]
这个是Tushare的数据接口？编码规则都不一样，日期格式也不一样，Tushare的复权因子在这里：https://tushare.pro/document/2?doc_id=28

**Comment by shiziye** [comment]
tushare pro接口

**Comment by jimmysoa** [comment]
我查了一下数据，跟你的对不上，可能你处理数据出现错乱了？
