### ISSUE TITLE
pro namechage数据错误

### ISSUE THREAD

**Issue by shiziye** [waditu/tushare#895]
tushare pro namechage接口获取数据
至少下列数据点，名称变更后，变更前对应数据有两条，其中一条end_date为空, 相当于与变更后名称重叠
000403(2018-11-22) 
000755(2018-11-14)
000803(2018-10-29)
000922(2018-11-27)
603188(2018-11-07)

**Comment by jimmysoa** [comment]
谢谢，已修复
