### ISSUE TITLE
Tushare HTTP Resutful API调用pro_bar接口失败

### ISSUE THREAD

**Issue by JackOne2009** [waditu/tushare#897]
请求参数： {
	"api_name": "pro_bar",
	"token": "2d519fe2bfdece2f94333edd2429046f30f6a3042ef0bc001127fb19",
	"params": {
		"pro_api" : "api",
		"ts_code": "300674.SZ",
		"asset": "E",
		"adj": "qfq",
		"freq": "D",
		"start_date" : "20190101",
		"end_date" : "20190102"
	},
	"fields": ""
} 
响应为： {"request_id": "a571c368190911e996cfbfbafef7d8ff1547586483260736", "code": -2001, "msg": "\u62b1\u6b49\uff0c\u6ca1\u6709pro_bar\u63a5\u53e3", "data": null}

**Comment by jimmysoa** [comment]
@zingvy 赞，谢谢你，给我ID加积分，哈哈

**Comment by JackOne2009** [comment]
呵呵，是的啊，多谢指导啊！
________________________________
发件人: Jimmy <notifications@github.com>
发送时间: 2019年1月16日 14:16
收件人: waditu/tushare
抄送: JackOne2009; Author
主题: Re: [waditu/tushare] Tushare HTTP Resutful API调用pro_bar接口失败 (#897)


Closed #897<https://github.com/waditu/tushare/issues/897>.

―

**Comment by zingvy** [comment]
@jimmysoa  哈哈那真是谢谢了，231853，正差积分呢，我是新用户
