### ISSUE TITLE
支持下载指数历史数据

### ISSUE THREAD

**Issue by kongscn** [waditu/tushare#9]
例如沪深300指数 `000300.SH` 的历史数据

**Comment by jimmysoa** [comment]
ts.get_hist_data('hs300'）#获取沪深300指数k线数据

**Comment by jimmysoa** [comment]
其他数据请参考文档：http://tushare.waditu.com

**Comment by kongscn** [comment]
:smile: 是我看文档太不认真了～ :+1:
