### ISSUE TITLE
 get_h_data('000300') error

### ISSUE THREAD

**Issue by fayeshine** [waditu/tushare#90]
hs300 = get_h_data('000300',index=True,start='1991-01-01', end='2016-01-01') 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

**Comment by extremewaysback** [comment]
Because your code contains something like Chinese character, which is not 'ascii';

You should define your default encoding to unicode 'utf-8' in front of your code as following:

    # -*- coding: utf-8 -*-
