### ISSUE TITLE
异常的时候，是不是应该给个明确的异常名称，这样方便捕获

### ISSUE THREAD

**Issue by vagrantTime** [waditu/tushare#900]
抱歉，您每分钟最多访问该接口200次，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。
我希望捕获这个异常，然后进行等待，但是不知道该捕获哪个异常，这样有时候是不太方便的。
账号：linyuanlvbing@126.com

**Comment by jimmysoa** [comment]
try catch 木有问题啊
