### ISSUE TITLE
[BUG] pro_bar 接口的freq参数不支持'5MIN', '1MIN'等参数

### ISSUE THREAD

**Issue by Anluzi** [waditu/tushare#903]
pro_bar 接口的freq参数不支持'5MIN', '1MIN'等参数。

我在运行以下代码时出现bug:

import tushare as ts
api = ts.pro_api('my token')
da = ts.pro_bar(ts_code='000001.SZ', pro_api=api, adj='qfq', start_date='20180901', end_date='20181231', freq = '5MIN')
print(da)

报错信息：
local variable 'df' referenced before assignment

自查源代码，在data_pro.py文件中，第93行'df'未被定义：
该段代码只判断了是否为日频/周频/月频，对于1min, 5min等其他频度的情况，直接write "df.set_index" (93行)，而此时df未被定义。

这段代码和官网上对于pro_bar接口的介绍（支持1min、5min频度）没有对应起来。
官网介绍pro_bar接口的链接：
https://tushare.pro/document/2?doc_id=109

My Tushare ID: xingzhiguanfang@126.com

**Comment by Anluzi** [comment]
@jimmysoa

**Comment by jimmysoa** [comment]
Pro版的分钟数据目前只对少数人开放，不好意思。
