### ISSUE TITLE
停复牌数据不准确

### ISSUE THREAD

**Issue by wangyaochong** [waditu/tushare#906]
002506.SZ在20140429到20150812期间都是停牌的，停复牌数据没有体现出来
000950.SZ在20170426到20180828期间都是停牌的，停复牌数据没有体现出来
目前获取到的停复牌信息数据(suspend接口)有点奇怪，有些有resume_date，有些没有，让人觉得比较困惑，能否调整一下，有两种方案：1、所有停复牌区间都记suspend_date和resume_date，没有resume_date说明依旧处于停牌中；2、针对每个停牌日，都记录一条数据，不记录resume_date。十分感谢。

**Comment by jimmysoa** [comment]
没有resume_date就表示不确定复牌日期，另外，“002506.SZ在20140429到20150812期间都是停牌的”你说的不对啊，20150426～20150514才是停牌的
