### ISSUE TITLE
业绩快报接口：express接口bps、yoy_sales、yoy_op等部分字段返回为None

### ISSUE THREAD

**Issue by owner11** [waditu/tushare#907]
米哥你好：
       业绩快报接口：express
       BUG描述：
       代码输入：
       pro = ts.pro_api()
       df1=pro.express(ts_code='002001.SZ', period='20171231')  
       #df1=pro.express(ts_code='002001.SZ', period='20181231')
       df2=pro.express(ts_code='600000.SH', period='20171231')  
       #df2=pro.express(ts_code='600000.SH', period='20181231')
       df1.describe()
       df2.describe()
       可以看到32个字段数据中，有['ts_code', 'ann_date', 'end_date', 'revenue', 'operate_profit', 'total_profit', 'n_income','total_assets','total_hldr_eqy_exc_min_int', 'diluted_eps', 'diluted_roe','yoy_net_profit', 'is_audit']这几个字段是有数据的。

       同时，有['bps', 'yoy_sales', 'yoy_op',
       'yoy_tp', 'yoy_dedu_np', 'yoy_eps', 'yoy_roe', 'growth_assets',
       'yoy_equity', 'growth_bps', 'or_last_year', 'op_last_year',
       'tp_last_year', 'np_last_year', 'eps_last_year', 'open_net_assets',
       'open_bps', 'perf_summary', 'remark']这几个字段的数据为None，是否为BUG，请米哥审阅。

登录账号（ID？）：13732417521

**Comment by jimmysoa** [comment]
有些目前确实还没有做，属于进程中的未完成事项，还是很感谢。
