### ISSUE TITLE
能获取指数的PE和PB吗？

### ISSUE THREAD

**Issue by kingofhawks** [waditu/tushare#91]
包括历史数据是否可行？

**Comment by jimmysoa** [comment]
在新版的get_today_all里已经可以返回实时的PE和PB，目前还没有发布，可以在通过github代码试用。
@kingofhawks

**Comment by kingofhawks** [comment]
@jimmysoa  能获得历史数据的PE和PB吗？

**Comment by jimmysoa** [comment]
历史的目前可以通过通联数据接口获取，如果你向自己留存历史，就每天调用一次today_all保存 @kingofhawks

**Comment by kingofhawks** [comment]
@jimmysoa thanks~

**Comment by zhouxiaojian1985** [comment]
> 历史的目前可以通过通联数据接口获取，如果你向自己留存历史，就每天调用一次today_all保存
看了下通联数据接口，关于指数行情的只有
1 指数基本信息getIdx
2 指数成分构成getIdxCons
没有查到可以获取指数历史PE和PB的API。
另外市场行情数据的API也没有找到，只有获取股票的历史PE和PB的getStockFactorsDateRange。

能否提示下指数的是哪个？

**Comment by kingofhawks** [comment]
另外，指数能获取历史数据的换手率吗？
