### ISSUE TITLE
000001.SZ  日线行情  20100630至20100825 无数据

### ISSUE THREAD

**Issue by JcOpenSource** [waditu/tushare#910]
In [4]: pro.daily(ts_code="000001.SZ", start_date="20100630", end_date="20100825")
Out[4]:
Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

相同的：
In [8]: pro.daily(ts_code="000001.SZ", trade_date="20100630")
Out[8]:
Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

In [9]: pro.daily(ts_code="000001.SZ", trade_date="20100701")
Out[9]:
Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

In [10]: pro.daily(ts_code="000001.SZ", trade_date="20100702")
Out[10]:
Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

In [11]: pro.daily(ts_code="000001.SZ", trade_date="20100703")
Out[11]:
Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

In [12]: pro.daily(ts_code="000001.SZ", trade_date="20100704")
Out[12]:
Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

这段数据是否存在问题？

**Comment by jimmysoa** [comment]
停牌
