### ISSUE TITLE
 pro.forecast 函数问题

### ISSUE THREAD

**Issue by yehonghao** [waditu/tushare#914]
首先官网例子：
pro = ts.pro_api()

pro.forecast(ts_code='600000.SH', fields='ts_code,ann_date,end_date,type,p_change_min,p_change_max,net_profit_min')
官方例子存在报错，ann_date或者period是必选
接着添加ann_date后：
 pro.forecast(ts_code='600177.SH',ann_date='2018-10-31', start_date='20160630',end_date='20190202')
试过好几个code 返回数据都是空。

**Comment by li-yong** [comment]
我也发现了，来报issue，发现你已经报了:-).

你可能弄错 ann_date 和 period 字段了， 业绩预告很难知道那天预告的（ann_date),  用 period 会好一些。  如果没有数据则返回空DF。

In[36]: pro_con.query('forecast', ts_code='600519.SH',fields=query_fields, period="20121231")
Out[37]: 
     ts_code            ...                          change_reason
0  600519.SH            ...              2012年度公司产品销量与价格同比上年度增长所致。

**Comment by jimmysoa** [comment]
文档进行了调整，谢谢
