### ISSUE TITLE
pro.daily 返回数据不完整，个别股票代码中的amount存在nan值，截止20190201共计221个。

### ISSUE THREAD

**Issue by liyanglzu** [waditu/tushare#915]
trade_date | ts_code | open | high | low | close | pre_close | change | pct_chg | vol | amount
19931130 | 000536.SZ | 10 | 10 | 9.5 | 9.65 | 10 | -0.35 | -3.5 | 19769 |  
19931201 | 000536.SZ | 9.6 | 9.6 | 8.8 | 9 | 9.65 | -0.65 | -6.74 | 19541 |  
19931202 | 000536.SZ | 8.85 | 8.95 | 8.6 | 8.7 | 9 | -0.3 | -3.33 | 13043 |  
19931203 | 000536.SZ | 8.6 | 8.75 | 8.45 | 8.5 | 8.7 | -0.2 | -2.3 | 8269 |  
19931206 | 000536.SZ | 8.4 | 9 | 8.1 | 9 | 8.5 | 0.5 | 5.88 | 18887 |  
19931207 | 000536.SZ | 9.15 | 9.2 | 8.45 | 8.65 | 9 | -0.35 | -3.89 | 24517 |  
19931208 | 000536.SZ | 8.65 | 8.7 | 8.4 | 8.6 | 8.65 | -0.05 | -0.58 | 11137 |  
19931209 | 000536.SZ | 8.7 | 8.75 | 8.4 | 8.45 | 8.6 | -0.15 | -1.74 | 8223 |  
19931210 | 000536.SZ | 8.45 | 8.7 | 8.2 | 8.65 | 8.45 | 0.2 | 2.37 | 15718 |  
19931213 | 000536.SZ | 8.75 | 8.8 | 8 | 8.05 | 8.65 | -0.6 | -6.94 | 12525 |  
19931214 | 000536.SZ | 8.2 | 8.5 | 8.05 | 8.15 | 8.05 | 0.1 | 1.24 | 8261 |  
19931215 | 000536.SZ | 8.15 | 8.35 | 7.7 | 8.25 | 8.15 | 0.1 | 1.23 | 9691 |  
19931216 | 000536.SZ | 8.35 | 8.35 | 7.9 | 7.9 | 8.25 | -0.35 | -4.24 | 5662 |  
19931217 | 000536.SZ | 7.9 | 8 | 7.75 | 7.8 | 7.9 | -0.1 | -1.27 | 5346 |  
19931220 | 000536.SZ | 7.65 | 7.65 | 6.35 | 6.75 | 7.8 | -1.05 | -13.46 | 13636 |  
19931221 | 000536.SZ | 6.7 | 6.85 | 6.5 | 6.75 | 6.75 | 0 | 0 | 8544 |  
19931222 | 000536.SZ | 6.8 | 6.8 | 6.5 | 6.55 | 6.75 | -0.2 | -2.96 | 3912 |  
19931223 | 000536.SZ | 6.45 | 6.45 | 6.25 | 6.25 | 6.55 | -0.3 | -4.58 | 4286 |  
19931223 | 000543.SZ | 5.85 | 6.15 | 5.85 | 6 | 6.2 | -0.2 | -3.23 | 10359 |  
19931223 | 600600.SH | 8 | 8.3 | 8 | 8.09 | 8 | 0.09 | 1.13 | 10235 |  
19931223 | 600601.SH | 11.56 | 11.99 | 11.54 | 11.6 | 11.48 | 0.12 | 1.05 | 15020 |  
19931223 | 600602.SH | 6.17 | 6.58 | 6.17 | 6.4 | 6.15 | 0.25 | 4.07 | 12251 |  
19931223 | 600603.SH | 20.2 | 21.17 | 20.2 | 20.45 | 20.01 | 0.44 | 2.2 | 10319 |  
19931223 | 600604.SH | 8.41 | 9 | 8.41 | 8.64 | 8.51 | 0.13 | 1.53 | 4000 |  
19931223 | 600605.SH | 6.1 | 6.58 | 6.08 | 6.21 | 6.2 | 0.01 | 0.16 | 2594 |  
19931223 | 600606.SH | 6.25 | 6.55 | 6.2 | 6.36 | 6.3 | 0.06 | 0.95 | 2536 |  
19931223 | 600608.SH | 9.95 | 10.25 | 9.82 | 10.15 | 9.9 | 0.25 | 2.53 | 7029 |  
19931223 | 600609.SH | 5.23 | 5.84 | 5.23 | 5.75 | 5.2 | 0.55 | 10.58 | 59894 |  
19931223 | 600610.SH | 7.05 | 7.28 | 6.91 | 7.1 | 7.05 | 0.05 | 0.71 | 1051 |  
19931223 | 600611.SH | 17.7 | 18.42 | 17.7 | 18.1 | 17.75 | 0.35 | 1.97 | 2424 |  
19931223 | 600612.SH | 14.9 | 16.38 | 14.63 | 15.9 | 14.95 | 0.95 | 6.35 | 1731 |  
19931223 | 600613.SH | 11.99 | 12.9 | 11.99 | 12.63 | 12.3 | 0.33 | 2.68 | 813 |  
19931223 | 600614.SH | 10.79 | 11.05 | 10.79 | 10.9 | 11 | -0.1 | -0.91 | 958 |  
19931223 | 600615.SH | 10.35 | 10.67 | 10.35 | 10.55 | 10.52 | 0.03 | 0.29 | 1149 |  
19931223 | 600616.SH | 18.52 | 19.2 | 18.52 | 18.85 | 18.8 | 0.05 | 0.27 | 594 |  
19931223 | 600618.SH | 12 | 12.39 | 11.85 | 12.15 | 12 | 0.15 | 1.25 | 1301 |  
19931223 | 600619.SH | 11.5 | 11.6 | 11.32 | 11.36 | 11.5 | -0.14 | -1.22 | 547 |  
19931223 | 600620.SH | 20.6 | 21.2 | 20.55 | 20.9 | 20.8 | 0.1 | 0.48 | 1568 |  
19931223 | 600621.SH | 12.2 | 12.3 | 11.9 | 12.1 | 12.16 | -0.06 | -0.49 | 1289 |  
19931223 | 600622.SH | 16.48 | 16.78 | 16.31 | 16.35 | 16.23 | 0.12 | 0.74 | 5449 |  
19931223 | 600623.SH | 14.82 | 15.08 | 14.7 | 14.95 | 11.5 | 3.45 | 30 | 725 |  
19931223 | 600624.SH | 13.6 | 14 | 13.58 | 13.72 | 13.6 | 0.12 | 0.88 | 3341 |  
19931223 | 600626.SH | 7.5 | 7.8 | 7.5 | 7.69 | 7.62 | 0.07 | 0.92 | 1687 |  
19931223 | 600628.SH | 29 | 29.5 | 28.72 | 28.85 | 28.7 | 0.15 | 0.52 | 2486 |  
19931223 | 600629.SH | 11.28 | 11.99 | 11.28 | 11.75 | 11.3 | 0.45 | 3.98 | 5454 |  
19931223 | 600630.SH | 5.69 | 6 | 5.65 | 5.9 | 5.8 | 0.1 | 1.72 | 1433 |  
19931223 | 600633.SH | 11.1 | 11.5 | 11.01 | 11.32 | 11.3 | 0.02 | 0.18 | 1747 |  
19931223 | 600634.SH | 17.51 | 18.08 | 17.3 | 17.51 | 17.18 | 0.33 | 1.92 | 5790 |  
19931223 | 600635.SH | 20.78 | 21.48 | 20.66 | 21 | 20.8 | 0.2 | 0.96 | 2559 |  
19931223 | 600636.SH | 13.2 | 13.59 | 13.2 | 13.25 | 13.18 | 0.07 | 0.53 | 3798 |  
19931223 | 600637.SH | 5.77 | 6.1 | 5.75 | 5.88 | 5.75 | 0.13 | 2.26 | 3194 |  
19931223 | 600638.SH | 20.15 | 20.49 | 20.15 | 20.2 | 20.15 | 0.05 | 0.25 | 1165 |  
19931223 | 600639.SH | 19.55 | 20.35 | 19.55 | 19.9 | 19.45 | 0.45 | 2.31 | 4354 |  
19931223 | 600640.SH | 24.3 | 24.6 | 23.99 | 24.2 | 24.49 | -0.29 | -1.18 | 806 |  
19931223 | 600641.SH | 20.61 | 22 | 20.61 | 21.7 | 21.7 | 0 | 0 | 1070 |  
19931223 | 600642.SH | 8.19 | 8.23 | 8.18 | 8.21 | 8.19 | 0.02 | 0.24 | 6692 |  
19931223 | 600643.SH | 20.48 | 20.9 | 20.45 | 20.65 | 20.59 | 0.06 | 0.29 | 2478 |  
19931223 | 600644.SH | 8 | 8.2 | 7.88 | 8.11 | 8.08 | 0.03 | 0.37 | 1501 |  
19931223 | 600645.SH | 15.8 | 16.1 | 15.8 | 15.9 | 15.9 | 0 | 0 | 1624 |  
19931223 | 600647.SH | 18.1 | 18.8 | 18.1 | 18.3 | 18.18 | 0.12 | 0.66 | 1326 |  
19931223 | 600648.SH | 24.1 | 24.9 | 24.04 | 24.6 | 24.3 | 0.3 | 1.23 | 1260 |  
19931223 | 600649.SH | 5.71 | 6.02 | 5.71 | 5.88 | 5.8 | 0.08 | 1.38 | 13266 |  
19931223 | 600650.SH | 14.8 | 15 | 14.79 | 14.9 | 14.78 | 0.12 | 0.81 | 1186 |  
19931223 | 600651.SH | 40 | 41.89 | 39.61 | 41 | 38.99 | 2.01 | 5.16 | 11615 |  
19931223 | 600652.SH | 38.61 | 40.4 | 38.61 | 38.9 | 38.3 | 0.6 | 1.57 | 11988 |  
19931223 | 600653.SH | 31.8 | 32.78 | 31.38 | 31.6 | 31 | 0.6 | 1.94 | 9139 |  
19931223 | 600654.SH | 15.8 | 16.78 | 15.57 | 16.05 | 15.18 | 0.87 | 5.73 | 96842 |  
19931223 | 600655.SH | 19.81 | 20.2 | 19.8 | 20.1 | 20 | 0.1 | 0.5 | 1390 |  
19931223 | 600657.SH | 9.88 | 9.88 | 9.6 | 9.68 | 9.6 | 0.08 | 0.83 | 684 |  
19931223 | 600658.SH | 6.95 | 7.1 | 6.91 | 7 | 6.91 | 0.09 | 1.3 | 4626 |  
19931223 | 600660.SH | 22.95 | 24.15 | 22.95 | 23.7 | 15.78 | 7.92 | 50.19 | 4086 |  
19931223 | 600661.SH | 11.8 | 12.15 | 11.8 | 12 | 11.9 | 0.1 | 0.84 | 2029 |  
19931223 | 600662.SH | 23.72 | 24.59 | 23.72 | 23.95 | 23.9 | 0.05 | 0.21 | 5391 |  
19931223 | 600663.SH | 19.6 | 20.5 | 19.6 | 20 | 19.45 | 0.55 | 2.83 | 42502 |  
19931223 | 600664.SH | 7.8 | 8.1 | 7.7 | 7.91 | 7.63 | 0.28 | 3.67 | 15912 |  
19931223 | 600665.SH | 7.26 | 7.6 | 7.26 | 7.49 | 7.32 | 0.17 | 2.32 | 2601 |  
19931223 | 600666.SH | 7 | 7.11 | 6.99 | 7 | 7.05 | -0.05 | -0.71 | 1659 |  
19931223 | 600667.SH | 5.8 | 6.08 | 5.8 | 5.87 | 5.83 | 0.04 | 0.69 | 9714 |  
19931223 | 600668.SH | 10.5 | 10.9 | 10.5 | 10.7 | 10.5 | 0.2 | 1.9 | 1703 |  
19931223 | 600671.SH | 10.08 | 10.49 | 10.08 | 10.32 | 10.2 | 0.12 | 1.18 | 1288 |  
19931223 | 600673.SH | 8.97 | 9.2 | 8.9 | 8.9 | 8.95 | -0.05 | -0.56 | 2013 |  
19931223 | 600674.SH | 7.88 | 8 | 7.83 | 7.86 | 7.88 | -0.02 | -0.25 | 2134 |  
19931223 | 600675.SH | 17.95 | 18.5 | 17.95 | 18.15 | 18.1 | 0.05 | 0.28 | 1430 |  
19931223 | 600676.SH | 11.9 | 12 | 11.8 | 11.94 | 11.88 | 0.06 | 0.51 | 1626 |  
19931223 | 600677.SH | 7 | 7.14 | 6.81 | 7 | 6.81 | 0.19 | 2.79 | 10348 |  
19931223 | 600678.SH | 20.78 | 20.78 | 20.05 | 20.7 | 20.5 | 0.2 | 0.98 | 5369 |  
19931223 | 600679.SH | 12 | 12 | 11.8 | 11.99 | 11.7 | 0.29 | 2.48 | 3170 |  
19931223 | 600680.SH | 19.85 | 20.28 | 19.82 | 20.05 | 20 | 0.05 | 0.25 | 1729 |  
19931223 | 600681.SH | 9.98 | 10.08 | 9.83 | 9.9 | 10.05 | -0.15 | -1.49 | 4109 |  
19931223 | 600682.SH | 12.6 | 12.95 | 12.55 | 12.75 | 12.79 | -0.04 | -0.31 | 7906 |  
19931223 | 600683.SH | 10.72 | 10.98 | 10.7 | 10.72 | 10.75 | -0.03 | -0.28 | 2669 |  
19931223 | 600684.SH | 16.09 | 16.79 | 16.08 | 16.5 | 16.09 | 0.41 | 2.55 | 9567 |  
19931223 | 600685.SH | 7.1 | 7.35 | 7.02 | 7.3 | 7.2 | 0.1 | 1.39 | 106522 |  
19931223 | 600686.SH | 10.6 | 10.99 | 10.55 | 10.64 | 10.68 | -0.04 | -0.37 | 17571 |  
19931223 | 600687.SH | 12.8 | 13 | 12.6 | 12.7 | 12.59 | 0.11 | 0.87 | 2332 |  
19931223 | 600688.SH | 4.55 | 4.79 | 4.5 | 4.65 | 4.53 | 0.12 | 2.65 | 5816 |  
19931223 | 600689.SH | 10.45 | 10.5 | 10.2 | 10.39 | 10.45 | -0.06 | -0.57 | 1154 |  
19931223 | 600690.SH | 10.1 | 10.1 | 9.5 | 9.61 | 9.46 | 0.15 | 1.59 | 4652 |  
19931223 | 600691.SH | 9.5 | 9.95 | 9.5 | 9.73 | 9.8 | -0.07 | -0.71 | 2532 |  
19931223 | 600692.SH | 10.2 | 10.39 | 10.2 | 10.27 | 10.26 | 0.01 | 0.1 | 1193 |  
19931223 | 600693.SH | 10.18 | 10.4 | 10.1 | 10.12 | 10.1 | 0.02 | 0.2 | 3674 |  
19931223 | 600694.SH | 10.52 | 10.88 | 10.5 | 10.58 | 10.66 | -0.08 | -0.75 | 3059 |  
19931223 | 600695.SH | 11.98 | 12.1 | 11.7 | 11.9 | 11.9 | 0 | 0 | 2190 |  
19931224 | 000536.SZ | 6.15 | 6.9 | 6.1 | 6.85 | 6.25 | 0.6 | 9.6 | 6251 |  
19931227 | 000536.SZ | 7 | 7 | 6.45 | 6.65 | 6.85 | -0.2 | -2.92 | 8505 |  
19931228 | 000536.SZ | 6.6 | 6.8 | 6.25 | 6.4 | 6.65 | -0.25 | -3.76 | 4489 |  
19931229 | 000536.SZ | 6.4 | 6.6 | 6.35 | 6.4 | 6.4 | 0 | 0 | 3707 |  
19931230 | 000536.SZ | 6.45 | 6.65 | 6.4 | 6.5 | 6.4 | 0.1 | 1.56 | 3716 |  
19931231 | 000536.SZ | 6.5 | 6.55 | 6.3 | 6.35 | 6.5 | -0.15 | -2.31 | 3340 |  
19940103 | 000536.SZ | 6.25 | 6.3 | 6.05 | 6.05 | 6.35 | -0.3 | -4.72 | 2248 |  
19940104 | 000536.SZ | 6 | 6.1 | 5.6 | 5.7 | 6.05 | -0.35 | -5.79 | 4480 |  
19940105 | 000536.SZ | 5.7 | 5.85 | 5.55 | 5.85 | 5.7 | 0.15 | 2.63 | 3821 |  
19940106 | 000536.SZ | 5.95 | 6.45 | 5.8 | 6.45 | 5.85 | 0.6 | 10.26 | 8305 |  
19940107 | 000536.SZ | 6.5 | 6.7 | 6.2 | 6.6 | 6.45 | 0.15 | 2.33 | 15199 |  
19940110 | 000536.SZ | 6.65 | 6.8 | 6.45 | 6.6 | 6.6 | 0 | 0 | 9867 |  
19940111 | 000536.SZ | 6.6 | 6.6 | 6.35 | 6.4 | 6.6 | -0.2 | -3.03 | 4288 |  
19940112 | 000536.SZ | 6.3 | 6.45 | 6.25 | 6.3 | 6.4 | -0.1 | -1.56 | 2459 |  
19940113 | 000536.SZ | 6.3 | 6.3 | 6.15 | 6.3 | 6.3 | 0 | 0 | 3405 |  
19940114 | 000536.SZ | 6.3 | 6.4 | 5.95 | 6.1 | 6.3 | -0.2 | -3.17 | 7566 |  
19940117 | 000536.SZ | 6.1 | 6.15 | 5.9 | 5.95 | 6.1 | -0.15 | -2.46 | 2702 |  
19940118 | 000536.SZ | 5.95 | 6.2 | 5.75 | 6.1 | 5.95 | 0.15 | 2.52 | 4963 |  
19940119 | 000536.SZ | 6.1 | 6.1 | 5.85 | 5.85 | 6.1 | -0.25 | -4.1 | 4821 |  
19940120 | 000536.SZ | 5.85 | 6 | 5.65 | 5.85 | 5.85 | 0 | 0 | 4120 |  
19940121 | 000536.SZ | 5.85 | 6 | 5.75 | 5.85 | 5.85 | 0 | 0 | 2783 |  
19940124 | 000536.SZ | 5.95 | 6.05 | 5.85 | 5.9 | 5.85 | 0.05 | 0.85 | 1871 |  
19940125 | 000536.SZ | 5.9 | 5.9 | 5.75 | 5.75 | 5.9 | -0.15 | -2.54 | 1795 |  
19940126 | 000536.SZ | 5.75 | 5.8 | 5.6 | 5.6 | 5.75 | -0.15 | -2.61 | 2611 |  
19940127 | 000536.SZ | 5.6 | 5.85 | 5.55 | 5.85 | 5.6 | 0.25 | 4.46 | 2928 |  
19940128 | 000536.SZ | 5.85 | 5.85 | 5.6 | 5.6 | 5.85 | -0.25 | -4.27 | 2233 |  
19940131 | 000536.SZ | 5.5 | 5.5 | 5.35 | 5.35 | 5.6 | -0.25 | -4.46 | 2799 |  
19940201 | 000536.SZ | 5.3 | 5.6 | 5.3 | 5.35 | 5.35 | 0 | 0 | 4166 |  
19940202 | 000536.SZ | 5.3 | 5.55 | 5.3 | 5.45 | 5.35 | 0.1 | 1.87 | 2175 |  
19940203 | 000536.SZ | 5.5 | 5.8 | 5.45 | 5.8 | 5.45 | 0.35 | 6.42 | 9039 |  
19940204 | 000536.SZ | 5.9 | 6.2 | 5.8 | 6.2 | 5.8 | 0.4 | 6.9 | 13934 |  
19940214 | 000536.SZ | 6.3 | 6.3 | 5.3 | 5.5 | 6.2 | -0.7 | -11.29 | 6376 |  
19940215 | 000536.SZ | 5.5 | 5.8 | 5.4 | 5.6 | 5.5 | 0.1 | 1.82 | 5833 |  
19940216 | 000536.SZ | 5.6 | 5.7 | 5.5 | 5.5 | 5.6 | -0.1 | -1.79 | 2905 |  
19940217 | 000536.SZ | 5.45 | 5.5 | 5.4 | 5.45 | 5.5 | -0.05 | -0.91 | 1473 |  
19940218 | 000536.SZ | 5.45 | 5.55 | 5.35 | 5.5 | 5.45 | 0.05 | 0.92 | 2206 |  
19940221 | 000536.SZ | 5.5 | 5.7 | 5.4 | 5.4 | 5.5 | -0.1 | -1.82 | 5131 |  
19940222 | 000536.SZ | 5.5 | 5.9 | 5.5 | 5.55 | 5.4 | 0.15 | 2.78 | 10843 |  
19940223 | 000536.SZ | 5.65 | 5.7 | 5.5 | 5.55 | 5.55 | 0 | 0 | 3481 |  
19940224 | 000536.SZ | 5.55 | 5.8 | 5.55 | 5.75 | 5.55 | 0.2 | 3.6 | 5627 |  
19940225 | 000536.SZ | 5.9 | 5.9 | 5.7 | 5.75 | 5.75 | 0 | 0 | 13483 |  
19940228 | 000536.SZ | 5.75 | 5.75 | 5.6 | 5.6 | 5.75 | -0.15 | -2.61 | 3833 |  
19940301 | 000536.SZ | 5.55 | 5.65 | 5.5 | 5.55 | 5.6 | -0.05 | -0.89 | 3830 |  
19940302 | 000536.SZ | 5.55 | 5.6 | 5.45 | 5.5 | 5.55 | -0.05 | -0.9 | 2379 |  
19940303 | 000536.SZ | 5.7 | 5.7 | 5.4 | 5.5 | 5.5 | 0 | 0 | 7439 |  
19940304 | 000536.SZ | 5.5 | 5.5 | 5.4 | 5.4 | 5.5 | -0.1 | -1.82 | 4123 |  
19940307 | 000536.SZ | 5.5 | 5.5 | 5.3 | 5.4 | 5.4 | 0 | 0 | 3230 |  
19940308 | 000536.SZ | 5.4 | 5.45 | 5.3 | 5.35 | 5.4 | -0.05 | -0.93 | 1593 |  
19940309 | 000536.SZ | 5.35 | 5.4 | 5.3 | 5.35 | 5.35 | 0 | 0 | 2449 |  
19940310 | 000536.SZ | 5.35 | 5.35 | 5.25 | 5.25 | 5.35 | -0.1 | -1.87 | 3337 |  
19940311 | 000536.SZ | 5.25 | 5.35 | 5.15 | 5.25 | 5.25 | 0 | 0 | 4701 |  
19940314 | 000536.SZ | 5.5 | 5.6 | 5.35 | 5.55 | 5.25 | 0.3 | 5.71 | 8532 |  
19940315 | 000536.SZ | 5.7 | 5.7 | 5.35 | 5.35 | 5.55 | -0.2 | -3.6 | 6611 |  
19940316 | 000536.SZ | 5.3 | 5.35 | 5.25 | 5.35 | 5.35 | 0 | 0 | 3525 |  
19940317 | 000536.SZ | 5.4 | 5.5 | 5.35 | 5.45 | 5.35 | 0.1 | 1.87 | 3354 |  
19940318 | 000536.SZ | 5.55 | 5.95 | 5.5 | 5.8 | 5.45 | 0.35 | 6.42 | 36155 |  
19940321 | 000536.SZ | 6 | 6.2 | 5.85 | 5.9 | 5.8 | 0.1 | 1.72 | 55925 |  
19940322 | 000536.SZ | 5.85 | 5.9 | 5.4 | 5.8 | 5.9 | -0.1 | -1.69 | 12294 |  
19940323 | 000536.SZ | 5.8 | 5.8 | 5.55 | 5.6 | 5.8 | -0.2 | -3.45 | 6436 |  
19940324 | 000536.SZ | 5.5 | 5.6 | 5.4 | 5.55 | 5.6 | -0.05 | -0.89 | 5794 |  
19940325 | 000536.SZ | 5.55 | 5.65 | 5.5 | 5.55 | 5.55 | 0 | 0 | 3267 |  
19940328 | 000536.SZ | 5.5 | 5.6 | 5.35 | 5.35 | 5.55 | -0.2 | -3.6 | 2505 |  
19940329 | 000536.SZ | 5.3 | 5.6 | 5.3 | 5.6 | 5.35 | 0.25 | 4.67 | 5668 |  
19940330 | 000536.SZ | 5.65 | 5.7 | 5.35 | 5.4 | 5.6 | -0.2 | -3.57 | 5196 |  
19940331 | 000536.SZ | 5.4 | 5.5 | 5.3 | 5.3 | 5.4 | -0.1 | -1.85 | 3125 |  
19940401 | 000536.SZ | 5.25 | 5.3 | 5.2 | 5.2 | 5.3 | -0.1 | -1.89 | 3613 |  
19940404 | 000536.SZ | 5.2 | 5.3 | 5.15 | 5.2 | 5.2 | 0 | 0 | 3377 |  
19940405 | 000536.SZ | 5.2 | 5.35 | 5.15 | 5.25 | 5.2 | 0.05 | 0.96 | 2433 |  
19940406 | 000536.SZ | 5.25 | 5.35 | 5.25 | 5.35 | 5.25 | 0.1 | 1.9 | 2492 |  
19940407 | 000536.SZ | 5.35 | 5.6 | 5.3 | 5.35 | 5.35 | 0 | 0 | 6814 |  
19940408 | 000536.SZ | 5.35 | 5.35 | 5.15 | 5.15 | 5.35 | -0.2 | -3.74 | 3591 |  
19940411 | 000536.SZ | 5.15 | 5.2 | 5.05 | 5.05 | 5.15 | -0.1 | -1.94 | 3363 |  
19940412 | 000536.SZ | 5.05 | 5.15 | 4.95 | 5.05 | 5.05 | 0 | 0 | 3455 |  
19940413 | 000536.SZ | 5.15 | 5.15 | 4.9 | 4.9 | 5.05 | -0.15 | -2.97 | 2162 |  
19940414 | 000536.SZ | 4.85 | 4.9 | 4.5 | 4.5 | 4.9 | -0.4 | -8.16 | 3573 |  
19940415 | 000536.SZ | 4.45 | 4.7 | 4.15 | 4.65 | 4.5 | 0.15 | 3.33 | 7479 |  
19940418 | 000536.SZ | 4.5 | 4.6 | 4.2 | 4.25 | 4.65 | -0.4 | -8.6 | 5326 |  
19940425 | 000536.SZ | 3.85 | 3.95 | 3.7 | 3.95 | 4.25 | -0.3 | -7.06 | 2627 |  
19940426 | 000536.SZ | 3.95 | 4.15 | 3.95 | 4.15 | 3.95 | 0.2 | 5.06 | 11072 |  
19940427 | 000536.SZ | 4.2 | 4.7 | 4.17 | 4.6 | 4.15 | 0.45 | 10.84 | 24898 |  
19940428 | 000536.SZ | 4.65 | 4.69 | 4.1 | 4.2 | 4.6 | -0.4 | -8.7 | 19187 |  
19940429 | 000536.SZ | 4.1 | 4.4 | 4.05 | 4.34 | 4.2 | 0.14 | 3.33 | 11211 |  
19940503 | 000536.SZ | 4.4 | 4.5 | 4.15 | 4.43 | 4.34 | 0.09 | 2.07 | 12059 |  
19940505 | 000536.SZ | 4.06 | 4.15 | 3.9 | 4.1 | 4.43 | -0.33 | -7.45 | 7530 |  
19940506 | 000536.SZ | 4.1 | 4.15 | 3.91 | 4.03 | 4.1 | -0.07 | -1.71 | 7005 |  
19940509 | 000536.SZ | 4.12 | 4.13 | 4 | 4.13 | 4.03 | 0.1 | 2.48 | 7535 |  
19940510 | 000536.SZ | 4.2 | 4.29 | 4.05 | 4.27 | 4.13 | 0.14 | 3.39 | 11017 |  
19940511 | 000536.SZ | 4.3 | 4.5 | 4.2 | 4.23 | 4.27 | -0.04 | -0.94 | 24903 |  
19940512 | 000536.SZ | 4.11 | 4.2 | 3.9 | 3.9 | 4.23 | -0.33 | -7.8 | 4717 |  
19940513 | 000536.SZ | 3.9 | 4.34 | 3.9 | 4.28 | 3.9 | 0.38 | 9.74 | 11033 |  
19940516 | 000536.SZ | 4.36 | 4.36 | 4.18 | 4.25 | 4.28 | -0.03 | -0.7 | 10505 |  
19940517 | 000536.SZ | 4.25 | 4.35 | 4.14 | 4.15 | 4.25 | -0.1 | -2.35 | 6259 |  
19940518 | 000536.SZ | 4.01 | 4.14 | 4 | 4.07 | 4.15 | -0.08 | -1.93 | 5823 |  
19940519 | 000536.SZ | 4.07 | 4.2 | 4.03 | 4.19 | 4.07 | 0.12 | 2.95 | 3657 |  
19940520 | 000536.SZ | 4.27 | 4.3 | 4.16 | 4.19 | 4.19 | 0 | 0 | 17759 |  
19940523 | 000536.SZ | 4.11 | 4.15 | 4.05 | 4.08 | 4.19 | -0.11 | -2.63 | 2338 |  
19940524 | 000536.SZ | 4.19 | 4.19 | 4.08 | 4.1 | 4.08 | 0.02 | 0.49 | 1867 |  
19940525 | 000536.SZ | 4.05 | 4.1 | 4.04 | 4.05 | 4.1 | -0.05 | -1.22 | 1581 |  
19940526 | 000536.SZ | 4.08 | 4.08 | 3.94 | 3.95 | 4.05 | -0.1 | -2.47 | 5304 |  
19940527 | 000536.SZ | 3.95 | 4.05 | 3.95 | 3.97 | 3.95 | 0.02 | 0.51 | 1562 |  
19940530 | 000536.SZ | 3.9 | 3.9 | 3.69 | 3.69 | 3.97 | -0.28 | -7.05 | 1942 |  
19940531 | 000536.SZ | 3.65 | 3.8 | 3.6 | 3.79 | 3.69 | 0.1 | 2.71 | 3014 |  
19940601 | 000536.SZ | 3.7 | 3.75 | 3.6 | 3.62 | 3.79 | -0.17 | -4.49 | 2410 |  
19940602 | 000536.SZ | 3.55 | 3.62 | 3.55 | 3.59 | 3.62 | -0.03 | -0.83 | 964 |  
19940603 | 000536.SZ | 3.58 | 3.65 | 3.55 | 3.55 | 3.59 | -0.04 | -1.11 | 2162 |  
19940606 | 000536.SZ | 3.5 | 3.5 | 3.33 | 3.38 | 3.55 | -0.17 | -4.79 | 1517 |  
19940607 | 000536.SZ | 3.38 | 3.38 | 3.3 | 3.34 | 3.38 | -0.04 | -1.18 | 441 |  
19940608 | 000536.SZ | 3.25 | 3.36 | 3.2 | 3.34 | 3.34 | 0 | 0 | 1912 |  
19940609 | 000536.SZ | 3.3 | 3.38 | 3.21 | 3.23 | 3.34 | -0.11 | -3.29 | 1602 |  
19940610 | 000536.SZ | 3.2 | 3.26 | 3.12 | 3.12 | 3.23 | -0.11 | -3.41 | 2872 |  
19940613 | 000536.SZ | 3.1 | 3.12 | 3 | 3 | 3.12 | -0.12 | -3.85 | 2053 |  
19940614 | 000536.SZ | 2.99 | 3.06 | 2.95 | 3 | 3 | 0 | 0 | 2516 |  
19940615 | 000536.SZ | 3 | 3.05 | 2.99 | 3.03 | 3 | 0.03 | 1 | 762 |  
19940616 | 000536.SZ | 3.02 | 3.2 | 2.95 | 3.14 | 3.03 | 0.11 | 3.63 | 4717 |  
19940617 | 000536.SZ | 3.15 | 3.3 | 3.03 | 3.24 | 3.14 | 0.1 | 3.18 | 9193 |  
19940620 | 000536.SZ | 3.05 | 3.21 | 3.02 | 3.02 | 3.24 | -0.22 | -6.79 | 4176 |  
19940621 | 000536.SZ | 3 | 3.05 | 2.96 | 3.05 | 3.02 | 0.03 | 0.99 | 3103 |  
19940622 | 000536.SZ | 3.05 | 3.13 | 3.05 | 3.1 | 3.05 | 0.05 | 1.64 | 1598 |  

很可能是数据来源就丢失成交金额的数据，请米哥团队核实。tushare版本号：1.2.20
联系方式：425800931@163.com

**Comment by jimmysoa** [comment]
太早期的数据，暂时没有办法解决这个问题
