### ISSUE TITLE
df=ts.pro_bar能生成数据，但在导入MYSQL数据库时报错

### ISSUE THREAD

**Issue by HewayPg** [waditu/tushare#916]
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [22] of <class 'int'>

察看DF数据，其他为序号索引，而pro.bar函数是日期排序。
请指教，谢谢

https://tushare.pro/register?reg=225669

**Comment by jimmysoa** [comment]
设置参数index = False
