### ISSUE TITLE
tusharepro目前需要的注意事项（不定期更新）

### ISSUE THREAD

**Issue by liyanglzu** [waditu/tushare#918]
1、更新日期：2019-02-09
     使用版本：tushare-1.2.20
#########################   我是万恶的分割线   #################################
今日更新的注意事项有
1.注意啊，所有包含时间的DataFrame可能都是倒序哟！其实，这好像不重要，但是会给你留坑，不信， 
   请直接先阅读本次的第5条。
2.注意啊，股票ts_code='001872.sz’实际上是ts_code='000022.sz'（已退市）更名的哈。
3.接上一条，虽然是更名的，但是新浪、网易、腾讯都认为这是一只新股票，历史数据没有合并；所以要 
  自己合并股票的历史信息。说好的大家都各自安好呢？但是为什么001872的上市时间跟000022一样呢？
4.daily_basic返回的时间序列居然是自然日啊，作为股票，大家不都只关心交易日吗？当然甚至个别人只 
  关心股票的交易日吧!所以不要强求米哥去把数据合并了，毕竟可供选择的数据源也没有合并啊。要是以 
  后有同花顺、东方财富这些数据源，可能就没有这些事儿了吧。
5.pro.daily和ts.pro_bar都是最大返回数组为4000，但是因为第一条——时间倒序的原因，你可能不会得到 
  最开始的结果。因为楼主最开始用pro.daily进行单股票下载的时候，时间从远到近，4000为一组，分组 
  获取的时候没有影响。但是pro_bar调用了daily_basic,对的就是那个返回的是自然日的小婊砸，数据直接 
  被截断了，导致我得不到想要的结果。那怎么办，干不过小婊砸，我还不是只有让她呗。对时间分组， 
  从近到远分，毕竟ts.pro_bar一次还是可以返回4000个数组，完美避开了daily_basic的影响。注意，因为 
  001872的上市日期是1993-05-05，目前数据记录时间为2018-12-26，在使用ts.pro_bar可能会提示“index 
  out of bounds”，因为人家001872的记录数据没有跟000022合并啊，记得要手工处理一下。
6.HTTPConnectionPool，这个是我经常遇到的问题，就是接口访问的速度太快了，得到的df数据时常为 
  None。所以我不知道怎么处理这个问题，遇上我不打算了解她是如何产生的，不过我在得到的数据是 
  None时，直接让其sleep上几秒，再次去访问接口。
7.接口daily对我有1分钟200次的限制，所以如果你跟我一样，那么请记住，ts.pro_bar也是有相应的限 
  制，因为ts.pro_bar调用了pro.daily接口。不会解决这个问题，我就简单粗暴的跟6一样，sleep一下。如 
  果你嫌太小了，可以试着提升自己的积分到5000，比如推广一下tushare，多在社区解答问题，推广一下 
  tushare,或者试着联系捐赠米哥。
8.上证是1990-12-19日营业的，深圳是1990-12-01营业的。不好意思，tushare数据好像是从12-19日开始 
   的。在daily接口中000536.sz的19931130-1994-06-22成交量的数据是为空的，1993-12-23，股票 
   600600-600695的成交量是空的。是的，有些股票数据有空值，记得注意一下。谁叫新浪啊、腾讯啊， 
   这些网站早期数据也不准确嘛。所以，大家不强求嘛。虽然我也不知道，这么久远的数据到底对你有没 
   有用。
###########################      我还是万恶的分割线           #######################
好了，今天的更新就结束了，先记录到这里。里面个别地方使用了不雅的网络语言，只求大家不那么严肃，可以一乐。最后祝大家新春快乐，工作顺利。嗯，忘记说最后一件事儿了，你的假期已余额不足，请及时充值。

**Comment by jimmysoa** [comment]
收到，谢谢写这么多，很细心。

**Comment by liyanglzu** [comment]
> 收到，谢谢写这么多，很细心。

2、更新日期：2019-02-12
使用版本：tushare-1.2.20
接口ts.pro_bar进行了修改，修改后的返回的方式发生改变。
当ts.pro_bar不带factors参数时，返回顺序是ts_code，trade_date,open
当ts.pro_bar带factors参数时，返回顺序是trade_date,ts_code,open
发生改变时间：2019-02-12

**Comment by liyanglzu** [comment]
> > 收到，谢谢写这么多，很细心。
> 
> 2、更新日期：2019-02-12
> 使用版本：tushare-1.2.20
> 接口ts.pro_bar进行了修改，修改后的返回的方式发生改变。
> 当ts.pro_bar不带factors参数时，返回顺序是ts_code，trade_date,open
> 当ts.pro_bar带factors参数时，返回顺序是trade_date,ts_code,open
> 另外，数据保存为csv格式后比昨天的数据要大了，但是数据仅仅多了一行。以000001.sz为例，昨天数据约为560kb,今天约为744kb
> 发生改变时间：2019-02-12
3.更新时间：2019-04-01
stock_basic接口不知道从什么时候会将公布上市时间的股票加入'L'状态中了，截止2019年4月1日，603379将在4月2日上市。如果有start_date = list_date的地方，结果会返回index out of bounds 即时间越界的情况发生
