### ISSUE TITLE
BUG：  ts.pro_bar接口调取换手率，量比时报错。

### ISSUE THREAD

**Issue by daihuangliang** [waditu/tushare#919]
报错为：pro_bar() got an unexpected keyword argument 'factors'

积分：https://tushare.pro/register?reg=123530

**Comment by liyanglzu** [comment]
> 报错为：pro_bar() got an unexpected keyword argument 'factors'
> 
> 积分：https://tushare.pro/register?reg=123530

在三分钟前才调用了，没有问题。贴上调用代码可能会发些问题在哪里

**Comment by daihuangliang** [comment]
import tushare as ts
ts.set_token('***')

pro = ts.pro_api()

df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'])

**Comment by liyanglzu** [comment]
df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)
不好意思，修改了一点点，你试一下这个能运行成功吗？

**Comment by jimmysoa** [comment]
@liyanglzu 谢谢帮忙解答

**Comment by daihuangliang** [comment]
试了还是不成功

**Comment by liyanglzu** [comment]
> 试了还是不成功

推荐这样调用：
pro = ts.pro_api(your_token)
df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)

**Comment by daihuangliang** [comment]
pro = ts.pro_api('my_token')
df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)
Traceback (most recent call last):

  File "<ipython-input-1-a2e3eec1969d>", line 4, in <module>
    df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)

TypeError: pro_bar() got an unexpected keyword argument 'factors'
