### ISSUE TITLE
BUG： ts.pro_bar接口调取换手率，量比时报错

### ISSUE THREAD

**Issue by daihuangliang** [waditu/tushare#920]
用df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)
试了还是一样的错误

**Comment by liyanglzu** [comment]
推荐这样调用：
pro = ts.pro_api(your_token)
df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)

**Comment by daihuangliang** [comment]
pro = ts.pro_api('my_taken')
df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)
Traceback (most recent call last):

  File "<ipython-input-1-a2e3eec1969d>", line 4, in <module>
    df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)

TypeError: pro_bar() got an unexpected keyword argument 'factors'

**Comment by liyanglzu** [comment]
> pro = ts.pro_api('my_taken')
> df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)
> Traceback (most recent call last):
> 
> File "", line 4, in 
> df = ts.pro_bar( ts_code='000001.SZ', start_date='20180101', end_date='20181011', factors=['tor', 'vr'],pro_api=pro)
> 
> TypeError: pro_bar() got an unexpected keyword argument 'factors'

你试一下在命令行下面运行我所提供的代码。另外，你是用的tusharepro吗？版本号1.2.21？

**Comment by jimmysoa** [comment]
升级一下吧
