### ISSUE TITLE
[BUG]000550.SZ日K线数据有误

### ISSUE THREAD

**Issue by ZodiacNailo** [waditu/tushare#921]
使用pro_bar读取000550.SZ（江铃汽车）截止2019-02-13的前复权数据时，发现有数据错误，能引发错误的代码如下：
![image](https://user-images.githubusercontent.com/14036803/52776779-4d73f100-307d-11e9-9d48-1ccc51b26419.png)

执行结果如下图所示：
![image](https://user-images.githubusercontent.com/14036803/52776841-71cfcd80-307d-11e9-86ac-6a55eb8bcd84.png)

该段代码中返回的000550.SZ在2018-01-22的前复权最高价为17.99，但使用同花顺以及东方财富查询该股票当日的前复权最高价，得到的结果均为18.31，如下两图所示：

![image](https://user-images.githubusercontent.com/14036803/52776106-f6b9e780-307b-11e9-83c4-2f158291200a.png)
![image](https://user-images.githubusercontent.com/14036803/52776186-0cc7a800-307c-11e9-921c-551f484d686b.png)

注册链接【https://tushare.pro/register?reg=217213】

**Comment by jimmysoa** [comment]
应该是复权因子的算法不一致，你对比一下万得和腾讯财经的数据看
