### ISSUE TITLE
业绩预告的调用方式希望与其他财务数据调用方式保持一致

### ISSUE THREAD

**Issue by ProV1denCEX** [waditu/tushare#923]
业绩预告的必选参数 现在是 ann_date 或 period 二选一，但是其他所有财务数据的必选参数是或至少包含ts_code。希望修改业绩预告的必选参数以保持与其他api的一致（希望将ts_code加入必选、允许只输入ts_code以返回对应代码的业绩预告）。由于ann_date无法被预知，period无法被精确定位，实际上这两个参数在设定上需要站在已知此2字段的基础上，这与预告的更新逻辑略有冲突。

**Comment by jimmysoa** [comment]
预告数据更财报数据性质并不同，目前暂时按这个参数来设定，谢谢。
