### ISSUE TITLE
使用pro_bar函数获取前复权数据有误，获取数据与未复权数据一致

### ISSUE THREAD

**Issue by samsxp** [waditu/tushare#924]
代码如下
`api=ts.pro_api()
#取前复权行情
df_qfq = ts.pro_bar(pro_api= api, ts_code='600519.sh', adj='qfq', start_date='20070101', end_date='20070104')
df_hfq = ts.pro_bar(pro_api= api, ts_code='600519.sh', adj='hfq', start_date='20070101', end_date='20070104')
df_wfq = ts.pro_bar(pro_api= api, ts_code='600519.sh', adj='', start_date='20070101', end_date='20070104')
df_adj = pro.query('adj_factor',ts_code='600519.sh')
df_adj[df_adj['trade_date']=='20070104']`
取得茅台2007年1月复权因子如下：
![image](https://user-images.githubusercontent.com/47703682/52906641-ec216d00-328a-11e9-976b-ee61fb698992.png)
前复权数据与未复权数据一样
![image](https://user-images.githubusercontent.com/47703682/52906653-4e7a6d80-328b-11e9-8d32-3193713d1432.png)
茅台2007年1月4日实际前复权全数据
<img width="191" alt="2019-02-17 8 10 12" src="https://user-images.githubusercontent.com/47703682/52906671-81246600-328b-11e9-8210-0ac38bbbf587.png">

检测000001.sz股票也存在这个数据，请指教

tushare账号信息
昵称： 赵永胜  
邮箱： 79880568@qq.com

**Comment by jimmysoa** [comment]
在Tushare数据接口里，不管是旧版的一些接口还是Pro版的行情接口，都是以用户设定的end_date开始往前复权，跟所有行情软件或者财经网站上看到的前复权可能存在差异，因为所有这些都是以最近一个交易日开始往前复权的。比如今天是2018年10月26日，您想查2018年1月5日～2018年9月28日的前复权数据，Tushare是先查找9月28日的复权因子，从28日开始复权，而行情软件是从10月26日这天开始复权的。
