### ISSUE TITLE
[Bug] stock_basic 数据缺失

### ISSUE THREAD

**Issue by winstonzhong** [waditu/tushare#927]
在指定list status 分别为L，D，P的情况下均不能返回以退市数据：
000022.SZ  深赤湾Ａ
**确认为数据缺失**

另外一个相关的问题：
调用pro.stock_basic 如果不指定list status, 则结果是默认的L， 这个缺省参数很容易被误认为是包含全部状态的。

**Comment by jimmysoa** [comment]
这个是合并上市改了股票代码，老的pro没有留存，但行情里有老代码的数据
