### ISSUE TITLE
TUSHARE PRO 股票历史数据不全

### ISSUE THREAD

**Issue by stillpassion** [waditu/tushare#928]
pro= ts.pro_api()
pf=ts.pro_bar(pro_api=pro, ts_code='000544.SZ', adj='qfq', start_date='19900101', end_date='20191231')
pf = pro.query('daily', ts_code='000544', start_date='19900101', end_date='20191231')
例如股票代码：000544.SZ 中原环保 | 19931208，000035.SZ 中国天楹 | 19940408。发现000544.SZ遗漏20011031前的股票历史数据；发现000035.SZ遗漏19971223前的股票历史数据。

TUSHARE PRO账号：13907359903。
邮箱 13907359903@139.COM。

**Comment by jimmysoa** [comment]
单次是有最大行数限制的，每次可以获取18年的历史，分两次取

**Comment by stillpassion** [comment]
分两次导出数据，会导致复权不连续的问题。请问要如何解决？
例如：pf = ts.pro_bar(pro_api=pro, ts_code='000014.SZ', adj='qfq', start_date='19900101', end_date='20051231')
df = ts.pro_bar(pro_api=pro, ts_code='000014.SZ', adj='qfq', start_date='20060101', end_date='20191231')
pdf = [pf,df]
result = pd.concat(pdf)20051231 日的股票信息 与 20160101 日的股票信息不连续。




姓名：李经坚 邮箱：13907359903@139.com
电话：13907359903
公司部门：郴州移动-数据中心
公司地址：郴州市北湖区青年大道1号


--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Jimmy  <notifications@github.com>
 

 
 发送时间: 2019-02-20 17:48:53
 

 
 收件人:waditu/tushare <tushare@noreply.github.com> 

 
 抄送:市场部_李经坚 <13907359903@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [waditu/tushare] TUSHARE PRO 股票历史数据不全 (#928)
 



单次是有最大行数限制的，每次可以获取18年的历史，分两次取
