### ISSUE TITLE
【BUG】TUSHARE PRO 股票前复权问题

### ISSUE THREAD

**Issue by stillpassion** [waditu/tushare#929]
ts.pro_bar(pro_api=pro, ts_code='600519.SH', adj='qfq', start_date='20010101', end_date='20191231')
股票：600519.SH 贵州茅台。
20051230 | 600519.SH | 46.5 | 46.52 | 44.9 | 45.62 | 46.77 | -1.15 | -2.45884 | 36647.56 | 167469.3
20060104 | 600519.SH | 12.39 | 12.39 | 12.04 | 12.09 | 12.46 | -0.37 |   | 35507.13 | 157456.2
20051230 股票价格 46.5元，20060104阶跃为12.39。存在较大出入。

TUSHARE账号：13907359903。
邮箱：13907359903@139.com。

**Comment by stillpassion** [comment]
ts.pro_bar(pro_api=pro, ts_code='600519.SH', adj='qfq', start_date='20010101', end_date='201901231')
股票：600519.SH 贵州茅台。
20051230 | 600519.SH | 46.5 | 46.52 | 44.9 | 45.62 | 46.77 | -1.15 | -2.45884 | 36647.56 | 167469.3
20060104 | 600519.SH | 12.39 | 12.39 | 12.04 | 12.09 | 12.46 | -0.37 |   | 35507.13 | 157456.2
20051230 股票价格 46.5元，20060104阶跃为12.39。存在较大出入。

TUSHARE账号：13907359903。
邮箱：[13907359903@139.com](mailto:13907359903@139.com)。

**Comment by stillpassion** [comment]
已发现问题原因。分两次导出数据，导致复权问题。请问分次导出，如何保证复权的连续性？

**Comment by jimmysoa** [comment]
如果要全部数据，可以下载未复权和复权因子本地计算
