### ISSUE TITLE
get_hs300s() 返回不足300只股票

### ISSUE THREAD

**Issue by CJK-Regan** [waditu/tushare#93]
```python
In [1]: import tushare as ts

In [2]: hs300 = ts.get_hs300s()

In [3]: hs300.size / 4
Out[3]: 279
```

然而[中证指数首页](http://www.csindex.com.cn/sseportal/csiportal/zs/jbxx/report.do?code=000300&&subdir=1)上的Excel表里是有300只的

**Comment by jimmysoa** [comment]
已修复，提交到了github

**Comment by RobotJiang** [comment]
为什么同为300行数据的结构，merge后只有273行。我看code应该没有重复的啊。

**Comment by jimmysoa** [comment]
@RobotJiang 不需要merge了，中证指数公司调整了。

**Comment by CJK-Regan** [comment]
@jimmysoa 建议爬取xls的时候用ftp的比较好，即[官网下载页面](http://www.csindex.com.cn/sseportal/csiportal/zs/jbxx/report.do?code=000300&&subdir=1)中相关下载里的链接。最新成分股是`15-12-30`调整的，而`get_hs300()`获取到的还是`15-9-30`的内容

**Comment by CJK-Regan** [comment]
补充：
成分股链接 ftp://115.29.204.48/webdata/000300cons.xls
权重链接 ftp://115.29.204.48/webdata/000300closeweight.xls

**Comment by jimmysoa** [comment]
中证公司调整好快:) 已修复，提交到了github
