### ISSUE TITLE
复权factor 有错误

### ISSUE THREAD

**Issue by winstonzhong** [waditu/tushare#932]
df = ts_pro.adj_factor(ts_code=to_symbol(code), ).sort_values('trade_date', ascending=False)
    tmp = df.drop_duplicates('adj_factor').copy()
    tmp['end'] = tmp.trade_date.shift(-1)
    tmp.dropna()

20150527 到 20180827 之间的factor都是错误的（都为1）。
    ts_code trade_date  adj_factor       end
0     600401.SH   20190225      18.868  20180828
115   600401.SH   20180828      18.870  20180827
116   600401.SH   20180827       1.000  20150527
856   600401.SH   20150527       6.285  20140613
1089  600401.SH   20140613       6.798  20140611
1091  600401.SH   20140611       5.865  20130527
1343  600401.SH   20130527       5.332  20120607
1576  600401.SH   20120607       5.232  20051123
2465  600401.SH   20051123       3.608  20050621

**Comment by jimmysoa** [comment]
数据没有错误，20150527是6.285

**Comment by winstonzhong** [comment]
20150527 之后的factor数据是错误的，为1
