### ISSUE TITLE
建议日线数据增加买卖委托挂单数据及5日线，20日，30日和60日线

### ISSUE THREAD

**Issue by yenairong** [waditu/tushare#935]
建议日线数据增加买卖委托挂单数据，为了方便作数据除权算法，用于分析股票趋势。同时日线，周线，月组建议增加ma5,ma10,ma20,ma30和ma60以及均价这样子更加利于计算股票均价和压力位。

建议者Id：
239568

**Comment by jimmysoa** [comment]
通用行情接口有均线功能
