### ISSUE TITLE
【BUG】20190222的港股通（深圳）数据有误

### ISSUE THREAD

**Issue by malonbear** [waditu/tushare#936]
显示如下：
   trade_date  ggt_ss   ggt_sz      hgt      sgt  north_money  south_money
0    20190226 -2579.0      5.0  1010.97  1319.05      2330.02      -2574.0
1    20190225 -1211.0   1883.0 -2089.44  2026.04       -63.40        672.0
2    20190222   798.0  **42000.0**  3965.10  2609.64      6574.74      42798.0
3    20190221  -581.0    948.0  1718.56   931.48      2650.04        367.0

**Comment by jimmysoa** [comment]
已修正
