### ISSUE TITLE
【BUG】招商港口股票历史数据缺失

### ISSUE THREAD

**Issue by stillpassion** [waditu/tushare#937]
pf = ts.pro_bar(pro_api=pro, ts_code='001872.SZ',  start_date='19900101', end_date='20051231')
df = ts.pro_bar(pro_api=pro, ts_code='001872.SZ',  start_date='20060101', end_date='20191231')
pt = pro.query('adj_factor', ts_code='001872.SZ', trade_date='')
pdf = [pf,df]
result = pd.concat(pdf)
发现 股票 招商港口 仅存在最近40天的数据。
邮箱：13907359903@139.com

**Comment by jimmysoa** [comment]
股票是合并上市，股票代码改了，历史数据需要用旧代码拼接
