### ISSUE TITLE
获取基金get_nav_open方法报错

### ISSUE THREAD

**Issue by wangzili** [waditu/tushare#938]
报错 TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"
查看了下代码，tushare/fund/nav.py文件中获取分页循环，
`fund_dfs = _parse_fund_data(ct.SINA_NAV_DATA_URL %` 
改为
`fund_dfs.append(_parse_fund_data(ct.SINA_NAV_DATA_URL %`
`ct.NAV_OPEN_T3))`后面加个括号就可以了

**Comment by jimmysoa** [comment]
请使用Pro版接口：https://tushare.pro/document/2?doc_id=119
