### ISSUE TITLE
需求：希望在下载股票数据的时候可以有一个参数用来下载例如上证50成分股，沪深300成分股，沪深500成分股，以及其他概念的成分股 

### ISSUE THREAD

**Issue by SSR2018** [waditu/tushare#941]

**Comment by SSR2018** [comment]
注册id：13482105589

**Comment by jimmysoa** [comment]
都已经有了，请参阅Pro网站：https://tushare.pro/document/2?doc_id=126 ， https://tushare.pro/document/2?doc_id=96
