### ISSUE TITLE
IF，IH期货数据出现问题

### ISSUE THREAD

**Issue by Yiran13** [waditu/tushare#943]
米哥打扰了：
在调用IF,IH期货数据的时候（fut_daily 函数），发现给出的数据排列是有明显问题的。
具体内容如下
![default](https://user-images.githubusercontent.com/19371254/53674467-19581d00-3c86-11e9-85b1-827e2805dc44.PNG)

代码：
![image](https://user-images.githubusercontent.com/19371254/53674533-8ec3ed80-3c86-11e9-8cfb-4e610f1c27ab.png)

**Comment by jimmysoa** [comment]
是matlab接口吗？可以用这个版本：https://github.com/faruto/Tushare_MATLAB_FSDK

**Comment by Yiran13** [comment]
是用的R接口. 
大哥辛苦了，这么晚给我回复解决问题.
