### ISSUE TITLE
获取沪深上市公司基本情况接口get_stock_basics，2017-06-14，000049数据类型错误

### ISSUE THREAD

**Issue by hecomlilong** [waditu/tushare#944]
import tushare as ts
codes = ts.get_stock_basics('2017-06-14')
print(type(codes.loc['000049']['timeToMarket']))
print(codes.loc['000049']['timeToMarket'])

执行以上语句可以发现timeToMarket是Series类型，而不是float64

https://tushare.pro/register?reg=241115
我的ID是241115，昵称是swiftll

**Comment by jimmysoa** [comment]
有上市还未发行的情况，上市日期是空字符
