### ISSUE TITLE
pro_bar请求不复权数据，实际返回前复权数据

### ISSUE THREAD

**Issue by quanzh** [waditu/tushare#946]
**代码如下：**
pro = ts.pro_api()
df = ts.pro_bar(pro_api=pro, ts_code='000001.SZ', adj='none' , start_date='20180101', end_date='20180801')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(df)
**返回结果：**
              ts_code trade_date   open   high    low  close  pre_close  \
trade_date                                                                
20180801    000001.SZ   20180801   9.42   9.50   9.11   9.15       9.42   
20180731    000001.SZ   20180731   9.37   9.49   9.25   9.42       9.39   
20180730    000001.SZ   20180730   9.32   9.49   9.26   9.39       9.25   
20180727    000001.SZ   20180727   9.30   9.36   9.18   9.25       9.25   
20180726    000001.SZ   20180726   9.40   9.48   9.21   9.25       9.38   
20180725    000001.SZ   20180725   9.44   9.47   9.33   9.38       9.40   
20180724    000001.SZ   20180724   9.39   9.59   9.33   9.40       9.42   
20180723    000001.SZ   20180723   9.04   9.45   9.00   9.42       9.11   
20180720    000001.SZ   20180720   8.73   9.20   8.61   9.11       8.73   
20180719    000001.SZ   20180719   8.75   8.81   8.69   8.73       8.70   
20180718    000001.SZ   20180718   8.75   8.85   8.69   8.70       8.72   
20180717    000001.SZ   20180717   8.74   8.75   8.66   8.72       8.73   
20180716    000001.SZ   20180716   8.85   8.90   8.69   8.73       8.88   
20180713    000001.SZ   20180713   8.92   8.94   8.82   8.88       8.88   
20180712    000001.SZ   20180712   8.60   8.97   8.58   8.88       8.64   
**20180711    000001.SZ   20180711   8.62   8.69   8.54   8.64       8.84**   
20180710    000001.SZ   20180710   8.88   8.88   8.75   8.84       8.89   
20180709    000001.SZ   20180709   8.55   8.89   8.54   8.89       8.52   
20180706    000001.SZ   20180706   8.47   8.64   8.32   8.52       8.46   
20180705    000001.SZ   20180705   8.48   8.59   8.41   8.46       8.47   
20180704    000001.SZ   20180704   8.49   8.61   8.47   8.47       8.53   
20180703    000001.SZ   20180703   8.55   8.56   8.32   8.53       8.47   
20180702    000001.SZ   20180702   8.91   8.91   8.41   8.47       8.95   
....

**数据对比**
20180712为除权日
20180711
同花顺、新浪数据：不复权价格为8.78
同花顺前复权价格为：8.64，新浪前复权价格为：8.65

ID: quanzhang@aliyun.com

**Comment by quanzh** [comment]
目前使用的最新版本：tushare-1.2.21

**Comment by quanzh** [comment]
目前使用pro.daily可以正确获取不复权数据（目前是参考000001.SZ，取部分日期对比同花顺数据看出是不复权数据）
接口描述上请说明是获取不复权数据，谢谢！

**Comment by jimmysoa** [comment]
在Tushare数据接口里，不管是旧版的一些接口还是Pro版的行情接口，都是以用户设定的end_date开始往前复权，跟所有行情软件或者财经网站上看到的前复权可能存在差异，因为所有这些都是以最近一个交易日开始往前复权的。比如今天是2018年10月26日，您想查2018年1月5日～2018年9月28日的前复权数据，Tushare是先查找9月28日的复权因子，从28日开始复权，而行情软件是从10月26日这天开始复权的。

常见问题里：https://tushare.pro/document/1?doc_id=122

adj='none'的问题，我们下一版修复，谢谢。
