### ISSUE TITLE
pro_bar报错index out of bound

### ISSUE THREAD

**Issue by broken1999** [waditu/tushare#950]
源代码：
pro = ts.pro_api()
ts_code='001872.SZ'
ts.pro_bar(pro_api=pro, ts_code=ts_code, freq='M', adj='qfq', start_date='20150101', end_date='20151231')

报错：
index out of bound
TypeError....

**Comment by sein-tao** [comment]
This problem is related to [issue #937](https://github.com/waditu/tushare/issues/937), [issue #887](https://github.com/waditu/tushare/issues/887), [issue #905](https://github.com/waditu/tushare/issues/905).
I have encountered the same problem recently.
As mentioned by others in the previous issues, it seems reasonable to fixed data to keep the API and logic of code clean and consistent.

**Comment by broken1999** [comment]
> This problem is related to [issue #937](https://github.com/waditu/tushare/issues/937), [issue #887](https://github.com/waditu/tushare/issues/887), [issue #905](https://github.com/waditu/tushare/issues/905).
> I have encountered the same problem recently.
> As mentioned by others in the previous issues, it seems reasonable to fixed data to keep the API and logic of code clean and consistent.

sorry. I do not understand the meaning of " it seems reasonable to fixed data to keep the API and logic of code clean and consistent."

can you maybe elaborate?

**Comment by sein-tao** [comment]
> > This problem is related to [issue #937](https://github.com/waditu/tushare/issues/937), [issue #887](https://github.com/waditu/tushare/issues/887), [issue #905](https://github.com/waditu/tushare/issues/905).
> > I have encountered the same problem recently.
> > As mentioned by others in the previous issues, it seems reasonable to fixed data to keep the API and logic of code clean and consistent.
> 
> sorry. I do not understand the meaning of " it seems reasonable to fixed data to keep the API and logic of code clean and consistent."
> 
> can you maybe elaborate?

To the best of my knowledge, there seems no API could tell the user that `001872.SZ` is related to its old code  `000022.SZ` and how they related. (If there actually is one, please point it out), The old code is not in the result from  `stock_basic` function with `list_status` = `L`, `D` or `P`. So the user may not even know that `000022.SZ` exist if they just use the tushare API.  The`namechange` function also gives no information that these two stocks are related. In my opinion, the API should not make such an assumption that their users have this detailed information about the data. 
Even all the users have such information, fixing the data by every user leads to repeated development of the same function that closely related to tushare, which is a sign that such function should be included in the API. Furthermore, if such events happened later, the users might be forced to maintain a table to store such code relationship. (Actually, I am using such a table to avoid hard code and keep the code extensible, even if only one special case exists now) Again, I believe this table should also be included in tushare.

It should be clarified that by saying "fix the data" (I just noticed the typo, lol), it doesn't mean to merge the data into one table. A table that related this to code and a function that could do the merge is a better solution.

**Comment by jimmysoa** [comment]
周 月线还没有实现复权
