### ISSUE TITLE
调用周线行情出现数据缺失

### ISSUE THREAD

**Issue by davis-lee0109** [waditu/tushare#953]
调用如下函数
df = pro.weekly(ts_code='000001.SZ', start_date='20151220', end_date='20160110', fields='ts_code,trade_date,open,high,low,close,vol,amount')
返回pandas如下：

  | ts_code | trade_date | close | open | high | low | vol | amount
-- | -- | -- | -- | -- | -- | -- | -- | --
000001.SZ | 20160108 | 11.12 | 12.00 | 12.03 | 10.90 | 2664762.94 | 3.033810e+06
000001.SZ | 20160101 | 11.99 | 12.43 | 12.46 | 11.95 | 2466136.73 | 2.980649e+06
000001.SZ | 20151225 | 12.41 | 12.14 | 12.78 | 12.11 | 4058326.50 | 5.055818e+06

2015年最后一个工作周是12月31日（星期四），这一周的数据就缺失了。
请排查一下看看是什么情况。

tushare上注册的ID号125927（davis） 
谢谢

https://tushare.pro/register?reg=125927

**Comment by jimmysoa** [comment]
周线月线会重新上线，目前月线也已经是停止的，更新后会通知，请关注群消息，谢谢
