### ISSUE TITLE
调用2019年的月行情无数据返回

### ISSUE THREAD

**Issue by HavendGithub** [waditu/tushare#958]
调用如下函数
# 月线行情
# 这里有问题，读不了19年的数据
df_monthly = pro.monthly(ts_code='600025.SH', 
                         start_date='20190101', 
                         end_date='20190301', 
                         fields='ts_code, trade_date, open,high, low, close, vol, amount')

tushare上注册的ID号243164（Havenzheng）
谢谢

https://tushare.pro/register?reg=243164

**Comment by jimmysoa** [comment]
月线的数据在日期上没有处理好，会重新生产上线，目前是暂停状态
