### ISSUE TITLE
获取所有历史数据失败

### ISSUE THREAD

**Issue by cicido** [waditu/tushare#959]
在获取一只股票所有数据时，经常报以下错
[Getting data:]HTTP Error 456: 
###HTTP Error 456: 

检查源代码，发现是按季度从
http://vip.stock.finance.sina.com.cn/corp/go.php/vMS_FuQuanMarketHistory/stockid/001896.phtml?year=2018&jidu=4
获取。
我设定pause=0.1 有时能获取，有时还是获取失败。
建议在
trading.py中的
def _parse_fq_data(url, index, retry_count, pause):
    for _ in range(retry_count):
        time.sleep(pause)
增加对pause的处理
if pause == 0:
    pause =  pause + 0.1
else:
    pause = pause * 2
以适应网站情况

**Comment by jimmysoa** [comment]
建议用Tushare Pro版的行情，旧版来自网络的数据无法做质量控制
