### ISSUE TITLE
【优化/建议】获取概念股分类明细数据接口增加一次性获取全部数据功能

### ISSUE THREAD

**Issue by peace-mind** [waditu/tushare#962]
接口：concept_detail
描述：获取概念股分类明细数据
现状：此接口必须传入概念id，要取此表全部数据，需要调用几百次接口，因为概念id有几百个
建议：如果不传入概念id，则一次性返回所有概念数据。这样调用者方便，对服务器压力也小，因为只需要调用一次就可以

**Comment by jimmysoa** [comment]
循环不太影响服务器压力，反倒是一次获取全部数据
