### ISSUE TITLE
000982.SZ 数据缺失 缺少2014.08.22~2016.02.25之间的数据

### ISSUE THREAD

**Issue by broken1999** [waditu/tushare#963]
源代码
ts.pro_bar(pro_api=pro, ts_code=‘000982.SZ’, freq='D', adj=None)

获取的结果是日期20140822 之后直接跳到20160225

**Comment by lynink** [comment]
对比券商提供的数据这段时间就是不存在的。

**Comment by broken1999** [comment]
确实，无bug，这个是误报
