### ISSUE TITLE
区块链行情获取失败（积分已超过3000）

### ISSUE THREAD

**Issue by yhmickey** [waditu/tushare#965]
----> 1 df = pro.coinbar(exchange='huobi', symbol='btcusdt', freq='1min', start_date='20180801', end_date='20180802')

C:\ProgramData\Anaconda2\lib\site-packages\tushare\pro\client.pyc in query(self, api_name, fields, **kwargs)
     41         result = json.loads(res.text)
     42         if result['code'] != 0:
---> 43             raise Exception(result['msg'])
     44         data = result['data']
     45         columns = data['fields']

<type 'str'>: (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u'\u672a\u627e\u5230\u6307\u5b9a\u6570\u636e\u6e90\uff0c\u8bf7\u8f93\u5165\u5408\u9002\u7684\u53c2\u6570', 0, 17, 'ordinal not in range(128)'))

**Comment by yhmickey** [comment]
raise Exception(result['msg'])
Exception: 未找到指定数据源，请输入合适的参数

**Comment by rockyzhaohui** [comment]
大侠，你的积分可以转赠一点给我吗？急需到500分查数据

**Comment by jimmysoa** [comment]
1分钟5分钟需要单独开权限，具体请咨询tushare群群主
