### ISSUE TITLE
查询交易日历有重复日期

### ISSUE THREAD

**Issue by HonnySonng** [waditu/tushare#968]
pro.query('trade_cal',

如:\

20180214
20180214
20180214
20180214
20180214
20180214
20180214

TU ID:128940

**Comment by rolandhii** [comment]
20180214 在 cal_date 那一栏并没有重复，只有在 pretrade_date 那一栏有重复，那是因为 20180215 到 20180221 是春节假期没有开市，所以上一个交易日都是 20180214。

**Comment by jimmysoa** [comment]
有很多交易所，每个交易所都有同样日期的
