### ISSUE TITLE
stk_account接口超时

### ISSUE THREAD

**Issue by xiaokesong** [waditu/tushare#969]
使用http的Restful请求经常返回超时，

请求如下：
{"api_name":"stk_account","token":"","params":{"start_date":"20010101","end_date":"20010201"},"fields":null}

返回如下：
<html>
    <head>
        <title>504 Gateway Time-out</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>504 Gateway Time-out</h1>
        </center>
        <hr>
            <center>nginx/1.15.0</center>
        </body>
    </html>
    
    
    
    
    
    

注册的ID号：reg=243037

**Comment by jimmysoa** [comment]
当时服务器调整，后来好了
