### ISSUE TITLE
get_hist_data数据缺失

### ISSUE THREAD

**Issue by ShtWu** [waditu/tushare#970]
ts.get_hist_data('000333', start = '2018-09-01', end = '2018-10-01')
返回值只2018-09-03到2018-09-07的数据。

**Comment by mingyuan2011** [comment]
可以通过tushare的接口查询停牌信息。
改股票因为重大事项停牌。

**Comment by mingyuan2011** [comment]
> ts.get_hist_data('000333', start = '2018-09-01', end = '2018-10-01')
> 返回值只2018-09-03到2018-09-07的数据。

可以通过tushare的接口查询停牌信息。
该股票因为重大事项停牌。

**Comment by ShtWu** [comment]
好的  谢谢！

**Comment by jimmysoa** [comment]
另外，请使用Pro版行情
