### ISSUE TITLE
pro.moneyflow  接口超时

### ISSUE THREAD

**Issue by liusw02** [waditu/tushare#973]

**Comment by liusw02** [comment]
# 实例
import tushare as ts # 数据
# Api接口
ts.set_token()
pro = ts.pro_api()
#获取单日全部股票数据
df = pro.moneyflow(trade_date='20190315')

#获取单个股票数据
df = pro.moneyflow(ts_code='002149.SZ', start_date='20190115', end_date='20190315')
print(df)
# OUT:
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out

**Comment by jimmysoa** [comment]
后来已经已经解决

**Comment by liusw02** [comment]
> 后来已经已经解决
可以用了我以为还要等一段时间呢，效率蛮高的  👍

**Comment by liusw02** [comment]
> 后来已经已经解决

可以用了。我以为还要等一段时间呢，效率蛮高的 👍
