### ISSUE TITLE
月线数据只能取到20181130？

### ISSUE THREAD

**Issue by shellinger** [waditu/tushare#974]
月k线的返回结果都只到2018年11月。
尝试了很多不同的股票代码，不管是否设定起讫时间，都无法获取之后月份的数据，但周线和日线数据是存在的，并没有停牌
例如可以对比如下结果：
df = ts.pro_bar(pro_api=pro, ts_code='600695.SH', freq='M', start_date='20170101', end_date='20190315')
df = ts.pro_bar(pro_api=pro, ts_code='600695.SH', freq='W', start_date='20170101', end_date='20190315')

(ID: 246108)

**Comment by jimmysoa** [comment]
是的，月线暂停了，等好了再发，我们会发通知给大家，请关注群里的消息
