### ISSUE TITLE
复权与非复权k线数据的返回结构不一致

### ISSUE THREAD

**Issue by shellinger** [waditu/tushare#975]
主体数据没问题，但以split方式存储数据时，会发现未复权的数据，index是序号（好像是这两天刚发生的变动），而复权的数据，index是日期（与以前一样）
可以比较如下语句：
df = ts.pro_bar(pro_api=pro, ts_code='600695', freq='D', start_date='20170101', end_date='20190315')
df.to_json(file, orient='split', force_ascii='false')

df = ts.pro_bar(pro_api=pro, ts_code='600695', adj='qfq', freq='D', start_date='20170101', end_date='20190315')
df.to_json(file, orient='split', force_ascii='false')

似乎是由程序修改引起的变动，最好统一一下

(ID: 246108)

**Comment by jimmysoa** [comment]
是的,通用接口用了日期,后面可以考虑reset_index
