### ISSUE TITLE
stock_basic 里 上港集箱(退) 这个ts_code是错误的

### ISSUE THREAD

**Issue by snowzjy** [waditu/tushare#977]
│ 2019-03-24 │ T00018.SH │ T00018 │ 上港集箱(退) │      │          │ 上海港集装箱股份有限公司 │ Shanghai Port Container Co., Ltd. │        │ SSE      │ CNY       │ D           │ 20000719  │ 20061020    │ N 

T00018.SH 应该修改为600018.SH

ID: snowzjy@163.com

**Comment by jimmysoa** [comment]
这个是退市的上港集箱,600018.SH是当前的上港集团
