### ISSUE TITLE
pro版本的fund_nav、index_daily、fund_daily的接口没有返回数据

### ISSUE THREAD

**Issue by lijh2010** [waditu/tushare#978]
2019/03/24 20:36:59 [query_start] table:index_daily,params:{"trade_date":"20190322","ts_code":"300399.SZ"},fields:[]
2019/03/24 20:36:59 can not got data, fields:11, items:0

我是通过golang语言编写http请求去获取数据的，
其他接口是有返回数据的，但以上三个接口，items这个列表的数量为0

tushare id：135051

**Comment by jimmysoa** [comment]
300399.SZ 这个是股票吧？用指数的接口是获取不到的，index_daily是指数行情
