### ISSUE TITLE
pro_bar 参数不支持 trade_date

### ISSUE THREAD

**Issue by greatwhole** [waditu/tushare#979]
现在有个想法是，能够获取某天所有股票的后复权数据，看了下貌似没有这个功能?

pro.daily 支持传入 trade_date，但是不支持传参 hfq 或者 qfq

pro_bar 支持传参 hfq 或者 qfq ， 但不支持 传入 trade_date

不知道是不是有这个功能，我没找到，还是确实没这个功能？如果确实的话，我提一个 mr ？

**Comment by jimmysoa** [comment]
通用行情目前暂时还不支持当天的全部复权, 主要是现在是动态计算的
