### ISSUE TITLE
【数据缺失】凤凰财经的接口返回的股票数据缺失较多

### ISSUE THREAD

**Issue by zheolong** [waditu/tushare#984]
股票代码sz000002，参见这个链接：http://api.finance.ifeng.com/akdaily/?code=sz000002&type=last

例如缺失2016-10-01  ~ 2016-10-09的数据，当然还有其他缺失部分

很多股票中间都或多或少缺失了数天，可以看下面的图，中间空出来的点比较多，断断续续的。

![屏幕快照 2019-03-29 下午2 54 57](https://user-images.githubusercontent.com/5104916/55214803-b03ad980-5232-11e9-836e-26e11d661082.png)

有没有什么接口可以获取完整的历史数据，而不是这种断断续续的数据？

**Comment by jimmysoa** [comment]
凤凰财经的API已经不推荐使用了，行情数据请使用pro版，https://tushare.pro/document/2?doc_id=27
