### ISSUE TITLE
index_basic 接口的问题

### ISSUE THREAD

**Issue by cnsunfocus** [waditu/tushare#991]
几个使用问题, 请教一下, 谢谢.
1. market参数传入CNI获取不到数据
2. https://tushare.pro/document/2?doc_id=94接口说明中的"指数列表" 似乎应该是"指数类别"
但查询结果似乎不太对.  比如
df = pro.index_basic(market='SSE', category='行业指数')
返回
  ts_code     name market publisher category base_date  base_point list_date
0  950105.SH     上证证券    SSE       上交所     行业指数  20121231      1000.0  20161018
1  h40105.SH  上证证券全收益    SSE       上交所     行业指数  20121231      1000.0  20161018
 
3. 证监会的行业指数对应哪个market?

**Comment by cnsunfocus** [comment]
问题3指的是880开头的一些板块指数:)

**Comment by cnsunfocus** [comment]
问题3里的指数, 好像是通达信自己编的, 880开头的. 应该获取不到......

**Comment by jimmysoa** [comment]
1、国证指数主要就是399哪些指数，market=SZSE
2、这个问题应该不存在，你输入的参数和出来的结果是一致的
3、目前没有专门提供证监会行业指数

**Comment by cnsunfocus** [comment]
那是我理解错了, 我以为行业指数是指 房地产/银行 这种
